theforeman/foreman-documentation

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

As part of
Bug 1741454 - Settings foreman_location and foreman_organization were
deprecated from discovery process
https://bugzilla.redhat.com/show_bug.cgi?id=1741454

Add updates to discovery facts

---

.travis.yml
guides/common/attributes.adoc

I have noticed an error when building the project. The attributes file was including file named "build" which no longer exists since build option is now passed via command line. This is a regression introduced in 8773d0d4d57cf64680d88121d0bb424b669cdb78.

Fixed build error on mising file

---

guides/common/attributes.adoc
guides/doc-Provisioning_Guide/topics/Infoblox_Integration.adoc
guides/upstreamize.rb

Easy peasy, one thing I hate hostname `Infoblox_hostname` I vote for changing this to simply `infoblox-host`. Issues:
* hostnames should always be lowercase
* dashes preferred over underscore
* it is a host not hostname

Infoblox upstreamization

---

guides/common/attributes.adoc
guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc

In addition I am commiting VSCode snippet file. If you use Visual Studio
Code editor for editing adoc files, you can now use `ifsat<TAB>` to
insert snippet quickly. Great time saver, I will add more as I find
those.
One question is on rhv.example.com. I felt like replacing it with
ovirt.example.com is not big deal because it continues with
/ovirt-engine in the URL anyway and I see no point in "hiding" that
OVirt is the upstream project for RHV. We are open source.
I also replaced "My RHV" with "My OVirt" in the compute resource names,
however this can be easily changed to something more neutral like "My
resource".
Other than that this is pretty straightforward conversion, no issues at
all.

Upstreamize RHV chapter

---

guides/doc-Provisioning_Guide/topics/Networking.adoc

Per https://developers.google.com/speed/public-dns/
I do wonder if we should point to possible other services. There's [Quad9's 9.9.9.9](https://www.quad9.net/) and [Cloudflare's 1.1.1.1](https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/) as well.
Technically forwarders aren't even needed.

Correct the Google resolver IP

---

guides/doc-Provisioning_Guide/topics/Resources.adoc

As part of
Bug 1757152 - Need to add a note in Satellite Provisioning Guide, as to
which repositories should be included in the synced Kickstart Repository
for a rhel 8 Operating System
https://bugzilla.redhat.com/show_bug.cgi?id=1757152

Add note about RHEL 8 repositories

---

guides/common/attributes.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

A *lot* of changes, most of them are actually not related to upstreamize process.

Re-review of bare metal chapter

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

As part of
https://bugzilla.redhat.com/show_bug.cgi?id=1758530
Issue #57

Remove deprecated command option from Hammer compute resource for VMware

---

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

Small fix for `hammer discovery-rule` command.
FYI: there is a convention for hammer commands naming which doesn't support underscores in command names or option names.

Fixes s/discovery_rule/discovery-rule

---

guides/doc-Provisioning_Guide/topics/app-Deploy_FIPS_hosts.adoc

As part of
Bug 1763347 - Wrong puppet.conf path on Appendix C.4 of provisioning
guide
https://bugzilla.redhat.com/show_bug.cgi?id=1763347

Fix path for puppet.conf file

---

guides/.gitignore
guides/asciidoc-include-linker.rb

I wrote a simple tool which creates symlinks in folder called `.alink`
which follows the order in which adoc includes appear in documents. This
makes navigation through modularized docs with a breeze.
Better to see it in a video:
https://www.youtube.com/watch?v=w03XYn-p1K0
Test it, share it, enjoy.

A tool to help to navigate modularized docs

---

guides/common/attributes.adoc

:ProductVersionRepoTitle: 6.7 was missing from upstream attributes.adoc
This is necessary for downstream betas

Update attributes file

---

guides/common/modules/ports_prerequisites.adoc
guides/common/modules/ref_system-requirements.adoc

As part of
Bug 1802588 - [upstream] add ifevals for installing Satellite ports and
firewall requirements
https://bugzilla.redhat.com/show_bug.cgi?id=1802588

Add ifevals for foreman and satellite port requirements

---

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

As part of
Bug 1802078 - [DDF] I guess intention of this statement was for intended
for PXE Less provisioning.
https://bugzilla.redhat.com/show_bug.cgi?id=1802078

Remove all support info and just keep link

---

guides/doc-Provisioning_Guide/topics/Virt-Libvirt.adoc

As part of
Bug 1803737 - Packages are locked preventing libvirt-client to be
installed
https://bugzilla.redhat.com/show_bug.cgi?id=1803737

Add new attribute to libvirt installation

---

guides/common/attributes.adoc
guides/doc-Provisioning_Guide/master.adoc
guides/doc-Provisioning_Guide/topics/Virt-Libvirt.adoc
guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc

Add section on how to use an Image Builder image in {Project}
As part of 
Bug 1804761 - The section 'Provisioning Using a Red Hat Image Builder Image' is not present in the Satellite 6.7 Beta Provisioning guide. 
https://bugzilla.redhat.com/show_bug.cgi?id=1804761

Bz#1804761

---

guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc

Couple of changes, the main change is that it's not possible to Publish via HTTP anymore in Katello. Therefore local repository URLs must be used. This means the procedure MUST be either done on Satellite (which we actually disencourage to do) or files should be copied over to a different server. Maybe we should change our mind and simply tell the user to do this on the Satellite server. That would do it, it's harmless.

BZ#1698333 - FDI instructions updated

---

guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc

Bug 1792263 - [DDF] In example you add $(hostname) which represents FQDN of capsule server, but in Satellite provisioning guide in
https://bugzilla.redhat.com/show_bug.cgi?id=1792263

Change unclear $(hostname) to the example URL of smart proxy

---

guides/common/attributes.adoc
guides/common/modules/proc_configuring-repositories.adoc

We want our community users to start testing our installation guide with 2.0rc except we did not update the links to the correct URL! This fixes it. Since the new docs are not official, we don't need to do any warnings like "this is RC version of Foreman" yet. We can implement that later once we start branching off documentation with every Foreman release.

Update installation links to 2.0

---

guides/common/modules/proc_configuring-capsule-default-certificate.adoc
guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc

Bug 1810218 - Command for installing customer certs to satellite missing
https://bugzilla.redhat.com/show_bug.cgi?id=1810218

Add example outputs of katello-certs-check and capsule-certs-generate

---

guides/common/Makefile
guides/common/linkchecker.ini

There is still an error ATM, it's because the target does not work.

Disable HTML link validator server cert check

---

guides/common/Makefile

It needs X509 client cert which we don't have and don't want to use actually.

Ignore cdn.redhat.com during link checking

---

guides/common/modules/proc_creating-a-custom-certificate.adoc

Bug 1796892 - [DDF] It should be noted that the custom certificates for the capsules must be signed by the same CA as the Satellite
https://bugzilla.redhat.com/show_bug.cgi?id=1796892#

Outline considerations for custom SSL certs

---

guides/common/modules/configuring_satellite_http_proxy.adoc

* Replace the procedure to create a proxy entry in Satellite with a new procedure that uses the new method
* Create a new title Verifying the HTTP Proxy connection to a
* Add CLI commands to set hammer settings
Bug 1806587 - Update documentation to not refer to --katello-proxy-* options
https://bugzilla.redhat.com/show_bug.cgi?id=1806587

Update documentation on configuring project with HTTP proxy

---

guides/common/modules/using_external_databases.adoc

For Bug 1772632 - Need to add postgres and mongodb supported version details
https://bugzilla.redhat.com/show_bug.cgi?id=1772632

Added postgresql supported version

---

guides/common/Makefile
guides/common/modules/proc_enabling-connections-from-capsule-to-satellite.adoc
guides/doc-Provisioning_Guide/topics/Cloud-OpenStack.adoc
guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

Bug 1809975 - [DDF] As the V2 API is considered deprecated, this should have V3.0 included
https://bugzilla.redhat.com/show_bug.cgi?id=1809975

Change OpenStack's API version to 3 in URLs

---

guides/doc-Provisioning_Guide/topics/Cloud-Azure.adoc

Bug 1829368 - Missing "No AzureGovCloud support" text for Azure provisioning
https://bugzilla.redhat.com/show_bug.cgi?id=1829368

State that Azure Government is not supported

---

guides/common/modules/enabling_the_satellite_tools_repository.adoc
guides/common/modules/proc_installing-the-katello-agent.adoc
guides/common/modules/synchronizing_the_satellite_tools_repository.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

Skip this wording in command blocks because they require the full name of the repo
Bug 1835718 - Make the wording of Satellite Tools repository consistent throughout the guides
https://bugzilla.redhat.com/show_bug.cgi?id=1835718

Substitute Satellite Tools with the attribute everywhere

---

guides/common/modules/configuring_satellite_http_proxy.adoc

Bug 1828755 - Array format missing for Excluding Hosts from Receiving Proxied Requests in Satellite 6 documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1828755

Fix hammer command to use array to list multiple hosts

---

guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-repositories.adoc

* `foreman-release-scl` package is not required on RHEL
* epel-release can be installed via yum on CentOS
* Repositories required for installing Foreman on RHEL 7 are fixed as per Foreman manual at https://theforeman.org/manuals/2.0/index.html#2.1Installation
Bug 1832217 - [upstream] Missing repos in Install guides
https://bugzilla.redhat.com/show_bug.cgi?id=1832217

Fix repositories as per @ekohl's feedback

---

guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc

Bug 1836524 - [DDF] There is a small correction in the command. Please make it as scp /root/capsule_cert/capsule_certs.tar
https://bugzilla.redhat.com/show_bug.cgi?id=1836524

Fix command to match the suggested command from output

---

guides/common/attributes.adoc
guides/common/modules/enabling_the_satellite_tools_repository.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_installing-the-katello-agent.adoc
guides/common/modules/synchronizing_the_satellite_tools_repository.adoc
guides/doc-Content_Management_Guide/topics/Managing_Activation_Keys.adoc
guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/app_create_images.adoc

Get rid of the workaround that listed the foreman-client repository for el7 only, which might be confusing
Bug 1835718 - Make the wording of Satellite Tools repository consistent throughout the guides
https://bugzilla.redhat.com/show_bug.cgi?id=1835718

Implement the new {foreman-client} attribute

---

guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc

Bug 1812251 - [DDF] Suggest to edit wording. Users who have installed a fresh Satellite from e.g. quick start, should always run the
https://bugzilla.redhat.com/show_bug.cgi?id=1812251

Clarify what command to run to install custom cert on Foreman

---

guides/common/modules/proc_configuring-repositories.adoc

We tell the reader to skip whole chapter, however we only want them to skip first two items on the list involving rhsm. Then the rest still applies.

Move rhsm warning in repo configuring

---

guides/doc-Provisioning_Guide/topics/Resources.adoc

Couple of issues solved:
1) The chapter uses "third-party" extensively, this does not make any sense upstream and I don't believe it's important to have even downstream.
2) Added note about CentOS mirror changes which are upcoming: https://community.theforeman.org/t/rfc-rename-centos-mirror-installation-media/18867
3) Moved the chapter closer to syncing, IM + syncing are essentially very important and for upstream users without Katello this should really come earlier.
The move is a separate commit so you can easily review the changes.

Install media corrections

---

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc
guides/doc-Provisioning_Guide/topics/Cloud-Azure.adoc
guides/doc-Provisioning_Guide/topics/Cloud-GCE.adoc
guides/doc-Provisioning_Guide/topics/Cloud-OpenStack.adoc
guides/doc-Provisioning_Guide/topics/Common_Compute_Resource_Prereqs.adoc
guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc
guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

Downstream build doesn't work with the temporary path to common in the non-common chapters
We will need to keep the old file until all the chapters are in common

Add back old file and change include path

---

guides/common/assembly_configuring-satellite-with-an-http-proxy.adoc
guides/common/modules/proc_configuring-pxe-files-proxy.adoc

This was brought by a user on IRC. It is not relevant downstream as the only content we support is RHEL via CDN and that goes into Katello which do not need to be proxied at all.

Add proxy configuration for PXE smart proxy

---

guides/doc-Planning_Guide/topics/Capsule_Server_Overview.adoc

The Internet Systems Consortium produce a DNS server (and related tools) distributed as ISC BIND (it used to be an acronym, see BIND on Wikipedia, but it is no longer developed by UCB, rather ISC). A google search for "ISC DNS" will take you to the ISC BIND9 page, so I don't feel we should confuse readers with separate references to ISC DNS (a name possibly unique to this document) and the actual ISC product.

Clarify DNS providers - ISC DNS vs ISC BIND

---

guides/common/Makefile

These links are often 401 (paywalled), the tool is unable to check them as there is no way to configure it that 401 should be considered as success. This removes these links.
Example failure:
```
URL        `https://access.redhat.com/solutions/3397771'
Name       `Impact of Disk Speed on Satellite Operations'
Parent URL file:///home/travis/build/theforeman/foreman-documentation/guides/build/doc-Installing_Proxy_on_Debian/index-satellite.html, line 219, col 101
Real URL   https://access.redhat.com/solutions/3397771
Check time 2.051 seconds
Result     Error: 403 Forbidden
```

Ignore access.redhat.com/solutions

---

.travis.yml
guides/Makefile
guides/common/Makefile
guides/common/linkchecker.ini
guides/doc-Managing_Hosts/topics/Running_Jobs_on_Hosts.adoc
guides/find-href

The article no longer exists. This fixes the link in the text.
Also this is a refactoring of Makefile, linkchecker is now called via `xargs` which gives much better results for viewing (single call). Also this supports now linkchecker-tryer which is a tool that tries to retry on links when error is returned.

Fixes 404 link for AWS support site

---

guides/doc-Managing_Hosts/topics/Running_Jobs_on_Hosts.adoc

Bug 1859361 - [DDF] This is displayed as SSH User. Hovering over it shows remote_execution_ssh_user in the tool tip
https://bugzilla.redhat.com/show_bug.cgi?id=1859361

Update UI label for SSH User

---

guides/doc-Administering_Red_Hat_Satellite/topics/proc_integrating-satellite-with-red-hat-single-sign-on-for-external-authentication.adoc

Bug 1862911 - [External AUTH RHSSO/Keyclaok] - Missing some important steps will cause integration setup failure with RHSSO
https://bugzilla.redhat.com/show_bug.cgi?id=1862911

Add the step to configure Login delegation logout URL

---

guides/doc-Administering_Red_Hat_Satellite/topics/proc_integrating-satellite-with-red-hat-single-sign-on-for-external-authentication.adoc

Bug 1862911 - [External AUTH RHSSO/Keyclaok] - Missing some important steps will cause integration setup failure with RHSSO comment#5
https://bugzilla.redhat.com/show_bug.cgi?id=1862911#c5

Update steps that configure Keycloak to set Valid redirect URI

---

guides/common/attributes.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Maintenance.adoc

Mark the whole section Managing Packages on the Base Operating System of Satellite Server to be built for Satellite only as package lock is not enabled on Foreman by default
Bug 1859747 - [RFE] Add a section on patching the Operating System in the "Administering Red Hat Satellite documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1859747

Add command that patches Satellite base OS

---

guides/common/assembly_using-satellite-ansible-content-collections.adoc
guides/common/modules/proc_installing-satellite-ansible-modules-via-rpm.adoc
guides/common/modules/proc_listing-using-satellite-ansible-modules.adoc
guides/doc-Administering_Red_Hat_Satellite/master.adoc

Content files backported from master #228 . PR for 6.8-beta
[RFE] Include Satellite Ansible modules with Ansible Core modules
https://bugzilla.redhat.com/show_bug.cgi?id=1828242

Add assembly/doc files for satellite ansible content collections

---

guides/doc-Configuring_Load_Balancer/topics/Overview.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=1865846
"Provisioning hosts is not supported in the Satellite load-balanced setup." The previous statement does not make it clear that provisioning/virt-who or other content is supported to be installed on the individual capsules that are load balanced but not the HA itself.

Change wording in Load Balanced configuration to quantify support for Provisioning

---

guides/common/attributes.adoc
guides/scripts/satellite-sync.sh

Upstream, Git checks link with each PR. For the links to work, the ProductVersion attribute must be set to a version that has live docs on customer portal, which is now 6.7. Downstream, this versions needs to be changed to 6.8-beta. This is now done with the satellite-sync script

Enable satellite-sync to keep working versions upstream

---

guides/doc-Managing_Hosts/topics/Integrating_Satellite_and_Ansible_Tower.adoc

Fixes #210 
I spotted this a while back while sharing with an upstream community member. 
I don't think that the product version here is necessary. It's been a feature since Satellite 6.3... it adds no value.

Remove unneccessary {ProductVersion}

---

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

chapter entitled "Provisioning Bare Metal Hosts" is just wrong for multiple reasons:
* It describes PXE workflow.
* PXE can be used on bare metal, virtualization and even on some clouds.
* It's confusing.
* We want to add new chapters on HTTP Boot provisioning as well.
Therefore I suggest to rename this.

Rename Bare metal hosts chapter

---

guides/common/attributes.adoc
guides/doc-Content_Management_Guide/master.adoc
guides/doc-Content_Management_Guide/topics/Importing_Custom_Content.adoc
guides/doc-Content_Management_Guide/topics/Importing_Red_Hat_Content.adoc
guides/doc-Content_Management_Guide/topics/Introduction.adoc
guides/doc-Content_Management_Guide/topics/Managing_Activation_Keys.adoc
guides/doc-Content_Management_Guide/topics/Managing_Content_Views.adoc
guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc
guides/doc-Content_Management_Guide/topics/Managing_Custom_Puppet_Content.adoc
guides/doc-Content_Management_Guide/topics/Managing_ISOs_and_Files.adoc
guides/doc-Content_Management_Guide/topics/Managing_OSTree_Branches.adoc

Fixes #158
There is no such thing as "custom" in Foreman or Satellite terminology. 
This slipped in to mean "non-Red Hat". 
I have filtered it out of the upstream docs as it is extremely confusing. 
I forget all my docs skillz so if there is a simpler way to implement this, let me know.

Handle custom term upstream

---

guides/common/modules/ref_system-requirements.adoc

Bug 1871844 - Need to update a note from Sat6.8 installation guide since
we support N-1 capsules
https://bugzilla.redhat.com/show_bug.cgi?id=1871844

Remove outdated statements that Capsule and Sat versions must match

---

guides/doc-Provisioning_Guide/topics/con_unattended-use-and-customization.adoc

This adds two brand new options, do not merge yet the patch is still pending.
https://github.com/theforeman/foreman-discovery-image/pull/125
Adds few more options which are there. I am not adding all of them, most of them are pretty low-level and don't need to be customized:
https://theforeman.org/plugins/foreman_discovery/15.0/index.html#3.1.5Discoveryimagekerneloptions

Added IPv6 FDI options

---

guides/common/attributes.adoc

Bug 1877397 - 6.8 Beta Upgrade instructions have wrong arguments to command
https://bugzilla.redhat.com/show_bug.cgi?id=1877397

Add attribute for upgrade

---

guides/common/attributes.adoc

Bug 1871225 - Incorrect repos for beta; beta repos don't have minor versions
https://bugzilla.redhat.com/show_bug.cgi?id=1871225

Change the ProductVersionRepoTitle attribute for Beta and add comment

---

guides/doc-Provisioning_Guide/topics/app-Deploy_FIPS_hosts.adoc

The old link was no longer valid (404).

Correct FIPS 140-2 link

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

This was missing causing the feature not to work over smart-proxy templates module.
https://community.theforeman.org/t/using-cloud-init-templates-with-foreman-proxy-foreman-proxy-content/20269

Add info about userdata remote_addr

---

guides/common/modules/con_provisioning-workflow.adoc

Boot order is essential thing and it looks like users quite often don't set it properly. This is the right thing to open up with!
Also the chapter actually explains network boot (using PXE). This title is better.

Added note about very important boot order

---

guides/common/modules/proc_adding-life-cycle-environments.adoc

Bug 1876185 - Deprecated command used to add lifecycle environment
https://bugzilla.redhat.com/show_bug.cgi?id=1876185
Bug 1876183 - Duplicate step to to check available lifecycle enviornment
https://bugzilla.redhat.com/show_bug.cgi?id=1876183

Remove a duplicate step and fix a deprecated option 

---

guides/doc-Administering_Red_Hat_Satellite/topics/adding_rhel_system_roles.adoc
guides/doc-Managing_Hosts/topics/Using_Ansible_Roles.adoc

Bug 1834626 - [DDF] I've discovered that in order to use Ansible through a capsule you need to run the follwing command first
https://bugzilla.redhat.com/show_bug.cgi?id=1834626

Add Configuring your Deployment to Run Ansible Roles

---

guides/common/attributes.adoc

Bug 1892211 - Documentation still refers to 6.8 Beta
https://bugzilla.redhat.com/show_bug.cgi?id=1892211

Fix the Infrastructure subscription name

---

guides/common/attributes.adoc

Bug 1892454 - Capsule installation repo instructions refer to rhel-7-server-satellite-tools-6-beta-rpms
https://bugzilla.redhat.com/show_bug.cgi?id=1892454

Fix the Satellite Tools repo attribute

---

guides/common/modules/ref_storage-guidelines.adoc

Bug 1886219 - Add recommendation about not mounting /tmp filesystem with noexec option in Red Hat Satellite or Capsule servers
https://bugzilla.redhat.com/show_bug.cgi?id=1886219

Add info about mountint /tmp with the exec mount option

---

guides/common/attributes.adoc

Bug 1895410 - Need correction in Satellite tools Repository which we enable during Capsule 6.8 Installation
https://bugzilla.redhat.com/show_bug.cgi?id=1895410

Fix the tools repo name for downstream

---

guides/common/modules/ref_satellite-storage-requirements.adoc

Bug 1896703 - Change directory to "/var/opt/rh/rh-postgresql12/" in Storage Requirements section to avoid warning during upgrade
https://bugzilla.redhat.com/show_bug.cgi?id=1896703

Change the PostgreSQL 12 mount point

---

guides/doc-Administering_Red_Hat_Satellite/topics/Disabling_Weak_Encryption.adoc

The doc say to make manual edits to files while the same can be done automatically by running the installer
Bug 1895336 - [Doc Bug] Disable weak ciphers out of date and are already updated in the documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1895336

Disable weak encryption using installer commands

---

guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc

I don't know why we have TFTP there, probably a copy paste problem.

Correct HTTP Boot proxy requirement

---

guides/common/modules/proc_configuring-satellite-for-outgoing-emails.adoc

Foreman 1.16 dropped support email.yaml support. It no longer reads this file so the instructions are completely useless. There never was a reason to restart httpd since the process never read it anyway.
Since Foreman 1.20 the installer also removes the outdated email.yaml. No user will on a supported version will ever see this file.

Remove outdated email.yaml references

---

guides/common/modules/snip_red-hat-images.adoc
guides/doc-Configuring_Load_Balancer/topics/Before_You_Begin.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_without_Puppet_for_Load_Balancing.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_without_Puppet.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Servers_for_Load_Balancing.adoc
guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc
guides/doc-Configuring_Load_Balancer/topics/Overview.adoc
guides/doc-Configuring_Load_Balancer/topics/Preparing_Satellite_Server_and_Capsule_Servers.adoc
guides/doc-Configuring_Load_Balancer/topics/Promoting_SCAP_Content_to_Clients.adoc
guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc
guides/doc-Configuring_Load_Balancer/topics/Verifying_the_Load_Balancing_Configuration.adoc

This PR converts the Configuring Load balancer guide to follow the `one sentence per line` idea.
See #326

Convert to one sentence per line

---

guides/common/modules/proc_adding-images-to-server.adoc
guides/common/modules/proc_adding-installation-media.adoc
guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
guides/doc-Managing_Hosts/topics/proc_creating_a_report_template.adoc
guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-satellite.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/Infoblox_Integration.adoc
guides/doc-Provisioning_Guide/topics/Networking.adoc
guides/doc-Provisioning_Guide/topics/configuring_the_discovery_service.adoc
guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc
guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
guides/doc-Provisioning_Guide/topics/proc_implementing-pxe-less-discovery.adoc

This PR fixes various minor grammar and spelling errors, mostly in the host provisioning guide.
I have one open question: in `guides/doc-Provisioning_Guide/common/modules/proc_adding-installation-media.adoc`, I'd ideally like to add another "family" example, i.e. ```Debian and Ubuntu belong the the `Debian` family.```.
IMHO this should happen on a different branch/PR as it's **not** solely fixing grammar and spelling etc. I'm interested in your thoughts.

Fix grammar and spelling errors in provisioning guide

---

guides/common/modules/proc_configuring-project-with-an-alternate-cname.adoc

Bug 1900761 - Reconfiguring Satellite with an Alternate CNAME does not
require --certs-reset but --certs-update-server instead
https://bugzilla.redhat.com/show_bug.cgi?id=1900761

Change certs-reset to certs-update-server and remove reinstalling cert

---

guides/common/modules/con_ssh-key-for-remote-execution-overview.adoc

Bug 1899630 - Bug 1903641 - [RFE] Document that it is possible to deploy
SSH keys to hosts automatically when registering hosts to Satellite
using the global registration template
https://bugzilla.redhat.com/show_bug.cgi?id=1899630

Document that users can deploy SSH keys upon hosts registration

---

guides/doc-Managing_Hosts/topics/using_insights_with_satellite_hosts.adoc

Bug 1903641 - [RFE] Document that it is possible to register hosts to
Insights automatically when registering hosts to Satellite using the
global registration template
https://bugzilla.redhat.com/show_bug.cgi?id=1903641

Document that users can configure hosts with Insights upon registration

---

guides/common/modules/ref_capsule-storage-requirements.adoc

Bug 1822391 - [DDF] Squid Storage Requirements are missing on Capsule
installation guide
https://bugzilla.redhat.com/show_bug.cgi?id=1822391

Add the /var/spool/squid/ directory to Proxy storage reqs table

---

.github/workflows/deploy.yml
README.md
guides/common/Makefile
guides/common/attributes.adoc
guides/common/header.adoc
guides/doc-Administering_Red_Hat_Satellite/master.adoc
guides/doc-Administering_with_Ansible/master.adoc
guides/doc-Configuring_Ansible/master.adoc
guides/doc-Configuring_Load_Balancer/master.adoc
guides/doc-Deploying_on_AWS/master.adoc
guides/doc-Installing_Satellite_Server_Disconnected/master.adoc
guides/doc-Managing_Hosts/master.adoc
guides/doc-Planning_Guide/master.adoc
guides/doc-Provisioning_Guide/master.adoc
web/content/_index.md
web/content/version-2.3/index.md
web/layouts/404.html

We have a branch support online now:
https://docs.theforeman.org/2.3/Planning_Guide/index-foreman.html
However it's not clear what guide version are you looking at. This introduces version number upstream to all titles, downstream there is a subtitle inserted but we don't do this workflow upstream. This will do it.

Add version to upstream titles

---

guides/doc-Managing_Hosts/topics/Administering_Hosts.adoc

* Return the procedure to edit syspurpose of a single host
* Say that editing syspurpose is possible on all RHEL hosts, not only 8
* Add a prerequisite that hosts must be registered with the submanager
* Describe that you can select a specific attribute, No Change, or None
Bug 1901920 - [RFE] Document setting system purpose on multiple hosts
via bulk action
https://bugzilla.redhat.com/show_bug.cgi?id=1901920

Apply pondrejk feedback to the editing syspurpose procedure

---

guides/common/modules/proc_adding-images-to-server.adoc
guides/common/modules/proc_creating-image-only-hosts.adoc

When converting all source files to "one sentence per line", I probably broke two `ifdef` directives.
This should be fixed now; see `git grep -i -n "ifdef:" | grep -v "\]$"`: there are no more "ifdef" occurrences without a closed square bracket at the end of the line.

Fix broken multiline ifdef directives

---

guides/common/modules/ref_capsule-storage-requirements.adoc

Bug 1889005 - /var/cache/pulp size recommendations in the documentation are outdated and can lead to filesystem fill-up situations
https://bugzilla.redhat.com/show_bug.cgi?id=1889005

Update /var/cache/pulp/ storage req to 32GB

---

guides/common/attributes.adoc

Foreman 2.4 has branched and nightly is at 2.5. On the Katello side 4.0 has also branched and nightly is at 4.1.

Update versions to 2.5/4.1 to match nightly

---

guides/common/modules/proc_configuring-repositories-proxy.adoc

-Config Repositories section
Sat 6.9 beta installation guide refers to repositories of 6.8 instead of 6.9 beta
https://bugzilla.redhat.com/show_bug.cgi?id=1929429

Remove redundant line in note

---

guides/common/attributes.adoc

When our HTML link validation was down, we also missed this.

Update our index-foreman.html links

---

guides/README.md
guides/common/attributes.adoc
web/layouts/404.html

This improves redirect from `index.html` to `index-el.html` in 404 error. Files haven't been deployed yet, I am going to look into that in a moment. This fixes #406.
Second change is a proposal to introduce `foreman` attribute when `foreman-el` or `foreman-deb` is set so we can write easier if statements.

Improve 404 redirect and foreman attribute

---

guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/proc_installing-the-satellite-server-packages.adoc

fix missing repository enablement segments for katello

---

guides/doc-Installing_Server_on_Red_Hat/master.adoc

This fixes the broken intro to Installation guide
This fixes #424

Fix broken reference

---

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc

Remove ref to guide when guide doesn't exist yet

Remove link to guide

---

guides/doc-Provisioning_Guide/topics/con_unattended-use-and-customization.adoc

These are the misisng ones from https://theforeman.org/plugins/foreman_discovery/15.0/index.html#3.1.5Discoveryimagekerneloptions
I skipped those which are not relevant anymore or I don't want them to be documented.

Added some missing discovery kernel options

---

guides/doc-Administering_Red_Hat_Satellite/topics/Changing_the_Password.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Using_Active_Directory.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Using_IdM.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Using_the_Red_Hat_Satellite_Content_Dashboard.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/configuring-direct-ad-integration-with-gss-proxy.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/creating-a-user.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/email-notifications.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/enrolling-satellite-server-with-the-ad-server.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/managing-ssh-keys-for-a-user.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/notification-types.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/testing-email-notifications.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc

This PR fixes two spelling errors (`commmand` and `congiguration`) as well as trailing whitespace and `*` instead of dashes for bullet points to greater consistency.
The two authentication sources `internal` and `external` are now indented below their parent bullet point.

Fix asciidoc consistency & spelling errors

---

guides/common/modules/proc_using-the-api-to-obtain-ssh-keys-for-remote-execution.adoc

The trailing tilde produces subscripted inline code which is not desirable.
The first tilde refers to the home directory of the user and is therefore necessary.
See [built docs](https://docs.theforeman.org/nightly/Managing_Hosts/index-foreman-el.html#using-the-api-to-obtain-ssh-keys-for-remote-execution_managing-hosts)

Fix inline code with trailing tilde

---

web/layouts/shortcodes/guide-list.html

Fix Qucikstart guide web links

---

guides/common/modules/proc_creating-a-job-template.adoc

This purely for consistency reasons; see `git grep -i -n "^=" guides | grep ":$"` as there are no other headers like this.

Remove trailing colon from header

---

guides/common/modules/proc_configuring-repositories-el.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc

Fixes #32169 - use yum.theforeman.org for Katello

---

guides/doc-Administering_Red_Hat_Satellite/topics/Monitoring_Resources.adoc

Removal of trends ection in Administration Guide
Bug 1901926 - [RFE] Remove documentation of Trends and Statistics from Satellite docs
https://bugzilla.redhat.com/show_bug.cgi?id=1901926

Removed trends section from document

---

guides/.gitignore
guides/README.md
guides/common/attributes-base.adoc
guides/common/attributes-foreman-deb.adoc
guides/common/attributes-foreman-el.adoc
guides/common/attributes-katello.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes.adoc
guides/diff-vs-master.sh

I know this is a change that will affect all of us, will break existing PRs and cause some cherry picking change but overall I think it's an important change to make rather sooner than later as another build flag is pending merge (https://github.com/theforeman/foreman-documentation/pull/453) and the attributes file is getting out of control.
**The problem**
As we migrated form Satellite docs, we started with Satellite attributes and enclosed them in if-statement and made a copy for "foreman" build. Then we added "katello" build, then we broke "foreman" into two and now there's another one incoming soon. Some if-blocks are copies (e.g. satellite vs foreman), other if-blocks are just overriding other values.
We need to have a consistent way of defining attributes and overriding them.
**The …

Big cleanup of attributes

---

guides/common/modules/proc_configuring-satellite-for-outgoing-emails.adoc

We don't test others, gray-listing is usually causing issues these days.

Fixes #1911299 - only postfix is tested email server

---

guides/common/modules/proc_disabling-registration-to-insights.adoc
guides/doc-Installing_Server_on_Red_Hat/master.adoc

Bug 1899895 - Document optional disabling Satellite to Insights registration
https://bugzilla.redhat.com/show_bug.cgi?id=1899895

Document section about disabling registration to Insights

---

guides/Makefile
guides/README.md
guides/common/Makefile
guides/diff-vs-master.sh

When you run `make -j5` (pick amount of cores your CPU have + 1) this will now take advantage of GNU make parallel sub-make execution. For me everything is 5x faster.
I could probably implement this for PDFs too but that would make the Makefile a bit unreadable as directory names cannot be reused as targets, so perhaps this could be done via some string substitution. It is not worth the effort, we rarely build PDFs locally, the benefit here is to quickly build HTMLs.
@melcorr I suggest you create the following alias in your profile:
alias make="make -j5"
Then building will be faster for you.

Run make html in parallel when -j is used

---

guides/doc-Administering_Red_Hat_Satellite/topics/Configuring_LDAP_Authentication_for_Red_Hat_Satellite.adoc

Hi @xprazak2
As part of [Foreman manual reboot](https://community.theforeman.org/t/foreman-manual-reboot/22606), I have reviewed the LDAP section [in the Foreman manual](https://theforeman.org/manuals/2.3/index.html#4.1.1LDAPAuthentication) against the upstreamed [Satellite docs](https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_LDAP). The idea would be to ensure we have everything in this repo, deprecate and then remove that content. 
I have found corresponding entries for everything except the following: 
```
**Active Directory password changes**
When using Active Directory, please be aware that users will be able to log in for up to an hour after a password change using the old …
```

Add introductory sentence to LDAP section

---

guides/common/Makefile
guides/common/assembly_performing-additional-configuration-on-capsule-server.adoc
guides/common/modules/proc_installing-the-satellite-server-packages.adoc
guides/doc-Managing_Hosts/topics/Adding_Packages_to_System_Groups.adoc

This patch removes unmatched endif statement which caused asciidoc to print an ERROR.
Because asciidoc still returns zero code, the build continued. The makefile now checks for ERROR strings in asciidoc output and fail if one is found.
This patch also removes one warning - reused id. This is to serve as an example how to fix those. Once we get rid of all warnings we can start failing when warnings are found so everything can be even more strict.

Fail on asciidoc error and fix one context

---

guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc

Since this is coming back to us, let's clear this and also cherry pick it into 6.9 if no objections are made.

The tested image format for liveimg is TAR

---

guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc

We do not support Secure Boot in Satellite, what we don't support we don't document. However it is worth mentioning this upstream, there are some limitations and recent vulnerabilities made it even more complicated.
HTTP UEFI Boot can be used with or without managed DHCP, in that case EFI must be configured to boot via HTTP directly. This improves instructions.

Add Secure Boot info, improve HTTP UEFI Boot

---

guides/doc-Provisioning_Guide/topics/proc_creating-discovery-rules.adoc

SSIA
I should probably link API docs, which we do not have yet. I want to work on this pretty soon (next week) so we can hold on this until this is moved upstream. For downstream I think I will be linking api_guide: https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/api_guide/index

Add example for sequences in discovery

---

guides/doc-Managing_Hosts/topics/proc_managing_and_monitoring_hosts_using_red_hat_web_console.adoc

This PR adapts cockpit documentation files for usage in the documentation of the downstream product orcharhino.

Adapt cockpit guide for orcharhino documentation

---

guides/common/modules/con_acd_introduction.adoc

This PR adapts ACD documentation files for usage in the documentation of the downstream product orcharhino.

Adapt ACD guide

---

guides/doc-Content_Management_Guide/topics/Importing_Content.adoc

-label fix
-new steps
Need to add steps for custom repo creating to consider/explain restrict to Architecture & OS version feature
https://bugzilla.redhat.com/show_bug.cgi?id=1933782

Update to section 6.5. Adding Custom RPM Repositories

---

guides/common/modules/proc_adding-a-default-http-proxy.adoc
guides/common/modules/proc_adding-openstack-connection.adoc
guides/common/modules/proc_adding-rhv-connection.adoc
guides/common/modules/proc_configuring-project-settings-for-keycloak-authentication-using-the-cli.adoc
guides/common/modules/proc_configuring-project-settings-for-keycloak-authentication-using-the-web-ui.adoc
guides/common/modules/proc_configuring-satellite-to-synchronize-content-with-a-local-cdn-server.adoc
guides/common/modules/proc_configuring-the-project-client-in-keycloak.adoc
guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc
guides/doc-Content_Management_Guide/topics/Managing_OSTree_Branches.adoc
guides/doc-Managing_Hosts/topics/Synchronizing_Templates.adoc
guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/Networking.adoc
guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc

This PR escapes HTTP links in inline code with a backslash.
In asciidoc, you can escape links using a backslash in inline codes as follows:
```
clickable            vs. not clickable
`http://example.com` vs. `\http://example.com`
```
This makes sense if the docs link to "foreman.example.com/pub/something" etc., as the URL such never be clicked on/resolve.

Escape http links in inline code

---

guides/common/modules/proc_executing-a-remote-job.adoc
guides/common/modules/ref_default-job-template-categories.adoc

This PR adapts remote execution files for usage in the documentation of the downstream product orcharhino.
Do you like the 30%-70% width distribution in the table? I feel like it's a small UX improvement. [original 50-50](https://docs.theforeman.org/nightly/Managing_Hosts/index-foreman-el.html#default-job-template-categories_managing-hosts)

Adapt remote execution guide

---

guides/common/Makefile
guides/common/modules/proc_creating-a-custom-certificate.adoc
guides/common/modules/proc_installing-server-packages-deb.adoc
guides/common/modules/proc_installing-server-packages-el.adoc

Thanks to changes in https://github.com/theforeman/foreman-documentation/pull/471 and two more changes, we can now treat, and I would never imagine saying that, WARNINGS as ERRORS. Meaning any asciidoc warning from now on will fail the build and PR tests as well. Neat, is it?
I also noticed that when you changed some adoc file in common directory, simply calling `make` would not recognize the change and you had to do `make clean`. This was because we were missing dependencies there.

Treat asciidoctor warnings as errors

---

guides/common/attributes.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=1951584

Update version number in attributes.adoc for 6.9 GA release

---

guides/common/attributes-base.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=1951584

Updated the repo names in attribute file for 6.9 GA

---

guides/common/assembly_installing-satellite-server-disconnected.adoc
guides/common/modules/proc_configuring-repositories.adoc
guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
guides/doc-Upgrading_and_Updating/docinfo.xml

This PR resolves issues in several titles from across the suite that prevent them from building correctly.
* "guides/common/assembly_installing-satellite-server-disconnected.adoc" referred to answer-file-based installations, the main content for which was removed in 1ea86e7104a14116aeee0af2a4a4f80d82c0bcdf. Removed related content and - most importantly - the XREF, which points to a dead reference today.
* "guides/common/modules/proc_configuring-repositories.adoc" pointed to storage XREFs, which are non-existent in that title and section. I suspect this is a copy and paste from the storage docs, so updated all refs to use 'repositories' instead and point to each of the relevant sections.
* "guides/doc-Content_Management_Guide/topics/Using_ISS.adoc" contains a Git conflict notice and an …

Resolved several issues preventing titles from building

---

guides/doc-Content_Management_Guide/topics/Importing_Red_Hat_Content.adoc
guides/doc-Content_Management_Guide/topics/Using_ISS.adoc

It's not evident from the changes in this PR, but there was a mismatch in XREFs - one pointed to an ID with 'Red_Hat' in it, two without. Because the more generic version is already on master, updated all refs to point to the one without 'Red_Hat' in it, resolving this issue and allowing the CMG to build.

Resolved an issue with XREFs in the Content Management Guide.

---

web/content/2.4.md
web/layouts/shortcodes/guide-list.html

I haven't noticed that the landing site has changed dramatically and my branch had an old version of that file. This should correct it.

Update 2.4 landing site

---

guides/common/attributes-base.adoc

Satellite 6.9 installation doc seems to show the wrong satellite 6.9 repo to be enabled
https://bugzilla.redhat.com/show_bug.cgi?id=1952165

Fixed repo name

---

guides/common/attributes-base.adoc

Satellite 6.9 installation doc seems to show the wrong satellite 6.9 repo to be enabled
https://bugzilla.redhat.com/show_bug.cgi?id=1952165

Update capsule repo name for 6.9 release

---

guides/common/attributes-satellite.adoc

Satellite 6.9 managing_hosts doc mentions the Satellite Tools beta repository rather than Satellite Tools 6.9
https://bugzilla.redhat.com/show_bug.cgi?id=1952153

Updated ProductVersionRepoTitle attribute to reflect 6.9

---

guides/common/linkchecker.ini

And it is up.
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.9/

Re-enable link checking of RH docs site

---

guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc
guides/common/modules/ref_ports-and-firewall-requirements.adoc

ICMP has no ports, it is a different (port-less) protocol and Smart Porxy uses ping message type.
ECHO is an (ancient) protocol which works both on TCP and UDP, however Smart Proxy only uses TCP version.
Both are used to find out if an IP address, which is considered as free to be used, is not alive.
This can be turned off completely via a setting option (via the installer).

Corrected protocols for ICMP/ECHO

---

guides/common/modules/proc_configuring-repositories.adoc

Add step to enable Ruby 2.7 module on EL8

---

guides/common/modules/proc_configuring-repositories-el.adoc

Add evgeni's feedback

---

guides/doc-Upgrading_and_Updating/master.adoc
guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc

Comments from @ekohl on IRC to fix. 
* Content relevent for downstream only
* Fix attribute

remove update guide for smart proxy

---

guides/common/modules/proc_configuring-your-deployment-to-run-ansible-roles.adoc

Removed the 'true' Boolean from the command line to enable the Ansible plug-in
Bug 1954530 - Command to enable ansible plugin on Capsules requires no value
https://bugzilla.redhat.com/show_bug.cgi?id=1954530
~

Removed Boolean from command line

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

remove pulp2 removal section for katello 4.1

---

guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc

Removed port 5646 from table 1.3 of the Installing Server Guide
Bug 1890876 - [BUG] Remove port 5646 from table 1.3 of capsule installation documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1890876
* [ X] Foreman 2.4
* [X ] Foreman 2.3 (Satellite 6.9)
* [ x] Foreman 2.1 (Satellite 6.8)

Removed port 5646

---

guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Capsule_Server.adoc

A warning has been added to the Prerequisites of the Renaming Casule Server section about steps to be
taken before renaming Capsule server until BZ1829115 is resolved
Bug 1931714 - Add WARNING in renaming capsule section untill BZ# 1829115 is not getting fixed
https://bugzilla.redhat.com/show_bug.cgi?id=1931714

Added warning to Renaming Capsule Server Section

---

guides/doc-Provisioning_Guide/topics/configuring_the_discovery_service.adoc

SSIA
https://community.theforeman.org/t/deleting-a-provisionned-host-then-rediscover-and-reprovision-fails-at-dhcp/23422

Add note about disjoint ranges for discovery

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

Corrected the 'package-cleanup' command line in 'Using the VMWare vSphere
Cloud-init and Userdata Templates for Provisioning'
Bug 1820129 - [DDF] package-cleanup --oldkernels -count=1
https://bugzilla.redhat.com/show_bug.cgi?id=1820129
* [ X] Foreman 2.5 (Satellite 6.10)
* [ X] Foreman 2.4
* [ X] Foreman 2.3 (Satellite 6.9)
* [ X] Foreman 2.1 (Satellite 6.8)

Corrected package-cleanup command line

---

guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Capsule_Server.adoc

The text has been corrected to remove the 'Prerequisites' title from the warning block, tidy the command
lines and remove a superfuous asciidoc command from the text.
Bug 1931714 - Add WARNING in renaming capsule section untill BZ# 1829115 is not getting fixed
https://bugzilla.redhat.com/show_bug.cgi?id=1931714
* [X ] Foreman 2.5 (Satellite 6.10)

Correction to warming in Renaming Casule Server section

---

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc

BZ1665893 was moved to Errata at 6.8 so the message can be removed from Satellite 6.9 (v2.3) documentation
Bug 1961082 - [DOC] Need to remove prerequisites recommendation about BZ#1665893 in Satellite 6.9 documentation guide
https://bugzilla.redhat.com/show_bug.cgi?id=1961082
* [X ] Foreman 2.5 (Satellite 6.10)
* [X ] Foreman 2.4

Removed recommendation on BZ1665893 from Prerequisites

---

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/introduction_updating_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/migrating_a_self_registered_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/post_upgrade_tasks.adoc
guides/doc-Upgrading_and_Updating/topics/post_upgrade_template_checks.adoc
guides/doc-Upgrading_and_Updating/topics/removing_satellite_tools_repository.adoc
guides/doc-Upgrading_and_Updating/topics/synchronizing_the_new_repositories.adoc
guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsules_separately_from_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_clients.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_discovery_capsule.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_discovery_parent.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_virt_who.adoc

As agreed, upstream docs must adhere to a one-sentence-per-line rule. 
The recently upstreamised wip upgrade guide did not follow this. 
This is my attempt to right that wrong. 

Apply one-sentence-per-line rule to upgrade guide

---

guides/common/modules/proc_configuring-project-settings-for-keycloak-authentication-using-the-web-ui.adoc

This PR disables some more unresolvable links.
Reason: `X.example.com` won't ever/most likely not resolve, i.e. users cannot/should not click these kinds of links.
See also https://github.com/theforeman/foreman-documentation/pull/487
Question: is the bold and italic on purpose or "should" this be inline code?

Disable unresolvable links

---

guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Capsule_Server.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Satellite_Server.adoc

In both Renaming Satellite Server and Renaming Casule Server sections an admonition has been added to check the
value retured by the hostname command for satellite-change-hostname to work correctly.
I have also moved a warning in the Renaming Capsule server section to avoid asciidoc formatting problems caused
when the admonition occurs directly after the Prerequisites title.
Bug 1922300 - A must prerequisite should be mentioned in "RENAMING SATELLITE SERVER OR CAPSULE SERVER" chapter
https://bugzilla.redhat.com/show_bug.cgi?id=1922300


Added admonition to check the status of hostname

---

guides/common/attributes.adoc

This is the 2.5 version branch so version numbers should match. This is https://github.com/theforeman/foreman-documentation/pull/547 but for stable.

Correct 2.5 version numbers

---

guides/common/attributes.adoc

This guide is for nightly and it should point to that. Without this, it falsely gives the impression it's for 2.4.

Set versions to nightly

---

guides/doc-Administering_Red_Hat_Satellite/topics/restoring-from-a-full-backup.adoc

Removed the word 'major' so that the text now states you should restore from the same version you backed up. Restoring
from an alternate minor version, for example 6.7 to 6.8 is not supported and may cause problems.
Bug 1846077 - misunderstanding between major and minor version
https://bugzilla.redhat.com/show_bug.cgi?id=1846077
* [X ] Foreman 2.4
* [X ] Foreman 2.3 (Satellite 6.9)
* [X ] Foreman 2.1 (Satellite 6.8)

Cleared misunderstanding between major and minor versions

---

guides/common/assembly_installing-capsule-server.adoc
guides/common/modules/proc_installing-capsule-server-packages.adoc
guides/common/modules/proc_installing-proxy-packages-el.adoc
guides/common/modules/proc_installing-smart-proxy-upstream.adoc
guides/common/modules/proc_registering-capsule-to-satellite-server.adoc
guides/common/modules/ref_capsule-storage-requirements.adoc
web/layouts/shortcodes/guide-list.html

This PR adds some better separation between vanilla (no Katello), content, and Satellite smart proxies.
I've removed the parts that say "Katello only" and hid those sections instead.
Let me know if I missed anything.

Better separate the smart proxy installation instructions between Katello and Foreman

---

guides/README.md

This PR adds orcharhino (Foreman downstream product by ATIX) to the readme.
It also updates the versions of Foreman and Satellite. Note that this is just in the readme, not the attributes which are used throughout the documentation.

Add orcharhino to readme as downstream product

---

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc

Some of the parameters have changed w.r.t to the orignal documentation.
This commit incorporates that.

Changes/Modifications to the import/export guide

---

guides/common/modules/proc_disabling-registration-to-insights.adoc
guides/common/modules/proc_using-insights-with-satellite-server.adoc

-Also updated insights registration command
Bug 1959123 - Enhancement:'Satellite now registers to Insights by default' not working as described in the documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1959123

Removed incorect text about registering to Insights by default

---

guides/common/modules/con_acd_architecture.adoc
guides/common/modules/proc_adding_an_ansible_playbook.adoc

* Fix path for ACD Ansible playbooks
* Add git support to Ansible playbook
* Extend ACD user roles
* Git branch commit tag no longer optional

Extend ACD documentation

---

guides/doc-Content_Management_Guide/topics/Importing_Content.adoc

A table of the hostnames available and portnumbers, plus a warning not to perform SSL inspections
on these communications was added.
Bug 1921928 - Satellite documentation needs more information on proxy part if it use to sync repositories
https://bugzilla.redhat.com/show_bug.cgi?id=1921928

Provided more information for adding an HTTP Proxy

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc

I'd say some cherry-pick introduced some trouble here. 
as part of
https://bugzilla.redhat.com/show_bug.cgi?id=1974361

Fix title of 2.3 content

---

guides/doc-Managing_Hosts/topics/proc_removing-a-host-from-satellite.adoc

The default behaviour has been changed with the release of Foreman 2.3.
See [f6fdaaf5b1f519db902e6469beda3b0f20d2411e](https://github.com/theforeman/foreman/commit/f6fdaaf5b1f519db902e6469beda3b0f20d2411e) in the foreman repository.

Rework "removing a host" deletion warning

---

guides/doc-Administering_Red_Hat_Satellite/topics/creating-a-compliance-policy.adoc

This PR removes a link to a closed BZ entry. It has been closed with `won't fix`, so I've reworded the sentence accordingly. IMHO it does not make sense to provide this link in our docs.
This PR is **very much up for discussion**, as I don't know how you want to handle such things.

Remove link to closed BZ

---

guides/doc-Administering_Red_Hat_Satellite/topics/Using_the_Red_Hat_Satellite_Content_Dashboard.adoc

Use `{Project}` attribute instead of Foreman to make it more downstream friendly.

Replace Foreman with Project attribute

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

The steps for version 6.9 also apply to vCenter Server version 7.
Bug 1952970 - Red Hat Satellite 6.8 needs to include Vcenter 7 support information
https://bugzilla.redhat.com/show_bug.cgi?id=1952970

Added vCentre 7 support inormation

---

guides/common/modules/ref_system-requirements.adoc

Lack of indentation separating the two sections reported. 

Fix indentation on FIPS mode

---

guides/doc-Administering_Red_Hat_Satellite/topics/Using_IdM.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/configuring-idm-authentication-on-satellite-server.adoc
guides/doc-Planning_Guide/topics/Configuration_Management_Support.adoc
guides/doc-Planning_Guide/topics/Content_Management_Support.adoc
guides/doc-Planning_Guide/topics/Host_Provisioning_Support.adoc

Only the "Foreman on EL6" commit should be picked into Satellite 6.8, or ignored.

drop old OS references that aren't supported anymore

---

guides/doc-Administering_Red_Hat_Satellite/topics/configuring-idm-authentication-on-satellite-server.adoc

our installer hard-codes HTTP and using _servicename_ here would imply
that the user can change this, while they can not.

use HTTP not a placeholder servicename when registering for IdM

---

.github/workflows/deploy.yml
web/README.md

Ewoud noticed that we actually build the web portion from the topic/stable branch, but since we do not overwrite files (due to documentation portion of the site) files do not get deleted and we haven't noticed. This fixes it, everything under `/web` should be built from `master`.
There is another solution to create a dedicated branch just for the web/ portion, however I do not like having two different content sets in two branches. This creates unecessary long checkouts when switching over, we have this problem with foreman-packaging (rpm/develop vs deb/develop) and I ended up having two separate checkouts for that. I would rather keep this approach when all content is in the single branch - master. This is where most of the development/writing takes place.

Always build web from the master

---

LICENSE

While this license was already mentioned in the footer, this makes it trivial to find. It may also help Github to detect the license.
It is a copy of https://creativecommons.org/licenses/by-sa/3.0/legalcode.txt
This commit was originally included in https://github.com/theforeman/foreman-documentation/pull/588 split off to keep it focused.

Add the CC-BY-SA 3.0 license text

---

guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc

Change {smart-proxy-context}_ca.example.com to {smart-proxy-context}-ca.example.com, as a FQDN cannot contain an underscore.
Bug 1973389 - Remove " _ " underscore from the hostname which used as example in documentation and not supported
https://bugzilla.redhat.com/show_bug.cgi?id=1973389

Remove underscore from example domain

---

guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
guides/common/modules/proc_installing-smart-proxy-upstream.adoc

Remove "quotes" attribute
The "quotes" attribute is what is causing the yellow highlighting
in our docs on occasions
I also added italic markers as per our doc style to indicated that foreman.example.com is a variable.

Fix incorrect attribute

---

guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc

This repository has been removed with Foreman 2.0.

Remove foreman-rails repository

---

guides/common/attributes.adoc
guides/common/modules/proc_acd_installation.adoc
guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc

Without this you get weird bugs after branching.

Use ProductVersion macro instead of hardcoding

---

web/content/2.3.md
web/content/2.4.md
web/content/2.5.md

Prior to this it ended up as:
Foreman 2.5 and Katello 4.1 documentation
Foreman 2.5 and Katello 4.1
This is because the title is always printed.

Remove duplicate headers

---

guides/common/modules/ref_ports-and-firewall-requirements.adoc

I suspect this was previously used for Crane (which ran on port 5000) but Crane is gone and replaced by Pulp 3 which uses port 443.

Remove use of port 5000 for running containers

---

guides/doc-Managing_Hosts/topics/Registering_Hosts.adoc

Bug 1963222 - Typo in the documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1963222

Red Hat, not Red Han (v2)

---

guides/common/modules/proc_configuring-external-dns.adoc

By using a file in /etc/foreman-proxy, you can use it just for this service and make foreman-proxy the group. That also allows the service to read the content without needing the named group.
Now step 1 is not needed at all. You may need bind-utils for nsupdate to test, but bind itself is certainly not needed. In the current guide it's installed just for the named group but that's really overkill.
Step 7 is not needed at all and was never needed. The installer will restart the service if needed.
Step 4 (testing) is a good step but I think example.com is a better domain than virtual.lan.
Note that this instruction now only works well if you have an existing installation where the foreman-proxy group is present. So carefully review this.
I also removed restorecon on Debian where we SELinux …

BZ1776930: Simplify the remote DNS instructions

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/proc_listing-using-satellite-ansible-modules.adoc

@evgeni pointed out on IRC that a FAM example
was rendering incorrectly in our docs.
https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#using-satellite-ansible-content-collections_admin
The attributes files included backticks
that also appeared in the codeblocks.
Best to format on the namespace as needed 
as the formatting limited its usage. 
@maximiliankolb - I didn't touch orcharhino as you have not exposed this section in your docs yet: https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-orcharhino.html#using-satellite-ansible-content-collections_admin 
I'm adding you as a reviewer as you might need me to adjust the orcharhino attributes also. 

Fix incorrect markup on FAM attribute

---

.mailmap
AUTHORS
generate-authors

Add AUTHORS file

---

guides/common/modules/con_acd_architecture.adoc

ACD supports now adding and editing arbitrary YAML data instead of only `key:value`.

ACD: allow Ansible parameters in yaml

---

guides/common/modules/proc_puppet-using-puppet-classes-host-group.adoc
guides/doc-Content_Management_Guide/docinfo.xml
guides/doc-Content_Management_Guide/topics/Creating_an_Application_Life_Cycle.adoc
guides/doc-Content_Management_Guide/topics/Introduction.adoc
guides/doc-Content_Management_Guide/topics/Managing_Content_Views.adoc
guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc
guides/doc-Planning_Guide/topics/Glossary.adoc
guides/doc-Planning_Guide/topics/Introduction.adoc

Content management of the Puppet content type was deprecated in a previous release.
This commit is intended to remove all references to the Puppet content type.

WIP: Deprecation: remove Puppet content support

---

guides/common/assembly_using-puppet-for-configuration-management.adoc
guides/common/modules/proc_puppet-setting-out-of-sync-time-for-puppet-managed-hosts.adoc

This PR documents how the "out of sync" interval is calculated which is not intuitive. See also [Foreman Community Forum](https://community.theforeman.org/t/outofsync-interval-vs-origin-downcase-interval/24538?u=maximilian).

Add puppet out of sync interval

---

guides/doc-Managing_Hosts/topics/Configuring_Host_Collections.adoc
guides/doc-Managing_Hosts/topics/con_overview-of-hosts-in-satellite.adoc
guides/doc-Managing_Hosts/topics/proc_adding-a-bonded-interface.adoc
guides/doc-Managing_Hosts/topics/proc_exporting_report_templates_api.adoc
guides/doc-Managing_Hosts/topics/proc_importing_report_templates_api.adoc
guides/doc-Managing_Hosts/topics/proc_managing_and_monitoring_hosts_using_red_hat_web_console.adoc
guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc
guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc
guides/doc-Managing_Hosts/topics/ref_customizing-the-registration-templates.adoc

This PR adapts the managing hosts guide for Foreman downstream product `orcharhino`. It does not make any changes to upstream or Satellite docs.

Adapt managing hosts guide for orcharhino

---

guides/common/modules/con_acd_architecture.adoc
guides/common/modules/proc_acd_installation.adoc
guides/common/modules/proc_puppet-configuring-a-puppet-class.adoc
guides/common/modules/proc_puppet-importing-a-puppet-module.adoc
guides/common/modules/proc_puppet-installing-a-puppet-module-from-puppet-forge.adoc
guides/common/modules/proc_puppet-updating-a-puppet-module.adoc
guides/common/modules/proc_puppet-using-puppet-classes-individual-host.adoc

This PR fixes the source highlighting for code blocks in the 'puppet for configuration management' documentation.

Remove bash highlighting in code blocks

---

guides/common/attributes-satellite.adoc

Part of the changes that move certain technical content to console.redhat.com. The changed  link already resolves successfully.
SATDOC-132 cloud.redhat.com changes
https://issues.redhat.com/browse/SATDOC-132

Change reference to cloud.redhat.com with console.redhat.com

---

guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc

Need to add "-t capsule" if the katello-certs-check is called with custom ssl certificates for Capsule server
Bug 1983101 - Deploying capsule certificates is confusing as per the documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1983101

BZ1983101 deploying capsule cert is confusing

---

guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc

The installer can set this up since [Foreman 1.18](https://github.com/theforeman/puppet-foreman_proxy/commit/fcf6d82fde29527bf063d6cb60199339fd4a6266).
Technically it should be safe to cherry pick this into all branches, but I must admit I haven't tested this. That's why I'd only pick it into upstream supported branches, but if the docs team is confident, I won't hold you back :)

Use installer options to set up DHCP multi homing

---

guides/common/modules/ref_capsule-server-scalability-considerations.adoc
guides/doc-Quickstart_Guide/master.adoc

Passenger support was dropped in Foreman 2.5.

Remove mentions of Passenger

---

guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
guides/common/modules/proc_enabling-connections-to-capsule.adoc
guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc
guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc

32e6122d156671e913b152ebfbade8af0c6ba387 started this effort, but I missed a few.
This is for any Pulp 3-only install, so Katello 4, meaning Foreman 2.5 should receive this as a cherry pick.

Remove all references of port 5000 for Docker

---

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc

Fixed a mischaracterization of composite export.

---

.github/PULL_REQUEST_TEMPLATE.md

I have added 3.0 as a cherry-pick option as we have branched. 
I have not removed 2.1 because I will wait until the downstream 
release of 2.5, otherwise we might face some backlash.

Add 3.0 to CP template

---

guides/common/assembly_provisioning-virtual-machines-kvm.adoc
guides/common/modules/con_types-of-provisioning-templates.adoc
guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
guides/common/modules/proc_verifying-dns-resolution.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Using_IdM.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/active-directory-with-cross-forest-trust.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/configuring-host-based-authentication-control.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/configuring-idm-authentication-on-satellite-server.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/kerberos-configuration-in-web-browsers.adoc
guides/doc-Content_Management_Guide/topics/Managing_Container_Images.adoc
guides/doc-Managing_Hosts/topics/proc_adding-a-bonded-interface.adoc
guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc

RHEL Platform documentation went through an upgrade during the weekend, and this upgrade changed several urls. I have been assured that eventually redirects will work over the next week or so, but the linkchecker is causing the links to fail, which is slowing progress. It is less time consuming just to fix and move on. 

Update platform links

---

README.md

Remove outdated TODO list from main readme.md

---

web/content/2.3.md
web/content/2.4.md
web/content/2.5.md

If a vernum ends in a 0, it is shortened
To avoid this, use quotes in the path

Update all web/content entries with quotes

---

guides/doc-Administering_Red_Hat_Satellite/topics/creating-a-complete-permission-table.adoc

This removes the extremely dangerous instruction to install all plugins. Users who do this can easily effectively break their installation. We have no way to safely remove plugins and there is no way back.
The correct thing to do is ensure the foreman-console package is installed. That's the only thing that is needed.
This also has the benefit that it works on all supported platforms rather than just EL7.
I consider this very important and would suggest to fix it where possible.

Install foreman-console instead of all plugins

---

web/content/3.0.md

Add katello 2.4 notes and contributors

---

Dockerfile
guides/README.md

This PR adds a `Containerfile` to build a container image & minimal usage instructions on how to build Foreman documentation without installing any other applications apart from docker/ a docker alternative. If someone is kind enough to rerun both commands on Fedora, I would **love** to replace `docker` with `podman`.
I hope this makes it easier for everyone to try and build their branch/contribution locally first before creating a PR.
On a sidenote: We could also create a separate repo (like `foreman-documentation-container-image`) to massively speed up Github actions. It'll be faster and save resources.

Build docs in container

---

guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc
guides/doc-Content_Management_Guide/topics/appendix-Importing_Content_ISOs_into_Connected_Satellite.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc
guides/doc-Planning_Guide/topics/Glossary.adoc

With the move to Pulp 3, the Background download policy has been removed from repositories.  This commit will remove references in the documentation to that download policy.
For any existing repositories that a user may have with 'Download Policy = Background', the upgrade will update them to 'Download Policy = Immediate'.  With this change, the process to fully complete a repository synchronization may appear to take longer as the sync will not be considered completed until all content in the repository is downloaded.

Deprecation: remove Repository Background download policy references

---

guides/common/modules/proc_creating_an_application_instance.adoc

This PR documents a new feature for ACD: Adding existing hosts to your app instance.

Add existing hosts when creating an app instance

---

guides/common/attributes.adoc

00de02be190de55babef8d6ac23380e7682a4a81 changed this to stable versions, but this branch is still the nightly branch.
This only affects master.

Correct version numbers for nightly

---

guides/doc-Planning_Guide/topics/Content_Management_Support.adoc

There was a question raised about this on an internal list, I believe we do support everything except ARM64. Do not merge until a PM confirms this please. @ares or @ehelms ?

Correct IBM POWER client support

---

guides/common/assembly_performing-additional-configuration-on-capsule-server.adoc
guides/common/modules/proc_configuring-installation.adoc
guides/common/modules/proc_enabling-katello-agent.adoc

Document how to enable Katello Agent infrastructure

---

guides/common/modules/proc_creating_an_application_instance.adoc

This PR documents using Ansible variables from different namespaces in ACD.
This allows you to refer to Foreman Host Parameters from Host Groups, Operating Systems, Locations, and Organizations.

Add Ansible variables from different namespaces to ACD

---

guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc

Fixed only for 2.5, `nightly` and `2.4` are ok

Fix link to registration doc in Configuring_Ansible guide

---

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc

Wrap the Debian reference for exclusion from Sat

---

guides/common/modules/proc_installing-the-satellite-server-packages.adoc

Satellite (Pantheon) docbook.xml is failing validation because this conditional does not include satellite

adds satellite conditional to rhel-7 section

---

.github/PULL_REQUEST_TEMPLATE.md

That's gone for us, RHD team should file PRs for "master" and cherry pick into older releases themselves. We will continue doing 6.9 but long term, I would like only to cherry pick into last two upstream release. What you think?

Remove Satellite 6.8 from GHT

---

guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc

iPXE EFI was implemented for a parlticular customer, but it is not reliable for general purpose environments. Let's remove that from our docs and upstream I will link the tutorial I wrote. This is the best I can do.

Limit support of iPXE EFI

---

guides/common/assembly_converting-a-host-with-convert2rhel.adoc
guides/common/assembly_importing-kickstart-repositories.adoc
guides/common/modules/proc_adding-life-cycle-environments.adoc
guides/common/modules/proc_configuring-satellite-to-synchronize-content-with-a-local-cdn-server.adoc
guides/common/modules/proc_creating-a-host-activation-key.adoc
guides/common/modules/proc_importing-a-subscription-manifest-into-satellite-server.adoc
guides/common/modules/proc_importing-kickstart-repositories.adoc
guides/common/modules/proc_installing-convert2rhel.adoc
guides/common/modules/proc_preparing-the-host-group.adoc
guides/common/modules/proc_reverting-satellite-to-download-content-from-red-hat-cdn.adoc
guides/doc-Content_Management_Guide/master.adoc
guides/doc-Content_Management_Guide/topics/Bulk_Updating_Content_Hosts_Subscriptions.adoc
guides/doc-Content_Management_Guide/topics/Containers_importing_container_images.adoc
guides/doc-Content_Management_Guide/topics/Containers_interacting_with_registry.adoc
guides/doc-Content_Management_Guide/topics/Containers_managing_authentication.adoc
guides/doc-Content_Management_Guide/topics/Creating_an_Application_Life_Cycle.adoc
guides/doc-Content_Management_Guide/topics/Importing_Content.adoc
guides/doc-Content_Management_Guide/topics/Managing_Activation_Keys.adoc
guides/doc-Content_Management_Guide/topics/Managing_Content_Views.adoc
guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc
guides/doc-Content_Management_Guide/topics/Managing_Errata.adoc
guides/doc-Content_Management_Guide/topics/Managing_ISOs_and_Files.adoc
guides/doc-Content_Management_Guide/topics/Managing_Locations.adoc
guides/doc-Content_Management_Guide/topics/Managing_Organizations.adoc
guides/doc-Content_Management_Guide/topics/Managing_Subscriptions.adoc
guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
guides/doc-Content_Management_Guide/topics/appendix-Importing_Content_ISOs_into_Connected_Satellite.adoc
guides/doc-Content_Management_Guide/topics/appendix-NFS_Share.adoc

* Set headings to level 1
* Add anchors
* Remove unnecessary whitespace
* Use 'RHEL' attribute
* Make anchors and headings more downstream friendly
* Replace 'capsule' with 'Proxy'
* Move 'appendix' directive to parent pages
In a follow up PR, I want to split up content into different files. This will result in one heading per file.

Rework content management guide

---

guides/doc-Content_Management_Guide/topics/QuickStart.adoc
guides/doc-Managing_Hosts/topics/Registering_Hosts.adoc
guides/doc-Managing_Hosts/topics/using_insights_with_satellite_hosts.adoc

One was already fixed, but there are others:
https://github.com/theforeman/foreman-documentation/pull/716

Registering host links corrected

---

guides/common/attributes.adoc

also updates inline instructions for clarity
this attribute ensures that links to the docs on the RH customer portal point to the current version, e.g. `access.redhat.com/documentation/en-us/red_hat_satellite/{AccessRedHatComVersion}/html/...`

updates AccessRedHatComVersion to 6.10-beta

---

guides/common/attributes-base.adoc

SATDOC-462 beta RPM name is incorrect
https://issues.redhat.com/browse/SATDOC-462

Mods beta rpm attribute

---

guides/common/attributes-satellite.adoc

this happens after publishing as the link-checker requires working links
this needs to be back-ported to 2.5, where the identical attributes are in a different file.

changes ProductVersion to 6.10-beta

---

guides/common/attributes-base.adoc

all instances of rhel-7-server changed to rhel-server-7
version numbers also updated
https://bugzilla.redhat.com/show_bug.cgi\?id\=2007353

fixes and updates rpms

---

guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Satellite_Server.adoc

Add parameter to update host name URL in Puppet after renaming Satellite Server
https://bugzilla.redhat.com/show_bug.cgi?id=2008947

BZ 2008947: Procedure to rename Satellite Server

---

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc

This is the follow-up in addition to [#784](https://github.com/theforeman/foreman-documentation/pull/784)

Keep external db config for both Mongo and Postgres in Satellite 6.9

---

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc

This matches proc_migrating-to-external-databases.adoc and ensures that PostgreSQL doesn't run on the system, which is the entire point of using an external database in the first place.
I have removed the Verify the status part since PostgreSQL shouldn't be running at all. It could also be changed to verify it isn't running. I'm not sure what's best here.

Set --foreman-db-manage false in ext DBs

---

guides/common/modules/proc_configuring-the-base-operating-system-with-offline-repositories.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Backup_Disaster_Recovery.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Configuring_Identity_Management.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Logging_and_Reporting_Problems.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Maintenance.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Using_IdM.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/configuring-tls-for-secure-ldap.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/gss-proxy.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/utilities-for-collecting-log-information.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc
guides/doc-Planning_Guide/topics/Introduction.adoc
guides/doc-Provisioning_Guide/topics/app_create_images.adoc
guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc

This PR replaces `{ProjectName} Server` and `{ProjectName} {SmartProxyServer}` with proper attributes:
find guides -iname "*.adoc" | xargs sed -i 's/{ProjectName} Server/{ProjectServer}/g'
find guides -iname "*.adoc" | xargs sed -i '' 's/{ProjectName} {SmartProxyServer}/{SmartProxyServer}/g'

Use ProjectServer and SmartProxyServer attributes

---

guides/doc-Planning_Guide/master.adoc
guides/doc-Quickstart_Guide/master.adoc
guides/doc-Upgrading_and_Updating/master.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc

Three guides are currently empty:
- [Planning for Foreman](https://docs.theforeman.org/nightly/Planning_Guide/index-foreman-el.html)
- [QuickStart Guide](https://docs.theforeman.org/nightly/Quickstart_Guide/index-katello.html)
- [Upgrading and Updating Foreman](https://docs.theforeman.org/nightly/Upgrading_and_Updating/index-foreman-el.html)
This PR removes the conditionals to show content again.

Some guides in nightly are empty

---

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc

For https://github.com/theforeman/foreman/pull/8855,
proxy must have enabled *Registration* and *Templates* features

Registration - required templates on proxy

---

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc

https://issues.redhat.com/browse/SATDOC-469
Relates to https://bugzilla.redhat.com/show_bug.cgi?id=2007494

SATDOC-469: Remove MongoDB mentions

---

drafts/architecture/components/pulp.adoc

This does a couple things aiming towards collaboration and centralization of architecture documentation.
1) Introduces a `drafts/` folder for collaborative development while working towards being able to publish
2) Adds a sub-folder for architecture documentation
3) Adds a component folder and transfer Pulp 3 information from https://github.com/theforeman/puppet-pulpcore/blob/master/README.md#installation-layout

Add Pulp 3 component architecture draft

---

guides/common/assembly_synchronizing-content-between-foreman.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc
guides/doc-Planning_Guide/topics/Deployment_Scenarios.adoc

This PR sets the `ISS` acronym from "Inter-Satellite Synchronization" to "Inter-Server Synchronization".
Example: [Issue in upstream guide](https://docs.theforeman.org/nightly/Content_Management_Guide/index-katello.html#Synchronizing_Content_Between_Servers_content-management)

Set ISS acronym to Inter-Server Synchronization

---

.github/workflows/deploy.yml
guides/common/Makefile

Our Github Action builds HTML pages for all variants and then it calls linkchecker on them. So far so good.
Now, we build with BaseURL that points to real sites:
* docs.foreman.org
* Red Hat Docs
* ATIX docs
Problem is, real sites are often out of date.
This patch solves it, it builds all HTML pages with BaseURL set to `file:///absolute/path/to/build/dir/` which then correctly maps all links. Link validation is more relevant as it checks links of the actual pull request. It is also faster.
And I also found that we call the linkchecker 5 times instead of just one. This will dramatically speed up pull request tests.

Build and check with local HTML links

---

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc

The changes from #554 were committed to 2.5 by a7f2017.
Later, it looks like b2a5f6b committed a whole slew of other (unwanted) changes while trying to cherry-pick the same PR.
a7f2017 (changes from #554) --> 18 additions and 48 deletions 👍 
b2a5f6b (changes from #554) --> 59 additions and 177 deletions 👎 
This reverts commit b2a5f6b2cc7521d0c1a55236b9696a260f2a77a0.

Revert "Changes/Modifications to the import/export guide (#554)"

---

guides/common/modules/con_provisioning-overview.adoc
guides/doc-Provisioning_Guide/master.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/configuring-the-discovery-service.adoc
guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
guides/doc-Provisioning_Guide/topics/proc_creating-hosts-from-discovered-hosts.adoc
guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc

Where relevant ifndef and ifdef statement s have been used to remove material from Satellite documentation
Bug 1938633 - We have to remove those topic from documentation, which we removed functionality from new satellite version
https://issues.redhat.com/browse/SATDOC-473

Removed information from Satellite docs which is no longer supported

---

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc

Bug 2013267 - Need to update time required to complete the upgrade in Prerequisites section of Sat6.10
https://issues.redhat.com/browse/SATDOC-477

Added statement that Pulp migration increases upgrade time

---

.github/workflows/deploy.yml

I tried but this is the best I am able to achieve with GHA.
This makes PDFs to be built only when we deploy (merge into master). It is slow and we have never had a build failure for PDF. It is safe to do.

Build PDFs only on deploy

---

guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc

BZ 2021473: Specify disk space requirement for Pulp content migration on 2.5

---

guides/common/assembly_importing-content.adoc
guides/common/modules/proc_configuring-selinux-to-permit-content-synchronization-on-custom-ports.adoc

Hello
Changes as discussed in: 
[ BZ#2012250 SELinux: denied name_connect comm="pulpcore-worker"](https://bugzilla.redhat.com/show_bug.cgi?id=2012250)

Add Config SELinux for Repos on Custom Ports

---

guides/common/assembly_installing-server-connected.adoc
guides/common/assembly_managing-red-hat-subscriptions.adoc
guides/common/modules/con_introduction-to-content-management.adoc
guides/common/modules/proc_adding-images-to-server.adoc
guides/common/modules/proc_adding-server-as-a-dynamic-inventory-item.adoc
guides/common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc
guides/common/modules/proc_disabling-dns-dhcp-tftp-for-unmanaged-networks.adoc
guides/common/modules/proc_verifying-dns-resolution.adoc
guides/common/modules/ref_capsule-server-scalability-considerations.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Logging_in_to_Red_Hat_Satellite.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/Using_Active_Directory.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/configuring-tls-for-secure-ldap.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/creating-a-compliance-policy.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/scap-content.adoc
guides/doc-Administering_Red_Hat_Satellite/topics/xccdf-profile.adoc
guides/doc-Managing_Hosts/topics/Registering_Hosts.adoc
guides/doc-Managing_Hosts/topics/creating-an-insights-plan.adoc
guides/doc-Managing_Hosts/topics/ref_advanced-bootstrap-script-configuration.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/app_create_images.adoc
guides/doc-Provisioning_Guide/topics/ref_discovery-template-and-snippets.adoc
guides/doc-Upgrading_and_Updating/topics/introduction_upgrading_satellite.adoc

Previously, Satellite was branded as "Satellite 6" to differentiate between "Satellite 5". The product is no longer supported and Satellite marketing is moving towards simply using "Red Hat Satellite". Therefore the attribute `{ProjectX}` which rendered as `Satellite 6` or `Foreman` is not needed.
This patch removes the attribute and all uses:
find guides -iname "*.adoc" | xargs sed -i 's/{ProjectX}/{Project}/g'
I would like blessing from @ares for this.

Remove ProjectX attribute

---

.github/PULL_REQUEST_TEMPLATE.md

We had issues with backporting some of the changes. Cherry picking is mostly seamless process, but due to amount of changes recently and also due to the fact that Red Hat Documentation team requires backporting into one year old branch, we very often encounter conflicts breaking the builds.
This patch removes the checkbox from the PR template and asks authors to file PRs on their own. This way we can ensure good quality by running builds via Github Actions.
I would suggest that Red Hat Documentation team would work earier in the process, e.g. when features are being completed rather than after beta Satellite release to avoid extra work of backporting changes.
https://github.com/theforeman/foreman-documentation/pull/816

Require PRs for backporting

---

guides/common/assembly_managing-suse-content.adoc
guides/common/modules/proc_adding-scc-accounts.adoc
guides/common/modules/proc_creating-a-suse-operating-system.adoc
guides/common/modules/proc_importing-suse-products.adoc
guides/common/modules/proc_installing-the-scc-manager.adoc
guides/common/modules/proc_preparing-suse-installation-media.adoc
guides/common/modules/proc_switching-scc-accounts.adoc
guides/common/modules/proc_synchronizing-suse-content.adoc
guides/doc-Content_Management_Guide/master.adoc

This PR add procedures on how to use the [SCC Manager plug-in](https://github.com/ATIX-AG/foreman_scc_manager) to manage content from SUSE.

Add 'Managing SUSE Content' to Content Management Guide

---

guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc
guides/common/modules/ref_ports-and-firewall-requirements.adoc

The port requirement tables have been redesigned and now incorporate more information on
the functions of each port. They are divided into outgoing and incoming traffic for
Satellite and Capsule
[doc] Reformat the port requirements tables
https://issues.redhat.com/browse/SAT-3277

Reformatted Port Requirement Tables

---

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc

Update procedure Registering a Host to RH Satellite

---

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc

Added a means of testing how complete the migration process is.
Bug 2013689 - Identify when the content migration is completed
https://issues.redhat.com/browse/SATDOC-489

Identify when Pulp migration is complete.

---

guides/common/modules/proc_overwriting-ansible-group-variables-in-application-instances.adoc
guides/common/modules/proc_setting-host-parameters-in-application-definitions.adoc
guides/common/modules/proc_viewing-application-instance-reports.adoc
guides/common/modules/proc_viewing-the-last-deployment-task.adoc
guides/doc-Application_Centric_Deployment/master.adoc

This PR adds four more ACD procedures:
* Add procedure to change host parameters for ACD
* Add procedure to overwrite Ansible group variables in ACD
* Add procedure to view application instance reports for ACD
* Add procedure to view last deployment task for ACD

Extend ACD procedures

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

When provisioning hosts on vSphere, using `open-vm-tools` and
`cloud-init`, one must do some extra configuration of `cloud-init` to
ensure that vSphere gets the correct callback and enables the network
conncetion before `cloud-init` attempts to fetch userdata from
Foreman/Satellite.

Fix instructions on provisioning on vSphere

---

guides/common/attributes-base.adoc

rhel-server-7-satellite-6-rpms --> rhel-7-server-satellite-6.10-rpms
rhel-server-7-satellite-capsule-6-rpms --> rhel-7-server-satellite-capsule-6.10-rpms
rhel-7-server-satellite-tools-6-rpms --> rhel-7-server-satellite-tools-6.10-rpms
via https://bugzilla.redhat.com/show_bug.cgi?id=2023921 and https://bugzilla.redhat.com/show_bug.cgi?id=2023924

fixes rpm versions lacking minor release version

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=1993960

BZ 1993960: Fix preparing image to use cloud-init template on 2.5

---

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

Fix to make master consistent with #847
https://bugzilla.redhat.com/show_bug.cgi?id=1993960

BZ 1993960: Fix preparing image to use cloud-init template

---

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc

Half the provisioning guide was missing as an ifndef was never closed. 

Add missing endif that broke the satellite build

---

guides/doc-Upgrading_and_Updating/master.adoc
guides/doc-Upgrading_and_Updating/topics/introduction_upgrading_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/migrating_a_self_registered_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc

No cherry picks.
This may be an intermediate fix that I need to verify in our internal Pantheon build and I don't have another way of verification than after merge. Unless we make local builds with bccutil work. Sorry!

Fix title and anchor in Upgrading Guide on 2.5

---

guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc

`git blame`: @maximiliankolb  🙈

Fix spelling of separate

---

guides/doc-Administering_Red_Hat_Satellite/topics/proc_estimating-the-size-of-a-backup.adoc

Updated the path of postgresql in backup documentation
Bug 1950553 - Change path of postgresql data directory in backup documentation for Satellite 6.8 and above
https://bugzilla.redhat.com/show_bug.cgi?id=1950553

Changed postgresql path

---

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc

Hello
for Sat7, minor text change as the menu is now greyed to prevent this bug:
Bug 2014251 - Global Registration: Selecting Satellite URL as the proxy fails to register hosts with default config
Using the internal Capsule is the default option, as it always was, its just that if you explicitly selected it you would have port 9090  appended. 
Thank you

Update global reg procedure text

---

guides/common/modules/con_provisioning-templates.adoc
guides/common/modules/proc_adding-scc-accounts.adoc
guides/common/modules/proc_creating-architectures.adoc
guides/common/modules/proc_creating-hardware-models.adoc
guides/common/modules/proc_creating-partition-tables.adoc
guides/common/modules/proc_using-a-synced-kickstart-repository.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc
guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

Hi.
This PR removes links to the management UI chapter of orcharhino docs.
It also fixes from hammer CLI commands and one potential bug where a ifdef has not been visible for satellite. See my comment.

Remove links to orcharhino management UI

---

guides/common/modules/proc_inspecting-available-errata.adoc

Corrected confusing word order for Applicable check box
Confusing word order in description of Applicable check box
https://issues.redhat.com/browse/SATDOC-250
* [X ] Foreman 3.0

Changed word order

---

guides/Makefile

We temporarily disabled linkchecker because adding a new guide
causes the linkchecker to fail the new builds.
The new guide builds just fine, so now re-enabling our checker.

Restore linkchecker

---

guides/common/attributes-base.adoc
guides/common/attributes-foreman-deb.adoc
guides/common/attributes-katello.adoc

This unifies the linking structure and prevents documents from linking back to foreman-el instructions when using Debian or Katello.

Always use the build to refer to documents

---

web/content/3.0.md
web/content/3.1.md
web/layouts/shortcodes/guide-list.html

This PR adds a link to the Release notes from https://github.com/theforeman/foreman-documentation/pull/699. They are currently not visible.

Add link to release notes

---

guides/common/modules/con_provisioning-overview.adoc
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
guides/doc-Provisioning_Guide/topics/proc_creating-hosts-from-discovered-hosts.adoc

There are two PXE less methods in Satellite: one is bootdisk which was limited in 6.10 (only supported bootdisks are Full Host and Subnet disk), that is the change that was supposed to be made. Then we have Discovery PXE less which is still present in Satellite, however, it is technical preview and the feature is not leaving this state until it is fully removed and replaced by something more reliable.
This PR fixes what was introduced in
https://github.com/theforeman/foreman-documentation/pull/794
I should have been more careful when doing the review.

Update support information on bootdisks

---

guides/common/modules/proc_changing-the-host-group-of-a-host.adoc

This got included as part of the modularization effort for the managing hosts.
Removing here is the easiest option available.
@maximiliankolb how did you avoid this in the provisioning guide as that is not in 3.1 but it is on master?

Remove 3.2 feature

---

guides/common/modules/proc_creating-a-compliance-policy.adoc
guides/common/modules/proc_preparing-a-cloud-init-template.adoc
guides/common/modules/proc_setting-the-fips-enabled-parameter.adoc
guides/common/modules/proc_uploading-a-tailoring-file.adoc

This PR fixes three spelling mistakes: `Complicance`, `Paramter`, and `Uplodaing`.

Fix spelling

---

README.md
guides/common/attributes-satellite.adoc
guides/common/attributes.adoc

The branching instructions now first happen by creating the branch. This means the guides will be available by the time the index is created. It also explicitly mentions some steps that were previously missed.
The Satellite versions are updated and now grouped together. It reuses macros to reduce duplication.

Update version numbers and branching instructions

---

guides/common/assembly_migrating-from-internal-databases-to-external-databases.adoc
guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc

This PR moves content from an assembly to an included file. No links are broken & no content is changed.

Modularize administering foreman guide

---

guides/common/modules/proc_disabling-puppet.adoc

Disabling Puppet -- currently unincluded, but will be included only for Satellite, Katello and orcharhino in future.

Add Puppet disablement procedure (unplaced)

---

guides/common/modules/con_introduction-to-content-management.adoc

This PR extends the introduction to the content management guide to provide information on more than RHEL content/subscriptions.

Rework introduction to content management guide

---

guides/common/modules/proc_loading-the-default-openscap-content.adoc

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2029060
* There will not be additional PRs, master and 3.1 are sufficient, because we want to deprecate it in Sat 7.0.

BZ2029060: Upload default OpenSCAP content using Hammer

---

.github/workflows/deploy.yml

And I think we do not need to run `bundle install` even, this is done by setup-ruby automatically.

Drop unnecessary bundle install from GHA

---

.github/workflows/deploy.yml

Nanoc has started to require Psych 3.1 or newer. This is shipped in Ruby 3. Ruby 3.1 actually has 4.0 and nanoc master has started to require that.

Update to Ruby 3.1 in building

---

guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/ref_supported-operating-systems.adoc

Foreman 3.1 dropped Ubuntu 18.04 as a platform. This reflects the change.

Drop Ubuntu 18.04 support

---

guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/ref_supported-operating-systems.adoc

Foreman 3.1 dropped Ubuntu 18.04 as a platform. This reflects the
change.
(cherry picked from commit 345045d50ab737b41e9c0e15ef2bf3f39114750b)

Drop Ubuntu 18.04 support (#969)

---

web/content/js/nav.js

I think this actually looks cleaner.
Also the landing page where we have a list of guides we can essentially kill now and use that space to explain key concepts:
* What is Foreman
* What platforms are supported
* What is Katello and why it is different
I also made the following changes:
* Added Release Notes missing guide.
* Moved Planning guide to Katello menu (it's not very relevant in Foreman context).

Use three columns menu to separate EL/DEB

---

web/content/js/nav.js

This guide does not exist for Debian and shouldn't be linked.

Remove Application Centric Deployment on Debian

---

guides/common/assembly_accessing-server.adoc
guides/common/modules/proc_logging-on.adoc
guides/doc-Administering_Red_Hat_Satellite/master.adoc

Installing the Katello root CA is, as the name suggests, a Katello only thing.
The starting and stopping guide relies on foreman-maintain which is unavailable on Debian so the whole section is hidden.
The external PostgreSQL guide is EL7 only (even incorrect on EL8 which is supported). For now it's just hidden on Debian but this needs serious work.
Additionally, OpenSCAP is unavailable on Debian so the sections are hidden.
This works towards resolving https://github.com/theforeman/foreman-documentation/issues/676.

Admin guide: hide invalid sections

---

guides/common/modules/proc_installing-postgresql.adoc

There is no reason to assume a whole /24 subnet needs access. This is insecure and can create security problems. By only allowing /32 it's limited to the exact IP.

Only allow the exact remote IP for Foreman

---

guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
guides/doc-Installing_Satellite_Server_Disconnected/master.adoc
guides/doc-Installing_Server_on_Red_Hat/master.adoc

Alternative cname, custom certs and external DB are only valid on Katello scenarios. Eventually these should be written for non-Katello but for now this hides the invalid sections.

Install guides: Hide invalid sections

---

guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/proc_installing-the-satellite-server-packages.adoc
guides/common/modules/ref_storage-requirements.adoc
guides/common/modules/ref_supported-operating-systems.adoc

It is better to list the newest first since we want to encourage users to use the latest version.
I also noticed we don't list RHEL 8 support while in upstream I think it should work. In general I've been thinking about merging some sections into just EL7 or EL8 but that can change the scope quite a bit so I won't do it in this PR.

List CentOS 8 before CentOS 7

---

web/content/css/_nav.scss

Many guide names are longer than the width of the title. This resizes the nav to fix the content. According to [caniuse](https://caniuse.com/mdn-css_properties_flex-basis_max-content) it's not available on all browsers, but at least on most. On unsupported browsers I'd expect it to behave as it previously did.

Make the drop downs fit the width of the content

---

guides/common/modules/proc_salt-authenticating-salt-minions-using-salt-autosign-grains.adoc

From now on, the corresponding reactor file calls a runner which retrieves the parameters (that were given manually before) from `/etc/salt/foreman.yaml`.
Please review my PR @bastian-src.

Remove Salt reactor configuration step

---

web/content/css/_nav.scss
web/content/js/nav.js
web/layouts/nav.html.erb

So Mel had a good point that with removal of 2.4 we lost Katello 4.0 docs. That was not intentional, I will backport the nanoc/JS/CSS changes also into 2.4 and re-publish it.
I am also trying to improve the version switcher so it is more clear what Foreman/Katello version are you on. However, the box is running from screen.
H.E.L.P.

Put F2.4/K4.0 back and improve version switcher

---

web/content/js/nav.js

We've moved content from the content management guide, but we currently don't show it in the navigation.

Show convert2rhel guide

---

.github/workflows/deploy.yml
Gemfile
guides/Makefile
guides/common/Makefile
guides/doc-Administering_with_Ansible/master.adoc
guides/doc-Configuring_Ansible/master.adoc
guides/doc-Installing_Proxy_on_Debian/master.adoc
guides/doc-Installing_Proxy_on_Red_Hat/master.adoc
guides/doc-Installing_Satellite_Server_Disconnected/master.adoc
guides/doc-Installing_Server_on_Debian/master.adoc
guides/doc-Installing_Server_on_Red_Hat/master.adoc
guides/doc-Quickstart_Guide/master.adoc

So it turns out we have several issues.
Asciidoctor PDF now has a missing dependency "matrix". Without this gem, PDF generation simply fails, probably a bug usptream.
Second problem actually hid the first one - I added `asciidoctor ... | tee LOGFILE; grep LOGFILE` to search for warnings which were never returned via exit code by asciidoctor, but I haven't realized that the pipe always returns zero exit code so even when HTML/PDF generation was broken (we had brokens links), makefile was still returning zero.
After I fixed the tee problem, a third appeared - recursive make implementation did not care about return codes from the submakes at all, therefore when targets "all-html" or "all-pdf" were called, it always returned zero even if we had issues (warnings via the grep command).
Finally, …

Fix PDF generation, exit code from make and parallelization

---

guides/common/modules/proc_configuring-satellite-for-outgoing-emails.adoc

Fixed the hyperlink for issue #33543 in section 4.6 Configuring Foreman server for Outgoing Emails.
@melcorr

Fixed link in sendmail configuration

---

guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc

This  commit adds the steps that would enable customer to upgrade from
6.10.0 -> 6.10.z in an airgapped downstream server.

In-place upgrade in an airgapped server

---

guides/common/modules/ref_template-macros.adoc

Added information about the truthy and falsy macros in the Templates Macros section of the Template Writing Reference appendix in the Managing Hosts document.
@melcorr

Added information about truthy and falsy macros

---

guides/common/modules/con_iss-import-export-cheat-sheet.adoc
guides/common/modules/con_monitoring-resources.adoc
guides/common/modules/proc_connected-foreman-for-managing-content-view-versions.adoc
guides/common/modules/proc_creating-a-composite-content-view.adoc
guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_creating-an-activation-key-to-consume-the-content-view.adoc
guides/common/modules/proc_exporting-a-content-view-version.adoc
guides/common/modules/proc_exporting-the-library-environment.adoc
guides/common/modules/proc_importing-a-content-view-version.adoc
guides/common/modules/proc_prerequisites-for-puppet.adoc
guides/common/modules/proc_promoting-a-content-view.adoc
guides/common/modules/proc_switching-scc-accounts.adoc
guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc
guides/common/modules/ref_webhooks-available-events.adoc

- Fixed instances where "Content Views" have been mentioned as "content views".
- Added an oxford comma in con_monitoring-resources.adoc.
- Capitalized "Lifecycle Environment" in proc_prerequisites-for-puppet.adoc
- Replaced "them" with "then" in proc_connected-foreman-for-managing-content-view-versions.adoc
@melcorr

Capitalize "Content View" and fix minor typos

---

guides/Makefile
guides/common/attributes-base.adoc
guides/common/attributes.adoc
guides/common/linkchecker.ini
guides/common/modules/con_host-global-status-overview.adoc
guides/common/modules/con_template-writing-reference.adoc
guides/common/modules/proc_salt-salt-variables.adoc

This is an alternative to https://github.com/theforeman/foreman-documentation/pull/1057 which takes some commits, but also does something different.
Rather than disabling the linkchecker because something is unavailable in downstream, this takes the approach of ignoring those broken links.

Re-enable linkchecker and fix broken URLs

---

guides/common/linkchecker.ini

There is no corresponding Satellite release to Foreman 3.2 so there is no point in checking.

Disable link checker for downstream docs

---

guides/common/modules/proc_restrict-custom-repository-RHEL9.adoc

FYI: I've checked; the anchor is not referenced anywhere.

Add underscore before context in anchor

---

guides/common/modules/proc_configuring-repositories.adoc

Yum can handle this and it's fewer steps for the user. This means a shorter guide.

Install *-release* packages on CentOS 7 in a single step

---

guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
guides/common/modules/con_content-management-types-overview.adoc
guides/common/modules/con_introduction-to-content-management.adoc
guides/common/modules/con_iss-scenarios.adoc
guides/common/modules/con_managing-content-views.adoc
guides/common/modules/con_provisioning-cloud-instances-on-openstack.adoc
guides/common/modules/con_provisioning-contexts.adoc
guides/common/modules/con_provisioning-virtual-machines-in-vmware.adoc
guides/common/modules/proc_adding-server-as-a-dynamic-inventory-item.adoc
guides/common/modules/proc_configuring-selinux-to-ensure-access-on-custom-ports.adoc
guides/common/modules/proc_creating-a-composite-content-view.adoc
guides/common/modules/proc_creating-a-remote-file-repository.adoc
guides/common/modules/proc_promoting-content-across-the-application-life-cycle.adoc
guides/common/modules/proc_registering-a-host-using-the-bootstrap-script.adoc
guides/common/modules/proc_registering-an-atomic-host.adoc
guides/common/modules/proc_using-activation-keys-for-host-registration.adoc
guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc
guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc
guides/common/modules/ref_ports-and-firewall-requirements.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc
guides/doc-Upgrading_and_Updating/topics/migrating_a_self_registered_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc

Cosmetic fine tuning. An attempt to remove version number from the project name, i.e. replacing {ProjectNameX} with {ProjectName}, where (hopefully) applicable.
Cherry-pick to:

Fix usage of attributes (ProjectName)

---

guides/doc-Release_notes/topics/katello-4.4.0.adoc
guides/doc-Release_notes/topics/katello-contributors.adoc
guides/doc-Release_notes/topics/katello.adoc

The changelog will be updated after the first RC and so on.

Add initial Katello 4.4.0 changelog entries

---

guides/common/assembly_configuring-satellite-with-an-http-proxy.adoc

this applies equally to Satellite *and* Katello installs

include "HTTP Proxy to Connect to Red Hat CDN" for Katello

---

web/content/index.adoc
web/content/js/nav.js
web/content/release-3.2.adoc

I've added some changes to get the process of publishing Foreman 3.2 (and hence Katello 4.4) docs.  This process needs to happen before I can make the release announcement since Katello relies on this new documentation website.
I'm not certain I edited everything correctly, so I need some help there. Also, is it right to say 3.2 is in the "RC-phase" as I did? It didn't seem right to say it's stable yet.

Add Foreman 3.2 links

---

guides/common/assembly_preparing-environment-for-installation-in-ipv6-network.adoc
guides/common/modules/con_adding-network-interfaces.adoc
guides/common/modules/con_applying-custom-configuration.adoc
guides/common/modules/proc_configuring-installation.adoc
guides/common/modules/proc_creating-a-webhook.adoc
guides/common/modules/proc_salt-importing-salt-states.adoc
guides/common/modules/proc_salt-running-salt.adoc
guides/common/modules/proc_salt-salt-example.adoc

This PR fixes various broken xrefs and simplifies (use xref directly without attribute containing the path to the guide) where possible.

Links with context

---

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc

Fixed the command to install satellite-clone

---

guides/doc-Planning_Guide/topics/Introduction.adoc

While planning it's good to know that there are EL8 packages. In fact, in upstream EL7 has been deprecated already and we may drop EL7 support in this or the next release.

Mention that there are EL8 packages

---

guides/common/Makefile

It was reported to me that guides do not build on MacOS because there are no hardlinks. Poor MacOS users, let's fix that :)

Allow building on Darwin

---

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc

In the section "Preparing to Migrate Content to Pulp 3", I added some new guidance on what to do if the "content prepare" upgrade step results in unmigratable contents from Red Hat repositories using on-demand policy. I added a new paragraph for the reader to find the instructions in a Knowledge base Solution and provided the link to determine what repositories the unmigratable contents belong to. I removed a paragraph discussing a percentage of missing or corrupted RPMs and modified a paragraph discussing repositories containing unmigratable contents being configured on Satellite with the On-demand download policy.
@melcorr 

Changed guidance for causes of corrupted content

---

README.md

I've updated the README to reflect the steps I had to take to set up the Foreman 3.2 + Katello 4.4 docs links.
There may be other steps to add as well, so feel free to suggest more changes.

Update the README to reflect the current branching process

---

guides/common/modules/proc_using-the-project-content-dashboard.adoc
guides/common/modules/ref_navigation-tabs-in-web-ui.adoc

In tables, you cannot use `image::`, but instead, must use inline images like `image:`.

Use inline images in tables

---

guides/common/attributes.adoc

With the release of Foreman 3.1 version 2.5 became unsupported.

Declare Foreman 2.5 unsupported

---

guides/common/modules/proc_configuring-repositories-el.adoc

While Puppet 6 is still supported, it's better to use Puppet 7.

Use Puppet 7 to install

---

web/content/js/versions.js

Fixes: 94bc6cdf7ae08ae87605ab723497ac02ba963c7b
@lzap I don't think this needs to be picked to stable releases, only the HTML part, right?

Correct the Foreman 3.2 state in navigation

---

guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
guides/common/modules/proc_configuring-external-dns.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2060420
Do not cherry-pick. There will be a separate PR for master+3.1+3.2.

Unlock packages before installing bind-utils 2.5

---

guides/common/modules/proc_adding-custom-deb-repository-example-for-debian-11.adoc

broken link: http://deb.debian.org/debian-security/dists/bullseye/updates
fixed link: http://deb.debian.org/debian-security/dists/bullseye-security

Fix release name of Debian Bullseye repo

---

guides/doc-Managing_Hosts/topics/Registering_Hosts.adoc

Removed the mention of RHEL 5 support
Bug 2062040 - Adding a note about RHEL5 and katello-host-tools on Satellite 6.10
https://bugzilla.redhat.com/show_bug.cgi?id=2062040

Removed RHEL5 mention

---

guides/common/modules/con_registering_hosts.adoc
guides/common/modules/proc_changing-the-method-the-bootstrap-script-uses-to-download-the-consumer-rpm.adoc
guides/common/modules/proc_creating-a-domain-for-a-host-during-registration.adoc
guides/common/modules/proc_enabling-remote-execution-on-the-host.adoc
guides/common/modules/proc_migrating-a-host-from-one-server-to-another-server.adoc
guides/common/modules/proc_migrating-a-host-from-red-hat-network.adoc
guides/common/modules/proc_providing-an-alternative-fqdn-for-the-host.adoc
guides/common/modules/proc_providing-the-hosts-ip-address.adoc
guides/common/modules/proc_registering-a-host-for-content-management-only.adoc
guides/common/modules/proc_registering-a-host-using-the-bootstrap-script.adoc
guides/common/modules/proc_registering-a-host-without-puppet.adoc

I ran `find guides -iname "*.adoc" | xargs sed -i "" "s/{RHEL} 5, 6/{RHEL} 6/g"`. Note that GNU sed does not require `""` with the `-i` option.

Remove RHEL 5

---

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc

A missing line between two instructions was added.
Include More Information Regarding Concerns During the Pulp 2 to Pulp 3 Migration
https://issues.redhat.com/browse/SATDOC-548

Added missing line from Pulp migration instructions

---

guides/common/assembly_configuring-external-idm-dns.adoc
guides/common/modules/con_host-substatus-overview.adoc
guides/common/modules/con_permissions-for-remote-execution.adoc
guides/common/modules/proc_adding-server-as-a-dynamic-inventory-item.adoc
guides/common/modules/proc_applying-errata-to-a-host.adoc
guides/common/modules/proc_applying-errata-to-multiple-hosts.adoc
guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
guides/common/modules/proc_enabling-power-management-on-managed-hosts.adoc
guides/common/modules/proc_promoting-a-content-view.adoc
guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
guides/doc-Configuring_Load_Balancer/topics/Promoting_SCAP_Content_to_Clients.adoc
guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc

Basically, empty titles only work for xrefs, but not DocURL links. See also commit message.

Add title to link with DocURL attribute

---

guides/common/assembly_managing-users-and-roles.adoc
guides/common/modules/proc_creating-an-api-only-user.adoc

You can create a user with a secret password that you don't save to disable log-in to the Foreman Web UI.

Add procedure to create API-only user

---

guides/common/attributes-satellite.adoc
guides/common/linkchecker.ini

Current development is tracking what will become Satellite 6.12.
https://github.com/theforeman/foreman-documentation/pull/1166 already corrects 3.1 but I wasn't quite sure what to with 3.2. Technically it doesn't map to any Satellite. You could do something like 3.12-pre but it's probably best to ignore it altogether.

Correct Satellite versions

---

guides/common/assembly_managing-organizations.adoc
guides/common/modules/con_managing-organizations.adoc

The default organization is named Default Organization, which results in Default_Organization as a label but this doesn't refer to labels.
I contemplated mentioning that it's affecter by the --initial-organization installer argument, but wasn't sure how to mention this clearly.
Debug certificates are a content feature, which only exists with Katello.  This means the content can be removed.
Technically this can be cherry picked but we hide all guides for non-Katello releases from the navigation so it doesn't matter that much. The other change is also pretty trivial.

Correct the default organization name & hide debug certs in non-Katello context

---

guides/common/assembly_configuring-an-alternate-cname.adoc
guides/common/modules/proc_adding-life-cycle-environments.adoc

This note is unnecessary because we only show these procedures in guides for Katello users.

Hide Katello only note

---

guides/common/modules/con_download-policies-overview.adoc
guides/common/modules/proc_adding-custom-deb-repositories.adoc

With Katello 4.1, it is also possible to download APT content "on-demand".
I am unsure about the second commit. The whole wording sounds off to me but I didn't come up with something better, so I just added `deb`.

Document new APT download policy "on-demand"

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Per SATDOC-6404, there was a condition ifdef:: for Katello right before the steps for "Regenerate certificates". A condition for Satellite needed to be added so it was added to ifdef::katello to appear as ifdef::katello,satellite.
* [**YES**] Foreman 3.2
* [**YES**] Foreman 3.1

Added condition for Satellite to command in line 43

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Included a new pre-check step (Ensure that "apache::purge_configs: false" entry is either not present or commented out in /etc/foreman-installer/custom-hiera.yaml file of The Red Hat Satellite 6.9\Capsule 6.9 servers which will be upgraded to 6.10)in the Updating and Upgrading in three sections.
@melcorr 

Included a pre-check step in three sections

---

guides/common/modules/con_troubleshooting.adoc
guides/doc-Installing_Server/master.adoc

I've removed the Debian-related fix because it's not cherry-picked into Katello 4.3 yet.

Cherry-pick: Add troubleshooting section for Katello

---

guides/common/modules/proc_exporting-a-repository.adoc
guides/doc-Content_Management_Guide/topics/Using_ISS.adoc

We need this fix for ccutil build.

Fix include path and reference 2.5

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Although, the brackets were present in last modification but there should be two brackets for the attributes that we
mentioned in the command. I removed it earlier considering the normal attribute instead command one.
Capsule 6.10 Upgrade Guide Step 14 to do Complete Capsule sync using hammer correction
https://issues.redhat.com/browse/SATDOC-717

Added the missing brackets with reference to last commit

---

guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc

Drop EL7 doc link from sync sys clock with chronyd

---

guides/common/modules/con_troubleshooting.adoc
guides/common/modules/proc_configuring-repositories.adoc
guides/doc-Installing_Server/master.adoc

Now that there's a proper module on EL8 this should be used.
In practice a user may see conflicts if the Ruby 2.5 or PostgreSQL module has been enabled. Those are the default modules but foreman (and thus katello) pulls in ruby:2.7 and postgresql:12. This means a user must run that version.
In case of PostgreSQL it can be that there's already a version 10 database. In that case an upgrade must be performed, but this is not documented. This can be considered unsupported for installations.
However, there are essentially no real upgrade instructions anyway. It's all part of foreman-maintain but that may result in a chicken-and-egg situation where you would need updated modules to update. So for now I'm not touching that.
This is only relevant for nightly now. Ideally speaking this goes into …

Use modularity on EL8

---

guides/common/modules/con_download-policies-overview.adoc
guides/common/modules/proc_importing-container-images.adoc

- Added xref to the changing download policy doc in the repo discovery section of "Importing Container Images" in the Content Management guide.
- Changed the description for download policies in the "Download Policies overview section".
@melcorr

Add information about changing download policies for docker images

---

guides/common/modules/ref_project-settings.adoc

Since the bug related to wildcard for "Exclude pattern for facts stored" and "Ignore interfaces with matching identifier" has been resolved, updating ref_project-settings.adoc with the latest information.
@melcorr

Update project settings to reflect latest information

---

.gitignore
guides/common/Makefile

Turns out MacOS/BSD does not support dereferencing. It is not a hard requirement, it looks like recursive copy does dereference `images/common` symlink anyway when making hard links on Linux. On MacOS (tested) it also dereference by default so it works as expected.

Do not use link dereferencing on MacOS

---

guides/common/linkchecker.ini

I've updated the linkchecker.ini  file to ignore all links that include the following string: access.redhat.com/documentation/en-us/red_hat_satellite/6.11" 
The reason is that the docs for Satellite 6.11 are not published yet.

linkchecker.ini to ignore links to Satellite 6.11

---

guides/common/modules/con_managing-ostree-content.adoc

OSTree is not enabled by default: https://github.com/theforeman/puppet-foreman_proxy_content/blob/ec6f3e75476c76b3f0389873aafb02ea192e96ff/manifests/init.pp#L121

OSTree is not enabled by default

---

guides/common/attributes.adoc

fix previous version of nightly being 3.2 not 3.1

---

guides/doc-Upgrading_and_Updating/topics/post_upgrade_tasks.adoc

Per SATDOC-657, added steps to disable katello-agent in installed versions of Satellite 6.10 and Capsule 6.10 due to deprecation of the katello-agent for future releases after 6.10. The request was to have these steps at the beginning of Chapter 4.

Added steps for disabling katello-agent

---

guides/common/modules/con_managing-content-views.adoc

Added definition
Bug 2000717 - [RFE]: Add information about what the "Default Organization View" is on Satellite
https://bugzilla.redhat.com/show_bug.cgi?id=2000717

Added definition of Default Organization View

---

guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc

Removed two mentions of sticky sessions
[doc] - Load balanced content with Capsules without sticky sessions  
https://issues.redhat.com/browse/SAT-6400

Removed mention of sticky sessions

---

guides/common/assembly_managing-container-images.adoc
guides/common/modules/proc_configuring-podman-to-trust-the-ca.adoc
guides/common/modules/proc_using-container-registries.adoc

Added text
Bug 2052838 - Podman login fails with : x509: certificate signed by unknown authority
https://bugzilla.redhat.com/show_bug.cgi?id=2052838

Added information on configuring podman to trust the CA

---

guides/doc-Content_Management_Guide/topics/Importing_Content.adoc

A new option was replaced i.e "Verify Content Checksum" with
Validate Content Sync as it is no longer an option for an advanced
synchronization in Satellite 6.10
"Validate Content Sync" is no longer an option for "Recovering a
Repository"
https://issues.redhat.com/browse/SATDOC-728

Replaced the new option in Recovering a Repository topic

---

guides/common/modules/proc_using-red-hat-insights.adoc

Described how to access insights information on hosts and recommendations.
[doc] - Improved Insights adoption
https://issues.redhat.com/browse/SAT-4686

Added location of insights host information

---

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc

The installer flags need to be updated as they should have the
correct username. The command replacement is applicable to
connected and disconnected networks both.
External database documentation need modification for user
https://issues.redhat.com/browse/SATDOC-751

Replace the command - Configuring Satellite to use External Databases

---

guides/common/modules/ref_performing-configuration-management.adoc

For xrefs, we should not hard-code the context but use the `{context}` attribute instead.

Remove context from xref

---

guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc

Ports had been removed from table 1.2 after Satellite 6.5. This change puts them back.
The information is current for Satellite 6.9. Note that the information in satellite 6.1/Foreman 2.5
is expanded and corrected.
Bug 1958092 - [Doc] Firewall documentation missing ports
https://bugzilla.redhat.com/show_bug.cgi?id=1958092

Added missing ports

---

guides/common/modules/proc_creating-a-local-file-repository.adoc

Added an alternative to the existing method which avoids downtime
calling satellite-installer in order to install the package python-pulp-manifest
https://issues.redhat.com/browse/SATDOC-244
* [X ] Foreman 3.0

Add alternative to installing pulp-manifest package

---

guides/common/modules/ref_supported-browsers.adoc

Per SATDOC-652, I updated the recommended the Supported Browsers list for Foreman 3.3.

Updated Supported Browsers List for Foreman 3.3

---

guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc

Separate PR for 3.0 which is not modularized. Changed to python3 where necessary.
Added the alternative method. Python3 step stops the server and increases downtime.
The alternative method does not.
calling satellite-installer in order to install the package python-pulp-manifest
https://issues.redhat.com/browse/SATDOC-244

Add alternative to pulp-manifest package

---

guides/common/modules/proc_using-a-synced-kickstart-repository.adoc

Note on enabling BaseOS and AppStreamm kickstart added.
Bug 2027484 - Provide info about AppStream unmanaged content
https://bugzilla.redhat.com/show_bug.cgi?id=2027484

Added note on enabling kickstart.

---

guides/common/modules/proc_using-a-synced-kickstart-repository.adoc

Note on enabling BaseOS and AppStreamm kickstart added.
Bug 2027484 - Provide info about AppStream unmanaged content
https://bugzilla.redhat.com/show_bug.cgi?id=2027484

Added note on enabling kickstart

---

guides/doc-Content_Management_Guide/topics/Managing_Content_Views.adoc

Added supplied information on Content View filters and Dependency Solving.
Bug 2034804 - Document (un)supported combinations of CV filters and dependency solving
https://bugzilla.redhat.com/show_bug.cgi?id=2034804

Corrected information on CV filters and dependency solving.

---

guides/doc-Release_notes/README.md

Fix typo in release note guide's READEME file.

---

guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc

I reworded the second to last bullet point of Section 2.2 per SATDOC-755. The IPv4 HTTP proxy is needed between the Satellite and the CDN, not the Satellite and the hosts. This was reworded based on the recommendation in the ticket.

Reworded Section 2.2 per SATDOC-755

---

Makefile
README.md
guides/README.md

It looks our `bundle install` must be done both in the root and web/ directories. This moves this into a new make target. Also Ruby is marked as deprecated on MacOS now and will not be updated from the legacy 2.6 version, so use brew Ruby instead.
Also serve is the default makefile target, that is confusing. Perhaps html is a better target.

Update MacOS build instructions

---

guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc

In Section 3.1 in Before You Begin, I removed any and all references to Foreman Hooks because they have been deprecated for future versions.

Removed reference to Foreman Hooks per SATDOC-918

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Per SATDOC-645, I added the steps for remote execution in Upgrading Capsule Servers from 6.9 Upgrading and Updating Guide into the same section in 6.10.
@melcorr 

Added REX section from 6.9 to 6.10 per SATDOC-645

---

guides/common/attributes-orcharhino.adoc

For inspiration: we restructured our downstream documentation: [all guides are now split by OS](https://docs.orcharhino.com/or/docs/sources/guides.html). cc @melcorr @Lennonka 

Bump orcharhino version

---

guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_without_Puppet_for_Load_Balancing.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_without_Puppet.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc

find guides -type f -iname "*.adoc" | xargs sed -i "" "s/--enable-foreman-proxy-plugin-remote-execution-ssh/--enable-foreman-proxy-plugin-remote-execution-script/g"
See discussion in Foreman Community Forum: [Foreman Remote Execution Plugin Documentation](https://community.theforeman.org/t/foreman-remote-execution-plugin-documentation/28889?u=maximilian)
I did not test/verify this change myself. I'd appreciate confirmation from a developer.

Update installer command for REX plugin

---

guides/common/modules/proc_configuring-an-alternative-directory-to-execute-remote-jobs-on-clients.adoc
guides/common/modules/proc_configuring-kerberos-authentication-for-remote-execution.adoc

Follows up on https://github.com/theforeman/foreman-documentation/pull/1301
```
foreman-3.3.0-0.5.rc1.el7.noarch
--[no-]enable-foreman-proxy-plugin-remote-execution-script Enable 'foreman_proxy_plugin_remote_execution_script' puppet module (default: true)
--foreman-proxy-plugin-remote-execution-script-cockpit-integration  Enables/disables Cockpit integration (current: true)
--reset-foreman-proxy-plugin-remote-execution-script-cockpit-integration Reset cockpit_integration to the default value (true)
--foreman-proxy-plugin-remote-execution-script-mode  Operation Mode of the plugin. (current: "pull-mqtt")
--reset-foreman-proxy-plugin-remote-execution-script-mode Reset mode to the default value ("ssh") …
```

Update installer commands for REX plugin

---

guides/common/assembly_installing-capsule-server.adoc
guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/proc_installing-capsule-server-packages.adoc
guides/common/modules/proc_installing-the-satellite-server-packages.adoc
guides/common/modules/proc_registering-to-red-hat-subscription-management.adoc
guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc
guides/common/modules/proc_verifying-firewall-settings.adoc
guides/common/modules/ref_capsule-storage-requirements.adoc
guides/common/modules/ref_ports-and-firewall-requirements.adoc
guides/common/modules/ref_storage-requirements.adoc
guides/common/modules/ref_supported-operating-systems.adoc

Added the new repositories for Satellite and Capsule Servers v6.11
supporting RHEL 8. Also, added the new content and modified the
existing one wherever required to make the documentation more accurate.
Support Satellite and Capsule running on RHEL 7 and RHEL 8 - commands
in the installation docs should reflect RHEL 8.
https://issues.redhat.com/browse/SAT-9421

Add the Repositories and repair the content for RHEL 8

---

guides/common/attributes.adoc
guides/common/modules/proc_upgrading-el7-to-el8.adoc
guides/doc-Upgrading_and_Updating/master.adoc

Created a new module for the master.adoc for Upgrading and Updating Foreman. This module is titled proc_upgrading-el7-to-el8.adoc. The content came from an existing document and was cleaned up for minimalist purposes and grammar. The content was pulled from this link: https://hackmd.io/@evgeni/B1AT256Q5
@melcorr This is the one you needed a PR for. Needed to clean up the content to fit minimalist principles. Did not see any attributes for RHEL so let me know if I missed that.

Created module for RHEL 7 to RHEL 8 upgrade

---

guides/common/attributes.adoc

marking 3.1 as an unsupported version upstream

mark 3.1 as unsupported upstream

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Per SATDOC-944, upgrade step was changed in Upgrading Capsule Servers to reflect the required repository containing the next version of Satellite.

Changed upgrade steps in Upgrading Capsule Servers

---

guides/common/modules/snip_host-registration-steps.adoc

Replaced the correct path of repository which will reflect in
Configuring Load Balancer, Installing Proxy, and Managing Content
section.
Replace /etc/yum.repos.d/redhat.conf with /etc/yum.repos.d/redhat.repo
in the Red Hat Capsule 6.11 installation guide and
anywhere else applicable
https://issues.redhat.com/browse/SATDOC-941

Replaced the path of repository

---

Makefile
guides/README.md

I was asked for give instructions for RHEL8 (CSB) owners, so I updated it. This was tested on CentOS 8 Stream which is hopefully close enough to the internal RHEL8 build in Red Hat.

Update README setup instructions for RHEL8

---

guides/common/attributes-base.adoc

Fixes: bfa9406ec6b2839fe086664957257fb05ac6dd03

correct rhel 7 server repo name

---

guides/common/attributes-base.adoc

we don't use this variable in the docs anymore

drop RepoRHEL8ServerAnsible definition

---

guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc
guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_without_Puppet.adoc

Fixed one of the value in the load balancing guide -
Configuring capsule server with default SSL certificates
for Load Balancing with puppet. Also, fixed the suggestion provided in
the first comment in BZ#2097378.
This is the same PR as PR#1329. Creating this one for the master branch
as per the suggestions provided in the comments on PR#1329 by @maximiliankolb 
[BUG] In the Load Balancing Guide for Satellite 6.10
and foreman upstream, :false" should be replaced with "false"
https://bugzilla.redhat.com/show_bug.cgi?id=2097378

Corrected value in the Load Balancing guides

---

guides/common/modules/proc_configuring-repositories.adoc

Removed the unnecessary reference of OS to avoid confusion. Also,
organized the content to make it more clear.
https://bugzilla.redhat.com/show_bug.cgi?id=2097758

Corrected sequence in numbering and fixed Debian section

---

guides/doc-Upgrading_and_Updating/master.adoc

we originally said this would not be supported, but after some testing,
it does work and would make users lifes easier

render leapp upgrade docs for foreman 3.1/katello 4.3

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

After viewing merged PR #1323, a comment mentioned a command having an extra - so it has been removed. This PR is also needed to cherry pick to 3.3, 3.2, and 3.1 since the original PR didn't get to be cherry picked.

Removed - in line 101 next to self-upgrade

---

guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
guides/common/modules/proc_installing-smart-proxy-upstream.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

the certs-generate command is branded differently between Katello and
Satellite and it's confusing for users to see the wrong name (even if it
works equally fine *technically*)

use the certs-generate attribute instead of foreman-proxy-certs-generate

---

guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc
guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc

Update load balanced Capsule port reference from 8443 to 443

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR add a `CONTRIBUTING.md` file to simplify contributing to Foreman documentation.

Add Contributing guidelines

---

guides/common/modules/proc_upgrading-project-from-el7-to-el8.adoc

it's `Leapp` not `LEAPP`
[ ] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.

correct spelling of Leapp

---

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc

Added ansible repo to the list of repos enabled on the clone system, without which the cloning will fail.

Add missing ansible repo in the upgrade guide

---

.github/PULL_REQUEST_TEMPLATE.md

`[ ]` doesn't render as a checkbox inside github, but `* [ ]` does :woman_shrugging:
[ ] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.

make "I am familiar" a real checkbox

---

guides/common/attributes-foreman-deb.adoc
guides/common/attributes-foreman-el.adoc
guides/common/attributes-katello.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes-titles-overrides.adoc
guides/common/attributes.adoc

Had to remake how title attributes are included, because the definitions were wrongly overwritten.

Remake title attributes (definitions were wrongly overwritten)

---

guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/ref_supported-operating-systems.adoc

add Debian 11 Bullseye to supported OSes

---

guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/ref_supported-operating-systems.adoc

Nightly only, includes #1362 to make the diff sane.

drop Buster from nightly - it's unsupported now

---

guides/common/modules/proc_browsing-repository-content-using-an-organization-debug-certificate.adoc

The URLs that are mentioned at present are incorrect and return
the 404 error because of http:// instead of https://. Updated 
both URLs with the new ones along with https:// as shared by the reporter.
Also, added the type of URL in the address bar of Firefox users.
Fix the url protocol and end points in Section 3.4 Browsing Repository
Content Using an Organization Debug Certificate
https://bugzilla.redhat.com/show_bug.cgi?id=2097382

Replaced the URLs for Firefox and CURL users

---

guides/doc-Planning_for_Project/master.adoc

Add context for Planning guide

---

guides/common/attributes.adoc

Corrected AccessRedHatComVersion attribute for 3.1

---

.github/PULL_REQUEST_TEMPLATE.md

if it's not an absolute link, it ends up being linked to https://github.com/theforeman/foreman-documentation/pull/CONTRIBUTING.md inside a PR which is not resolving as it should

fix contributing link

---

guides/common/modules/proc_installing-and-configuring-the-puppet-agent.adoc

Per SATDOC-968, in Section 1.5 of the Managing Configurations Using Puppet Integration in Red Hat Satellite guide, "The Red Hat Satellite Client Puppet 7.0 repository" was changed to "The Red Hat Satellite Client 6.11 repository."

6.11 version-less client repo for puppet-agent

---

guides/common/modules/proc_migrating-to-external-databases.adoc

Add installer options for setting external database users

---

guides/common/modules/proc_upgrading-project-from-el7-to-el8.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc

Per SATDOC-660, I added a step in Before You Begin in the Upgrading Satellite Server section. The step added is "If you previously upgraded Satellite from 6.7 or an earlier version, or if the /var/lib/pgsql directory has any content, ensure it is empty before proceeding. Satellite 6.11’s migrated postgres database content will be stored in this directory."
* [YES] Foreman 3.2
* [YES] Foreman 3.1

Added new step for /var/lib/pgsql as a prerequisite

---

.github/workflows/preview.yml

GH only allows 65k big comments, but diffs can be bigger :(

deploy diff to surge, don't embedd it

---

.github/workflows/preview.yml

correct paths for diffing -- the preview is in preview

---

guides/common/modules/con_migrating-project-to-el8.adoc
guides/common/modules/proc_creating-a-host.adoc
guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
guides/common/modules/proc_editing-the-system-purpose-of-multiple-hosts.adoc

seems they have been renamed on access.redhat.com

fix performing_a_standard_rhel_installation links

---

.github/workflows/preview.yml

diffstat, by default, tries to strip as many common path prefixes as
possible. that means, if we change files that only affect one guide, it
will also happily strip the guide folder, making the output unusable.
explicitly configure it to strip two levels, which maps to
`preview/<release>/` and is something that is truly common for any given
PR

always strip exactly two levels from the diffstat output

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

the detection of the correct config dir was fixed in the installer some
time ago in
https://github.com/theforeman/foreman-installer/commit/6fef25e5d3a41f46bff9794946b2c6faed6c84f5
and this warning is not necessary anymore

drop warning for running the installer in a dir with config subdir

---

guides/common/assembly_installing-satellite-server-disconnected.adoc
guides/common/modules/proc_configuring-the-base-operating-system-with-offline-repositories-in-rhel-7.adoc
guides/common/modules/proc_configuring-the-base-operating-system-with-offline-repositories-in-rhel-8.adoc

Added a module that describes how to install forman on RHEL 8.6
Existing module updated and used for RHEL 7 instructions:
proc_configuring-the-base-operating-system-with-offline-
repositories.adoc
New module added for RHEL 8 instructions:
proc_configuring-the-base-operating-system-with-offline-
repositories-in-rhel-8.adoc
Content was verified by the QA before creating this PR.

Disconnected installation instructions on RHEL 8.6

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

in b5602838a194cbc2415a0f2a9999debd3d1d84dd a condition to generate
certificates was adjusted, but it was overseen that this also added
unneded repository operations to the satellite version of the guide.
Fixes: b5602838a194cbc2415a0f2a9999debd3d1d84dd

don't suggest to enable upstream repositories for satellite

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

there is no more MongoDB after upgrading to 6.10

don't mention MongoDB during upgrades

---

guides/common/modules/ref_system-requirements.adoc

Since https://projects.theforeman.org/issues/35138 this is no longer a requirement. This is only for nightly.

Drop umask system requirement

---

guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

Change include path to guide common symlink

---

guides/common/attributes-satellite.adoc

Modified the attribute for version-specific client repo
as it resembled a specific one. Made it more generic as per the
release notes.
Incorrect name for Satellite Client repo in Installation guide
https://bugzilla.redhat.com/show_bug.cgi?id=2103698

Modified attribute for version specific client repo

---

.github/workflows/deploy.yml
.github/workflows/preview.yml

this is especially useful if there was a successful preview build in the
past, but the latest revision didn't succeed and thus the preview link
would not reflect the changes in the PR

comment on PRs if the preview could not be generated

---

guides/common/assembly_maintaining-server.adoc
guides/common/modules/proc_deleting-report-records.adoc
guides/common/modules/proc_deleting-task-records.adoc

Both procedures are based on `guides/common/modules/proc_deleting-audit-records.adoc`.

Add procedures to delete report and task records

---

guides/common/assembly_configuring-networking.adoc
guides/common/modules/con_facts-and-nic-filtering.adoc
guides/common/modules/proc_optimizing-performance-by-removing-nics-from-database.adoc

Added new modules (Facts and NIC filtering and
Optimizing performance by removing NICs from database).
These modules explain how to filter facts and NICs in order to
optimize the performance and remove unwanted facts and NICs
from the database and system.
These modules are added under Provisioning Hosts > Network Resources.
This PR also contains the reviews and suggestions provided in PR#1351.
Add chapters about facts, filtering and cleaning
https://bugzilla.redhat.com/show_bug.cgi?id=2009649

New modules for Filtering and Removing Facts

---

guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

The TargetVersionMaintainUpgrade attribute needed to be removed because
it was determined to be downstream specific and outdated for upstream
documentation. This is related to an already existing PR #1413 which
addresses removing the attribute for other versions.

Remove TargetVersionMaintainUpgrade attribute

---

guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Step 7 and Step 9 of the Upgrading a connected Satellite section had a command reference that was pointing to the previous target version for 6.10. Updated the command reference and built a preview that shows it properly references 6.11.

Changed upgrade command to reflect current version

---

guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc

Per SAT-6405, I added port 443 in the Destination Port of the Capsule incoming traffic table where port 8443 is mentioned.

Added Port 443 to Capsule incoming traffic table

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

This PR adds the missing guideline for Enterprise Linux 8 to the upgrade docs for the server part (including the breaking change for 4.5, where the Module Streams have to be enabled before running `foreman-installer`),
but also streamlines it then a bit to make sure the wording is the same for server and smart proxy.
This is my first PR against the documentation repo, I hope I didn't write total nonsense, and break every possible guideline for the docs 🙂 (I tried to look for recent changes and comply to these as guidelines)
Any help and comment is very welcome!
Thank you!
Fixes #1317

Katello upgrade docs improvement for EL 8

---

guides/common/modules/proc_configuring-installation.adoc

As per the Bugzilla, the installation log location should be
/var/log/foreman-installer/satellite.log and not the
/var/log/foreman-installer/satellite-installer --scenario satellite.log
in Configuring Satellite Installation.
The installation log location is now updated based on the suggestion.
https://bugzilla.redhat.com/show_bug.cgi?id=2104280

Correction in the installation logs location

---

guides/doc-Upgrading_and_Updating/topics/synchronizing_the_new_repositories.adoc

The module Synchronizing the New Repositories contains list of repos.
As per the comment in Bugzilla, the list needed an update.
List has been updated to reflect the requested information in bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=2104310

Updated Repo list in Synchronizing New Repositories

---

guides/common/modules/proc_configuring-installation.adoc

1. prefer tmux over screen (screen is deprecated since EL7.6)
2. only put the Red Hat KCS link behind an ifdef
3. drop all unnecessary ifdefs

unify "watch installation" section

---

guides/common/modules/proc_configuring-installation.adoc
guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

screen has been deprecated in EL 7.6 and is not present in EL8+ at all
simplify documentation by only mentioning one tool

drop reference to screen, only document tmux

---

guides/common/modules/proc_configuring-puma-workers.adoc

Adding +attributes to make sure '{foreman-installer}' gets expanded

---

guides/common/modules/con_content-management-types-overview.adoc
guides/doc-Managing_Content/master.adoc

Our product management moved this feature to a later Satellite version, so we need to unpublish it for Sat 6.11.

Unpublish OSTree content management for Satellite

---

web/content/js/versions.js

IMHO does not require cherry-picking because the navigation comes from master only.
WRONG: https://docs.theforeman.org/release/3.1/#
See

Link to correct build target in navigation

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc

Added post-upgrade steps after final step in **Upgrading Satellite to Red
Hat Enterprise Linux 8 In-Place Using Leapp.** This change was required
because they were missing in the latest release.

Add post-upgrade steps to Upgrading using Leapp

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc

New paragraph added to the Upgrade Paths section. It states that moving
the PostgreSQL data directory will require space if the /var/lib/pgsql/
paths are on different partitions.

Add line for moving the PostgreSQL data directory

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc

only a fraction is different between Satellite and non-Satellite builds.
move these to an ifdef section, and everything else outside of it

streamline Leapp prerequisite difinition

---

guides/common/modules/proc_configuring-repositories.adoc

Enabling only satellite:el8 module, system warns enablement conflicts.
To inform users about this warnings and its impact,
an admonition is added to the module - configuring repositories.
This admonition is added only to the satellite version of docs.
In the original PR#1432, Some checks were failed due to git conflict.
Hence creating this PR.
It contains the latest version of admonition.
https://bugzilla.redhat.com/show_bug.cgi?id=2104560

Added admonition for Enabling satellite:el8 module

---

guides/common/modules/proc_configuring-repositories-proxy.adoc

Omitted a repository that was not required while installing the proxy
on RHEL 7.
Incorrect repository for Capsule installation on RHEL 7
https://bugzilla.redhat.com/show_bug.cgi?id=2104573

Remove the redundant RHEL 7 repo

---

guides/common/modules/proc_configuring-repositories-proxy.adoc

Enabling only satellite-capsule:el8, system warns enablement conflicts.
To inform users about this warnings and its impact,
an admonition is added to the module - Configuring Repositories.
This admonition is added only to the satellite version of docs.
https://bugzilla.redhat.com/show_bug.cgi?id=2104609

Enabling satellite-capsule:el8 module Admonition

---

guides/common/modules/con_provisioning-cloud-instances-in-amazon-ec2.adoc
guides/common/modules/con_provisioning-cloud-instances-on-google-compute-engine.adoc

Remove links to orcharhino documentation

---

guides/common/modules/proc_using-container-registries.adoc

Removes the warning about the Container Gateway not supporting authenticated repositories.

Remove container gateway unauthenticated repo warning

---

guides/common/attributes-satellite.adoc
guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Log file name was incorrect in the Upgrading {SmartProxyServer}s guide.
The name has been corrected from satellite.log to capsule.log.
This issue was reported in BZ#2104682
https://bugzilla.redhat.com/show_bug.cgi?id=2104682

Corrected the log file name in the upgrade guides

---

guides/common/modules/con_content-filter-overview.adoc
guides/common/modules/proc_adding-repositories.adoc
guides/common/modules/proc_creating-a-content-filter-for-apt-content.adoc
guides/common/modules/proc_creating-a-content-filter-for-yum-content.adoc
guides/common/modules/proc_creating-a-content-view-short.adoc
guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_managing-the-lifecycle-of-the-content-view.adoc
guides/common/modules/proc_promoting-your-content-view-to-the-new-lifecycle-environment.adoc
guides/common/modules/proc_viewing-module-streams.adoc

Per SATDOC-6389, the Content Management workflow had some outdated information in certain sections specifying the CM workflow. Some steps needed to be updated to reflect the changes to the UI including fields. Following files and their changes include:
In common/modules/con_content-filter-overview.adoc, table was updated to reflect RPM and Container Image Tag.
In common/modules/proc_adding-repositories.adoc, steps were updated to reflect latest changes to UI.
In common/modules/proc_creating-a-content-filter-for-apt-content.adoc, new step was added in the procedure for Filter Detail Page access before clicking on Affected Repositories.
In common/modules/proc_creating-a-content-filter-for-yum-content.adoc, new step was added in the procedure for Filter Detail Page access before clicking on …

Updated various outdated Content Mgmt sections

---

web/content/index.adoc
web/content/release-2.4.adoc
web/content/release-2.5.adoc
web/content/release-3.0.adoc
web/content/release-3.1.adoc
web/content/release-3.2.adoc
web/content/release-3.3.adoc
web/content/release-nightly.adoc

This only shows a small set of guides to keep it easier for users to navigate. Copying the full navigation will be confusing for new users because the list is overwhelming.
It also removes links to guides which aren't even in the top navigation (and thus are considered not to be ready).
There is still plenty of room for improvement on this, like implementing columns, but this is a start.
If this is considered OK, the same should be applied to all releases.

Restructure nightly landing page

---

guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc

The update in the upgrade guide about updating to the latest 6.9.z.
First need to update to the latest 6.9.z before upgrading to 6.10.
The same was requested in BZ#2049350
Changes only applicable for Satellite version 6.10.
https://bugzilla.redhat.com/show_bug.cgi?id=2049350

Update in the module - Upgrading satellite Server

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

As mentioned in the description of BZ#2104699, added a reference to
Deploying a Custom SSL Certificate to {SmartProxy} Server section.
This section is currently available in Installing {SmartProxy} server guide.
Reference added in the procedure - Upgrading {SmartProxy} Servers
https://bugzilla.redhat.com/show_bug.cgi?id=2104699

Added reference to Installing SmartProxy Server Guide

---

guides/doc-Planning_for_Project/topics/Introduction.adoc

Nightly has dropped EL 7 and Debian 10, but stable branches still have that support so it shouldn't be cherry picked.

Correct availability of server packages

---

guides/common/modules/proc_configuring-logging-to-journal.adoc

The installer should restart any services which are needed. Since we dropped Passenger support this doesn't even work to restart Foreman.

Drop redundant Apache restart

---

guides/common/modules/ref_system-requirements.adoc

The puppetserver user doesn't exist. puppet agent runs as root and puppetserver runs as puppet.
The foreman user only exists when foreman is installed. This isn't the case on content proxies so it isn't a requirement.

Correct user requirements

---

guides/common/modules/proc_configuring-repositories-el.adoc

CentOS Stream has ansible-core which means Ansible 2.9 can no longer be installed. Setting up the repositories is redundant.
<del>Submitting as a draft since I'm still verifying it in https://github.com/theforeman/forklift/pull/1544.</del>

Drop installation of centos-release-ansible-29

---

guides/doc-Managing_Configurations_Puppet/master.adoc

Satellite does not support third party tools and thus shouldn't be documented.

Drop r10k instructions for Satellite

---

guides/common/modules/snip_host-registration-steps.adoc

A step to update subscription manager config while project host
registration has been added.
This step is added after having discussion in BZ#2105995
This step is required for proper Registration method in Load-balancing 
capsule setup for a clients.
https://bugzilla.redhat.com/show_bug.cgi?id=2105995  

A step added to update subscription manager config

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/con_migrating-project-to-a-new-el-system.adoc
guides/common/modules/proc_creating-a-backup-of-a-server-on-el7.adoc
guides/common/modules/proc_installing-and-configuring-the-puppet-agent.adoc
guides/common/modules/proc_restoring-a-backup-of-a-server-on-el8.adoc
guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc
guides/common/modules/ref_performing-a-fresh-installation-of-a-server-on-el8.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

In upstream it's common to use Enterprise Linux to mean any RHEL-like OS (RHEL, its clones and CentOS Stream (which is technically more of an upstream). In satellite only RHEL is used.
The guidance on using this is that where it doesn't matter, {EL} should be used (such as disk space requirements). In cases where it does make a difference (like setting up repositories) the actual names should be used. It may also result in multiple sections.
This takes a more conservative approach than https://github.com/theforeman/foreman-documentation/pull/982 in that it doesn't replace as many sections. I wonder if this should or shouldn't be cherry picked. It's fairly safe and picking it makes future cherry picks easier due to fewer conflicts.
* For Foreman 3.0 or …

Introduce EL macro

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

This aligns configuring repositories instructions. The katello module should depend on foreman which makes foreman redundant. We also explicitly state the stream rather than depending on there being only one stream.
Fixes: 801d7c8676a6e330c94ac4f0199a64fbe24b6fe1

Make DNF module enablement consistent

---

guides/common/modules/con_converting-a-host-to-rhel-with-convert2rhel.adoc
guides/common/modules/proc_creating-an-activation-key-to-consume-the-content-view.adoc
guides/common/modules/proc_distributing-keys-for-remote-execution.adoc
guides/common/modules/proc_using-red-hat-insights.adoc
guides/common/modules/snip_host-registration-steps.adoc

try `git grep "registering-a-host_"` vs. `git grep "registering_hosts_"`.
I ran `find . -type f -iname "*.adoc" | xargs sed -i "" "s/registering-a-host_/Registering_Hosts_/g"`.

Fix link to registering hosts

---

guides/common/modules/proc_importing-a-virtual-machine-from-vmware.adoc

Fix spelling of identical

---

guides/common/modules/proc_preparing-a-cloud-init-template.adoc

While preparing for the Cloud-init template, the relevant team has deprecated
the old snippet idm-register. It is now replaced with the new one.
'idm_register' snippet still referenced in provisioning guide
https://bugzilla.redhat.com/show_bug.cgi?id=2106348

Replace a deprecated snippet

---

guides/common/modules/proc_creating-a-backup-of-a-server-on-el7.adoc
guides/common/modules/proc_restoring-a-backup-of-a-server-on-el8.adoc

Few hyperlinks were pointing to the beginning of the Administering Project guide.
Updated such hyperlinks to point to the specific section in
the Administering {Project} guide.
Changes are made only in the Migrating Satellite to a New RHEL System
section of the Upgrade guide.  
No more updates required from the docs side.
https://bugzilla.redhat.com/show_bug.cgi?id=2110885

Updated incorrect Hyperlinks in Migration Chapter

---

guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc

If the SCA is enabled by the customer in the portal, there is no need of
attaching the subscription after registering the Project server. A user
can start the configuration part directly.
No mention of no need to attach a subscription with
Simple Content Access mode
https://bugzilla.redhat.com/show_bug.cgi?id=2104602

Add note on subscription attachment

---

guides/common/modules/proc_configuring-ipxe-to-reduce-provisioning-times.adoc

This treats all EL-based installs the same and only shows the appropriate instructions. We have macros to determine if it's deb based or RPM based so those are used to simplify the end user instructions.

Generalize the ipxe installation instructions

---

guides/common/modules/proc_registering-capsule-to-satellite-server.adoc

The mentioning of the base operating system was not required as it does not
play any role in reaching out to Red Hat CDN. So, the second prerequisite
was corrected with accurate information about proxy server, and project 
correlation.
Should 'Red Hat CDN' be 'the Satellite'
https://bugzilla.redhat.com/show_bug.cgi?id=2104596

Modify the prerequisites to install Proxy

---

guides/common/assembly_importing-content.adoc
guides/common/modules/proc_adding-custom-deb-repository-example-for-debian-11.adoc
guides/common/modules/proc_adding-custom-rpm-repositories-for-alma-linux-9.adoc
guides/common/modules/proc_adding-custom-rpm-repositories-for-centos-stream-9.adoc
guides/common/modules/proc_adding-custom-rpm-repositories-for-oracle-linux-9.adoc
guides/common/modules/proc_adding-custom-rpm-repositories-for-rocky-linux-9.adoc
guides/common/modules/proc_creating-an-installation-medium-for-debian.adoc
guides/common/modules/proc_extracting-gpg-public-key-fingerprints-from-release-files.adoc

Current example for DEB only: [Adding DEB Repository Example for Debian 11](https://docs.theforeman.org/nightly/Content_Management_Guide/index-katello.html#Adding_Custom_DEB_Repository_Example_for_Debian_11_content-management)
* Do not cherry-pick to 3.2 and below because there are no clients for EL9 available.

Add short procedures on how to add custom RPM repositories for EL9

---

guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

In step 1 of High-Level Upgrade Steps, the first step for cloning is
optional. The word Optional is added to clarify that before clicking
the link to the guide for Cloning Satellite Server.

Make cloning optional in upgrade workflow

---

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

In upstream the installer is ran explicitly with the --certs-tar-file location. This means the stored answer is irrelevant and we can safely use any location we want. It just has to be consistent.
For Satellite it's different since satellite-maintain is used without the --certs-tar-file option. This means the file must be transfered to the expected location. The safest way to do so is via the answers file.
This is poor phrasing, but it was the easiest way to demonstrate what I think is the correct solution to https://github.com/theforeman/foreman-documentation/pull/1479/files#r929881587.

Recommend the correct tar file location in Satellite

---

web/content/js/versions.js

In f2edd6ab45cddb26f57e892f613666b15979721b this guide was renamed (and picked to 3.1), but the navigation wasn't updated. This meant an old stale guide was being linked.
I don't think navigation needs to be cherry picked.

Link to the correct Administering guide

---

guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc

The main block in puppet.conf is used for both the server and agent.  Modifying it in the agent block only affects the agent.
Restarting the server is also not needed. The puppetserver is technically a completely unrelated daemon. Combined with changing only the agent section in puppet.conf it remains at the old log level. The puppet-agent daemon automatically reloads the config if it changed, as can be seen in the logs:
Config file /etc/puppetlabs/puppet/puppet.conf changed; triggering re-parse of all config files.

Correct puppet-agent log level instructions

---

guides/common/modules/proc_performing-a-full-backup.adoc

In Administering Foreman, section 9.2.: Changed "PgSQL database"
to "PostgreSQL database" as that is the correct wording.

Change PgSQL database to PostgreSQL database

---

Makefile

The `make` utility runs each line in the Makefile in a different
shell from the current working directory. Therefore lines
containing `cd web` and `cd ..` have no effect on the rest
of the commands. Bundle then installs dependencies in the `vendor`
directory which is created outside  of the `foreman-documentation`
repository. You can try this out yourself by running `make prep` in 
the `foreman-documentation` directory. Putting two commands on 
the same line results in them being executed by the same shell 
and dependencies are installed within the repository.

Fix `make prep` in top-level Makefile

---

guides/common/assembly_using-external-databases.adoc
guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc
guides/common/modules/proc_installing-the-sos-package.adoc

These notes should never be added. Instead, ifdef should be used to generate the appropriate manual.

Remove 'For Red Hat systems only' note

---

guides/common/modules/proc_applying-errata-to-multiple-hosts.adoc

Removed RHEL 7 specific references and updated to reflect RHEL 8 based
installation and upgrade scenarios. The change was required because
support for installation on RHEL 7 is being dropped and only RHEL 8
installations will be supported.

Drop version number for RHEL hosts

---

guides/common/modules/proc_configuring-the-qpid-mgmt-pub-interval-parameter.adoc
guides/common/modules/proc_renaming-smart-proxy.adoc

This was [#32125](https://projects.theforeman.org/issues/32125) but that's been resolved in Foreman 2.5.

Remove old workaround for hostname-change.rb

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc

For Satellite, Leapp will enable the right module, but not for
Foreman/Katello. However, without the module enabled, users won't get
updates past the original version they've upgraded to.

enable the foreman/katello modules after leapp upgrade

---

guides/common/modules/proc_building-a-discovery-image.adoc

Using the upstream repository for creating Foreman Discovery Image (FDI)
works also in non-Satellite environments.

Rework Building a Discovery Image

---

guides/common/modules/con_backing-up-server-and-proxy.adoc
guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc
guides/common/modules/proc_installing-the-discovery-service.adoc
guides/common/modules/proc_migrating-to-external-databases.adoc
guides/common/modules/proc_recovering-from-a-full-disk.adoc
guides/common/modules/proc_restarting-services.adoc
guides/common/modules/proc_salt-activating-salt.adoc
guides/common/modules/proc_starting-and-stopping-server.adoc
guides/common/modules/proc_using-an-nfs-share-for-content-storage.adoc
guides/doc-Planning_for_Project/topics/Glossary.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

Replaced multiple occurrences of `{foreman-maintain}` services
with {Project} services.
Command `{foreman-maintain} service <action>` controls the
{Project} services, so whenever the text is descriptive, it
should read "{Project} services", not `{foreman-maintain}` services.

Replace `foreman-maintain` services

---

guides/common/modules/snip_host-registration-steps.adoc

In Installing Capsule Server, section 2.1; changed three
occurences of "Check the `/etc/yum.repos.d/redhat.repo`" to
"Check the `/etc/yum.repos.d/redhat.repo` file" to clarify
that the object in question is a file.

Add missing clarification to file

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc
guides/common/modules/ref_system-requirements.adoc

Added an admonition to clarify that:
Only DEFAULT and FIPS crypto-policies are supported in Project.
Note is project-specific & in sections requested in BZ#2115256.
Added note in `ifdef` statement keeping impact minimal on other guides.
https://bugzilla.redhat.com/show_bug.cgi?id=2115256

Added Admonition about supported Crypto Policies

---

guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc
guides/doc-Administering_Project/master.adoc
guides/doc-Administering_with_Ansible/master.adoc
guides/doc-Configuring_Ansible/master.adoc
guides/doc-Configuring_Load_Balancer/master.adoc
guides/doc-Deploying_Project_on_AWS/master.adoc
guides/doc-Installing_Proxy/master.adoc
guides/doc-Installing_Server/master.adoc
guides/doc-Installing_Server_Disconnected/master.adoc
guides/doc-Managing_Configurations_Puppet/master.adoc
guides/doc-Managing_Content/master.adoc
guides/doc-Managing_Hosts/master.adoc
guides/doc-Performance_Tuning_Guide/master.adoc
guides/doc-Planning_for_Project/master.adoc
guides/doc-Provisioning_Hosts/master.adoc
guides/doc-Upgrading_and_Updating/master.adoc

I modified the condition for output of the feedback module in Satellite.
Expects reversal of removed l10n markers as mentioned in https://github.com/theforeman/foreman-documentation/issues/1471#issuecomment-1189198094

Issue #1471: Output feedback module for HTML deliverables only

---

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc

The protocol is a part of latest version but it is required to consider
the same for earlier versions too. It is applicable to even earlier
versions while writing this commit.
Add more information on External database configuration with SSL in
Documentation  for both ends.
https://bugzilla.redhat.com/show_bug.cgi?id=2079973

Add the missing SSL protocol for external database

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

Removed an Obsolete "--upgrade" option from the upgrade guide,
section Upgrading a Disconnected Project Server.
Passing the --upgrade option results in errors, hence cannot be used.
https://bugzilla.redhat.com/show_bug.cgi?id=2119099

Removed Obsolet option --upgrade from UpgradeGuide

---

guides/common/modules/proc_configuring-installation.adoc
guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

The `screen` utility has been updated to `tmux`. This change was
required because Red Hat has deprecated the 'screen' utility and
removed it from RHEL 8.

Change outdated screen tool to tmux

---

guides/doc-Release_Notes/topics/foreman.adoc

While individual releases were added, the headline features, upgrade warnings and deprecations weren't. This copies them from theforeman.org.

Add Foreman 3.2 release notes

---

guides/common/modules/proc_installing-postgresql.adoc

the notes and the code block got in their ways

fix rendering of the "edit postgresql.conf" section

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc

A step is created to show how network interfaces are renamed and
running the installer once more with the new interface names. The
change was required because upgrading using Leapp is inhibited by an
unsupported network configuration.

Add networking interface rename command

---

guides/common/modules/proc_downloading-the-binary-dvd-images.adoc

Until RHEL 7, there was Red Hat Enterprise Linux Server version as a
name in the Product variant. After the release of RHEL 8, it is changed to
Red Hat Enterprise Linux for x86_64. It is also applicable to RHEL 9
as well. Hence, renamed the Product Variant.
[DDF] This is only true for RHEL7, for RHEL8 the variant is
"Red Hat Enterprise Linux for x86_64"
https://bugzilla.redhat.com/show_bug.cgi?id=2119293

Rename the Product Variant for RHEL 8 and above

---

guides/common/modules/proc_downloading-the-binary-dvd-images.adoc

Add the reference of EL8 alongside EL7 in the section of Downloading
the Binary DVD Images. Also, mention the name of the relevant option
visible.
[DDF] This is only true for EL7, add the EL8 variant
https://bugzilla.redhat.com/show_bug.cgi?id=2119293

Add EL8 reference for downloading images

---

guides/common/modules/proc_estimating-the-size-of-a-backup.adoc

The procedure in Administering Foreman, section 9.1 assumes
RHEL 7 disk layout. Added correct location of PostgreSQL data
for RHEL 8 and 9 while maintaining the original location for
RHEL 7.
Please cherry-pick 6e231a30c7525d7920c578289dc238626db9c335 into:
Please cherry-pick fb40004da94195977b87a15f35cc76a840de108f into:

Change location of PostgreSQL data

---

guides/common/modules/proc_upgrading-rhel7-hosts-to-rhel8.adoc

The RHEL7 to RHEL8 upgrade guide mentions that installer uses Puppet under the hood. Changing the plugin name as this information is not relevant to the user.
https://bugzilla.redhat.com/show_bug.cgi?id=2117556

Fix the leapp plugin name

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

Fixed two broken links in Updating and Upgrading guide in section 3.1.2,
procedure steps 9 and 10. Split step 10 into sections for EL 7 and EL 8
and added corresponding link in the EL 8 section.

Fix broken links in Updating and Upgrading guide

---

guides/common/modules/proc_reclaiming-postgresql-space.adoc

A suggestion was received to replace PostGre Switch command to cover
the candlepin & pulpcore database replacing option ``--dbname` to `all`.
It has been updated after receiving confirmation from SME in BZ#2122618.
Updates are made in the module - Reclaiming PostgreSQL Space
https://bugzilla.redhat.com/show_bug.cgi?id=2122618

Updated postgres option to make it more inclusive

---

guides/doc-Content_Management_Guide/topics/Importing_Content.adoc

The list of the supported URLs for adding custom repositories
was needed to make users aware. In addition to this, there is a
condition to using file:// protocol where the file permissions and SELinux
are setup to only allow file:// syncs within the
/var/lib/pulp/sync_imports/ directory.
What are the supported URL (http, https,file,nfs,git etc)
for custom repositories?
https://bugzilla.redhat.com/show_bug.cgi?id=2078031

Add supported URLs for Custom repositories

---

guides/common/modules/proc_overriding-ansible-variables.adoc

This PR removes the part from the URL that is not required in the URL.
Ansible User Guide is redundant and hence being removed.
It does not affect any information part and does not break anything.
For details see comments in BZ#2119611
https://bugzilla.redhat.com/show_bug.cgi?id=2119611

Removed redundant part from the Hyperlink text

---

guides/doc-Administering_Project/master.adoc

The instructions are very katello-centric and don't work on Foreman.
I'm unsure about cherry picks. We don't link to the guides for non-nightly so it doesn't matter that much.

Drop migrating internal DB to external from foreman-el

---

guides/common/modules/proc_completing-the-rhel6-image.adoc
guides/common/modules/proc_completing-the-rhel7-image.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc

In b9437c01aa8bd93ebe56ab8321abbc87f8bb1cbf the macro was changed to `dnf clean` but these instructions are specifically for EL6 or EL7 which have yum.

Fix yum clean instruction

---

guides/common/assembly_configuring-satellite-with-an-http-proxy.adoc
guides/common/assembly_installing-server-connected.adoc
guides/common/modules/proc_configuring-http-proxy-to-connect-to-cdn.adoc

The configuration in HTTP Proxy to connect to the Content Delivery
Network is required at the time of registering the project server to
CDN. At present, it is a part of configuring the project server with an
HTTP Proxy which is not correct. So, we moved the section here to the
installation process where the registration process takes place.
Instructions "Configuring the HTTP Proxy to Connect to CDN"
should be before "Registering to Subscription Management"
in project Documentation.
https://bugzilla.redhat.com/show_bug.cgi?id=2117691

Move the HTTP Configuration section to installation

---

guides/common/modules/con_managing-dns-using-smart-proxy.adoc
guides/common/modules/proc_configuring-dns-libvirt.adoc

This looks like the dhcp_libvirt description was copied.
Fixes: 29f85aab7520b52425d3917e3148ec2c9434f978

Correct the description of dns_libvirt

---

guides/common/modules/con_configuring-external-authentication.adoc

In Administering {Project}, section 14: when the mail is not set
properly and/or available via an external source, during the first
login, the email will be requested. However, this is not mentioned
in the docs. Added a note to notify the user about this behavior.

Add a note about requesting unset email

---

guides/common/modules/proc_configuring-repositories-proxy.adoc

This document is only used for satellite. That means all non-satellite content can be dropped. It also has set some macros that unused.
The expected diff of this PR is no visual change. Perhaps some empty lines are dropped.

Remove redundant macros from configuring proxy repos

---

guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc

In Upgrading and Updating guide, section 3.1.1.: Updated the rpm
command to a simpler and faster variant in step 10 of the procedure.
`rpm -q --last kernel` only shows information relevant to the user
and the shortened output is more readable compared to the output of
`rpm -qa --last | grep kernel`.

Update the rpm command

---

guides/common/modules/proc_using-shellhook-arguments.adoc

Added missing quotes in Administering Project guide, section 16.8.

Add missing quotes

---

guides/common/modules/proc_creating-variables-for-convert2rhel-role.adoc

In Managing Content, section 11.3.: Updated the table with additional variables that need to be created if converting an Oracle system to convey the message more clearly.

Update table with additional variables

---

guides/common/modules/proc_creating-variables-for-convert2rhel-role.adoc

In Managing Content guide, section 11.3.: Provided examples for variables that the user has to create. Removed duplicate information from the description of the `{project-context}_validate_certs` variable.

Provide examples for Ansible variables

---

guides/common/modules/proc_using-an-nfs-share-for-content-storage.adoc

In Using an NFS Share for Content Storage of Managing Content 
Variable {Project} was not rendering correctly when used in codeblock. 
It was due to missing "attributes" label above the code block. 
Fixed by adding "attributes" label above the code block.
Module - proc_using-an-nfs-share-for-content-storage.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2123939

Fixes for the occurrences of {Project}

---

guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc

Replaced a .include directives command as this one is deprecated. 
Support for the same will be removed in the future versions of systemd. 
New command is added to replace .include derivatives as per suggestion. 
New command includes drop-in files.
https://bugzilla.redhat.com/show_bug.cgi?id=2122559

Replaced .include directives with drop-in files

---

guides/common/modules/proc_assigning-convert2rhel-role-to-project-server.adoc

In Managing Content guide, section 11.2.: Added another step in the procedure to inform the user to continue by creating required variables for the role. This is to clarify that the Ansible role is not to be run yet.

Add a note about not running Ansible role

---

guides/common/modules/con_provisioning-contexts.adoc
guides/common/modules/con_provisioning-templates.adoc
guides/common/modules/proc_assigning-a-host-to-a-specific-organization.adoc
guides/common/modules/proc_browsing-repository-content-using-an-organization-debug-certificate.adoc
guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
guides/doc-Administering_Project/master.adoc
guides/doc-Deploying_Project_on_AWS/topics/AWS_Use_Case_Considerations.adoc
guides/doc-Managing_Content/master.adoc

We're moving these chapters to _Administering_ guide for Sat 6.12:
- Managing organizations
- Managing locations
-------

Move managing organizations and locations (Satellite)

---

guides/common/modules/con_managing-content-views.adoc

In Managing Content guide, section 8.: expanded list to include container image tag filters.

Add container image tag filters

---

guides/common/modules/con_content-filter-overview.adoc
guides/common/modules/proc_adding-repositories.adoc
guides/common/modules/proc_creating-a-content-filter-for-apt-content.adoc
guides/common/modules/proc_creating-a-content-filter-for-yum-content.adoc
guides/common/modules/proc_creating-a-content-view-short.adoc
guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_managing-the-lifecycle-of-the-content-view.adoc
guides/common/modules/proc_promoting-your-content-view-to-the-new-lifecycle-environment.adoc
guides/common/modules/proc_viewing-module-streams.adoc

Cherry-picking changes from this https://github.com/theforeman/foreman-documentation/commit/b64ed4ac8d6203111f5778f44d0cd7139d013db3. They are missing in both 3.1 and 3.2. All related to "Creating a Content View".

Update various procedures for managing content (#1206)

---

guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc

Port 443 has been mentioned twice in the Ports configuration table for LB. The second instance is not required, as HTTPS 443 source is defined at the beginning of the config and will be used by haproxy to control the traffic from RHSM\YUM or any other https-based requests.
https://bugzilla.redhat.com/show_bug.cgi?id=2119979

Remove duplicate entry for port 443 in LB guide

---

guides/common/assembly_template-writing-reference.adoc
guides/common/modules/proc_using-autocompletion-in-templates.adoc

Adding a module describing the Autocopmpletion option for template writing in the Managing Hosts doc.

Add details about Autocompletion option for templates

---

guides/common/modules/proc_exporting-a-repository.adoc

* Removes interactive shell sessions
* Removes a duplicate procedure
* Removes '--organization _My_Organization_' parameter
* Remove RPM repositories to Yum repositories & sort alphabetically
See also https://github.com/theforeman/foreman-documentation/issues/1263 cc @jeremylenz 

Rework exporting a repository

---

guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc

In one section, DDF requested to know what templates were being referred to specifically. SME stated it covers job and provisioning templates. This change was required to help clarify the templates being referred to in the section mentioning templates. This is the same change as PR #1645 but for the 3.3 branch.

Define templates in context

---

guides/common/modules/proc_installing-openscap-plugin.adoc

Hammer cli plugin is always available & enabled by default downstream. Steps are not required to enable it.
Added a condition for such one step in proc_installing-openscap-plugin.
https://bugzilla.redhat.com/show_bug.cgi?id=2125360

Add condition for Satellite specific step

---

guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc

In Foreman 2.3.4 the remote address verification was tightened to [only trust certain proxies](https://projects.theforeman.org/issues/30779). Then in Foreman 3.2 the installer added [a flag to configure this](https://projects.theforeman.org/issues/34089).

Update remote address for remote proxies

---

guides/common/attributes-satellite.adoc
guides/common/modules/proc_synchronizing-smartproxy-servers-through-project-web-ui.adoc
guides/doc-Upgrading_and_Updating/master.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

If users skip the pre-migration steps and opt to sync their repositories after upgrading their Project server, running this command fails to synchronize their content with their capsule servers:
```
```
Users are able to sync this content with a full capsule sync in the project web UI. This is for Foreman 2.5 (Satellite 6.10) only.

Synchronize smartproxy servers through web ui

---

guides/common/modules/con_backing-up-server-and-proxy.adoc
guides/common/modules/con_scap-content.adoc
guides/common/modules/con_security-content-automation-protocol.adoc
guides/common/modules/con_ssh-key-management.adoc
guides/common/modules/con_using-freeipa.adoc
guides/common/modules/con_using-ldap.adoc
guides/common/modules/proc_configuring-host-based-authentication-control.adoc
guides/common/modules/proc_configuring-logging-to-journal.adoc
guides/common/modules/proc_recovering-from-a-full-disk.adoc

The recent project version does not support RHEL7 as the base OS. Replaced links in the Administering Project doc that point to the RHEL7 guides, to point to the corresponding RHEL8 guides.

Remove EL7 references for most recent project versions

---

guides/common/modules/proc_building-a-discovery-image.adoc

The previous instructions were for EL7, even though they described it as EL8. The Orcharhino instructions are correct for EL8. This change moves everything to EL8 for non-Satellite and keeps EL7 for Satellite.
The only modification is that the repository file is now modified for production use. This mostly means using mirror lists and pointing to the exact release for which the documentation is generated.

Use EL8-based instructions in upstream

---

guides/common/modules/ref_storage-requirements.adoc

The partition size of /usr for RHEL 8 is 3GB at present which is not
accurate as it is more than that. It is now increased to 5GB for EL8.
Also, there is already a detailed guide on the same which helps user
to set correct size of partitions that includes /usr as well.
So, we have added a link to redirect users to the detailed guide.
Recommended /usr partition size for RHEL 8 is incorrect.
https://bugzilla.redhat.com/show_bug.cgi?id=2108615

Reconsider /usr partition size for RHEL 8

---

guides/common/modules/proc_configuring-http-proxy-to-connect-to-cdn.adoc

When Project forwards information to insights, the added hostname also becomes part of the process. Hence, it became necessary to add this Host name along with its Port and Protocol to the proxy whitelist table. It is part of configuring the HTTP Proxy to connect to the CDN.
https://bugzilla.redhat.com/show_bug.cgi?id=1804313

Add a Host name to proxy whitelist

---

guides/common/attributes-satellite.adoc
guides/common/modules/proc_installing-and-configuring-the-puppet-agent.adoc

PR to resolve merge Conflicts.
A list of repositories is added to which has puppet-agent rpm available. 
Added a new attribute in the attribute-satellite.adoc 
Module updated-Installing & Configuring Puppet Agent on a Host Manually.
https://bugzilla.redhat.com/show_bug.cgi?id=2126470 (cherry picked from commit fb4bd022b6110f4121acb6bff313a29f7cf6ce46)

Add repositories' list the puppet-agent rpm is available in

---

guides/common/modules/proc_building-a-discovery-image.adoc

The previous instructions were for EL7, even though they described it as EL8. The Orcharhino instructions are correct for EL8. This change moves everything to EL8 for non-Satellite and keeps EL7 for Satellite.
The only modification is that the repository file is now modified for production use. This mostly means using mirror lists and pointing to the exact release for which the documentation is generated.
(cherry picked from commit 9feb8b384c05d79305b59b77eeaff80cb826ce64)
Submitting as a separate PR since there was a conflict in cherry picking.

[3.3] Use EL8-based instructions in upstream

---

guides/common/modules/proc_building-a-discovery-image.adoc

The previous instructions were for EL7, even though they described it as EL8. The Orcharhino instructions are correct for EL8. This change moves everything to EL8 for non-Satellite and keeps EL7 for Satellite.
The only modification is that the repository file is now modified for production use. This mostly means using mirror lists and pointing to the exact release for which the documentation is generated.
(cherry picked from commit 9feb8b384c05d79305b59b77eeaff80cb826ce64)
Submitting as a separate PR since there was a merge conflict around the title usage (due to 5c6be653e092340f0ccd7a316458f63c62a19178).

[3.4] Use EL8-based instructions in upstream

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/con_how-to-configure-inter-server-sync.adoc
guides/common/modules/con_synchronizing-content-between-servers.adoc
guides/doc-Managing_Content/master.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc

The full-form of ISS was written incorrectly as Inter-Server Synchronization. This is now renamed correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=2129148

Modify the value of acronym ISS

---

guides/doc-Release_Notes/redmine_release_notes

The header now says:
"A full list of issues is available on Redmine."
Instead of:
"A full list of issues is available via Redmine."
I feel like this preposition fits the header better. Any thoughts?

Replace "via" with "on" in RN header

---

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc
guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
guides/doc-Upgrading_and_Updating/master.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

Structured the Upgrading using Leapp section to include "or {SmartProxy} in addition to {Project}. All the steps were the same except for the step requiring SELinux to be in enforcing mode and running the proper command. This step says it's specifically for {Project}. This change was required because there was no mention of upgrading {SmartProxy} using Leapp.
@evgeni take a look and see if this makes sense now that we've added "or {SmartProxy}".

Add SmartProxy upgrade using Leapp

---

guides/common/modules/ref_example-settings-for-ldap-connections.adoc

Adding the missing "Photo attribute" to the example settings for active directory table. Currently, we see jpegPhoto as a hint on the LDAP auth page, but this does not work, as the attribute should be thumbnailPhoto.

Add a missing setting in the example settings for AD table

---

guides/common/modules/ref_storage-requirements.adoc

Added a storage requirement for external database
https://bugzilla.redhat.com/show_bug.cgi?id=2129924

Added a storage requirement for external database

---

guides/common/attributes-orcharhino.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Same changes as in #1669. This PR exists because of a merge conflict when cherry-picking the original PR to 3.1 branch. While resolving the conflict, I also made a little adjustment to the conflicting section.

Add a step to regenerate custom certificates on branch 3.1

---

guides/common/assembly_using-external-databases.adoc
guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc
guides/common/modules/proc_preparing-a-host-for-external-databases.adoc

Adding the reference of EL8 alongside EL7 for the upstream v3.1. It is required to keep the reference of both as they are supported by Foreman 3.1/Katello 4.3
Need to update guide to have instructions to use EL8 based external DB
https://bugzilla.redhat.com/show_bug.cgi?id=2097380

Add EL8 to External Database guide alongside EL7

---

guides/common/assembly_provisioning-cloud-instances-gce.adoc

While troubleshooting a project case on provisioning to the Google Cloud, we've discovered that the only Google Cloud images that are visible to the project are Team-supported gold images. Neither customer-created nor other third-party Google Cloud images are accessible from Project. So, we have asked end-users to consider only images with Project through the Google Cloud that are supported by team.
https://bugzilla.redhat.com/show_bug.cgi?id=2106854

Mention a condition for gold images for GCE hosts

---

guides/common/modules/proc_enabling-puppet.adoc

Add a missing "puppet-server-formen-url" Flag.
It is required when Configuring Capsule as a Puppet Server. 
As of 6.11, the downstream project no longer generates this 
for the "project-installer" command to be run on the Capsule server.
https://bugzilla.redhat.com/show_bug.cgi?id=2133052

Add missing command-Configuring Capsule as a Puppet Server

---

guides/common/attributes-satellite.adoc
guides/common/modules/proc_creating-a-local-file-repository.adoc
guides/common/modules/proc_creating-a-remote-file-repository.adoc

This PR is specifically created for Foreman 3.1 and 3.3. This PR is a replica of PR #1650 created to keep EL7 instructions. Steps updated for creating a local/remote file repository. The tool will be provided by utils repo (not client). Hence steps are now splited for RHEL 8 and 7.
Added 2 new variables for downstream docs in attribute-satellite. Also, Pulp Manifest package name is different for RHEL 7 and 8.
https://bugzilla.redhat.com/show_bug.cgi?id=2123940

PR with EL7 instructions - replica of PR#1650

---

guides/common/modules/ref_system-requirements.adoc

The project only supports the UTF-8 encoding system. However, there are some users who set another encoding method in their system and as a result, they face issues in the installation process. Hence, we are asking users to set UTF-8 as an encoding method mandatorily before installing Project.
https://bugzilla.redhat.com/show_bug.cgi?id=2127567

Warn users about setting other Unicode

---

guides/doc-Upgrading_and_Updating/topics/synchronizing_the_new_repositories.adoc

Specified Red Hat Satellite Client repo version in the *Synchronizing the New Repositories* procedure in *Upgrading and Updating* guide.
See [BZ#2119134](https://bugzilla.redhat.com/show_bug.cgi?id=2119134) for reference.

Specify Red Hat Satellite Client repo version

---

guides/common/modules/proc_disabling-puppet.adoc

Added a step to refresh smartproxy features in the Disabling Puppet Integration with Project procedure.
See [BZ#2132688](https://bugzilla.redhat.com/show_bug.cgi?id=2132688) for reference.

Refresh smartproxy features when removing puppet

---

guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc

This reverts commit 1705488d82dc6c7e4550c740fb0c46a908f4a17f.
Those changes are not needed since `leapp-repository-0.16.0-8.el7_9` which is present in current RHEL7.

Revert "Add workaround to prerequisites of Leapp (#1703)"

---

guides/common/modules/ref_storage-requirements.adoc

The partition size of /usr for RHEL 8 is 3GB at present which is not accurate as it is more than that. It is now increased to 5GB for EL8. Also, there is already a detailed guide on the same which helps user to set correct size of partitions that includes /usr and /var/lib/qpidd as well. So, we have added a link to redirect users to the detailed guide.
https://bugzilla.redhat.com/show_bug.cgi?id=2108615

Reconsider partition size for EL8

---

guides/common/modules/proc_adding-custom-rpm-repositories.adoc

The list of the supported URLs for adding custom rpm repositories
was needed to make users aware. In addition to this, there is a
condition to use file:// protocol where the file permissions and selinux
are setup to only allow file:// syncs within the
/var/lib/pulp/sync_imports/ directory.
What are the supported URL (http, https,file,nfs,git etc)
for custom repositories?
https://bugzilla.redhat.com/show_bug.cgi?id=2123631

Add supported URLs for Custom RPM repositories

---

guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc

If Simple Content Access is used while registering the proxy server, the mentioned section becomes optional for end-users to consume. Earlier, due to this section, end-users could not install the project server because they used SCA which was not mandatory.
Now, it is noted to the end-users at the starting of the section to skip this section if they are already using SCA as it will automatically enable proxy to consume project subscriptions.
https://bugzilla.redhat.com/show_bug.cgi?id=2108541

Make the use of SCA optional

---

guides/common/modules/con_postgresql-as-an-external-database-considerations.adoc
guides/common/modules/proc_installing-postgresql.adoc

Adding the reference of EL8 alongside EL7 for the upstream v3.1. It is required to keep the reference of both as they are supported by Foreman 3.1/Katello 4.3
Need to update guide to have instructions to use EL8 based external DB
https://bugzilla.redhat.com/show_bug.cgi?id=2097380

Fix EL8 to External Database guide alongside EL7

---

guides/common/attributes-satellite.adoc

This fix seems to have "got lost" on the 3.3 branch, while it's present on master and 3.4.
Relates to: https://bugzilla.redhat.com/show_bug.cgi?id=2136485

Fix Client repo name on 3.3
