guides/common/assembly_managing-dhcp-on-smart-proxies.adoc
guides/common/assembly_managing-dns-on-smart-proxies.adoc
guides/common/modules/con_managing-dhcp-using-smart-proxy.adoc
guides/common/modules/con_managing-dns-using-smart-proxy.adoc
guides/common/modules/proc_configuring-dhcp-libvirt.adoc
guides/common/modules/proc_configuring-dns-libvirt.adoc
guides/common/modules/proc_securing-the-dhcp-api.adoc
guides/common/modules/ref_dhcp-isc-settings.adoc
guides/common/modules/ref_dhcp-options-for-network-configuration.adoc
guides/doc-Installing_Proxy/master.adoc

Integrate DHCP/DNS into Smart Proxies

---

guides/common/assembly_managing-dns-on-smart-proxies.adoc
guides/common/modules/con_managing-dns-using-smart-proxy.adoc
guides/common/modules/proc_configuring-dns-powerdns.adoc

@maximiliankolb I'm not sure about Orcharhino here. Does it package the plugin?

Document dns_powerdns usage

---

guides/doc-Release_Notes/topics/foreman-3.4.0.adoc

Release notes for Foreman 3.4.0

---

web/content/index.adoc
web/content/js/versions.js

Update website for Foreman 3.4.0(GA)

---

guides/common/modules/proc_benchmark-disk-performance.adoc
guides/common/modules/ref_storage-guidelines.adoc

Fixing sections about benchmarking disk performance

---

guides/common/modules/con_extra-scap-content.adoc
guides/common/modules/proc_creating-partition-tables.adoc

Remove EL version

---

guides/common/modules/proc_installing-packages-on-a-host.adoc
guides/doc-Managing_Content/master.adoc

Adding a module describing the new package installation procedure.

Add details about package installation via webUI

---

guides/common/modules/proc_adding-rhel-system-roles.adoc

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2121848

Add repo on RHEL8 (Ansible system roles)

---

guides/common/modules/con_how-puppet-integrates-with-project.adoc
guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc
guides/doc-Planning_for_Project/topics/Introduction.adoc
web/content/js/versions.js

Reword "Content Management Guide" to "Managing Content"

---

guides/doc-Upgrading_and_Updating/topics/post_upgrade_template_checks.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc

Define templates in context

---

.gitignore

Add vendor directory to .gitignore on branch 3.1

---

.gitignore

Add vendor directory to .gitignore on branch 3.2

---

.gitignore

Add vendor directory to .gitignore on branch 2.5

---

guides/common/modules/proc_configuring-project-with-an-alternate-cname.adoc

Add necessary whitespace below header

---

guides/common/attributes-orcharhino.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

Add a step to regenerate custom certificates

---

guides/common/modules/proc_configuring-server-to-synchronize-content-over-a-network.adoc

Fixing a code block that didn't render correctly due to a missing "attributes" parameter.

Fix code block

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc

Repair the attributes for EL

---

guides/common/modules/con_composite-content-views-overview.adoc
guides/common/modules/con_external-authentication-for-provisioned-hosts.adoc
guides/common/modules/con_host-substatus-overview.adoc
guides/common/modules/con_managing-content-views.adoc
guides/common/modules/con_managing-dhcp-using-smart-proxy.adoc
guides/common/modules/con_managing-dns-using-smart-proxy.adoc
guides/common/modules/con_overview-of-hosts.adoc
guides/common/modules/con_performance-tuning-quickstart.adoc
guides/common/modules/con_puma-workers-and-threads-recommendations.adoc
guides/common/modules/proc_adding-installation-media.adoc
guides/common/modules/proc_adding-packages-to-a-host-collection.adoc
guides/common/modules/proc_assigning-a-tailoring-file-to-a-policy.adoc
guides/common/modules/proc_benchmark-disk-performance.adoc
guides/common/modules/proc_configuring-project-environment-for-performance.adoc
guides/common/modules/proc_configuring-selinux-to-ensure-access-on-custom-ports.adoc
guides/common/modules/proc_creating-a-content-view-filter-for-errata.adoc
guides/common/modules/proc_creating-multiple-locations.adoc
guides/common/modules/proc_estimating-the-size-of-a-backup.adoc
guides/common/modules/proc_importing-ostree-content.adoc
guides/common/modules/proc_overriding-ansible-variables.adoc
guides/common/modules/proc_registering-hosts.adoc
guides/common/modules/proc_tuning-with-predefined-profiles.adoc
guides/common/modules/proc_uploading-a-tailoring-file.adoc
guides/common/modules/ref_authentication-settings.adoc
guides/common/modules/ref_capsule-server-scalability-considerations.adoc
guides/common/modules/ref_discovered-settings.adoc
guides/common/modules/ref_ports-and-firewall-requirements.adoc
guides/common/modules/ref_provisioning-settings.adoc
guides/common/modules/ref_storage-guidelines.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc

Follow-up to https://github.com/theforeman/foreman-documentation/pull/1696
(I only cherrypicked it, I didn't re-run the replacement script.)

Issue 1423 typography endashes 3.1

---

guides/common/assembly_importing-kickstart-repositories.adoc
guides/common/modules/con_importing-kickstart-repositories.adoc
guides/common/modules/proc_importing-kickstart-repositories.adoc
guides/doc-Managing_Content/master.adoc

Add procedure to import kickstart repos for EL9

---

guides/README.md

Update convention for images (issue 1261)

---

guides/common/modules/proc_preparing-a-host-for-external-databases.adoc

Fixes: 35285d7b17647440e22f54d99cd5a93084728f75

properly enable the needed repos on el8 too

---

guides/doc-Planning_for_Project/topics/Configuration_Management_Support.adoc
guides/doc-Planning_for_Project/topics/Content_Delivery_Network.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Glossary.adoc
guides/doc-Planning_for_Project/topics/Hosts.adoc
guides/doc-Planning_for_Project/topics/Introduction.adoc
guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc

Fine tuning for Satellite 6.12 GA.

Fine tune - Planning

---

guides/common/modules/con_transport-modes-for-remote-execution.adoc
guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
guides/common/modules/proc_migrating-from-katello-agent-to-remote-execution.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2136485

Improve REX pull

---

.github/dependabot.yml

add dependabot config to update our actions

---

guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
guides/common/modules/proc_installing-the-dns-infoblox-module.adoc
guides/common/modules/proc_reverting-to-internal-dns-service.adoc
guides/common/modules/ref_dns-options-for-network-configuration.adoc

See individual commits for details. I think they could be picked all the way down to 3.1 but I didn't check if they all apply cleanly.

Various DNS installer related documentation fixes

---

guides/common/attributes-orcharhino.adoc

[orcharhino 6.1 Release Notes](https://orcharhino.com/orcharhino-6-1-0/)

Bump orcharhino version to 6.1

---

guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
guides/common/modules/proc_importing-all-available-ansible-playbooks.adoc
guides/common/modules/proc_importing-an-ansible-playbook-by-name.adoc
guides/doc-Deploying_Hosts_AppCentric/master.adoc

Add procedures on how to import ansible playbooks with API

Add procedures on how to import ansible playbooks

---

guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc

Add note in Prerequisites to upgrade EL version for 3.3

---

guides/common/attributes.adoc

Foreman 3.5 [has branched](https://community.theforeman.org/t/foreman-3-5-branching-process/31040) and documentation should follow. 3.5.0-rc1 is [in progress](https://community.theforeman.org/t/foreman-3-5-0-rc1-release-process/31183).

Prepare Foreman 3.5 branch

---

guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
guides/common/modules/ref_capsule-server-scalability-considerations.adoc
guides/common/modules/ref_system-requirements.adoc

Cherry-picks vary by commit, see commit messages. (I'll do them once approved.)

Various updates - Installing

---

guides/common/attributes-base.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes-titles.adoc
guides/common/attributes.adoc
guides/common/linkchecker.ini
guides/common/modules/con_managing-red-hat-subscriptions.adoc
guides/common/modules/con_synchronizing-content-between-servers.adoc
guides/common/modules/proc_deleting-multiple-compliance-reports.adoc
guides/common/modules/proc_enabling-auto-attach.adoc
guides/common/modules/proc_exporting-report-templates-using-the-api.adoc
guides/common/modules/proc_importing-report-templates-using-the-api.adoc
guides/common/modules/proc_renaming-server.adoc
guides/common/modules/proc_restoring-from-a-full-backup.adoc
guides/doc-Planning_for_Project/topics/Capsule_Server_Overview.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
guides/scripts/unify_emphasis.py

Taken over #1750 at @ekohl's request plus implemented feedback.
Added an attribute for **Configuring VM Subscriptions** guide.
Edited **Disconnected** guide URL attribute to match the **Disconnected** guide title attribute.

Verify all Satellite doc links - taken over from Ewoud

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/con_synchronizing-content-between-servers.adoc
guides/common/modules/proc_restoring-from-a-full-backup.adoc
guides/common/modules/ref_performing-a-fresh-installation-of-a-server-on-el8.adoc
guides/doc-Planning_for_Project/topics/Capsule_Server_Overview.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

Fix URLs to Disconnected guide on 3.1

---

guides/common/attributes-base.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes-titles.adoc
guides/common/attributes.adoc
guides/common/modules/con_synchronizing-content-between-servers.adoc
guides/common/modules/con_template-writing-reference.adoc
guides/common/modules/proc_deleting-multiple-compliance-reports.adoc
guides/common/modules/proc_enabling-auto-attach.adoc
guides/common/modules/proc_exporting-report-templates-using-the-api.adoc
guides/common/modules/proc_importing-report-templates-using-the-api.adoc
guides/common/modules/proc_renaming-server.adoc
guides/common/modules/proc_restoring-from-a-full-backup.adoc
guides/common/modules/ref_performing-a-fresh-installation-of-a-server-on-el8.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc
guides/doc-Planning_for_Project/topics/Hosts.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

Changes made in #1775 cherry-picked to 3.2 branch. While I realize that most of the changes here are irrelevant for 3.2 since there is no Satellite version, it could prevent merge conflicts in future.

Verify All Satellite doc links on 3.2

---

guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/attributes-titles.adoc
guides/common/attributes.adoc
guides/common/modules/con_template-writing-reference.adoc
guides/common/modules/proc_deleting-multiple-compliance-reports.adoc
guides/common/modules/proc_enabling-auto-attach.adoc
guides/common/modules/proc_exporting-report-templates-using-the-api.adoc
guides/common/modules/proc_importing-report-templates-using-the-api.adoc
guides/common/modules/proc_renaming-server.adoc
guides/common/modules/proc_restoring-from-a-full-backup.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc
guides/doc-Planning_for_Project/topics/Hosts.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc

Changes from #1775 cherry-picked to 3.1.

Verify All Satellite doc links on 3.1

---

guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc

Fix links in Managing Content

---

guides/common/modules/proc_configuring-repositories.adoc

Fixes: b5fdcc05a78142212ff85da84f85de33e8e02cb4

don't enable the repos on rhel twice

---

guides/common/modules/con_synchronizing-content-between-servers.adoc

Fix URL context

---

guides/common/modules/con_template-writing-reference.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Glossary.adoc
guides/doc-Planning_for_Project/topics/Hosts.adoc

Fixing links uncovered in #1806.
Dropped links to non-existent sections.
Updated links to existing sections.

Update links on 3.1

---

.github/workflows/deploy.yml
guides/Makefile
guides/common/attributes-base.adoc

This is a cherry pick of https://github.com/theforeman/foreman-documentation/pull/1804

Enable linkchecking again

---

guides/common/attributes-satellite.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc

Fix RN link and drop EL 7 reference from Upgrading guide

---

guides/common/modules/ref_storage-requirements.adoc

Fixes: b5fdcc05a78142212ff85da84f85de33e8e02cb4

remove duplicate external-db storage hint

---

guides/common/modules/con_template-writing-reference.adoc

Show Smart Class Parameters for orcharhino

---

guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc

Use EL8 to set up the load balancer

---

guides/common/attributes-satellite.adoc
guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc

changes from #1830 applied to 3.3 branch.

Set correct repositories in Cloning server on 3.3

---

guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/proc_installing-from-the-offline-repositories.adoc
guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
guides/common/modules/proc_resolving-package-dependancy-errors.adoc
guides/common/modules/snip_satellite-el8-enable-note.adoc

Made the note about satellite:el8 into a snippet and included where appropriate.
The second commit is a response to [BZ#2141133](https://bugzilla.redhat.com/show_bug.cgi?id=2141133)

Add a note about satellite:el8 where appropriate

---

guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/proc_installing-from-the-offline-repositories.adoc
guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
guides/common/modules/proc_resolving-package-dependancy-errors.adoc
guides/common/modules/snip_satellite-el8-enable-note.adoc

Changes from #1844 applied to 3.3 branch, should be also applicable to 3.2 and 3.1.

Add a note about satellite:el8 module where appropriate on 3.3

---

CONTRIBUTING.md

Hey! As already revealed Monday to some of you, I wrote a blog article on using git as a technical writer. I hope this makes contributing ever easier.

Add link to blog article about using git

---

.github/PULL_REQUEST_TEMPLATE.md

Follow-up PR for https://github.com/theforeman/foreman-documentation/pull/1853

Add orcharhino version to PR template

---

guides/doc-Release_Notes/topics/foreman-3.5.0.adoc
guides/doc-Release_Notes/topics/foreman.adoc

Preferably only approve this now and merge this once it's been released. See https://community.theforeman.org/t/foreman-3-5-0-rc2-release-process/31354 for that.

Foreman 3.5.0-rc2 release notes

---

guides/common/modules/con_configuring-networking.adoc
guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc
guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
guides/common/modules/proc_creating-operating-systems.adoc

Hide text for orcharhino builds

---

guides/common/modules/proc_salt-salt-variables.adoc

Remove broken xref

---

guides/common/assembly_using-kernelcare.adoc
guides/common/modules/con_kernelcare_client.adoc
guides/common/modules/con_using-the-kernelcare-plug-in.adoc
guides/common/modules/proc_creating-kernelcare-repositories-el.adoc
guides/common/modules/proc_installing-the-kernelcare-package-on-managed-hosts.adoc
guides/common/modules/proc_installing-the-kernelcare-plug-in.adoc
guides/common/modules/proc_live-patching-hosts-using-kernelcare.adoc
guides/common/modules/proc_viewing-patched-kernel-version.adoc
guides/doc-Managing_Hosts/master.adoc

Add documentation for Foreman KernelCare plugin

---

guides/common/modules/proc_installing-the-kernelcare-plug-in.adoc
guides/doc-Managing_Hosts/master.adoc

Kernelcare 3.4

---

web/content/release-3.1.adoc

Follow-up to https://github.com/theforeman/foreman-documentation/pull/1891

Link to currently built guide for 3.1

---

guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc

Small cleanup in "Managing File Repositories"

---

guides/common/modules/con_limitations-to-repository-dependency-resolution.adoc
guides/common/modules/proc_creating-operating-systems.adoc
guides/doc-Upgrading_and_Updating/topics/introduction_updating_satellite.adoc

This PR fixes https://github.com/theforeman/foreman-documentation/issues/1689

Fix semantic versioning Terminology

---

guides/common/assembly_configuring-provisioning-resources.adoc
guides/common/modules/proc_creating-custom-provisioning-snippets.adoc
guides/common/modules/ref_custom-provisioning-snippet-example-for-debian.adoc
guides/common/modules/ref_custom-provisioning-snippet-example-for-enterprise-linux.adoc

Documents https://github.com/theforeman/foreman/pull/9483

Document "Custom Post" and "Custom Pre" Provisioning Snippets

---

guides/common/modules/con_user-groups.adoc
guides/common/modules/proc_configuring-external-user-groups.adoc
guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
guides/common/modules/proc_configuring-project-to-use-ldap.adoc
guides/common/modules/proc_creating-a-user.adoc
guides/common/modules/proc_renaming-server.adoc
guides/common/modules/ref_description-of-ldap-settings.adoc
guides/doc-Administering_Project/master.adoc
guides/doc-Installing_Server/master.adoc

Move  "Configuring external authentication" to Installing Server

---

web/content/js/versions.js

Link: https://docs.theforeman.org/nightly/Tuning_Performance/index-katello.html
not available in 3.2 and below.

Add Tuning Performance to navbar

---

guides/common/attributes-base.adoc
guides/common/attributes-foreman-deb.adoc
guides/common/modules/proc_benchmarking-raw-db-performance.adoc
guides/common/modules/proc_estimating-the-size-of-a-backup.adoc
guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc
guides/common/modules/proc_installing-postgresql.adoc
guides/common/modules/proc_performing-a-snapshot-backup.adoc
guides/common/modules/ref_capsule-storage-requirements.adoc
guides/common/modules/ref_storage-requirements.adoc
guides/doc-Planning_for_Project/topics/Required_Technical_Users.adoc

3.3 had conflicts so a manual pick of https://github.com/theforeman/foreman-documentation/pull/1825 was needed.

Cherry pick PostgreSQL attributes PR to 3.3

---

web/content/index.adoc

Fixes: ad2b32f8ed91434000e31ee20171643d286a3bcf

Correct landing page on (un)supported versions

---

.github/PULL_REQUEST_TEMPLATE.md

based on https://github.com/theforeman/foreman-documentation/milestone/2
cc @ekohl

Add support EL versions to PR template

---

guides/common/modules/proc_creating-an-organization.adoc
guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc

Introduce new Candlepin changes

---

guides/doc-Planning_for_Project/topics/Content_Management_Support.adoc

Planning guide -added architectures for RHEL 9

---

guides/common/modules/con_using-ldap.adoc

Remove a paragraph about SSSD

---

guides/common/modules/proc_live-patching-hosts-using-kernelcare.adoc

Clarify update kernel job template

---

guides/common/assembly_administering-hosts.adoc

Follow-up PR to https://github.com/theforeman/foreman-documentation/pull/1960 @bangelic

Simplify ifdef directives

---

guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
guides/common/modules/proc_setting-the-job-rate-limit-on-smartproxy.adoc

Set the job rate limit on smartproxy

---

guides/common/modules/proc_configuring-kerberos-authentication-for-remote-execution.adoc
guides/common/modules/proc_installing-webhooks-plugin.adoc

BZ links:
* 1st: https://bugzilla.redhat.com/show_bug.cgi?id=2170144
* 2nd: https://bugzilla.redhat.com/show_bug.cgi?id=2170410

Minor bug fixes

---

guides/common/modules/proc_configuring-the-fallback-to-any-smartproxy-setting.adoc
guides/common/modules/proc_configuring-the-global-smartproxy-remote-execution-setting.adoc

I know I just made a PR like this a couple days ago but these I randomly found while browsing through the guides. This time I used `git grep` to see if there were any more instances but was not able to find any.

Split more conjugated words

---

guides/common/assembly_managing-activation-keys.adoc
guides/common/modules/con_managing-activation-keys.adoc
guides/common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc
guides/common/modules/proc_creating-an-activation-key.adoc
guides/common/modules/proc_enabling-and-disabling-repositories-on-activation-key.adoc
guides/common/modules/proc_enabling-auto-attach.adoc
guides/common/modules/proc_updating-red-hat-subscriptions-on-multiple-hosts.adoc
guides/common/modules/proc_updating-subscriptions-associated-with-an-activation-key.adoc
guides/common/modules/snip_do-not-attach-subscriptions-to-key.adoc
guides/common/modules/snip_only-valid-if-sca-disabled.adoc

Inspect individual commits for easier review.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2166944
cc @jeremylenz 

Update Managing Content guide (SCA, Activation keys)

---

guides/common/assembly_host-management-and-monitoring-using-cockpit.adoc
guides/common/modules/proc_disabling-cockpit-on-project.adoc

CC @adamruzicka 
[BZ link](https://bugzilla.redhat.com/show_bug.cgi?id=2168503)
Cherry-picks:
First commit:
Second commit:

Disable Cockpit

---

guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc

Fix attribute

---

guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc

Clarify remediations in host Leapp upgrade 2.5

---

guides/common/modules/proc_changing-the-method-the-bootstrap-script-uses-to-download-the-consumer-rpm.adoc
guides/common/modules/proc_creating-a-domain-for-a-host-during-registration.adoc
guides/common/modules/proc_enabling-remote-execution-on-the-host.adoc
guides/common/modules/proc_migrating-a-host-from-one-server-to-another-server.adoc
guides/common/modules/proc_migrating-a-host-from-red-hat-network.adoc
guides/common/modules/proc_providing-an-alternative-fqdn-for-the-host.adoc
guides/common/modules/proc_providing-the-hosts-ip-address.adoc
guides/common/modules/proc_registering-a-host-for-content-management-only.adoc
guides/common/modules/proc_registering-a-host-using-the-bootstrap-script.adoc
guides/common/modules/proc_registering-a-host-without-puppet.adoc

Remove multiple occurences of extra comma

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman-3.5.2.adoc

Release notes for 3.5.2

---

guides/common/modules/proc_importing-container-images.adoc

My bad. See https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Importing_Container_Images_content-management & https://github.com/theforeman/foreman-documentation/pull/2056
I will simply merge/cherry-pick this after running GHA.

Resolve attributes in code blocks

---

guides/common/assembly_configuring-external-authentication.adoc
guides/common/attributes-base.adoc
guides/common/modules/con_using-personal-access-tokens.adoc
guides/common/modules/proc_creating-a-personal-access-token.adoc
guides/common/modules/proc_revoking-a-personal-access-token.adoc

Document Personal Access Tokens

---

guides/common/modules/con_using-freeipa.adoc
guides/common/modules/con_using-ldap.adoc
guides/common/modules/snip_do-not-use-both-ldap-and-freeipa.adoc

BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=1266407

Do not use both LDAP and FreeIPA for authentication

---

guides/common/modules/con_prerequisites-for-configuring-smart-proxy-server-for-load-balancing.adoc

Follow-up for https://github.com/theforeman/foreman-documentation/pull/2064

3.3: Add missing prerequisite for load balancing

---

guides/common/modules/proc_assigning-a-sync-plan-to-multiple-products.adoc
guides/common/modules/proc_changing-the-method-the-bootstrap-script-uses-to-download-the-consumer-rpm.adoc
guides/common/modules/proc_creating-a-domain-for-a-host-during-registration.adoc
guides/common/modules/proc_enabling-remote-execution-on-the-host.adoc
guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
guides/common/modules/proc_migrating-a-host-from-one-server-to-another-server.adoc
guides/common/modules/proc_migrating-a-host-from-red-hat-network.adoc
guides/common/modules/proc_providing-an-alternative-fqdn-for-the-host.adoc
guides/common/modules/proc_providing-the-hosts-ip-address.adoc
guides/common/modules/proc_registering-a-host-for-content-management-only.adoc
guides/common/modules/proc_registering-a-host-using-the-bootstrap-script.adoc
guides/common/modules/proc_registering-a-host-without-puppet.adoc
guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc

Please review commit by commit; only the last commit contains a manual change. All other commits can be reproduced for both review and after potential merge conflicts during rebasing.

Ensure --organization parameter examples are somewhat consistant

---

guides/common/attributes-base.adoc
guides/common/modules/con_content-promotion-across-the-application-life-cycle.adoc
guides/common/modules/con_managing-content-views.adoc

Introduce pkg_arch and pkg_ext attributes

---

guides/doc-Release_Notes/topics/foreman-3.6.0.adoc

This adds the last release notes compared to RC2 and declares the version as stable.

Release Foreman 3.6.0

---

guides/common/modules/ref_general-settings-information.adoc

use project macro for URL setting

---

guides/common/attributes-base.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/con_unattended-use-customization-and-image-remastering.adoc
guides/common/modules/proc_adding-life-cycle-environments.adoc
guides/common/modules/proc_building-a-discovery-image.adoc
guides/common/modules/proc_configuring-network-services.adoc
guides/common/modules/proc_configuring-the-discovery-service.adoc
guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
guides/common/modules/proc_installing-the-discovery-service.adoc
guides/common/modules/proc_registering-hosts.adoc
guides/common/modules/proc_removing-life-cycle-environments-from-smart-proxy.adoc
guides/common/modules/proc_renaming-server.adoc
guides/common/modules/proc_scheduling-a-recurring-ansible-job-for-a-host.adoc
guides/common/modules/snip_using-file-repositories-for-installation-media-for-debian-and-ubuntu.adoc

Please review commit by commit. Note that "hammer proxy_content" must have been an error.

Various small changes for  orcharhino build target

---

guides/common/modules/proc_configuring-the-discovery-service.adoc

Follow-up PR to fix broken 3.3 build due to https://github.com/theforeman/foreman-documentation/commit/87aefa7b4619462829361529680a12bd2e4c8bb5
Will merge with "green" GHA.

Install FDI package only on orcharhino and Satellite

---

guides/common/modules/proc_configuring-project-to-use-ldap.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2176549

Fix LDAP Authentication Source path in ProjectWebUI

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.8.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc
guides/doc-Release_Notes/topics/katello.adoc

Add katello 4.8 branching docs

---

guides/doc-Upgrading_and_Updating/topics/upgrading_content_hosts.adoc

The mention of a bug in Bugzilla needs to be removed because it was
closed as a WONTFIX.

Remove mention of bug in procedure

---

guides/common/modules/con_how-puppet-integrates-with-project.adoc
guides/common/modules/proc_disabling-puppet.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-manually.adoc

Various small improvements in Puppet-related modules. Mostly requested by RH QE, I added a couple more.

Improve Puppet-related text

---

guides/common/modules/con_managing-red-hat-subscriptions.adoc
guides/common/modules/con_registering_hosts.adoc
guides/common/modules/snip_deprecated-entitlement-subscriptions.adoc

Make a repeating paragraph into a snippet.
No content modification, just code cleanup.
Followup to #2134 

Snippetize a repeating paragraph

---

guides/doc-Content_Management_Guide/topics/Importing_Content.adoc

Fix incorrect script in Managing Content on 2.5

---

guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc

Add link for steps to create a certificate for v3.1

---

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc

Fix plugin enablement command 2.5

---

guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
guides/doc-Content_Management_Guide/topics/Managing_Subscriptions.adoc
guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc

Rename Smart Management to Satellite 2.5

---

guides/common/modules/proc_configuring-project-to-use-ldap.adoc

Fixed the repetition of the same action.

Fix duplicate action

---

guides/common/assembly_provisioning-virtual-machines-proxmox.adoc
guides/common/modules/con_provisioning-virtual-machines-in-proxmox.adoc
guides/common/modules/proc_adding-a-proxmox-connection-to-server.adoc
guides/common/modules/proc_adding-proxmox-details-to-a-compute-profile.adoc
guides/common/modules/proc_adding-proxmox-images-to-server.adoc
guides/common/modules/proc_creating-hosts-on-proxmox.adoc
guides/common/modules/proc_creating-hosts-on-vmware.adoc
guides/common/modules/proc_deleting-a-virtual-machine-on-proxmox.adoc
guides/common/modules/proc_importing-a-virtual-machine-from-proxmox-into-project.adoc
guides/common/modules/proc_installing-the-proxmox-plug-in.adoc
guides/doc-Provisioning_Hosts/master.adoc

Add documentation for Proxmox

---

guides/common/modules/ref_description-of-ldap-settings.adoc

Fix the Attribute rendering

---

guides/common/attributes-satellite.adoc
guides/common/linkchecker.ini
guides/doc-Administering_Project/docinfo.xml
guides/doc-Administering_with_Ansible/docinfo.xml
guides/doc-Configuring_Load_Balancer/docinfo.xml
guides/doc-Deploying_Project_on_AWS/docinfo.xml
guides/doc-Installing_Proxy/docinfo.xml
guides/doc-Installing_Server/docinfo.xml
guides/doc-Installing_Server_Disconnected/docinfo.xml
guides/doc-Managing_Configurations_Ansible/docinfo.xml
guides/doc-Managing_Configurations_Puppet/docinfo.xml
guides/doc-Managing_Content/docinfo.xml
guides/doc-Managing_Hosts/docinfo.xml
guides/doc-Planning_for_Project/docinfo.xml
guides/doc-Provisioning_Hosts/docinfo.xml
guides/doc-Tuning_Performance/docinfo.xml
guides/doc-Upgrading_and_Updating/docinfo.xml

This PR is of Downstream. I am open to Upstream as well. We can wait for Upstream v3.7 (maybe the planned Satellite 6.14) to cherry-pick. 

Initialize new version

---

guides/common/modules/con_content-filter-overview.adoc

Add line about source RPMs

---

guides/common/modules/ref_migrating-ansible-content.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2209035

Fix Ansible Automation hub link

---

guides/common/modules/proc_configuring-a-host-for-openscap.adoc
guides/common/modules/proc_configuring-a-host-group-for-openscap.adoc
guides/common/modules/proc_enabling-openscap.adoc

- Add command arguments to install modules for policy deployment
- Fixup the ID and links for SEO

Improve Installing OpenSCAP on SmartProxy

---

Makefile
README.md
guides/common/attributes.adoc
web/content/index.adoc
web/content/js/versions.js
web/content/release-3.7.adoc

I'm mostly submitting this as PR to raise visibility and will merge this myself.

Reflect Foreman 3.7 has branched

---

guides/common/modules/con_how-to-synchronize-content-using-export-and-import.adoc

Removed extra period in NOTE number 2

---

guides/common/modules/proc_creating-snapshots-of-a-managed-host.adoc

Document "Snapshot Mode" in Foreman Snapshot Management plug-in

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.9.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc
guides/doc-Release_Notes/topics/katello.adoc

Updates for Katello 4.9.0.rc1

---

guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc

The example links contained incorrect paths + further tweaks.

Improve Downloading Files to Hosts

---

guides/common/modules/ref_examples-ldap-filters.adoc

Render note as a note and not a code block

---

guides/common/modules/proc_installing-the-proxmox-plug-in.adoc

Use foreman-installer to install Proxmox

---

guides/common/modules/proc_deploying-a-policy-in-a-host-group-using-ansible.adoc
guides/common/modules/proc_deploying-a-policy-in-a-host-group-using-puppet.adoc
guides/common/modules/proc_deploying-a-policy-on-a-host-using-ansible.adoc
guides/common/modules/proc_deploying-a-policy-on-a-host-using-puppet.adoc
guides/common/modules/ref_inclusion-of-remote-scap-resources.adoc
guides/doc-Managing_Security_Compliance/master.adoc

Fetch remote SCAP resources

---

web/content/index.adoc
web/content/js/versions.js

Merge https://github.com/theforeman/foreman-documentation/pull/2247 first.

Change latest supported version to be 3.7.0

---

guides/common/modules/proc_creating-a-job-template.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2116369

Enable Ansible Callback in job template

---

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc

Fix format and reword

---

guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
guides/common/modules/con_using-extended-cron-lines.adoc

Add module about extended cron lines

---

guides/common/modules/proc_adding-amazon-ec2-images-to-server.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2218859

Fix button label

---

guides/common/modules/proc_viewing-a-compliance-policy.adoc

Improve Show Guide step on 3.5

---

guides/common/modules/proc_booting-virtual-machines.adoc
guides/common/modules/proc_chainbooting-ipxe-from-pxelinux.adoc
guides/common/modules/snip_step-set-bootstrap-http-url.adoc

Snippetize setting bootstrap URL in Provisioning

---

guides/common/modules/con_resolving-package-dependencies.adoc
guides/common/modules/proc_adding-errata-to-an-incremental-content-view.adoc

Update dependency solving guidelines

---

guides/common/modules/proc_creating-a-composite-content-view.adoc

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2222938

Fix hammer command in Creating a Composite CV

---

guides/common/modules/con_how-puppet-integrates-with-project.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-provisioning.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-manually.adoc
guides/doc-Managing_Configurations_Puppet/master.adoc

Requested by RH QA. + Additional improvements to all builds.

Add note about enabled Puppet (Inst&Cfg Agent)

---

guides/common/assembly_provisioning-virtual-machines-proxmox.adoc
guides/common/modules/proc_adding-a-remote-console-connection-for-a-managed-host-on-proxmox.adoc

Add procedure for remote console on Proxmox

---

guides/common/modules/proc_creating-a-compliance-policy.adoc
guides/common/modules/proc_deleting-a-compliance-policy.adoc
guides/common/modules/proc_deleting-a-compliance-report.adoc
guides/common/modules/proc_deleting-multiple-compliance-reports.adoc
guides/common/modules/proc_editing-a-compliance-policy.adoc
guides/common/modules/proc_examining-compliance-failures-of-a-host.adoc
guides/common/modules/proc_examining-hosts-per-rule-compliance-result.adoc
guides/common/modules/proc_listing-available-scap-contents.adoc
guides/common/modules/proc_loading-the-default-openscap-contents.adoc
guides/common/modules/proc_running-a-security-compliance-scan-on-demand.adoc
guides/common/modules/proc_uploading-a-tailoring-file.adoc
guides/common/modules/proc_uploading-additional-scap-content.adoc
guides/common/modules/proc_viewing-a-compliance-policy.adoc
guides/common/modules/proc_viewing-compliance-policy-statistics.adoc

Improve user account prerequisite wording (SCAP)

---

.github/PULL_REQUEST_TEMPLATE.md
guides/common/attributes-orcharhino.adoc

See https://orcharhino.com/orcharhino-6-5-0/
:tada:

Bump orcharhino version to 6.5

---

guides/common/modules/ref_system-requirements.adoc

Clarify FUTURE crypto-policy

---

guides/common/assembly_administer-settings-information.adoc
guides/common/modules/proc_using-red-hat-insights.adoc
guides/common/modules/ref_redhat-cloud-settings.adoc
guides/doc-Managing_Hosts/master.adoc

Show RHCloud plug-in for orcharhino

---

guides/common/attributes-base.adoc
guides/common/modules/proc_configuring-a-host-for-registration.adoc
guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
guides/common/modules/proc_configuring-podman-to-trust-the-ca.adoc
guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
guides/common/modules/proc_importing-a-content-view-version-from-a-web-server.adoc
guides/common/modules/proc_importing-a-repository-from-a-web-server.adoc
guides/common/modules/proc_importing-into-the-library-environment-from-a-web-server.adoc

* Use foreman-server-com and smartproxy-example-com where appropriate
* Use separate FQDN for remote server

Introduce attribute server-example-com

---

web/content/js/versions.js

Follow-up PR for https://github.com/theforeman/foreman-documentation/pull/2355

Add Salt to navigation

---

guides/common/modules/proc_adding-custom-deb-repository-example-for-debian-11.adoc
guides/common/modules/proc_adding-custom-deb-repository-example-for-ubuntu-22-04.adoc

Update link to subscription-manager for DEB

---

guides/common/modules/proc_configuring-remote-execution-for-pull-client-on-project-server.adoc
guides/common/modules/proc_configuring-remote-execution-for-pull-client-smart-proxy.adoc

Remove leading whitespace

---

guides/doc-Release_Notes/topics/foreman.adoc

Release notes foreman ansible 11

---

guides/common/modules/proc_adding-vmware-images-to-server.adoc

Correct fields from WebUI to create image

---

web/content/js/versions.js

Add Updating Guide to Upstream

---

guides/doc-Updating_Project/docinfo.xml

Add RH to the Title of the Documentation.

Fix Docinfo.xml

---

guides/common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc

Reword attaching RH subscriptions

---

guides/common/modules/snip_only-valid-if-sca-disabled.adoc

Show link to redhat.com only for Satellite

---

guides/common/modules/con_transport-modes-for-remote-execution.adoc

Fixup #2440

---

guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc

https://github.com/theforeman/foreman-documentation/pull/2473 addressed [BZ#2238788](https://bugzilla.redhat.com/show_bug.cgi?id=2238788) for versions 3.7 and later. This PR introduces the same change, but for versions 3.6 and previous.

Be more specific about creating a yum config file

---

guides/common/modules/proc_installing-packages-on-a-host.adoc
guides/common/modules/proc_removing-packages-from-a-host.adoc
guides/common/modules/proc_upgrading-packages-on-a-host.adoc
guides/common/modules/snip_managing-packages-api.adoc

Add API procedures to Managing Packages

---

guides/common/modules/proc_running-salt.adoc
guides/common/modules/proc_viewing-salt-reports.adoc

Rework procedure to run Salt

---

guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc

This change only landed in nightly now, so no cherry picks.

Refs #36697 - Use installer to modify Candlepin logging

---

guides/common/modules/con_unattended-use-customization-and-image-remastering.adoc
guides/common/modules/proc_provisioning-ubuntu-autoinstall-through-smart-proxies.adoc
guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc
guides/doc-Managing_Hosts/master.adoc
guides/doc-Provisioning_Hosts/master.adoc

Remove xref for orcharhino

---

guides/common/modules/proc_exporting-a-content-view-version.adoc
guides/common/modules/proc_exporting-a-repository-incrementally-in-a-syncable-format.adoc
guides/common/modules/proc_exporting-a-repository-incrementally.adoc
guides/common/modules/proc_exporting-a-repository.adoc
guides/common/modules/proc_importing-a-content-view-version-from-a-web-server.adoc
guides/common/modules/proc_importing-a-content-view-version.adoc
guides/common/modules/proc_importing-a-repository-from-a-web-server.adoc
guides/common/modules/proc_importing-a-repository.adoc
guides/common/modules/proc_importing-into-the-library-environment-from-a-web-server.adoc
guides/common/modules/proc_importing-into-the-library-environment.adoc
guides/common/modules/proc_synchronizing-a-single-repository.adoc
guides/common/modules/proc_using-upstream-server-as-a-content-store.adoc
guides/common/modules/proc_using-upstream-server-to-sync-content-view-versions.adoc

Allow exporting DEB content

---

guides/common/assembly_managing-suse-content.adoc
guides/common/modules/proc_adding-an-scc-account.adoc
guides/common/modules/proc_adding-errata-to-an-incremental-content-view.adoc
guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
guides/common/modules/proc_configuring-server-to-consume-content-from-a-custom-cdn.adoc
guides/common/modules/proc_configuring-server-to-sync-content-using-exports.adoc
guides/common/modules/proc_configuring-server-to-synchronize-content-over-a-network.adoc
guides/common/modules/proc_configuring-simplified-alternate-content-sources.adoc
guides/common/modules/proc_creating-an-organization.adoc
guides/common/modules/proc_importing-ostree-content.adoc
guides/common/modules/proc_importing-suse-products.adoc
guides/common/modules/proc_importing-the-katello-root-ca-certificate.adoc
guides/common/modules/proc_managing-ostree-content-with-content-views.adoc
guides/common/modules/proc_removing-an-scc-account.adoc
guides/common/modules/proc_reverting-server-to-download-content-from-red-hat-cdn.adoc
guides/common/modules/proc_updating-an-scc-account.adoc
guides/doc-Upgrading_Project/topics/proc_upgrading-content-hosts.adoc

Please review the first two commits separately. They're just fixing something I was unsure and had to look at the existing source code.

Add Hammer CLI procedures for SCC Manager plug-in

---

guides/common/modules/proc_removing-a-host-from-server.adoc

origin: [question in Foreman Community Forum](https://community.theforeman.org/t/delete-host-via-hammer-cli-dont-delete-from-the-web/35375?u=maximilian)

Remove host from Foreman using Hammer CLI

---

guides/common/attributes-base.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/con_load-balancing-considerations.adoc
guides/common/modules/proc_building-a-discovery-image.adoc
guides/common/modules/proc_cloning_satellite_server.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-repositories.adoc
guides/common/modules/proc_creating-a-personal-access-token.adoc
guides/common/modules/proc_exporting-a-content-view-version-in-a-syncable-format.adoc
guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
guides/common/modules/proc_updating-disconnected-server.adoc
guides/common/modules/proc_updating-server.adoc
guides/common/modules/proc_updating-smart-proxy.adoc
guides/common/modules/ref_system-requirements.adoc
guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
guides/doc-Upgrading_Project/topics/proc_upgrading-a-disconnected-project-server.adoc
guides/doc-Upgrading_Project/topics/proc_upgrading-smartproxy-server.adoc
guides/scripts/upstreamize.rb

Consolidate version attribute

---

guides/common/modules/proc_adding-a-bonded-interface.adoc
guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc
guides/common/modules/proc_configuring-network-services.adoc
guides/common/modules/proc_registering-clients-using-the-bootstrap-script.adoc

Remove network interface from foreman-installer

---

guides/common/modules/proc_loading-the-default-openscap-contents.adoc

Add link to RH Knowledgebase (SCAP) Satellite only

---

guides/common/modules/proc_tuning-apache-httpd-child-processes.adoc

https://docs.theforeman.org/nightly/Tuning_Performance/index-katello.html#tuning_apache_httpd_child_processes_performance-tuning

Use emphasis for file path

---

guides/common/modules/proc_provisioning-ubuntu-autoinstall-through-smart-proxies.adoc
guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc

I though I could handle the small merge conflict ...
Fixes https://github.com/theforeman/foreman-documentation/commit/e626a883d45772749973cbd36103056c84548875

Fix 3 4 create hosts

---

guides/common/assembly_provisioning-cloud-instances-azure.adoc
guides/common/assembly_provisioning-cloud-instances-ec2.adoc
guides/common/assembly_provisioning-cloud-instances-gce.adoc
guides/common/assembly_provisioning-cloud-instances-openstack.adoc
guides/common/assembly_provisioning-virtual-machines-kubevirt.adoc
guides/common/assembly_provisioning-virtual-machines-kvm.adoc
guides/common/assembly_provisioning-virtual-machines-proxmox.adoc
guides/common/assembly_provisioning-virtual-machines-rhv.adoc
guides/common/assembly_provisioning-virtual-machines-vmware.adoc
guides/common/assembly_using-pxe-to-provision-hosts.adoc
guides/common/modules/con_prerequisites-for-vmware-provisioning.adoc
guides/common/modules/con_provisioning-cloud-instances-on-google-compute-engine.adoc
guides/common/modules/con_provisioning-cloud-instances-on-microsoft-azure-resource-manager.adoc
guides/common/modules/con_provisioning-cloud-instances-on-openstack.adoc
guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc
guides/common/modules/con_provisioning-virtual-machines-on-kvm.adoc
guides/common/modules/con_provisioning-virtual-machines-on-ovirt.adoc
guides/common/modules/proc_configuring-a-finish-template-for-amazon-ec2.adoc
guides/common/modules/proc_creating-hosts-on-proxmox.adoc
guides/common/modules/proc_creating-hosts-on-vmware.adoc
guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
guides/common/modules/proc_creating-hosts-with-unattended-provisioning.adoc
guides/common/modules/proc_creating-image-based-hosts-on-amazon-ec2.adoc
guides/common/modules/proc_creating-image-only-hosts.adoc
guides/common/modules/proc_creating-network-or-image-based-hosts.adoc
guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc
guides/common/modules/snip_steps-create-a-host-tab-host.adoc
guides/common/modules/snip_steps-create-a-host-tab-interfaces.adoc

I have cherry-picked both commits from 3.4. This PR is just to be safe. Will merge with green GHA.

Cherry pick host snippet 3 3

---

guides/common/modules/con_backing-up-server-and-proxy.adoc

See https://docs.theforeman.org/3.7/Administering_Project/index-katello.html#backing-up-foreman-server-and-smart-proxy_admin

Remove plus sign

---

guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc

Hide plus sign for orcharhino

---

guides/common/attributes-base.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
guides/common/modules/proc_configuring-simplified-alternate-content-sources.adoc
guides/common/modules/proc_removing-life-cycle-environments-from-smart-proxy.adoc
guides/common/modules/snip_host-registration-steps.adoc

See https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Adding_Lifecycle_Environments_content-management

Use context attribute due to whitespace

---

guides/common/modules/proc_adding-a-bonded-interface.adoc
guides/common/modules/proc_creating-a-host.adoc
guides/common/modules/proc_creating-hosts-on-vmware.adoc
guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
guides/common/modules/proc_creating-hosts-with-unattended-provisioning.adoc
guides/common/modules/proc_creating-image-based-hosts-on-amazon-ec2.adoc
guides/common/modules/proc_creating-image-only-hosts.adoc
guides/common/modules/proc_creating-network-or-image-based-hosts.adoc

* Sort options in alphabetical order
* Use generic examples
* Prefer "--organization" over "--organization-id"
* Use descriptive variable names

Streamline commands for "hammer host create"

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.10.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc
guides/doc-Release_Notes/topics/katello.adoc

* [✓] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Updates for Katello 4.10.0 - Release notes

---

guides/common/modules/proc_configuring-repositories-el.adoc
guides/common/modules/proc_enabling-puppet.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
guides/doc-Quickstart/master.adoc

cherry-picks for https://github.com/theforeman/foreman-documentation/pull/2551

Cherry-picks for Puppet to 3.8

---

guides/common/modules/proc_configuring-repositories-el.adoc
guides/common/modules/proc_enabling-puppet.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
guides/doc-Quickstart/master.adoc

cherry-picks for https://github.com/theforeman/foreman-documentation/pull/2551

Cherry-picks for Puppet to 3.7

---

guides/common/attributes.adoc

With the GA release this is now officially supported.

Declare Foreman 3.8 as supported

---

guides/doc-Release_Notes/topics/foreman.adoc

Refs #36723 - Release note for Fedora/RH Atomic removal

---

guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
guides/doc-Upgrading_Project/topics/proc_upgrading-a-disconnected-project-server.adoc

document to create hstore during upgrade

---

guides/common/linkchecker.ini

Ignore Satellite 6.14 links

---

guides/common/modules/proc_executing-a-remote-job.adoc

https://bugzilla.redhat.com/show_bug.cgi?id=2209987

Explain how to run job on nested groups

---

guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
guides/common/modules/proc_configuring-simplified-alternate-content-sources.adoc
guides/common/modules/proc_removing-life-cycle-environments-from-smart-proxy.adoc
guides/common/modules/snip_host-registration-steps.adoc

Use double underscore for attributes

---

guides/doc-Release_Notes/topics/foreman.adoc
guides/doc-Release_Notes/topics/katello.adoc

Refs https://github.com/theforeman/foreman-documentation/pull/2560

Add placeholder for release notes

---

guides/common/modules/proc_upgrading-hosts-to-next-major-rhel-release.adoc

Fix link to RHEL guide

---

guides/common/modules/con_converting-a-host-to-rhel.adoc

A couple of formal improvements.

Improve Convert2RHEL [priority]

---

guides/common/assembly_searching-and-bookmarking.adoc
guides/common/modules/con_using-keyboard-shortcuts.adoc

Document keyboard shortcuts

---

README.md

as discussed during Triage today.

Add hint about docinfo.xml

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
guides/common/attributes.adoc
web/content/index.adoc
web/content/js/versions.js
web/content/release-3.9.adoc

Update site to include Foreman 3.9

---

guides/common/modules/proc_generating-host-monitoring-reports.adoc

Related to PR#2612 to fix cherry pick

---

guides/doc-Release_Notes/topics/katello-4.11.0.adoc
guides/doc-Release_Notes/topics/katello.adoc

Release notes for Katello 4.11.0.

Add release notes for Katello 4.11

---

guides/common/modules/proc_disabling-puppet.adoc

The user has to be warned about this Known Issue.

Add KI BZ#2087067 Puppet fails re-enablement

---

guides/common/modules/proc_adding-a-proxmox-connection-to-server.adoc
guides/common/modules/proc_adding-proxmox-details-to-a-compute-profile.adoc
guides/common/modules/proc_creating-hosts-on-proxmox.adoc

Specify adding individual Proxmox nodes

---

guides/common/modules/proc_creating-a-custom-product.adoc

The opening sentence ends with a preposition so it has been rewritten
to stay in active voice and read a little better.

Rewrite opening sentence

---

guides/common/modules/proc_creating-hosts-with-unattended-provisioning.adoc

Remove duplicated step 3.1

---

guides/common/assembly_installing-server-connected.adoc
guides/common/attributes-base.adoc
guides/common/attributes-foreman-deb.adoc
guides/common/modules/con_configuring-server.adoc
guides/common/modules/con_installing-server.adoc
guides/common/modules/con_performing-additional-configuration.adoc
guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
guides/common/modules/proc_renaming-smart-proxy.adoc
guides/common/modules/proc_securing-the-dhcp-api.adoc
guides/doc-Installing_Server/master.adoc

Follow-up to splitting project-* and client-* attributes

---

guides/common/modules/proc_adding-installation-media.adoc

Refs ed837f994691203498a551d533b22c89001bf55d
and PR #2678 on Github.

Use installation media over HTTP for orcharhino

---

guides/common/modules/proc_using-insights-with-satellite-server.adoc
guides/common/modules/proc_using-red-hat-insights.adoc

the section has been rewritten in 3.7 onwards so this is only needed for 3.5 and lower.

Fix link to Red Hat Insights guide

---

guides/common/modules/proc_synchronizing-content-from-project-server-to-smart-proxy-servers.adoc

cherry-pick as much as possible ^^

Fix spelling of unnecessary

---

guides/common/attributes-base.adoc
guides/common/attributes-foreman-el.adoc
guides/common/attributes-katello.adoc
guides/common/attributes-orcharhino.adoc
guides/common/modules/ref_supported-operating-systems.adoc
guides/doc-Planning_for_Project/topics/Glossary.adoc
web/content/index.adoc

An attempt to use EL and clarify the term Enterprise Linux.
Please cherry-pick my commits into: **N/A**

Clarify EL

---

guides/common/modules/con_smartproxy_performance_tests.adoc

current docs: https://docs.theforeman.org/nightly/Tuning_Performance/index-katello.html#Smart_Proxy_Performance_Tests_performance-tuning
Closes #2699

Fix asciidoc syntax

---

guides/common/modules/ref_supported-operating-systems.adoc

xref is not working, the target is in another guide.

Use guide link instead of xref [fix]

---

guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/con_host-group-settings-and-nested-host-groups.adoc
guides/common/modules/con_restricting-hosts-access-to-content.adoc
guides/common/modules/con_working-with-host-groups.adoc
guides/common/modules/proc_decreasing-performance-impact-of-the-pull-based-rex-transport.adoc
guides/common/modules/proc_refreshing-content-counts-on-smart-proxy.adoc

Make content type depend on Host OS

---

CONTRIBUTING.md
README.md
guides/README.md

The contributing guidelines in a single place + links + cosmetics

Improve READMEs

---

guides/common/modules/proc_adding-a-remote-console-connection-for-a-host-on-proxmox.adoc

Fix "VNC for hosts on Proxmox"

---

guides/common/modules/con_prerequisites-for-vmware-provisioning.adoc

Add support for VMware 8 for orcharhino

---

guides/common/attributes-orcharhino.adoc
guides/common/modules/proc_renaming-smart-proxy.adoc

Extend procedure "Rename Smart Proxy Server" for orcharhino

---

guides/common/assembly_introduction-to-provisioning.adoc
guides/common/assembly_preparing-environment-for-capsule-installation.adoc
guides/common/assembly_preparing-environment-for-installation.adoc
guides/common/modules/proc_creating-compute-profiles.adoc
guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
guides/common/modules/proc_registering-capsule-to-satellite-server.adoc
guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
guides/common/modules/ref_port-and-firewall-requirements.adoc
guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc
guides/common/modules/ref_supported-virtualization-infrastructures.adoc
guides/common/modules/ref_template-macros.adoc
guides/common/modules/ref_troubleshooting-sync-errors.adoc
guides/doc-Planning_for_Project/topics/Capsule_Server_Overview.adoc

follow-up task after we have renamed various titles.

Fix file names

---

guides/README.md

Reword reviews on Github

---

CONTRIBUTING.md

Add capitalization to contributing guidelines

---

guides/common/assembly_installing-server-connected.adoc
guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
guides/common/modules/proc_configuring-remote-execution-for-pull-client-on-project-server.adoc
guides/common/modules/proc_configuring-remote-execution-for-pull-client-smart-proxy.adoc
guides/common/modules/proc_configuring-satellite-deployment-with-an-external-dhcp-server.adoc
guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
guides/common/modules/proc_enabling-connections-from-capsule-to-satellite.adoc
guides/common/modules/proc_enabling-connections-to-capsule.adoc
guides/common/modules/proc_installing-postgresql.adoc
guides/common/modules/proc_installing-the-sos-package.adoc
guides/common/modules/proc_using-tftp-services-through-nat.adoc
guides/common/modules/snip_make-firewall-settings-persistant.adoc

Install "sos" on Foreman on EL/Katello & remove random secrets

---

guides/README.md
guides/common/modules/con_managing-python-type-content.adoc
guides/common/modules/proc_downloading-python-packages-to-a-host-from-a-python-repository.adoc
guides/common/modules/proc_installing-python-packages-from-server.adoc
guides/common/modules/proc_synchronizing-python-repositories.adoc
guides/common/modules/proc_uploading-files-to-a-python-repository.adoc
guides/common/modules/snip_managing-packages-api.adoc

Capitalize "Python"

---

.github/PULL_REQUEST_TEMPLATE.md

See https://orcharhino.com/orcharhino-6-7-0/

Add orcharhino 6.7 based on Foreman 3.5

---

guides/common/modules/proc_registering-a-host.adoc

Refs #36688 - Provide option to use wget for the new Register Host feature

---

guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
guides/common/assembly_configuring-external-dhcp.adoc
guides/common/assembly_installing-capsule-server.adoc
guides/common/assembly_performing-additional-configuration-on-capsule-server.adoc
guides/common/assembly_preparing-environment-for-capsule-installation.adoc
guides/common/modules/proc_cloning_satellite_server.adoc
guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc

Remove blank lines between anchor IDs and titles

---

guides/common/assembly_configuring-external-dhcp.adoc
guides/common/assembly_configuring-external-idm-dns.adoc
guides/common/assembly_configuring-external-services.adoc
guides/common/modules/con_configuring-project-with-external-dhcp.adoc
guides/common/modules/con_configuring-project-with-external-idm-dns.adoc
guides/common/modules/con_configuring-project-with-external-services.adoc

You can review this commit by commit; the built HTML should be 100% identical. I have only moved things around. I will create a follow-up PR to fix things.
:warning: Squash when merging!

Modularize external services

---

guides/common/modules/con_configuring-project-with-external-idm-dns.adoc
guides/common/modules/con_configuring-project-with-external-services.adoc
guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
guides/common/modules/proc_configuring-external-dns.adoc
guides/common/modules/proc_configuring-external-tftp.adoc
guides/common/modules/proc_configuring-satellite-deployment-with-an-external-dhcp-server.adoc
guides/common/modules/proc_reverting-to-internal-dns-service.adoc

Please review commit by commit. I think we should squash this when merging.

Rework external services

---

guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc

Reword our to my

---

CONTRIBUTING.md

Refs 72e580b9732d8caa222dc02c4f55df2f81738c53

Do not capitalize content view

---

guides/doc-Administering_Project/docinfo.xml
guides/doc-Administering_with_Ansible/docinfo.xml
guides/doc-Configuring_Load_Balancer/docinfo.xml
guides/doc-Deploying_Project_on_AWS/docinfo.xml
guides/doc-Installing_Proxy/docinfo.xml
guides/doc-Installing_Server/docinfo.xml
guides/doc-Installing_Server_Disconnected/docinfo.xml
guides/doc-Managing_Configurations_Ansible/docinfo.xml
guides/doc-Managing_Configurations_Puppet/docinfo.xml
guides/doc-Managing_Content/docinfo.xml
guides/doc-Managing_Hosts/docinfo.xml
guides/doc-Managing_Security_Compliance/docinfo.xml
guides/doc-Monitoring_Project/docinfo.xml
guides/doc-Planning_for_Project/docinfo.xml
guides/doc-Provisioning_Hosts/docinfo.xml
guides/doc-Tuning_Performance/docinfo.xml
guides/doc-Updating_Project/docinfo.xml
guides/doc-Upgrading_Project/docinfo.xml
guides/doc-Upgrading_Project_Disconnected/docinfo.xml

This way, we only have to update the version in a single place - `attributes-satellite.adoc`
Yes, they work in downstream build. I can provide PoC upon request.

Use attributes in docinfo.xml (Sat)

---

guides/common/assembly_installing-satellite-server-disconnected.adoc
guides/common/modules/con_configuring-server.adoc
guides/common/modules/con_content-delivery-network-structure.adoc
guides/common/modules/con_content-filter-examples.adoc
guides/common/modules/con_hammer-cli-overview.adoc
guides/common/modules/con_installing-server.adoc
guides/common/modules/con_load-balancing-solution-architecture.adoc
guides/common/modules/con_simple-content-access-sca-in-project.adoc
guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
guides/common/modules/proc_configuring-remote-execution-for-pull-client-smart-proxy.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-satellite-for-outgoing-emails.adoc
guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
guides/common/modules/proc_monitoring-puppet.adoc
guides/common/modules/proc_using-an-imagebuilder-image-for-provisioning.adoc
guides/common/modules/ref_capsule-server-scalability-considerations.adoc
guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc
guides/common/modules/ref_port-and-firewall-requirements.adoc
guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc

* Change "Note: text" to "[NOTE]" + block to comply with Asciidoc best practices for admonitions.

Change note format

---

CONTRIBUTING.md

- Add RH Subscription Manager to capitalization list
- Fix alphabetical order of non-capitalization list

Update "Capitalization" section, CONTRIBUTING.md

---

guides/common/assembly_configuring-provisioning-resources.adoc
guides/common/modules/con_network-boot-provisioning-workflow.adoc
guides/common/modules/con_provisioning-cloud-instances-on-openstack.adoc
guides/common/modules/con_provisioning-virtual-machines-in-proxmox.adoc
guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc
guides/common/modules/con_provisioning-virtual-machines-on-kvm.adoc
guides/common/modules/con_provisioning-virtual-machines-on-ovirt.adoc
guides/common/modules/proc_deleting-a-virtual-machine-on-amazon-ec2.adoc
guides/common/modules/proc_deleting-a-virtual-machine-on-proxmox.adoc
guides/common/modules/proc_deleting-a-vm-on-google-gce.adoc
guides/common/modules/proc_deleting-a-vm-on-microsoft-azure.adoc
guides/common/modules/proc_deleting-a-vm-on-vmware.adoc
guides/common/modules/proc_removing-a-virtual-machine-upon-host-deletion.adoc
guides/common/modules/snip_resource-remove-vm.adoc

I remade an ugly note into a proper procedure module. My own initiative.

Modularize note to destroy VMs on delete

---

guides/common/modules/proc_upgrading-hosts-to-next-major-release.adoc
guides/doc-Managing_Hosts/master.adoc

Verified the steps in the Web UI on Foreman 3.9.

Reword RHEL to EL for Leapp upgrades

---

CONTRIBUTING.md
guides/common/assembly_importing-content.adoc
guides/common/assembly_managing-content-views.adoc
guides/common/attributes-base.adoc
guides/common/modules/con_content-filter-overview.adoc
guides/common/modules/con_content-types-in-project.adoc
guides/common/modules/con_download-policies-overview.adoc
guides/common/modules/con_importing-content.adoc
guides/common/modules/con_introduction-to-content-management.adoc
guides/common/modules/con_load-balancing-solution-architecture.adoc
guides/common/modules/proc_adding-custom-deb-repositories.adoc
guides/common/modules/proc_adding-upstream-repositories-for-debian-11.adoc
guides/common/modules/proc_adding-upstream-repositories-for-ubuntu-22-04.adoc
guides/common/modules/proc_creating-a-content-filter-for-deb-content.adoc
guides/common/modules/proc_exporting-a-content-view-version.adoc
guides/common/modules/proc_exporting-a-repository.adoc
guides/common/modules/proc_extracting-gpg-public-key-fingerprints-from-release-files.adoc
guides/common/modules/proc_managing-packages-on-the-base-operating-system.adoc
guides/common/modules/proc_providing-the-salt-client-to-salt-minions.adoc
guides/common/modules/snip_generating-content.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
guides/doc-Planning_for_Project/topics/Glossary.adoc

initial discussion: https://github.com/theforeman/foreman-documentation/pull/2802#discussion_r1495927975
I now went with "Deb" to align with "Yum" and to have better consistency throughout the docs. cc @apinnick 

Reword Deb content

---

guides/common/modules/proc_applying-errata-to-multiple-hosts.adoc
guides/common/modules/proc_assigning-a-sync-plan-to-multiple-products.adoc
guides/common/modules/proc_creating-a-host-group-for-each-lifecycle-environment.adoc
guides/common/modules/proc_creating-multiple-locations.adoc
guides/common/modules/proc_promoting-a-content-view.adoc
guides/common/modules/proc_synchronizing-all-repositories-in-an-organization.adoc
guides/common/modules/proc_updating-the-details-of-multiple-operating-systems.adoc

RHSSG guidelines: https://redhat-documentation.github.io/supplementary-style-guide/#code-example-syntax-highlighting

Change [source,bash] to [source,terminal]

---

guides/common/modules/proc_downloading-python-packages-to-a-host-from-a-python-repository.adoc

see https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md?plain=1#L77

Capitalize Python

---

guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_managing-ostree-content-with-content-views.adoc

Relates to Foreman issue #36459

Remove import only for CV

---

guides/common/modules/con_host-substatus-overview.adoc

List all sub-statuses

---

guides/common/attributes-base.adoc
guides/common/attributes-orcharhino.adoc
guides/common/modules/proc_adding-installation-media.adoc
guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
guides/common/modules/proc_creating-a-suse-operating-system.adoc
guides/common/modules/proc_creating-an-installation-medium-for-debian.adoc
guides/common/modules/proc_creating-an-operating-system-for-debian.adoc
guides/common/modules/proc_creating-operating-systems.adoc
guides/common/modules/proc_creating-partition-tables.adoc
guides/common/modules/proc_executing-a-remote-job.adoc
guides/common/modules/proc_executing-a-restorecon-template-on-multiple-hosts.adoc
guides/common/modules/snip_host-parameters-for-orcharhino-clients.adoc

Set of commits to use "client-*" attributes

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
guides/common/attributes.adoc
web/content/index.adoc
web/content/js/versions.js
web/content/release-3.10.adoc

Update master to include Foreman 3.10

---

guides/doc-Release_Notes/topics/foreman-3.10.0.adoc
guides/doc-Release_Notes/topics/foreman.adoc

Fix Release Notes for 3.10

---

guides/common/modules/con_using-ipxe-to-reduce-provisioning-times.adoc

Remove 'you'

---

guides/common/modules/proc_renaming-server.adoc
guides/common/modules/proc_renaming-smart-proxy.adoc

Fix emphasis and Hammer example values

---

guides/common/modules/proc_setting-the-service-level.adoc
guides/common/modules/proc_using-activation-keys-for-host-registration.adoc

Sort Hammer args in alphabetical order

---

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc

I am aware `3.1` is EOL but there can be end-users planning to Upgrade.

Fix visible +

---

guides/common/assembly_registering-hosts.adoc
guides/common/modules/proc_customizing-host-registration-by-using-snippets.adoc
guides/common/modules/proc_customizing-registration-by-using-snippets.adoc

Documents https://github.com/theforeman/foreman/pull/10059
Please cherry-pick my commits into: N/A (expected in Foreman 3.11)

Refs #37189 - Registration before & after snippets

---

guides/common/assembly_managing-dns-on-smart-proxies.adoc
guides/common/modules/proc_configuring-dns-route53.adoc

Add Route53 DNS provider

---

guides/common/modules/proc_upgrading-a-connected-project-server.adoc
guides/common/modules/proc_upgrading-smartproxy-server.adoc
guides/doc-Release_Notes/topics/foreman.adoc

add PostgreSQL 13 release note

---

guides/common/modules/con_projectserver-operating-system.adoc
guides/doc-Planning_for_Project/topics/Introduction.adoc

add EL9 to OS list

---

guides/common/modules/proc_configuring-the-discovery-service.adoc
guides/common/modules/proc_installing-the-discovery-service.adoc

We have a request to add this info.

Add FDI base info

---

guides/common/modules/proc_configuring-the-discovery-service.adoc
guides/common/modules/proc_installing-the-discovery-service.adoc

Almost the same as #2899 , but for older versions.

Add FDI base info 3.4

---

guides/doc-Release_Notes/topics/foreman.adoc

https://community.theforeman.org/t/can-we-drop-the-append-domain-names-to-the-host-setting/29150/19

Add upgrade warning about shortnames 3.9

---

guides/common/modules/proc_disabling-puppet.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc

Hide link to BZ for orcharhino

---

guides/common/modules/con_importing-kickstart-repositories.adoc
guides/common/modules/con_managing-errata.adoc

source: https://almalinux.org/

Rename Alma Linux to AlmaLinux

---

guides/common/modules/ref_webhooks-available-events.adoc

Use attribute for Smart Proxies

---

guides/common/attributes-base.adoc
guides/common/attributes-katello.adoc
guides/common/attributes-orcharhino.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/ref_system-requirements.adoc
guides/doc-Quickstart/master.adoc

This is a cherry pick of https://github.com/theforeman/foreman-documentation/pull/2902 and I'd like to see a preview instead of blindly cherry picking.

Mark quickstart guide ready for 3.9

---

CONTRIBUTING.md
guides/common/modules/ref_cli-help.adoc
guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
guides/common/modules/ref_glossary-of-terms.adoc
guides/common/modules/ref_supported-operating-systems.adoc
guides/doc-Planning_for_Project/master.adoc

Please review commit by commit and focus on the diff. I know that there are more questionable entries. I will create a follow-up PR to fix some more.

Rework glossary

---

guides/common/modules/proc_registering-project-as-a-keycloak-client.adoc

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2271398

Install python3-lxml for keycloak-httpd-client-install

---

guides/doc-Upgrading_Project/docinfo.xml

Fix abstract in Upgrading Satellite

---

guides/common/modules/proc_updating-disconnected-server.adoc
guides/common/modules/proc_updating-server.adoc
guides/common/modules/proc_updating-smart-proxy.adoc

This change relies upon the availability of a new `update` command dedicated to minor updates from https://github.com/theforeman/foreman_maintain/pull/802

Use foreman-maintain update command for update guide

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman-3.9.3.adoc

Add release notes for 3.9.3

---

guides/common/assembly_configuring-provisioning-resources.adoc
guides/common/modules/proc_associating-partition-tables-with-disk-encryption.adoc

Depends on https://github.com/theforeman/foreman/pull/9887

Add procedure to use encrypted disks using PT

---

guides/common/modules/con_performing-additional-configuration-on-smart-proxy-server.adoc

Rephrase use this chapter

---

guides/common/modules/proc_upgrading-a-connected-project-server.adoc
guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
guides/common/modules/proc_upgrading-smartproxy-server.adoc

Rely on self-upgrade

---

guides/common/modules/proc_creating-a-host.adoc
guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
guides/common/modules/proc_upgrading-smartproxy-server.adoc
guides/common/modules/proc_uploading-content-to-custom-rpm-repositories.adoc

Use navigate to for WebUI paths

---

guides/common/modules/proc_adding-custom-rpm-repositories.adoc

Use "EL" attribute because the repos work for all Enterprise Linux OS.

Update example URL for Yum repo discovery

---

guides/common/modules/proc_registering-a-host.adoc

Reword rpms to packages

---

guides/common/modules/ref_glossary-of-terms-used-in-project.adoc

Please cherry-pick if necessary.
See https://github.com/theforeman/foreman-documentation/blob/master/guides/common/modules/con_content-types-in-project.adoc?plain=1

Use attribute in link

---

CONTRIBUTING.md
guides/common/assembly_performing-additional-configuration-on-smart-proxy-server.adoc
guides/common/modules/con_host-group-settings-and-nested-host-groups.adoc
guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
guides/common/modules/proc_creating-a-content-view-filter-for-errata.adoc
guides/common/modules/proc_installing-packages-on-a-host.adoc
guides/common/modules/proc_managing-the-lifecycle-of-the-content-view.adoc
guides/common/modules/proc_synchronizing-a-single-repository.adoc
guides/common/modules/proc_synchronizing-suse-content.adoc
guides/common/modules/proc_using-upstream-server-as-a-content-store.adoc
guides/common/modules/proc_using-upstream-server-to-sync-content-view-versions.adoc
guides/common/modules/ref_content-settings.adoc
guides/common/modules/ref_navigation-tabs-in-web-ui.adoc
guides/common/modules/ref_overview-of-the-host-columns.adoc
guides/common/modules/ref_permissions-required-to-provision-hosts.adoc

Fix le capitalization

---

guides/common/modules/proc_synchronizing-ansible-collections.adoc

Fix URL to Ansible Galaxy User guide

---

guides/common/modules/proc_reverting-to-internal-dns-service.adoc

Add missing whitespace

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
guides/common/attributes.adoc
web/content/index.adoc
web/content/js/versions.js
web/content/release-3.11.adoc

Update master for 3.11 branching

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.13.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc
guides/doc-Release_Notes/topics/katello.adoc

* [x ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Katello 4.13 release notes

---

guides/common/modules/ref_supported-clients-in-registration.adoc

Supported OS+arch for orcharhino

---

guides/common/assembly_importing-content.adoc
guides/common/assembly_managing-activation-keys.adoc
guides/common/assembly_managing-application-lifecycles.adoc
guides/common/assembly_managing-content-views.adoc
guides/common/assembly_managing-errata.adoc
guides/common/attributes-base.adoc
guides/common/attributes-satellite.adoc
guides/common/modules/ref_best-practices-for-activation-keys.adoc
guides/common/modules/ref_best-practices-for-content-views.adoc
guides/common/modules/ref_best-practices-for-errata.adoc
guides/common/modules/ref_best-practices-for-lifecycle-environments.adoc
guides/common/modules/ref_best-practices-for-patching-content-hosts.adoc
guides/common/modules/ref_best-practices-for-products-and-repositories.adoc
guides/common/modules/ref_best-practices-for-sync-plans.adoc
guides/common/modules/snip_tip-file-repositories-by-atix.adoc

* Add client-os-context attribute

Add best practices for managing content

---

guides/common/modules/con_performing-post-upgrade-tasks.adoc

Refs b7f8cef1f490c7d1ba10531fc8010d6e699fdbfa
Extends https://github.com/theforeman/foreman-documentation/pull/3052

Show pulp_container migration for orcharhino

---

guides/doc-Release_Notes/topics/foreman-3.11.0.adoc

I've categorized a lot of issues and that's why the diff is big. There were also various issues with both 3.10.0 and 3.11.0 for the fixed in release.

Update 3.11.0 release notes

---

web/releases/3.11.json
web/releases/3.9.json

To be merged together with https://github.com/theforeman/theforeman.org/pull/2155 and some other PRs that have yet to be opened.

Mark Foreman 3.11.0 as GA

---

guides/common/attributes.adoc

To be merged together with https://github.com/theforeman/theforeman.org/pull/2155 & friends

Mark Foreman 3.9 as unsupported

---

guides/common/attributes.adoc

To be merged together with https://github.com/theforeman/theforeman.org/pull/2155 & friends.

Mark Foreman 3.11 as stable

---

guides/doc-Release_Notes/topics/katello-4.13.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc

Updating release notes and contributors

---

guides/common/attributes-orcharhino.adoc
guides/common/modules/con_content-types-in-project.adoc
guides/common/modules/proc_importing-a-content-view-version-from-a-web-server.adoc
guides/common/modules/proc_importing-a-content-view-version.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-provisioning.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-manually.adoc
guides/common/modules/proc_registering-a-host.adoc
guides/common/modules/ref_advanced-settings-in-the-job-wizard.adoc
guides/common/modules/snip_generating-content.adoc
guides/common/modules/snip_host-registration-steps.adoc

Various small extensions for orcharhino

---

guides/common/modules/proc_creating-partition-tables.adoc
guides/common/modules/snip_ptable-format.adoc

When the user skips to the CLI procedure, they don't check the example in the WebUI procedure. :)

Specify ptable format in CLI procedure

---

guides/common/modules/ref_kinds-of-provisioning-templates.adoc

Add links to RHEL 8 and 9 Kickstart references

---

guides/common/modules/con_updating-project-to-next-minor-version.adoc
guides/common/modules/proc_updating-disconnected-server.adoc
guides/common/modules/proc_updating-server.adoc

Add section on updating operating system

---

guides/common/modules/ref_system-requirements.adoc

Fix RHEL 9 FIPS link

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman-3.11.1.adoc

Add 3.11.1 release notes

---

CONTRIBUTING.md

Closes https://github.com/theforeman/foreman-documentation/issues/3148

Remove "Product" from contributing.md

---

guides/common/modules/con_applying-custom-configuration.adoc
guides/common/modules/con_content-delivery-network-structure.adoc
guides/common/modules/con_iss-scenarios.adoc
guides/common/modules/con_products-and-repositories.adoc
guides/common/modules/proc_adding-an-http-proxy.adoc
guides/common/modules/proc_adding-custom-rpm-repositories.adoc
guides/common/modules/proc_changing-the-http-proxy-policy-for-a-product.adoc
guides/common/modules/proc_changing-the-http-proxy-policy-for-a-repository.adoc
guides/common/modules/proc_creating-kernelcare-repositories-el.adoc
guides/common/modules/proc_enabling-red-hat-repositories.adoc
guides/common/modules/proc_enabling-the-project-client-name-repository.adoc
guides/common/modules/proc_exporting-a-content-view-version.adoc
guides/common/modules/proc_exporting-the-library-environment.adoc
guides/common/modules/proc_importing-a-repository.adoc
guides/common/modules/proc_importing-individual-iso-images-and-files.adoc
guides/common/modules/proc_importing-into-the-library-environment.adoc
guides/common/modules/proc_managing-ostree-content-with-content-views.adoc
guides/common/modules/proc_resolving-package-dependency-errors.adoc
guides/common/modules/proc_synchronizing-a-single-repository.adoc
guides/common/modules/proc_synchronizing-repositories.adoc
guides/common/modules/proc_synchronizing-the-project-client-name-repository.adoc
guides/common/modules/proc_using-upstream-server-as-a-content-store.adoc
guides/common/modules/proc_using-upstream-server-to-sync-content-view-versions.adoc
guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc

Changed "Product" to "product", changed a couple occurrences of "Repository" to "repository".
Closes https://github.com/theforeman/foreman-documentation/issues/3148

Change "Product" to "product"

---

guides/common/modules/proc_upgrading-smartproxy-server.adoc

Add a missing colon

---

guides/common/modules/proc_deploying-a-policy-in-a-host-group-using-ansible.adoc
guides/common/modules/proc_deploying-a-policy-in-a-host-group-using-puppet.adoc
guides/common/modules/proc_deploying-a-policy-on-a-host-using-ansible.adoc
guides/common/modules/proc_deploying-a-policy-on-a-host-using-puppet.adoc
guides/common/modules/snip_prerequisite-repositories-with-oscap.adoc
guides/common/modules/snip_prerequisite-rhel-repositories.adoc

Expand oscap prerequisite for upstream

---

guides/common/modules/proc_migrating-to-external-databases.adoc

Remove a step where PostgreSQL is stopped and then started

---

.github/workflows/vale.yml
guides/common/modules/ref_system-requirements.adoc

Also updated Vale workflow because it was not running.

Fix broken link to RHEL 8 doc

---

guides/doc-Upgrading_Project/master.adoc

Refs https://community.theforeman.org/t/yet-another-foreman-upgrade-fail/38868/6?u=maximilian cc @jeremylenz 

Add hint about upgrading Katello

---

guides/common/modules/con_performing-post-upgrade-tasks.adoc
guides/common/modules/proc_performing-post-upgrade-tasks.adoc
guides/doc-Upgrading_Project/master.adoc
guides/doc-Upgrading_Project_Disconnected/master.adoc

Add command for new rake task

---

guides/common/modules/proc_configuring-installation.adoc

Mention --full-help in installation section

---

guides/common/attributes-titles.adoc
web/releases/3.10.adoc
web/releases/3.10.json
web/releases/3.11.adoc
web/releases/3.11.json
web/releases/nightly.adoc
web/releases/nightly.json

Applying sentence case to upstream titles, especially in navigation.
Supported releases and nightly only.

Fix titles in web navigation

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.13.1.adoc

Add Katello 4.13.1 release notes

---

guides/common/attributes-satellite.adoc

Fix Satellite URLs 'by using'

---

guides/common/assembly_configuring-external-services.adoc
guides/common/assembly_using-infoblox-as-dhcp-and-dns-providers.adoc
guides/common/modules/con_infoblox-limitations.adoc
guides/common/modules/con_using-infoblox-as-dhcp-and-dns-providers.adoc
guides/common/modules/proc_installing-the-dhcp-infoblox-module.adoc
guides/common/modules/proc_installing-the-dns-infoblox-module.adoc
guides/common/modules/proc_installing-the-infoblox-ca-certificate-on-smartproxy.adoc
guides/common/modules/proc_installing-the-infoblox-ca-certificate.adoc
guides/doc-Installing_Proxy/master.adoc
guides/doc-Provisioning_Hosts/master.adoc

Until we have a guide for networking, this will be a better place for Infoblox DHCP and DNS setup.

Move Infoblox from Provisioning to Installing

---

guides/common/modules/ref_system-requirements.adoc

They've changed them... again. [Failed linkchecker](https://github.com/theforeman/foreman-documentation/actions/runs/10355523298/job/28663359837?pr=3209)

Fix FIPS RHEL URLs

---

guides/common/modules/proc_installing-fapolicyd-on-server.adoc

Add instruction for installing fapolicyd on an existing install

---

guides/common/modules/proc_creating-a-host.adoc

Fixing a typo.
https://issues.redhat.com/browse/SAT-27144
No.

Fix a typo

---

guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc

this is needed becasue RHEL didn't ship the errata with the patches yet

use copr for leapp on RHEL too

---

guides/common/modules/ref_storage-guidelines.adoc

Feedback from https://issues.redhat.com/browse/SAT-24917

Add /var/lib/pgsql to list of high-bandwidth, low-latency directories

---

guides/common/modules/proc_configuring-pcp-data-collection.adoc

This is based on feedback from https://issues.redhat.com/browse/SAT-26588

Add pmproxy to list of monitoring services to restart

---

guides/common/assembly_configuring-external-authentication.adoc
guides/common/assembly_configuring-repositories.adoc
guides/common/assembly_installing-capsule-server.adoc
guides/common/assembly_installing-server-connected.adoc
guides/common/assembly_preparing-smartproxyservers-for-load-balancing.adoc
guides/common/assembly_upgrading-to-rhel9.adoc
guides/common/modules/con_configuring-external-authentication.adoc
guides/common/modules/con_configuring-repositories.adoc
guides/common/modules/con_important-user-and-group-account-information-for-active-directory-accounts.adoc
guides/common/modules/con_upgrading-el-on-project-or-proxy.adoc
guides/common/modules/proc_configuring-pcp-data-collection.adoc
guides/common/modules/proc_configuring-repositories-foreman-deb.adoc
guides/common/modules/proc_configuring-repositories-foreman-el.adoc
guides/common/modules/proc_configuring-repositories-katello.adoc
guides/common/modules/proc_configuring-repositories-orcharhino.adoc
guides/common/modules/proc_configuring-repositories-satellite.adoc
guides/common/modules/proc_migrating-project-or-smartproxy-using-backup.adoc
guides/common/modules/proc_registering-project-as-a-client-of-keycloak.adoc
guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
guides/common/modules/ref_storage-guidelines.adoc
guides/doc-Quickstart/master.adoc
guides/doc-Upgrading_Project/master.adoc
guides/doc-Upgrading_Project_Disconnected/master.adoc

A few commits were missed during 3.12 branching. This PR is a cherrypick of those commits into 3.12 master

Cherrypick missed commits into 3.12 master

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
guides/common/attributes.adoc
web/releases/3.12.adoc
web/releases/3.12.json

Update master for 3.12 branching

---

guides/common/modules/proc_performing-a-full-backup.adoc

Currently the documentation does not talk about the usecases for the different types of backups. Users are bound to get confused about which procedure to use when backing up. Adding information about usecases for online and offline backups.
JIRA links:
- Backup documentation improvement: https://issues.redhat.com/browse/SAT-23077
- Online backups are for production: https://issues.redhat.com/browse/SAT-26312

Add more information about online and offline backup

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.14.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc
guides/doc-Release_Notes/topics/katello.adoc

Katello 4.14 Release notes, contibutors, headline features and upgrade warnings
https://community.theforeman.org/t/katello-4-14-rc1-release-procedure/39182

Katello 4.14 release notes

---

guides/doc-Release_Notes/topics/foreman.adoc

This largely copies the deprecation from Foreman 3.11's release notes.
Heads up for users that the next version will remove the support.

Add deprecation for running on EL 8 with Foreman 3.12

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman-3.10.1.adoc

Add Foreman 3.10.1 release notes

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman-3.11.2.adoc

Add Foreman 3.11.2 release notes

---

guides/common/modules/con_network-boot-provisioning-workflow.adoc
guides/common/modules/con_performance-tuning-quick-start.adoc
guides/common/modules/con_performance-tuning-quickstart.adoc
guides/common/modules/con_prerequisites-for-image-based-provisioning.adoc
guides/common/modules/con_provisioning-cloud-instances-on-microsoft-azure-resource-manager.adoc
guides/common/modules/con_provisioning-virtual-machines-in-proxmox.adoc
guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc
guides/common/modules/con_provisioning-virtual-machines-on-ovirt.adoc
guides/common/modules/con_puma-threads.adoc
guides/common/modules/con_remote-execution-in-project.adoc
guides/common/modules/con_remote-execution-workflow.adoc
guides/common/modules/con_renaming-server-or-smart-proxy.adoc
guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
guides/common/modules/con_resolving-package-dependencies.adoc
guides/common/modules/con_restricting-hosts-access-to-content.adoc
guides/common/modules/con_retrieving-metrics.adoc
guides/common/modules/con_scap-content-in-project.adoc
guides/common/modules/con_searching-and-bookmarking.adoc
guides/common/modules/con_security-content-automation-protocol.adoc
guides/common/modules/con_shellhooks-plugin.adoc
guides/common/modules/con_smartproxy_performance_tests.adoc
guides/common/modules/con_synchronizing-content-between-servers.adoc
guides/common/modules/con_tailoring-xccdf-profiles.adoc
guides/common/modules/con_transport-modes-for-remote-execution.adoc
guides/common/modules/con_troubleshooting-postgresql.adoc
guides/common/modules/con_updating-project-to-next-patch-version.adoc
guides/common/modules/con_user-groups.adoc
guides/common/modules/con_using-pxe-to-provision-hosts.adoc
guides/common/modules/con_using-webhooks.adoc
guides/doc-Tuning_Performance/master.adoc

Renaming of files is done in a separate PR.

Fix "by using" in concepts N--Z

---

guides/common/modules/proc_upgrading-a-connected-project-server.adoc
guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
guides/common/modules/proc_upgrading-smartproxy-server.adoc

Drop --target-version for upgrade

---

guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc

(cherry picked from commit 72b7266614b40da4ae795257d9ecbe73632057f1)

use literal .z, not italic (to replace) in target-version option

---

guides/common/modules/proc_exporting-a-repository.adoc

Removing a space that shouldn't be there.
I missed this when reviewing https://github.com/theforeman/foreman-documentation/pull/3239 and now it bothers me way more than it should.
I'm sorry..?

Remove extra space

---

web/releases/3.12.json
web/releases/nightly.json

Adding Hammer guide to Foreman web navigation menus.
We don't cherry-pick these, correct?

Add Hammer guide to navigation

---

web/releases/3.12.json
web/releases/nightly.json

Adding the API guide to Foreman web navigation menus.
We don't cherry-pick these, correct?

Add API guide to navigation

---

guides/doc-Release_Notes/topics/foreman.adoc

Deprecate Ubuntu 20.04 in 3.12

---

guides/common/modules/proc_resetting-custom-ssl-certificate-to-default-self-signed-certificate-on-project.adoc
guides/common/modules/proc_reverting-to-internal-dns-service.adoc

Fixing a couple of broken links.
They are broken. But also https://issues.redhat.com/browse/SAT-27790 
N/A

Fix broken links in Installing

---

guides/common/modules/con_postgresql-tuning.adoc
guides/common/modules/proc_synchronizing-ansible-collections.adoc

$ rg "source, YAML"
$ rg "source, Yaml"
$ rg "source,YAML"
$ rg "source,Yaml"
See #3337 

Unify macro for YAML code blocks

---

guides/common/modules/con_provisioning-methods-in-project.adoc

Small fixes to align with style guidelines.
No tech review required.

Small fixes for provisioning methods

---

.github/workflows/vale.yml

Adding token

---

.github/workflows/vale.yml

Reverts theforeman/foreman-documentation#3368

Revert "Adding token"

---

guides/common/modules/ref_supported-clients-in-registration.adoc

Fixing capitalization
Only needs style review. Does not need tech review.

Fix capitalization in module

---

guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc

Listing required repos for Capsule leapp upgrade
Because they were missing and users would be running into problems not knowing that they need them.
https://issues.redhat.com/browse/SAT-27981
Not sure about the formatting.

List required repos for Capsule leapp upgrade

---

guides/common/modules/proc_cloning_satellite_server.adoc

Extending the procedure to clone to the target server with a step for EL 9.
https://issues.redhat.com/browse/SAT-27940
N/A

Add cloning server steps for EL 9

---

guides/common/modules/con_projectserver-operating-system.adoc
guides/common/modules/proc_configuring-repositories-foreman-deb.adoc
guides/common/modules/proc_upgrading-a-connected-project-server.adoc
guides/common/modules/ref_supported-operating-systems.adoc
guides/doc-Release_Notes/topics/foreman.adoc

Adding Debian 12 to docs
We now support Debian 12

Add Debian 12 (Bookworm) 

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.14.1.adoc

Add Katello 4.14.1 changelog and doc entry

---

guides/common/assembly_administer-settings-information.adoc
guides/common/modules/ref_discovery-settings.adoc

Follow-up on #3399 for older branches

Fix heading of Discovery settings 3.8

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
guides/common/attributes.adoc
web/releases/3.13.adoc
web/releases/3.13.json

update master for 3.13 branching

---

guides/common/modules/proc_configuring-pcp-data-collection.adoc

Fixes #3187
@Imaanpreet Does that make sense to you? Do you want me to backport this?
Refs https://github.com/theforeman/foreman-documentation/pull/3187

Add hint about replacing example.com

---

guides/common/modules/con_kickstart-workflow.adoc
guides/common/modules/proc_creating-a-host.adoc
guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
guides/common/modules/proc_editing-the-system-purpose-of-multiple-hosts.adoc
guides/common/modules/ref_kinds-of-provisioning-templates.adoc
guides/common/modules/ref_storage-requirements.adoc

Cherrypicking https://github.com/theforeman/foreman-documentation/pull/3429 into 3.10.
If successful, please also cherrypick into versions down to 3.5, thanks.

Update links to RHEL docs (#3429)

---

guides/common/modules/ref_template-sync-settings.adoc

Add oxford comma

---

guides/common/linkchecker.ini
guides/common/modules/ref_configuring-logging-levels-with-hammer-cli.adoc

also, guessing, the next satellite version will probably be 6.17 :)

6.16 is GA, let's linkcheck it

---

guides/common/modules/proc_deploying-the-ca-certificate-on-a-host-by-using-ansible-rex.adoc
guides/common/modules/proc_deploying-the-ca-certificate-on-a-host-by-using-script-rex.adoc

Fixing markup of UI options to bold formatting
IBM SG
https://issues.redhat.com/browse/SAT-29163

Fix markup in deploying CA cert with REX

---

guides/common/modules/proc_associating-a-virtual-machine-from-a-hypervisor.adoc

A consistency fix for a step in a procedure.
https://issues.redhat.com/browse/SAT-28627

Small fix for a procedure step

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/katello-4.14.2.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc

Adding in Katello 4.14.2 release notes and updating the contributors
For the Katello 4.14.2 release.

Add Katello 4.14.2 contributors and release notes

---

guides/common/modules/ref_best-practices-for-content-views.adoc

Removing quotes at the end of a line.
Looks like a mistake.

Drop quotes (a typo fix)

---

guides/common/modules/con_shellhooks-plugin.adoc

$ rg -i "plug-in"
$ rg -i "plugin"
fix spelling.

Reword plug-in to plugin

---

guides/common/modules/proc_synchronizing-python-repositories.adoc

Refs PR 11202 for katello on GitHub
Refs Remine issue 37974
new option in katello nightly

Limit number of Python package versions

---

guides/common/modules/con_upgrade-paths.adoc

Upgrade considerations for Hammer and API.
To remind the user to upgrade their scripts and integrations if they have any.

Add upgrade considerations for Hammer and API

---

guides/common/linkchecker.ini
guides/common/modules/con_introduction-to-salt.adoc
guides/common/modules/con_salt-architecture.adoc
guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc

Fix broken links :crossed_fingers: 

---

guides/common/modules/proc_upgrading-a-connected-project-server.adoc

Add missing trailing colon

---

guides/common/modules/snip_managing-packages-api.adoc

follow up to https://github.com/theforeman/foreman-documentation/pull/3444/files#diff-8473cc38e67814ebd36b68d2f1f497f3b6813895b19c2270ef78787275685bc8R57
you can run Hammer CLI as normal user.

Prefix Hammer command with dollar sign

---

guides/common/attributes-satellite.adoc

Increasing Satellite version to 6.17
Satellite 6.17 will be based on Foreman 3.14

Bump Satellite version to 6.17

---

web/releases/3.13.json

Fixing navigation for 3.13 guides
Closes https://github.com/theforeman/foreman-documentation/issues/3496

Fix navigation for 3.13 guides

---

guides/doc-Release_Notes/topics/foreman.adoc

A release note that was missed
https://community.theforeman.org/t/release-team-meeting-2024-12-04/40442/2

Add a note that running on EL8 is no longer supported

---

guides/common/modules/proc_synchronizing-repositories.adoc

fix placeholder value for Hammer CLI
consistency

Fix example value for Hammer CLI

---

.github/PULL_REQUEST_TEMPLATE.md
guides/common/attributes-orcharhino.adoc

orcharhino 7.0 :partying_face:

Bump orcharhino to 7.0

---

guides/common/modules/con_defining-your-content-library.adoc

cherry-pick as necessary/applicable.

Fix spelling of defining

---

guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc

Fix spelling of configure

---

guides/common/modules/con_importing-the-project-client-name-repository.adoc

~same as ten minutes ago. Kindly asking for another review~ @asteflova 
While working on fixing a broken xref, Anet and I found out that the whole section is not in use -> let's drop it. You can see that the GHA bot edited the first comment but there's still no changed file.

Remove unused text

---

guides/common/modules/proc_troubleshooting-remote-jobs-timing-out-after-yggdrasil-update.adoc

and another one ... cherry-pick as necessary

Fix spelling of yggdrasil

---

guides/common/modules/con_using-ipxe-to-reduce-provisioning-times.adoc

Deprecating the iPXE feature in Satellite
[SAT-28823](https://issues.redhat.com/browse/SAT-28823) (public)
- For Satellite 6.17

Deprecate iPXE in Satellite

---

guides/common/modules/con_performing-post-upgrade-tasks.adoc

Fix spelling mistake

---

.github/workflows/labeler.yml

Specifying the event to trigger PR labeling
We don't want it to run on every PR edit
Please cherry-pick my commits into: N/a

Specify PR labeler event

---

guides/common/modules/proc_assigning-resource-quotas-to-a-user.adoc

Fix spelling of resource

---

.github/workflows/deploy.yml

follow-up PR for https://github.com/theforeman/foreman-documentation/pull/3648

Bump GHA download-artifact to v4

---

.github/workflows/vale.yml

Update vale action to v2 and use Ubuntu 24.04 to run it

---

guides/common/assembly_disaster-recovery-by-virtualizing-your-projectserver.adoc
guides/common/assembly_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
guides/common/modules/con_disaster-recovery-by-virtualizing-your-project-server.adoc
guides/common/modules/con_disaster-recovery-by-virtualizing-your-projectserver.adoc
guides/common/modules/proc_preparing-for-disaster-recovery-by-virtualizing-your-projectserver.adoc
guides/common/modules/proc_recovering-from-disaster-by-restoring-a-vm-snapshot-of-projectserver.adoc
guides/common/modules/ref_prerequisites-disaster-recovery-by-virtualizing-your-projectserver.adoc
guides/common/modules/snip_disaster-recovery-hostname-cannot-change.adoc
guides/doc-Administering_Project/master.adoc

Adding steps for disaster recovery by virtualizing Project Server.
A follow-up to https://github.com/theforeman/foreman-documentation/pull/3558
Somewhat depends on https://github.com/theforeman/foreman-documentation/pull/3614
~~A lot of blanks but I'm hoping that opening a PR and getting feedback will help fill them in.~~

Add DR virtualization scenario

---

guides/common/modules/con_overview-of-recommended-disaster-recovery-plans.adoc

Fix grammar in DR overview

---

guides/doc-Release_Notes/topics/foreman.adoc
guides/doc-Release_Notes/topics/katello.adoc

Because we always do that after branching and cf0c81548b54 should have done that.

Clean out nightly release notes after branching

---

guides/common/modules/con_updating-project-to-next-patch-version.adoc

We had previously provided clarification around how to think about operating system updates. This appears to still be causing confusion. This is another attempt to clarify the language.

Clarify language around operating system updates

---

.github/PULL_REQUEST_TEMPLATE.md
guides/common/attributes-orcharhino.adoc

source: https://orcharhino.com/ressourcen/release-notes/orcharhino-7-1/
:partying_face:

Bump orcharhino to 7.1

---

guides/common/modules/proc_preparing-for-disaster-recovery-with-active-and-passive-project-server-with-external-storage.adoc
guides/common/modules/proc_recovering-from-disaster-with-active-and-passive-project-server-with-external-storage.adoc
guides/common/modules/ref_prerequisites-disaster-recovery-with-active-and-passive-project-server-and-external-storage.adoc

Minor stylistic changes
To align with current conventions and used styles

Super late review of PR 3679 (disaster recovery)

---

guides/common/assembly_importing-kickstart-repositories.adoc
guides/common/modules/con_importing-kickstart-repositories.adoc
guides/common/modules/con_provisioning-templates.adoc
guides/common/modules/con_synchronizing-template-repositories.adoc
guides/common/modules/proc_creating-an-installation-medium-for-ubuntu-22-04.adoc
guides/common/modules/proc_preparing-a-synchronized-kickstart-repository.adoc
guides/common/modules/proc_provisioning-ubuntu-autoinstall-through-smart-proxies.adoc
guides/common/modules/proc_setting-up-job-templates.adoc

* Simplify links by removing "{context}"
* Fix broken links by fixing them :upside_down_face: 
mostly to fix broken links
I am currently working on fixing broken links in downstream for 3.12. This is just a first PR to get started.

Fix and simplify links

---

guides/common/modules/ref_port-and-firewall-requirements.adoc

Adding closing double quotes.
Without the quotes, the first line in the table doesn't get interpreted as a header.
N/A

Add missing closing quotes

---

guides/common/modules/con_overview-of-recommended-disaster-recovery-plans.adoc
guides/common/modules/proc_preparing-for-disaster-recovery-with-active-and-passive-project-server-with-external-storage.adoc
guides/common/modules/ref_prerequisites-disaster-recovery-with-active-and-passive-project-server-and-external-storage.adoc

* Minor wording tweaks for improved clarity.
* Removing obsolete WIP comments.
https://github.com/theforeman/foreman-documentation/issues/3704
N/A

Tweak DR to improve wording and remove comments

---

guides/common/modules/con_applying-errata-to-hosts.adoc
guides/common/modules/con_converting-a-host-to-rhel.adoc
guides/common/modules/con_transport-modes-for-remote-execution.adoc
guides/common/modules/proc_applying-errata-to-multiple-hosts.adoc
guides/common/modules/proc_configuring-provisioning-callback-for-a-host.adoc
guides/common/modules/proc_creating-a-content-view.adoc
guides/common/modules/proc_creating-an-activation-key-to-consume-the-content-view.adoc
guides/common/modules/proc_deploying-a-virt-who-configuration-on-target-server.adoc
guides/common/modules/proc_distributing-ssh-keys-for-remote-execution.adoc
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
guides/common/modules/proc_installing-standalone-hammer.adoc
guides/common/modules/proc_promoting-a-content-view.adoc
guides/common/modules/proc_renaming-server.adoc
guides/common/modules/ref_best-practices-for-patching-content-hosts.adoc
guides/common/modules/ref_resetting-custom-ssl-certificate-to-default-self-signed-certificate-on-hosts.adoc

Fixing broken links
To improve UX
* follow-up to https://github.com/theforeman/foreman-documentation/pull/3764
* last PR to fix broken links (for now)

Fix broken links (part 6)

---

guides/common/attributes-orcharhino.adoc

Change URL for orcharhino Clients
new generation

Bump orcharhino Clients to gen3

---

guides/common/modules/ref_supported-browsers.adoc

Declare that Satellite is translated into Korean

---

guides/common/modules/proc_uploading-duplicate-content.adoc

Removing a plus sign that isn't supposed to be there.
Plus signs that aren't supposed to be there should be removed.
N/A
All applicable branches

Drop unnecessary plus sign

---

guides/common/modules/ref_template-macros.adoc

split line with multiple sentences
to adhere to our convention.

Use one sentence per line

---

guides/common/modules/proc_installing-the-infoblox-ca-certificate.adoc

use long option ...
... for readability

Use long options for curl

---

guides/common/modules/con_managing-content-view-environments.adoc

Adding Technology preview note to concept.
RN review found it was a Technology preview and not a new feature.
https://issues.redhat.com/browse/SAT-33410

Add tech preview note for multiple CV envs

---

guides/common/assembly_managing-red-hat-subscriptions.adoc
guides/common/modules/con_managing-red-hat-subscriptions.adoc
guides/common/modules/proc_configuring-subscriptions-service.adoc
guides/common/modules/proc_tracking-subscription-usage-by-using-the-subscriptions-service.adoc

This is a new PR because #3623 accidentally was closed.
In reference to https://issues.redhat.com/browse/SAT-31458

Add subscription central info to Managing RH subscriptions

---

guides/common/modules/proc_creating-a-playbook-with-modules-from-project-ansible-collection.adoc

clarify that it can be *any* system that can run the ansible modules

---

guides/doc-Release_Notes/topics/foreman-3.15.0.adoc
guides/doc-Release_Notes/topics/foreman-contributors.adoc

I somehow managed to push 3.15 RNs without proper review; sorry about that! Please review the commit https://github.com/theforeman/foreman-documentation/commit/5df11e08a1fb5812528b294f9954ef798d576790 and let me know if something needs fixing.
Also, I used an incomplete list of contributors so here is a hopefully complete one.

3.15 RN + Add correct contributors

---

Makefile
guides/common/attributes.adoc
web/releases/3.15.adoc
web/releases/3.15.json

3.15 branching changes
3.15 branching, according to https://github.com/theforeman/foreman-documentation#branching-new-release

3.15 update

---

guides/doc-Release_Notes/topics/katello-contributors.adoc

Foreman 3.15 + Katello 4.17
Refs 1fef0202238d7b864aa14a02bf24dc78e8ddeaaa

Fix Katello version

---

guides/common/attributes-satellite.adoc
guides/common/linkchecker.ini

Increasing version numbers for Satellite docs and updating the ignored docs version in linkchecker configuration
Planning docs for a new release

Bump Satellite version

---

guides/common/modules/proc_integrating-route-53-dns.adoc

fix a typo.
Refs 41a73f080ef43f9cbd3ab044782b4688112c73fa
Please cherry-pick as necessary.

Fix spelling of life cycle

---

guides/common/modules/proc_integrating-route-53-dns.adoc

fix another typo
Refs 723dccdb007b85ba12e3259c689c1c45ac5e22a1
Please cherry-pick as necessary.

Fix spelling of hosts

---

guides/common/modules/proc_creating-a-playbook-with-modules-from-project-ansible-collection.adoc

document how to use an http proxy with the ansible collection

---

guides/common/attributes.adoc

Updating 3.15 support status
3.15 going GA

3.15 going GA, updating support status

---

guides/common/assembly_managing-content-view-environments.adoc
guides/common/modules/con_comparison-of-content-view-environments-and-composite-content-views.adoc
guides/common/modules/con_content-view-environment-ordering-and-priority.adoc
guides/common/modules/con_content-view-environments-overview.adoc
guides/common/modules/proc_assigning-content-view-environments-to-activation-keys.adoc
guides/common/modules/proc_removing-all-content-view-environments-from-an-activation-key.adoc

* Fix two broken links
* Make example activation key italic
* Use ProjectWebUI attribute
* Use attributes for example content
* Use foreman-example-com macro in favor of hardcoded FQDN
* Use sentence-case capitalization
* Write Hammer CLI in favor of Hammer
Refs PR 3609 on GitHub
Because I was too late to review https://github.com/theforeman/foreman-documentation/pull/3609 in a reasonable time.

Make multiple CV environments fit for all builds

---

guides/common/attributes-orcharhino.adoc

overwrite attribute for orcharhino builds.
The command differs between upstream and downstream.
Example source in live downstream docs: https://docs.orcharhino.com/or/docs/sources/installation_and_maintenance/installing_orcharhino_server.html#Setting_a_Tuning_Profile

Set attribute foreman-installer for orcharhino

---

guides/common/modules/con_hammer-cheat-sheet.adoc
guides/common/modules/con_metrics-data-retention.adoc
guides/common/modules/con_metrics-overview.adoc
guides/common/modules/con_pcp-metrics.adoc
guides/common/modules/proc_changing-data-retention-policy.adoc
guides/common/modules/proc_changing-default-logging-interval.adoc
guides/common/modules/proc_configuring-hosts-to-use-an-alternate-cname-for-content-management.adoc
guides/common/modules/proc_configuring-pcp-data-collection.adoc
guides/common/modules/proc_configuring-project-with-an-alternate-cname.adoc
guides/common/modules/proc_disabling-registration-to-insights.adoc
guides/common/modules/proc_enabling-web-ui-access-to-metrics.adoc
guides/common/modules/proc_installing-pcp.adoc
guides/common/modules/proc_installing-the-load-balancer.adoc
guides/common/modules/proc_registering-satellite-server-with-insights.adoc
guides/common/modules/proc_retrieving-archived-metrics.adoc
guides/common/modules/proc_retrieving-live-metrics.adoc
guides/common/modules/proc_retrieving-metrics-in-the-web-ui.adoc
guides/common/modules/proc_tuning-with-predefined-profiles.adoc
guides/common/modules/proc_verifying-pcp-configuration.adoc
guides/common/modules/proc_viewing-data-storage-statistics.adoc

Use double quotes in favor of single quotes for anchors.
for consistency.
There are some reference files that are created automatically from output of Hammer CLI.
$ rg "^\[id='"

Use double quotes in anchors

---

guides/common/modules/con_smartproxy-features.adoc
guides/common/modules/con_template-writing-reference.adoc
guides/common/modules/con_web-ui-overview.adoc
guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
guides/common/modules/proc_enabling-power-management-on-hosts.adoc
guides/common/modules/proc_enrolling-projectserver-in-freeipa-domain.adoc
guides/common/modules/proc_exporting-a-repository-incrementally.adoc
guides/common/modules/proc_registering-a-host.adoc
guides/common/modules/proc_synchronizing-a-single-repository.adoc
guides/common/modules/proc_updating-a-puppet-module.adoc

fix broken links and adjust titles
to improve UX
* Affects nightly to at least Foreman 3.14.

Fix broken links and titles

---

guides/common/modules/proc_enabling-the-flatpak-remote.adoc
guides/common/modules/proc_importing-and-exporting-content-to-project-server-for-flatpak.adoc
guides/common/modules/proc_installing-flatpak-applications-on-project-hosts.adoc
guides/common/modules/proc_setting-up-flatpak-remote-for-smartproxy.adoc
guides/common/modules/proc_using-container-registries.adoc

Small doc bug fixes.
Brought up in a Slack conversation and I created a bug ticket:
https://issues.redhat.com/browse/SAT-34237

Add prerequisite and fix command line in Flatpak

---

guides/common/linkchecker.ini
guides/common/modules/con_using-the-kernelcare-plugin.adoc

Fix tuxcare.com URL

---

guides/common/modules/proc_benchmarking-raw-db-performance.adoc
guides/common/modules/proc_cloning-satellite-server.adoc
guides/common/modules/proc_configuring-repositories-el.adoc
guides/common/modules/proc_sharing-the-dhcp-configuration-files-and-lease-database-over-nfs.adoc

The package-install attribute should be used on infrastructure servers, so those used to run Foreman itself. That includes Foreman, Foreman Proxies but also external database servers.
This is effectively a noop in the produced documentation, but it's the correct attribute.
I had this in https://github.com/theforeman/foreman-documentation/pull/2936 and I'm trying to wrap things up. Having a small and dedicated PR makes it easier to review.
I didn't check any cherry picks because I didn't investigate.

Use package-install attribute on infrastructure servers

---

guides/common/assembly_monitoring-hosts-by-using-insights.adoc
guides/common/assembly_monitoring-hosts-by-using-red-hat-insights.adoc
guides/common/modules/proc_obfuscating-hostnames-and-ip-addresses.adoc
guides/doc-Managing_Hosts/master.adoc

Adding procedure for obfuscating host information.
https://issues.redhat.com/browse/SAT-34092

Add obfuscation procedure

---

guides/common/assembly_managing-flatpak-repositories-in-project.adoc
guides/common/modules/proc_creating-a-flatpak-remote.adoc
guides/common/modules/proc_enabling-the-flatpak-remote-by-using-hammer-cli.adoc
guides/common/modules/proc_enabling-the-flatpak-remote-using-hammer-cli.adoc
guides/common/modules/proc_importing-and-exporting-content-to-project-server-for-flatpak.adoc
guides/common/modules/proc_installing-flatpak-applications-on-project-hosts.adoc
guides/common/modules/proc_mirroring-remote-flatpak-repositories-to-project-products.adoc
guides/common/modules/proc_scanning-a-flatpak-remote.adoc
guides/common/modules/proc_setting-up-flatpak-remote-for-smartproxy.adoc
guides/common/modules/proc_viewing-flatpak-remote-details.adoc

Adding UI procedures for Flatpak and removing an
endpoint in a command line.
For UI procedures: https://issues.redhat.com/browse/SAT-31578 
For removing endpoint: https://issues.redhat.com/browse/SAT-31507

Add UI procedure for Flatpak and remove endpoint in command line

---

guides/common/modules/ref_supported-cloud-providers.adoc

Add links to provisioning cloud instances

---

guides/common/modules/proc_adding-an-scc-account.adoc

Reflect update to WebUI of foreman_scc_manager.
Two buttons in the Foreman SCC Manager plugin have been renamed. One has not been documented so far.
See https://github.com/ATIX-AG/foreman_scc_manager/pull/151
draft PR until I can provide a screenshot.

Rename buttons in Web UI of foreman_scc_manager

---

guides/common/assembly_using-boot-disks-to-provision-hosts.adoc
guides/common/modules/proc_enabling-bootdisk-plugin.adoc

Add docs on how to install foreman_bootdisk.
There were no docs on how to install this plugin.

Add docs to install foreman_bootdisk plugin

---

guides/common/modules/con_content-synchronization-by-using-export-and-import.adoc

Incorrect statement in note for export and import version match.
https://issues.redhat.com/browse/SAT-35913

Change statement in note

---

guides/common/modules/con_pulp-data-considerations.adoc

Use ProjectServer in favor of Project server

---

guides/common/modules/con_registering-clients-to-the-load-balancer.adoc
guides/doc-Configuring_Load_Balancer/master.adoc

Render https://docs.theforeman.org/nightly/Configuring_Load_Balancer/index-katello.html for all builds
part of #396 
* Hide host registration using "bootstrap.py" for orcharhino builds.

Make Configuring Load Balancers fit for all builds

---

guides/common/modules/con_managing-organizations.adoc
guides/common/modules/con_planning-organization-and-location-context.adoc
guides/common/modules/proc_creating-a-location.adoc
guides/common/modules/proc_deleting-a-location.adoc
guides/common/modules/proc_deleting-an-organization.adoc
guides/doc-Managing_Organizations_and_Locations/master.adoc

Make the guide ready for users for all builds.
Part of #396.

Show "Managing organizations and locations" guide for all builds

---

guides/common/header.adoc
guides/doc-Configuring_virt_who_VM_Subscriptions/master.adoc
guides/doc-Managing_Content/master.adoc
guides/doc-Managing_Security_Compliance/master.adoc
web/content/css/_ribbon.scss
web/content/css/default.scss

Adding the banner for unsupported and pre-release versions to 3.15.
https://github.com/theforeman/foreman-documentation/pull/3653
https://github.com/theforeman/foreman-documentation/pull/4084

Add banner for unsupported and pre-release to 3.15

---

guides/common/header.adoc
guides/doc-Configuring_virt_who_VM_Subscriptions/master.adoc
guides/doc-Managing_Content/master.adoc
guides/doc-Managing_Security_Compliance/master.adoc
web/content/css/_ribbon.scss
web/content/css/default.scss

Adding the banner for unsupported and pre-release versions to 3.14.
https://github.com/theforeman/foreman-documentation/pull/3653
https://github.com/theforeman/foreman-documentation/pull/4084

Add banner for unsupported and pre-release to 3.14

---

guides/common/header.adoc
guides/doc-Managing_Content/master.adoc
guides/doc-Managing_Security_Compliance/master.adoc
guides/doc-Planning_for_Project/master.adoc
guides/doc-Quickstart/master.adoc
web/content/css/_ribbon.scss
web/content/css/default.scss

Adding the banner for unsupported and pre-release versions to 3.10.
https://github.com/theforeman/foreman-documentation/pull/3653
https://github.com/theforeman/foreman-documentation/pull/4084

Add banner for unsupported and pre-release to 3.10

---

guides/common/attributes-satellite.adoc

Since 51f5a9093490acf78c6daf4940ace504b8491c8f and 9169132a3ec8938066cef709eb135302cd91590c these have been unused.
Originally part of https://github.com/theforeman/foreman-documentation/pull/3596, but split off for clarity.
These attributes are unused.
I wouldn't expect any diff since they are supposed to be unused.

Remove unused RHEL 7 attributes

---

guides/common/header.adoc
web/content/css/_ribbon.scss

Adding a banner/ribbon that opens the form to create a new issue.
https://github.com/theforeman/foreman-documentation/issues/3640
To be added only to pre-release + supported versions.

Add 'Report issue' banner

---

guides/common/header.adoc
guides/common/ribbons.adoc
guides/doc-Administering_Project/master.adoc
guides/doc-Administering_with_Ansible/master.adoc
guides/doc-Configuring_Load_Balancer/master.adoc
guides/doc-Configuring_User_Authentication/master.adoc
guides/doc-Deploying_Hosts_AppCentric/master.adoc
guides/doc-Deploying_Project_on_AWS/master.adoc
guides/doc-Hammer_CLI/master.adoc
guides/doc-Installing_Proxy/master.adoc
guides/doc-Installing_Server/master.adoc
guides/doc-Installing_Server_Disconnected/master.adoc
guides/doc-Managing_Configurations_Ansible/master.adoc
guides/doc-Managing_Configurations_Puppet/master.adoc
guides/doc-Managing_Configurations_Salt/master.adoc
guides/doc-Managing_Content/master.adoc
guides/doc-Managing_Hosts/master.adoc
guides/doc-Managing_Organizations_and_Locations/master.adoc
guides/doc-Managing_Security_Compliance/master.adoc
guides/doc-Monitoring_Project/master.adoc
guides/doc-Planning_for_Project/master.adoc
guides/doc-Project_API/master.adoc
guides/doc-Provisioning_Hosts/master.adoc
guides/doc-Quickstart/master.adoc
guides/doc-Release_Notes/master.adoc
guides/doc-Tuning_Performance/master.adoc
guides/doc-Updating_Project/master.adoc
guides/doc-Upgrading_Project/master.adoc
guides/doc-Upgrading_Project_Disconnected/master.adoc

The same change as https://github.com/theforeman/foreman-documentation/pull/4135, except the list of guides is slightly different so there is a different set of master.adoc files being updated.
https://github.com/theforeman/foreman-documentation/pull/4135
A separate PR rather than cherry-pick to make sure I update all the master.adoc files on this branch.

Move ribbons out of common/header.adoc (3.12)

---

guides/common/modules/proc_installing-the-salt-plugin.adoc
guides/common/modules/proc_installing-the-scc-manager.adoc

Add installation instructions for two Hammer CLI plugins
* https://github.com/theforeman/foreman-installer/pull/1013
* https://github.com/theforeman/foreman-installer/pull/1010

Add Hammer CLI plugins for foreman_salt and foreman_scc_manager plugins

---

guides/image-sources/prov-call-home.iuml
guides/image-sources/provisioning-image-finish.plantuml
guides/image-sources/provisioning-image-userdata.plantuml
guides/image-sources/provisioning-installer-bootdisk-fullhost.plantuml
guides/image-sources/provisioning-installer-bootdisk-subnet.plantuml
guides/image-sources/provisioning-installer-httpboot.plantuml
guides/image-sources/provisioning-installer-pxeboot.plantuml

Improving the "call home" step in provisioning diagrams
To make the step more descriptive and clear

Improve call home in provisioning diagrams

---

guides/common/attributes-base.adoc
guides/common/modules/con_aws-requirements.adoc
guides/common/modules/con_composite-content-views-overview.adoc
guides/common/modules/con_content-filter-examples.adoc
guides/common/modules/con_managing-errata.adoc
guides/common/modules/con_provisioning-cloud-instances-on-microsoft-azure-resource-manager.adoc
guides/common/modules/con_resolving-package-dependencies.adoc
guides/common/modules/proc_applying-errata-to-multiple-hosts.adoc
guides/common/modules/proc_configuring-a-finish-template-for-amazon-ec2.adoc
guides/common/modules/proc_configuring-the-freeipa-authentication-source-on-projectserver.adoc
guides/common/modules/proc_creating-custom-rhel-images.adoc
guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
guides/common/modules/proc_exporting-a-content-view-version-incrementally.adoc
guides/common/modules/proc_exporting-a-repository-incrementally-in-a-syncable-format.adoc
guides/common/modules/proc_exporting-a-repository-incrementally.adoc
guides/common/modules/proc_exporting-the-library-environment-incrementally.adoc
guides/common/modules/proc_preparing-a-synchronized-kickstart-repository.adoc
guides/common/modules/proc_registering-to-red-hat-subscription-management.adoc
guides/common/modules/proc_restricting-customrepoid-to-a-specific-operating-system-version-or-architecture-in-project.adoc
guides/common/modules/proc_updating-disconnected-server-on-EL9.adoc
guides/common/modules/proc_using-activation-keys-for-host-registration.adoc
guides/common/modules/ref_capsule-storage-requirements.adoc
guides/common/modules/ref_playbook-example-enable-repositories-and-create-a-content-view.adoc
guides/common/modules/ref_playbook-example-synchronize-repositories-and-publish-a-content-view.adoc
guides/common/modules/ref_storage-guidelines.adoc
guides/common/modules/ref_storage-requirements.adoc
guides/common/modules/snip_prerequisites-common-compute-resource.adoc
guides/doc-Updating_Project/master.adoc

Use proper attributes to better differentiate between Foreman platform, RHEL Clients, EL Clients, and Clients.
I will move technical issues, if any, to separate issues. This PR is merely about the correct attribute.

Fix attribute usage for Client OS

---

guides/common/modules/proc_installing-the-discovery-service.adoc

Extend procedure to install foreman_discovery: also install the relevant Hammer CLI plugin
Affects nightly to at least Foreman 3.14.
$ foreman-installer --full-help | grep cli-discovery

Install Hammer CLI plugin for foreman_discovery

---

guides/common/assembly_configuring-repositories.adoc
guides/common/assembly_installing-capsule-server.adoc
guides/common/assembly_installing-satellite-server-disconnected.adoc
guides/common/assembly_installing-server-connected.adoc
guides/common/assembly_managing-red-hat-subscriptions.adoc
guides/common/assembly_preparing-environment-for-project-server-installation.adoc
guides/common/assembly_preparing-smartproxyservers-for-load-balancing.adoc
guides/common/modules/con_aws-requirements.adoc
guides/common/modules/con_configuring-project-server.adoc
guides/common/modules/con_preparing-your-environment-for-project-installation-in-an-ipv6-network.adoc
guides/common/modules/proc_configuring-project-installation.adoc
guides/common/modules/proc_enabling-client-connections-to-project-server.adoc
guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
guides/common/modules/proc_installing-project-server-packages.adoc
guides/common/modules/proc_preparing-for-using-external-databases.adoc
guides/common/modules/proc_registering-to-red-hat-subscription-management.adoc
guides/common/modules/proc_verifying-dns-resolution.adoc
guides/common/modules/ref_port-and-firewall-requirements.adoc
guides/common/modules/ref_system-requirements.adoc
guides/doc-Quickstart/master.adoc

* Hide Katello-only feature for foreman-el and foreman-deb
* Rework various assemblies to simplify future maintenance
Part of #396 
* Please review commit by commit.
* Note that there are more changes necessary to make the guides work for foreman-el and foreman-deb.

Make "Installing Foreman Server" suitable for all builds - part I

---

guides/common/modules/proc_installing-the-discovery-service.adoc

Add Foreman Discovery Image 5.1 to list of FDIs
New FDI release [5.1](https://downloads.theforeman.org/discovery/releases/5.1/)

Add FDI 5.1

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman.adoc
guides/doc-Release_Notes/topics/katello.adoc

Transforming capitalization of headings in upstream Release notes to sentence case
For consistency with other guides

Use sentence case for RN headings

---

guides/common/assembly_installing-the-load-balancer.adoc
guides/common/assembly_registering-clients-to-the-load-balancer.adoc
guides/common/modules/con_configuring-smartproxyservers-with-custom-ssl-certificates-for-load-balancing-without-puppet.adoc
guides/common/modules/con_configuring-smartproxyservers-with-default-ssl-certificates-for-load-balancing-without-puppet.adoc
guides/common/modules/con_installing-and-configuring-the-load-balancer.adoc
guides/common/modules/con_registering-clients-to-the-load-balancer.adoc
guides/common/modules/proc_configuring-repositories-foreman-el.adoc
guides/common/modules/proc_configuring-repositories-proxy.adoc
guides/common/modules/proc_configuring-repositories-satellite.adoc
guides/common/modules/proc_installing-the-load-balancer.adoc
guides/common/modules/proc_registering-a-host-to-the-load-balancer-using-api.adoc
guides/common/modules/proc_registering-a-host-to-the-load-balancer-using-cli.adoc
guides/common/modules/proc_registering-a-host-to-the-load-balancer-using-web-ui.adoc
guides/common/modules/proc_registering-capsule-to-satellite-server.adoc
guides/common/modules/proc_registering-clients-using-host-registration.adoc
guides/common/modules/proc_registering-clients-using-the-bootstrap-script.adoc
guides/common/modules/proc_setting-the-load-balancer-for-host-registration.adoc
guides/common/modules/ref_ports-configuration-for-the-load-balancer.adoc
guides/common/modules/ref_prerequisites-configuring-smartproxyservers-for-load-balancing.adoc
guides/common/modules/snip_host-registration-steps.adoc
guides/common/modules/snip_verification-enabled-repolist.adoc
guides/doc-Configuring_Load_Balancer/master.adoc

Addresses issues reported by https://github.com/jhradilek/asciidoctor-dita-vale
Bigger changes worth highlighting:
* The procedure for installing the load balancer included two discrete headings so I broke them up into two modules and created a new assembly for them.
* The snippet for host registration is far too convoluted for me to deal with as a whole so I broke out the parts relevant for load balancing and added them as new, separate, DITA-compliant modules. This included a few more updates to the respective assembly.
* EDIT: I'm moving the `.Verification` heading out of a separate snippet file. The heading must be part of the procedure module itself to avoid a warning from Vale.
https://issues.redhat.com/browse/SAT-36254
* We do not accept PRs for …

Fix issues reported by asciidoctor-dita-vale (Configuring Load Balancer)

---

guides/common/modules/proc_creating-uln-repositories.adoc

Updating a link that's no longer working.
Linkchecker reported the broken link.

Fix link to ULN oracle docs

---

guides/doc-Release_Notes/master.adoc
guides/doc-Release_Notes/topics/foreman-3.16.0.adoc
guides/doc-Release_Notes/topics/foreman-contributors.adoc
guides/doc-Release_Notes/topics/foreman.adoc

Foreman 3.16 Release Notes

---

guides/doc-Release_Notes/topics/katello-4.18.0.adoc
guides/doc-Release_Notes/topics/katello-contributors.adoc
guides/doc-Release_Notes/topics/katello.adoc

Update documentation for Katello 4.18.0.rc2

Update documentation for Katello 4.18.0.rc2

---

guides/common/modules/proc_installing-a-puppet-module.adoc

Spelling out an alternative way to install a Puppet module into actual steps.
https://github.com/theforeman/foreman-documentation/issues/4191
N/A

Split alternative puppet installation method to separate steps

---

guides/common/modules/proc_getting-scap-contents-from-upstream.adoc

Fix spelling of contents

---

guides/common/modules/proc_exporting-a-content-view-version-incrementally.adoc
guides/common/modules/proc_exporting-the-library-environment-incrementally.adoc
guides/common/modules/snip_syncable-exports.adoc

Removing syncable-exports snippet
Snippet is only 3 lines long and used in 2 modules. 
Unlikely to be reused.
No tech review or testing required.

Remove syncable-exports snippet

---

guides/common/modules/proc_configuring-pull-based-transport-for-remote-execution.adoc
guides/common/modules/proc_configuring-salt-on-project.adoc
guides/common/modules/proc_enabling-client-connections-to-project-server.adoc
guides/common/modules/proc_enabling-connections-to-capsule.adoc
guides/common/modules/proc_enabling-omapi-authentication-in-isc-dhcp.adoc
guides/common/modules/proc_installing-postgresql.adoc
guides/common/modules/snip_make-firewall-settings-persistent.adoc
guides/common/modules/snip_verify-firewall-settings.adoc

Reverts theforeman/foreman-documentation#4253

Revert "Removing firewall config snippets"

---

guides/common/modules/proc_registering-capsule-to-satellite-server.adoc

Adding a blank line that seems to be missing.
Without it, the beginning of the host registration snippet is part of the preceding bulleted list.
N/A

Add missing blank line

---

guides/doc-Release_Notes/topics/foreman.adoc

Adding a link to the Foreman Ovirt plugin as discussed in #4238

Add a link to the Foreman oVirt Plugin

---

guides/common/modules/con_provisioning-virtual-machines-in-proxmox.adoc

Name the supported Proxmox versions similarly to VMWare.
To help users verify if they can attach their Proxmox instance to Foreman.
Needs tech ACK.

Add list of supported Proxmox versions

---

guides/common/modules/proc_synchronizing-the-new-repositories.adoc
guides/common/modules/proc_upgrading-smartproxy-server.adoc
guides/common/modules/proc_upgrading-the-external-database-operating-system.adoc

Shorten/split long sentences in miscellaneous sections of the connected upgrade guide.
JIRA: https://issues.redhat.com/browse/SAT-35663

Fix content readability issues for connected upgrading guide

---

guides/common/modules/proc_removing-red-hat-subscriptions-and-subscription-manifests.adoc

Change admonition about removing RH manifests

---

guides/common/assembly_monitoring-project-resources.adoc
guides/common/modules/con_monitoring-project-resources.adoc
guides/common/modules/con_monitoring-resources.adoc
guides/common/modules/proc_using-the-project-content-dashboard.adoc
guides/common/modules/ref_performing-configuration-management.adoc
guides/doc-Administering_Project/master.adoc

Rename chapter & drop unnecessary note.
Fixes https://github.com/theforeman/foreman-documentation/issues/3671
While rewording this, I had doubts about the issue. I would also be OK not merging this & closing the issue on GitHub.

Reword introduction to monitoring resources

---

guides/common/modules/ref_activation-keys.adoc
guides/common/modules/ref_content-life-cycles.adoc
guides/common/modules/ref_general-information.adoc
guides/common/modules/ref_hosts.adoc
guides/common/modules/ref_orgs-locs-and-repos.adoc
guides/common/modules/ref_provisioning-environments.adoc
guides/common/modules/ref_users-and-permissions.adoc

Reworking Hammer cheat sheet to remove hard line breaks
DITA compliance
- Please, stick with the scope of the changes in this PR when reviewing.

Comply with DITA - Using Hammer - line breaks
