- guides/common/modules/con_transport-modes-for-remote-execution.adoc
- guides/common/modules/proc_configuring-project-to-use-ldap.adoc
- guides/common/modules/proc_creating-an-api-only-user.adoc
Due to a bug in our internal build system, I'm adding this workaround for two xrefs on a single line.
The bug causes wrong automatic selection of link labels -- the resulting links are rendered as a single link, which results in bad UX with the docs.
I'm not adding this to _master_, because we expect this bug to be fixed before the next release.
Cherry-pick to 3.1 and 2.5.
> Label double xref manually 3.3

- guides/common/modules/proc_promoting-a-content-view.adoc
Remove 2 steps from Promoting a Content View proc
> removes 2 procedure steps from proc_promoting-a-content-view.adoc

- guides/doc-Release_Notes/redmine_release_notes
[Quoting StackOverflow](https://stackoverflow.com/questions/2180322/ruby-gsub-doesnt-escape-single-quotes):
> \' means $' which is everything after the match. Escape the \ again and it works
> Correct escaping in Redmine release notes script

- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
In the section for Upgrading {SmartProxy} Servers, the steps for
regenerating certificates for {SmartProxy} were removed. This change
was required because there is no need to regenerate {SmartProxy}
certificates or copying the resulting tarball to {SmartProxy} for the
6.11 to 6.12 upgrade.
> Remove steps to regenerate capsule certs

- guides/doc-Upgrading_and_Updating/topics/upgrading_content_hosts.adoc
In the Upgrading Content Hosts section,
the note was updated to provide a
reference about the pull-based provider
feature so customers can try it.
> Update note to provide Pull Provider feature

- guides/common/modules/con_content-management-types-overview.adoc
- guides/doc-Managing_Content/master.adoc
OSTree content management is not available in Satellite 6.12
> Hide OSTree content for Satellite on 3.3

- guides/common/modules/proc_refreshing-the-compute-resources-cache.adoc
- guides/common/modules/proc_synchronizing-templates-using-the-api.adoc
- guides/common/modules/proc_synchronizing-templates-with-a-local-directory-using-the-api.adoc
This was required in Satellite API guide so I thought the same change should be done in the rest of the guides as well.
Related BZ: [https://bugzilla.redhat.com/show_bug.cgi?id=1917726](https://bugzilla.redhat.com/show_bug.cgi?id=1917726)
> Remove API version from curl header option

- guides/common/attributes-satellite.adoc
I'm not sure why the release notes use the Multi page view, but in 3d7230b7c24146e152488c64a80d8aa033164705 I just moved the existing link to a macro.
On a related note: I'd really like it if we could align Satellite links on a single style.
> Use MultiBaseURL instead of copying it

- guides/common/modules/con_gss-proxy.adoc
- guides/common/modules/con_using-freeipa.adoc
Dropped references to EL 7.1 which is no longer supported.
[Related BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2134737)
> Drop references to EL 7.1

- guides/common/attributes.adoc
In Katello Nightly (to be 4.7) the version has been updated to 3.21.
> Update Pulpcore version to 3.21

- guides/common/linkchecker.ini
Satellite 6.10 is GA so all links must resolve.
> Check all Satellite documentation links

- guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
Removed link to deprecated KCS about API changes inbetween Satellite versions 6.3 and 6.6 on branch 2.5
[Related BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2135236)
> Remove link to deprecated KCS for 2.5

- guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc
Removed link to deprecated KCS article about API changes inbetween Satellite versions 6.3 and 6.6.
[Related BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2135236)
> Remove link to deprecated KCS

- guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
The procedure for enrolling server with AD needs to be changed, as it does not work properly.
https://bugzilla.redhat.com/show_bug.cgi?id=2118978
> Fix a step in Configuring External Authentication

- guides/common/assembly_administering-hosts.adoc
- guides/common/modules/con_switching-between-hosts.adoc
- guides/common/modules/proc_executing-a-remote-job.adoc
Added the description of a new feature where users can easily switch
between hosts without leaving the page. Also, added the description
of scheduling remote execution jobs that is on the same page. The status
of the recent jobs can be viewed from the same page as well.
[Foreman demo] New features in host page
https://issues.redhat.com/browse/SATDOC-746
> New feature: Host Switcher

- guides/common/attributes-satellite.adoc
- guides/common/attributes.adoc
- guides/common/linkchecker.ini
- The `project-client-name` attribute is currently set to `Satellite Client {ProductVersionRepoTitle}` rendering the incorrect value `Satellite Client 6.12` for repos.
- The `AccessRedHatComVersion` is set to `6.11`, causing doc links to redirect to 6.11 docs instead of 6.12. Correcting these values for the 3.3 branch, which translates to 6.12.
> Fix the attributes for Satellite 6.12

- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_creating-a-local-file-repository.adoc
- guides/common/modules/proc_creating-a-remote-file-repository.adoc
Added missing steps required for creating a local/remote file type repo. 
This is a copy of PR#1650. 
It was hard to rebase the original PR. 
So created this PR with steps for EL 8 only.
This PR should be merged in foreman-3.4 only.
> Update steps for creating a local/remote file repository

- guides/doc-Upgrading_and_Updating/topics/updating_capsule_server_to_next_minor_version.adoc
- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
In several sections, the attribute for
`rhel-7-server-satellite-maintenance-6.12-rpms` was incorrect and needed to be updated with the attribute for
`rhel-8-server-satellite-maintenance-6.12-rpms`. This change was required because Satellite 6.12 is only a RHEL 8 based release. We do not have a RHEL 7 based repo for Satellite 6.12.
> Update repo label attribute in various sections

- guides/doc-Upgrading_and_Updating/topics/synchronizing_the_new_repositories.adoc
Repository names were changed. This
change was required because the Red Hat
Satellite Client repo is version
independent such as "Red Hat Satellite
Client 6 for RHEL 8 x86_64 RPMs". The
repository names were updated to
reflect that.
> Update section with correct repositories

- guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
The EL8 is missing in the content for the process of preparing the host for the external database. Hence, it needs to be added as upstream projects support it except Orcharhino.
https://bugzilla.redhat.com/show_bug.cgi?id=2119884
> Add EL8 support in preparing host for external DB

- guides/common/assembly_installing-satellite-server-disconnected.adoc
- guides/common/modules/con_provisioning-virtual-machines-on-kvm.adoc
- guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
- guides/common/modules/proc_configuring-repositories-proxy.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
- guides/common/modules/proc_installing-capsule-server-packages.adoc
- guides/common/modules/proc_installing-the-infoblox-ca-certificate-on-smartproxy.adoc
- guides/common/modules/proc_installing-the-satellite-server-packages.adoc
- guides/common/modules/proc_registering-to-red-hat-subscription-management.adoc
- guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc
- guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc
- guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
- guides/common/modules/proc_verifying-dns-resolution.adoc
- guides/common/modules/proc_verifying-firewall-settings.adoc
- guides/common/modules/ref_capsule-server-scalability-considerations.adoc
- guides/common/modules/ref_capsule-storage-requirements.adoc
- guides/common/modules/ref_storage-guidelines.adoc
- guides/common/modules/ref_storage-requirements.adoc
- guides/common/modules/ref_supported-operating-systems.adoc
- guides/common/modules/ref_system-requirements.adoc
Removed the references of EL7 from the 2 most recent project versions of downstream as it is no longer supported. However, the EL7 is still supported at upstream and hence it is unchanged.
[doc] - Remove EL7-specific references from all installation guides and from the Provisioning guide
https://issues.redhat.com/browse/SAT-9867
> Manage EL7 and EL8 references at upstream & downstream

- guides/common/modules/proc_creating-a-composite-content-view.adoc
- guides/common/modules/ref_content-settings.adoc
The term 'component Content View' was introduced to denote the Content Views included in a composite Content View. However, since this caused confusion among the users, the change has been reverted and any mentions of component Content View are removed from the UI. This term will soon be dropped from the hammer CLI as well as API too. Removing it from the docs as well.
> Remove mentions of component Content View

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
LEAPP in RHEL was updated to not need this workaround anymore (RHBA-2022:7895)
We didn't update the LEAPP that we ship in our Copr, so let's leave the note for non-Satellite builds as is.
> don't show the --disable-system-checks for Satellite LEAPP update

- guides/common/attributes-satellite.adoc
Because Sat 6.12 runs on RHEL8 only, we need to use `dnf` to install, update and remove packages.
> Set 'dnf' as package manager for Satellite on 3.3

- guides/doc-Configuring_Load_Balancer/topics/Before_You_Begin.adoc
> Fix URL in Configuring Load Balancer module

- guides/common/attributes-base.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
- guides/common/attributes.adoc
- guides/common/linkchecker.ini
- guides/common/modules/con_managing-red-hat-subscriptions.adoc
- guides/common/modules/con_synchronizing-content-between-servers.adoc
- guides/common/modules/proc_deleting-multiple-compliance-reports.adoc
- guides/common/modules/proc_enabling-auto-attach.adoc
- guides/common/modules/proc_exporting-report-templates-using-the-api.adoc
- guides/common/modules/proc_importing-report-templates-using-the-api.adoc
- guides/common/modules/proc_renaming-server.adoc
- guides/common/modules/proc_restoring-from-a-full-backup.adoc
- guides/common/modules/ref_performing-a-fresh-installation-of-a-server-on-el8.adoc
- guides/doc-Planning_for_Project/topics/Capsule_Server_Overview.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc
- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
Same changes as in #1775 for 3.3 branch. There were merge conflicts in linkchecker.ini and attributes-satellite.adoc.
> Verify All Satellite doc links for 3.3

- guides/common/attributes.adoc
Foreman 3.4 is currently the latest supported release so it should be listed as stable.
> Declare it Foreman 3.4 as stable

- guides/doc-Release_Notes/master.adoc
Looking at the past releases it appears nobody understands the README I wrote so here's an explicit marker where it should be added.
I don't think cherry picks are needed since all releases have versions so there it's clear.
> Add a comment where releases should be added

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/foreman-contributors.adoc
- guides/doc-Release_Notes/topics/foreman.adoc
- guides/doc-Release_Notes/topics/katello-contributors.adoc
- guides/doc-Release_Notes/topics/katello.adoc
See individual commits for details.
The styles of authors are still quite different, but I wonder which is best. Perhaps a long list is not too bad given it's an appendix. Should Foreman adopt the same style as Katello?
> Clean up Foreman 3.4 release notes

- web/content/js/versions.js
Fixes: 0c77d6a50df47ff90ea8378b7501a2b7d1f782c3
> Add Foreman 3.5 & Katello 4.7 to versions.js

- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
There can be some more EL7 references that should be removed.
> Remove EL7 reference

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
Process for upgrading Disconnected Satellite Server via Leapp added.
Change was required because we did not have the process in the initial
creation of the new Upgrading Satellite to Red Hat Enterprise Linux 8
In-Place Using Leapp section.
@evgeni  this is the same as #1427 but the merge conflicts were not easily resolved since #1683  changed the name of this file. All suggestions from #1427 were put into this PR and #1427 was closed.
> Add process for Disconnected Server via Leapp

- guides/common/modules/proc_configuring-repositories-deb.adoc
Puppet 7 is the latest and recommended version.
This also introduces an attribute to avoid repetition.
> Update Debian installation instructions to Puppet 7

- guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc
Module migrating_a_self_registered_satellite.adoc is not included in the Upgrading guide and the link to it is invalid, therefore it needs to be removed.
In the long term, the module could be included back in the guide, however; it needs to be updated since it contains references to EL 6 and I don't know whether its contents are still actual. For the short-term solution, this link needs to be removed because it is an invalid link in the released Satelliite 6.11 as well as in the soon to be released Satellite 6.12.
> Remove link to unincluded module

- guides/common/modules/proc_configuring-the-cleaning-unused-tasks-feature.adoc
- The bug mentioned in this section has been closed as WONTFIX, as the cleanup feature has been deliberately disabled for upgraded Satellites.
- Restructured the section to make the option to enable and disable the task cleanup feature more prominent.
- Removed the **Procedure** header as this only contained two separate options for configuring the task cleanup.
> Restructure the task cleanup section

- guides/common/modules/ref_host-parameter-hierarchy.adoc
- guides/doc-Provisioning_Hosts/master.adoc
This is based on https://theforeman.org/manuals/3.4/index.html#4.2.3Parameters
> Add Foreman Host Parameter Hierarchy

- guides/common/modules/proc_installing-the-scc-manager.adoc
Since Foreman 3.4 there is installer support for scc-manager. This greatly simplifies the steps needed.
This came up in https://github.com/theforeman/foreman-documentation/pull/1773/files#r1018084831.
> Use installer support for scc-manager plugin

- .github/workflows/deploy.yml
- guides/Makefile
Python 2 is EOL and this allows moving forward.
It looks like it's only used for linkchecker so cherry picking to all releases looks safe.
> Use Python 3 in CI workflows

- guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
A step in the procedure Chainbooting virtual machines was incorrect. 
The same has been reported in this BZ-2134961.
This PR contains fix for reported issue for foreman 2.5.
https://bugzilla.redhat.com/show_bug.cgi?id=2134961
> Step update in Chainbooting virtual machines

- guides/common/modules/con_template-writing-reference.adoc
- guides/doc-Planning_for_Project/topics/Glossary.adoc
Updating of puppet guide made some links invalid.
Updated links to chapters which I found in the new puppet guide.
Dropped links to chapters which I did not find.
I am 99% positive there are more invalid links but these I found for now in the process of fixing invalid puppet links on 3.1. 
> Update and drop links to puppet guide

- guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc
Change from #1794 applied to 3.2 branch.
> Remove link to unincluded module on 3.2

- guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
Reverts theforeman/foreman-documentation#1799
@dubewarsagar I'm truly sorry, Sagar, my mistake. The original procedure in 2.5 looks actually correct. Hosts > [Provisioning Setup] Operating Systems is a GUI path that does exist. A host group does not have a "Templates" tab that is mentioned in the next step.
> Revert "Step update in Chainbooting virtual machines" on 2.5

- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
Removed reference to EL 7 and edited Release notes URL based on checking all the URLs in the upgrading guide for the upcoming release of Satellite 6.12.
> Upgrading guide - finishing touches

- guides/doc-Upgrading_and_Updating/master.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc
Satellite 6.12 is based on Foreman 3.3 and does not support EL7→EL8 upgrades anymore, while Foreman still does (there the removal happens in 3.4).
> don't render "upgrade os" steps for Satellite builds

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
> Correct the non-Katello instructions for cloud-init

- guides/common/attributes-base.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes.adoc
- guides/common/modules/proc_installing-the-project-ansible-modules-from-rpm.adoc
This also removes a section where the attribute was not used, but should have. Since it's EL7 specific and doesn't apply to EL8, it should be removed.
Fixes: eb0b825d2a29c3bf0d195f8a854da375037073be
> Drop SatelliteAnsibleVersion attribute

- guides/common/modules/con_performing-post-upgrade-tasks.adoc
- guides/doc-Upgrading_and_Updating/master.adoc
Without Katello there is no content management so this part is not needed.
> Make Upgrading virt-who Katello-only

- .github/workflows/deploy.yml
- guides/Makefile
- guides/scripts/linkchecker-tryer
The official [linkchecker-tryer project](https://github.com/terryyin/linkchecker-tryer) has been unmaintained for the past 7 years, but clearly it was serving a purpose. Many links sometimes give some network error and aren't really a 404 which was breaking CI needlessly.
This takes the code from the original project and makes it run on Python 3. It removes reduce and filter since they're fairly hard to understand.  The current code should be easier to follow.
I also thought about submitting the script elsewhere so we don't have to maintain it in multiple places, but then we have to deal with installing it.
@evgeni I'd appreciate a look at this.
Fixes #1831
* We do not accept PRs for Foreman 2.3 …
> Re-introduce linkchecker-tryer

- guides/common/linkchecker.ini
Since Satellite 6.12 docs were not published on the RH website, linkchecker would fail when checking for doc links to these. As 6.12 docs have now been published, linkchecker should be able to reach the doc links.
> Remove Satellite 6.12 docs from linkchecker ignore list

- guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
There is a requirement to add the service principal i.e. Smart Proxy in the command of Creating a Kerberos Principal on the IdM Server process. There is a high probability of issues being occurred without a service principal in the command.
https://bugzilla.redhat.com/show_bug.cgi?id=2118391
> Add the missing service principal

- guides/common/assembly_configuring-the-discovery-service.adoc
- guides/common/modules/con_configuring-the-discovery-service.adoc
- guides/common/modules/proc_configuring-the-discovery-service.adoc
- guides/common/modules/proc_installing-the-discovery-service.adoc
- guides/common/modules/proc_installing-webhooks-plugin.adoc
- guides/common/modules/proc_uninstalling-microsoft-azure-plugin.adoc
We need to remove the `tfm` as a package prefix as it no longer supports EL8 in Project version 3.4 and later.
https://bugzilla.redhat.com/show_bug.cgi?id=2138391
> Remove tfm as package prefix for EL8

- guides/common/attributes-satellite.adoc
- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
Changes made in this PR:
- Set repos in Cloning Satellite to previous version since Cloning Satellite deals with a previous version of Satellite. Introduced attributes for repos that I used.
- Sorted repos by RHEL version and then alphabetically
- Removed outdated comment
When reviewing, I recommend checking commits separately.
> Cloning server

- guides/common/assembly_configuring-provisioning-resources.adoc
- guides/common/modules/proc_creating-an-operating-system-for-debian.adoc
This is due to user feedback: we should ensure users don't set the minor version for Ubuntu 22.04 when trying to provision hosts using Ubuntu Autoinstall. cc @bastian-src
> Show create OS for both Debian and Ubuntu

- guides/doc-Content_Management_Guide/topics/Managing_Organizations.adoc
The URL to add in the address bar to browse the accessible paths for 
all the repositories was incorrect for foreman 2.5. 
The same has been reported in BZ-2135217 and fixed in this PR.
https://bugzilla.redhat.com/show_bug.cgi?id=2135217
> Update in the paths for the repositories URL

- guides/common/modules/proc_configuring-satellite-deployment-with-an-external-dhcp-server.adoc
The installer restarts and refreshes the Foreman Proxy if needed. The user doesn't have to perform these.
I only picked the upstream supported version, but it probably applies to all versions.
> Remove redunant proxy instructions

- guides/common/modules/con_managing-red-hat-subscriptions.adoc
- guides/common/modules/proc_disabling-subscription-connection.adoc
As of Katello 4.6, Simple Content Access status is no longer tied to the upstream manifest, so we need to update some wording to ensure it continues to be accurate.
> Update Simple Content Access wording

- guides/common/modules/proc_benchmarking-raw-db-performance.adoc
- guides/common/modules/proc_configuring-repositories-el.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-hosts.adoc
- guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
- guides/common/modules/proc_renaming-server.adoc
- guides/common/modules/proc_renaming-smart-proxy.adoc
- guides/common/modules/proc_resolving-package-dependancy-errors.adoc
- guides/common/modules/proc_uninstalling-amazon-ec2-plugin.adoc
- guides/common/modules/proc_uninstalling-google-gce-plugin.adoc
- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
- guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc
- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
- guides/doc-Upgrading_and_Updating/topics/migrating_a_self_registered_satellite.adoc
This replaces a lot of manual definitions. It should be noted that
yum/dnf localinstall is deprecated (on EL7+) and an alias for install so
they can also be replaced.
> Use package-{install,remove} macros where appropriate

- guides/common/modules/con_registering_hosts.adoc
Also inverted the order so the newest EL is on top.
[Related BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2144382)
> Add EL 9 to supported host OS list

- guides/common/attributes-base.adoc
- guides/common/attributes-foreman-deb.adoc
- guides/common/modules/proc_configuring-a-host-for-registration.adoc
- guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
- guides/common/modules/proc_configuring-satellite-deployment-with-an-external-dhcp-server.adoc
- guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
- guides/common/modules/proc_installing-postgresql.adoc
- guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc
- guides/common/modules/proc_using-an-nfs-share-for-content-storage.adoc
- guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc
Using systemctl enable --now is equivalent to enable and start. It is already used in some places in the documentation, but this makes it consistent. The benefit for users is that they have to copy fewer commands.
It's still a draft since there are some oddities which I'll highlight.
> Use systemctl enable --now

- .github/PULL_REQUEST_TEMPLATE.md
> add Satellite 6.11 and 6.12 to PR template

- guides/doc-Administering_Project/docinfo.xml
- guides/doc-Administering_with_Ansible/docinfo.xml
- guides/doc-Configuring_Load_Balancer/docinfo.xml
- guides/doc-Deploying_Project_on_AWS/docinfo.xml
- guides/doc-Installing_Proxy/docinfo.xml
- guides/doc-Installing_Server/docinfo.xml
- guides/doc-Installing_Server_Disconnected/docinfo.xml
- guides/doc-Managing_Configurations_Ansible/docinfo.xml
- guides/doc-Managing_Configurations_Puppet/docinfo.xml
- guides/doc-Managing_Content/docinfo.xml
- guides/doc-Managing_Hosts/docinfo.xml
- guides/doc-Planning_for_Project/docinfo.xml
- guides/doc-Provisioning_Hosts/docinfo.xml
- guides/doc-Tuning_Performance/docinfo.xml
- guides/doc-Upgrading_and_Updating/docinfo.xml
The Satellite version in docinfo.xml files needs to be updated to able to build Pantheon previews.
> Update satellite version to 6.13 in docinfo

- guides/doc-Upgrading_and_Updating/topics/snip_needs_reboot.adoc
Resolves: #1858
Since `dnf needs -restarting` is available on el8, I tried to select the version that for running on RHEL/CentOS Stream require 8.
The plugin used is part of `dnf-plugins-core` which is installed on a system with `@Base` (and if I read comps.xml correctly actually comes with @core).
plugin presence has been successfully verified on both RHEL8 and CentOS Stream 8 @Base installs
> dnf needs-rebooting -r instead of 2 steps

- guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc
> Do not use yaml syntax highlighting

- guides/common/modules/proc_booting-virtual-machines.adoc
- guides/common/modules/proc_chainbooting-ipxe-from-pxelinux.adoc
In the section of Booting Virtual Machines and Chainbooting iPXE from PXELinux in the Provisioning Guide, the URL for the project was rendering of smartproxy which was incorrect. It needed to be fixed by replacing it with the project URL. Also, we mentioned the separate URL for smartproxy to avoid confusion while configuration.
If we kept this unchanged, the deployment would have failed as port 8000 will not be listening on the project server.
https://bugzilla.redhat.com/show_bug.cgi?id=2123489
> Correct the URLs in iPXE DHCP configuration

- guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
Removed incorrect steps for setting *iPXE Template* through the Hosts page (Hosts > All Hosts). 
Added missing steps setting *PXE Loader*.
https://bugzilla.redhat.com/show_bug.cgi?id=2134961
> Update in Chainbooting virtual machines Steps

- guides/common/modules/con_backing-up-server-and-proxy.adoc
- guides/common/modules/proc_restoring-from-a-full-backup.adoc
- guides/doc-Administering_Project/master.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc
> Render Backup/Restore documentation for Debian too

- guides/common/modules/proc_upgrading-hosts-to-next-major-rhel-release.adoc
- guides/doc-Managing_Hosts/master.adoc
Currently, the Managing Hosts guide only has information about RHEL 7 to RHEL 8 upgrade. The same procedure can be used for upgrading RHEL 8 hosts to RHEL 9. Tweaking the contents of the `Upgrading Hosts From RHEL 7 to RHEL 8` section so that it applies to upgrades between any major RHEL release.
- Renamed proc_upgrading-rhel7-hosts-to-rhel8.adoc to proc_upgrading-hosts-to-next-major-rhel-release.adoc.
- Edited the contents to make it more generic.
- Renamed the section to "= Upgrading Hosts to Next Major Red Hat Enterprise Linux Release.
> Add information about RHEL 8 to RHEL 9 upgrade

- guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
There is already a warning ahead of time that it can be done. Generally speaking we don't want to force users to review all changes and the installer should just work.
> Drop explicit noop step in disconnected upgrade

- guides/common/modules/snip_using_installer_noop.adoc
- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc
Only Red Hat customers can access the knowledge base. Ideally this would actually be part of the manual itself, but until then we should hide the link.
It also extracts the text to a snippet to avoid repetition. In one instance it's part of a list so it can't be extracted.
> Only show RH KB solution on Satellite

- guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
- guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc
The current command in enabling and synchronizing the Project Client Repositories is not working. Now, the correct command has been added to both sections.
https://bugzilla.redhat.com/show_bug.cgi?id=2148091
> Correct the command for enabling & syncing repos

- guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
The present command is not upgrading the Project to correct version. Therefore, it was required to add the maintenance repository for both, Project and Proxy. The newly added command will ensure the correct version of project to be upgraded.
https://bugzilla.redhat.com/show_bug.cgi?id=2148466
> Work around an upgrade bug in Satellite repositories

- guides/doc-Managing_Hosts/master.adoc
> Show KernelCare plug-in only for Katello

- guides/common/modules/proc_configuring-http-proxy-to-connect-to-cdn.adoc
- guides/common/modules/proc_synchronizing-ansible-collections.adoc
- guides/common/modules/ref_ports-and-firewall-requirements.adoc
cloud.redhat.com URL is a redirect to console.redhat.com, which can cause timeout errors (especially with API calls)
https://bugzilla.redhat.com/show_bug.cgi?id=2149457
> Fix RH Hybrid Cloud Console mentions

- guides/common/modules/proc_creating-a-local-file-repository.adoc
The upstream URL format mentioned in the documentation was throwing a sync error. 
It is not corrected.
A new step is added to describe how to sync a file repository that exists on the Project.
https://bugzilla.redhat.com/show_bug.cgi?id=2131854
> Steps update for Creating a local file repository

- guides/common/modules/proc_rex-pull-based-transport.adoc
- guides/doc-Tuning_Performance/master.adoc
> Add Mosquitto tuning

- guides/common/modules/proc_estimating-the-size-of-a-backup.adoc
- In the older version docs, the example for full backup took into consideration the sizes of the **/var/lib/mongodb** directory, bringing the total size to 680 GB. 
```
480G	/var/lib/mongodb
100G       /var/lib/pgsql/data
100G	/var/lib/pulp
```
- This brought the total size to 681 GB. Subsequent docs did not include the **/var/lib/mongodb** directory, as the project migrated from **pulp2** to **pulp3**, but the example size of 681 GB was not changed.
- Updating the docs to reflect the correct size for the example backup scenario.
Bugzilla link: https://bugzilla.redhat.com/show_bug.cgi?id=2150343
> Correct estimated backup size in example

- guides/common/modules/proc_importing-a-repository.adoc
Removed few obsolete steps from the module - Importing a repository.
https://bugzilla.redhat.com/show_bug.cgi?id=2134228
> Update instructions for Importing a repository

- guides/common/assembly_configuring-the-discovery-service.adoc
- guides/common/modules/con_configuring-the-discovery-service.adoc
- guides/common/modules/proc_implementing-pxe-less-discovery.adoc
We are hiding these instructions to build the discovery image because 
we don't have working instructions.
Soon we will plan a task to rewrite the steps to work on RHEL 8.
https://bugzilla.redhat.com/show_bug.cgi?id=2151585
> Hide "Building a Discovery Image" module

- web/content/js/versions.js
Foreman 3.5.1 is the GA version and that makes Foreman 3.3 unsupported.
> Declare Foreman 3.5 as supported & 3.3 as unsupported

- guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
- guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
Follow-up to https://github.com/theforeman/foreman-documentation/pull/1906
Merge conflict was only in `guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc` which I've checked out from 3.3 and sorted the list of repos on RHEL 8 manually & amended to the first commit. cc @adamlazik1
> Managing file repositories 3.3

- guides/common/assembly_configuring-the-discovery-service.adoc
- guides/common/modules/proc_configuring-the-discovery-service.adoc
- guides/common/modules/proc_installing-the-discovery-service.adoc
- guides/common/modules/proc_installing-the-scc-manager.adoc
- guides/common/modules/proc_installing-webhooks-plugin.adoc
- guides/common/modules/proc_uninstalling-microsoft-azure-plugin.adoc
The EL8 does not support tfm as a prefix for packages but the EL7 does. Therefore, we added a note to alert users to remove the prefix if they are carrying out the process for EL8. The tfm prefix remains unchanged for EL7. This is applicable to Project versions 3.2 and 3.1.
https://bugzilla.redhat.com/show_bug.cgi?id=2138391
> Add note to remove tfm as package prefix for EL8

- guides/common/assembly_getting-started-with-ansible.adoc
- guides/common/modules/con_supported-ansible-versions.adoc
We wanted to mention supported Ansible versions, however, they actually depend on the user's configuration of the base OS. Perhaps it's still worth mentioning.
https://bugzilla.redhat.com/show_bug.cgi?id=2139700
> Mention supported Ansible versions

- guides/common/attributes-base.adoc
- guides/common/attributes-foreman-deb.adoc
- guides/common/modules/proc_benchmarking-raw-db-performance.adoc
- guides/common/modules/proc_estimating-the-size-of-a-backup.adoc
- guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc
- guides/common/modules/proc_installing-postgresql.adoc
- guides/common/modules/proc_performing-a-snapshot-backup.adoc
- guides/common/modules/ref_capsule-storage-requirements.adoc
- guides/common/modules/ref_storage-requirements.adoc
- guides/doc-Planning_for_Project/topics/Required_Technical_Users.adoc
See individual commits for details. This should be picked back to 3.3.
> Introduce attributes for PostgreSQL paths & update storage tables

- guides/scripts/linkchecker-tryer
In 95a8a2f7d74882613237ad033a9b14f7dbc14d7d the linkchecker-retryer implementation was rewritten. While it certainly helps compared to no retryer, it doesn't fix all issues. This increases the number of times it retries, which hopefully makes it work better.
> Increase linkchecker-tryer retries to 5

- guides/common/modules/con_remote-execution-workflow.adoc
We mention how project searches for the remote execution proxy of a host and we cover all the points except one i.e. the "Prefer registered through proxy for remote execution" settings. Hence, we are adding a case where project prefers to execute remote workflow that are registered through proxies. From all the other processes that are mentioned in this section, this is the preferable way and it is the reason why we kept it in the starting of section.
Document the function of "Prefer registered through proxy for remote execution" option in "Remote Execution Workflow" section
https://bugzilla.redhat.com/show_bug.cgi?id=2123976
> Add a case in Remote Execution Workflow

- guides/doc-Planning_for_Project/topics/Required_Technical_Users.adoc
> improve technical users table to closer match deployments

- guides/common/modules/proc_enabling-puppet.adoc
- guides/common/modules/proc_renaming-server.adoc
Currently, protocol "https://" is missing for foreman-example-com 
in the module Enabling Puppet Integration with {Project}
This has been reported as one of the DDF.
https://bugzilla.redhat.com/show_bug.cgi?id=2157880
> Add protocol for : foreman-example-com

- guides/common/attributes-foreman-el.adoc
- guides/common/attributes-katello.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_configuring-repositories-proxy.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/common/modules/proc_installing-from-the-offline-repositories.adoc
- guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
- guides/common/modules/proc_resolving-package-dependency-errors.adoc
- guides/common/modules/snip_dnf-module-enable-note.adoc
- guides/common/modules/snip_satellite-el8-enable-note.adoc
> correct module-enable-note for capsules and non-satellite builds

- guides/common/modules/proc_installing-openscap-plugin.adoc
This became necessary to cherry-pick the commit from @dubewarsagar 's PR for the version `3.2` and `3.1`. Because this change is applicable to even mentioned versions according to the reporter.
https://bugzilla.redhat.com/show_bug.cgi?id=2158411
(cherry picked from commit fc47b5b924ec5f28a8962c8fc6d3e8d7083d2698)
> Rework procedure to install OpenSCAP plugin (#1632)

- guides/common/modules/proc_configuring-your-deployment-to-run-ansible-roles.adoc
The collections directive should be "collections_paths" (according to [ansible.cfg example](https://github.com/ansible/ansible/blob/stable-2.10/examples/ansible.cfg#L64))
> Fix typo in Ansible cfg directive

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
Added RHEL 8 instructions for the Disconnected
Satellite Server section
of the guide. This change was needed because there were no instructions
on the Minor update procedure for
connected/disconnected Red Hat
Satellite 6 on RHEL 8.
@evgeni This is the first PR I am submitting for SATDOC-1019 
specifically for the Disconnected section.
> Add EL 8 instructions to Disconnected section

- guides/common/modules/proc_generating-host-monitoring-reports.adoc
Generating report entitlement requires an extra option compared to other reports.
CC @adamruzicka 
[BZ link](https://bugzilla.redhat.com/show_bug.cgi?id=2156762)
> Add an example of generating report entitlement

- guides/common/assembly_administering-hosts.adoc
- guides/common/modules/proc_selecting-host-columns.adoc
- guides/common/modules/ref_overview-of-the-host-columns.adoc
- guides/doc-Managing_Hosts/master.adoc
Also added descriptions of the host columns in an appendix.
> Add procedure to select columns in the host table

- guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
Enabling Satellite Utils module was missing in 2 modules: 
Creating a Local Source for a Custom File Type Repository and 
Creating a Remote Source for a Custom File Type Repository
This has been reported in BZ2116585.
For confirmation see: https://bugzilla.redhat.com/show_bug.cgi?id=2116585#c12
https://bugzilla.redhat.com/show_bug.cgi?id=2116585
> Add missing step to enable satellite-utils module

- guides/common/modules/proc_renaming-server.adoc
The bootstrap procedure to register hosts is deprecated, users should use the curl command instead.
Resolves merge conflicts in #1927. The content is verified by SME.
(cherry picked from commit 46a85444cda166a4253b29a8eef05f5dc37e52b0)
> Replace bootstrap with the curl command on 3.2 and 3.1

- guides/common/modules/proc_adding-an-http-proxy.adoc
- guides/common/modules/proc_configuring-http-proxy-to-connect-to-cdn.adoc
- guides/common/modules/snip_host-names-for-http-proxy.adoc
The *.akamaiedge.net Host hame should also be part of Adding an HTTP Proxy while Importing Content. The reason is it is a part of Configuring the HTTP Proxy in the Installation Guide.
https://bugzilla.redhat.com/show_bug.cgi?id=2152785
> Add akamaiedge.net Host name in adding HTTP proxy

- guides/common/assembly_getting-started-with-ansible.adoc
- guides/common/modules/proc_configuring-your-deployment-to-run-ansible-roles.adoc
- guides/common/modules/ref_customizing-ansible-configuration.adoc
Foreman used to store essential Ansible settings in a config file that was managed by Foreman (and overwritten on each foreman-installer run). Now, Foreman stores these values as `.env`. This allows the user to customize Ansible configuration in a persistent manner.
> Customize Ansible cfg persistently

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
Instructions were missing to enable {Project} Maintenance repository on EL 8. 
The same has been reported in BZ-2114484 and fixed in this PR.
https://bugzilla.redhat.com/show_bug.cgi?id=2114484
> Add missing instructions for EL 8

- guides/common/modules/proc_configuring-repositories-proxy.adoc
"attributes" lable was missing for one of the code-blocks.
It was causing one of the attribute to render incorrectly.
The same has been fixed in this MR.
https://bugzilla.redhat.com/show_bug.cgi?id=2161266
> Add missing attribute lable to a code block

- guides/common/modules/proc_restoring-a-backup-of-a-server-on-el8.adoc
- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
Repo sync fails on Project servers installed on RHEL8. This happens for systems that have been upgraded from RHEL 7 to RHEL 8, or migrated to RHEL 8. A workaround for this is to reindex the databases after upgrading or migrating to RHEL 8. Adding this workaround to the two procedures that are impacted by this bug.
Bug link: https://bugzilla.redhat.com/show_bug.cgi?id=2161413
> Add a step to reindex databases after migration to RHEL8

- guides/common/modules/proc_configuring-repositories-proxy.adoc
It was causing one of the attribute to render incorrectly. 
Original PR is #1938. 
This PR is for version 3.4 only. 
https://bugzilla.redhat.com/show_bug.cgi?id=2161266
> Missing "attributes" lable for one of code-blocks

- guides/common/modules/con_managing-red-hat-subscriptions.adoc
Manifests have migrated to the Hybrid Cloud Console. New documentation
is available at Subscription Central
(https://access.redhat.com/documentation/
en-us/subscription_central/2021).
The link has been updated to reflect this change.
> Change link for manifests for Subscription

- guides/common/modules/proc_creating-hosts-on-vmware.adoc
The end-user needs to add the activation key via parameters but there were not any proper steps documented for the same to add the kt_activation_keys. Therefore, we added the required steps in the topic Creating Hosts on VMware. In addition to this, we are guiding an end-user to enter the correct values in the field of Name and Value.
https://bugzilla.redhat.com/show_bug.cgi?id=2122797
> Add the reference to activation key

- guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
Creating a Local Source for a Custom File Type Repository and 
Creating a Remote Source for a Custom File Type Repository 
This PR is a clone of PR#1930 for foreman version 3.3 and 3.1
For confirmation see: https://bugzilla.redhat.com/show_bug.cgi?id=2116585#c12
https://bugzilla.redhat.com/show_bug.cgi?id=2116585
> missing step to enable Sat Utils in 2 modules

- guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
The current procedure does not give a clear understanding of exporting the Subscription Manifest from the Red Hat Hybrid Cloud Console. We added enhanced navigation to export the manifest and import it into the Satellite.
https://bugzilla.redhat.com/show_bug.cgi?id=2158805
-
> Enhance the procedure to export Subscription Manifest

- guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc
- guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/1828. Created a separate PR for 3.1 as suggested in the original PR.
- As puppetserver and puppet-related features are disabled in later versions, the installer options in the LB docs fail for "with Puppet" scenarios.
- The procedures in the below two sections are affected:
1.Configuring {SmartProxyServer} with Default SSL Certificates for Load Balancing with Puppet
2.Configuring {SmartProxyServer} with Custom SSL Certificates for Load Balancing with Puppet
- The installer commands in these two sections result in the error:
`[ERROR ] [configure] Could not set groups on user[foreman-proxy]: Execution of '/sbin/usermod -G puppet foreman-proxy' returned 6: usermod: group 'puppet' does not exist`
- This is because the …
> Update LB docs to include puppet options in installer commands in branch 3.1

- guides/common/modules/ref_overview-of-the-host-columns.adoc
Edited list of selectable columns based on the newest snapshot. Attaching screenshot below.
Note: BIOS columns do not appear in the screenshot but are planned to be included.
> Update list of selectable columns

- guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
- guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc
The client repositories for enabling and synchronizing the project client for EL9 and EL8 were not added. Now it is added for both of them along with the updated Web UI procedure.
https://bugzilla.redhat.com/show_bug.cgi?id=2150297
> Add EL9 & EL8 repos for enabling and syncing

- guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
- guides/common/modules/proc_executing-a-remote-job.adoc
- guides/common/modules/ref_advanced-settings-in-the-job-wizard.adoc
The new job wizard requires updating the procedure.
I also separated the despription of advanced settings to another module as I believe it makes the procedure more readable. Users can click on the provided link to learn more about the advanced settings.
CC @adamruzicka
> Update the Executing a remote job procedure

- guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
2 items from in the Pre-Migration Checks were duplicate. 
They are removed in this PR for foreman version 2.5. 
https://bugzilla.redhat.com/show_bug.cgi?id=2164509
> Remove duplicate content from Pre-Migration Checks

- guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
- guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc
The client repositories for enabling and synchronizing the project client for EL9 and EL8 were not added. Now it is added for both of them along with the updated Web UI procedure.
https://bugzilla.redhat.com/show_bug.cgi?id=2150297
> Add EL6 to EL9 client repos for enabling & syncing

- guides/common/modules/proc_setting-the-load-balancer-for-host-registration.adoc
- guides/common/modules/snip_host-registration-steps.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Configuring_Load_Balancer/topics/Installing_the_Load_Balancer.adoc
- guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc
In a deployment with load balancing, the user can configure SmartProxies to provide a load balancer as an option for the global registration feature. Then the user can register hosts in Foreman to the load balancer directly, which eliminates the need to manually reconfigure subscription manager on the hosts after registration.
> Register hosts through a load balancer

- guides/common/assembly_administering-hosts.adoc
- guides/common/assembly_managing-activation-keys.adoc
- guides/common/modules/proc_enabling-and-disabling-repositories-on-hosts.adoc
- guides/common/modules/proc_upgrading-hosts-to-next-major-rhel-release.adoc
- guides/common/modules/proc_upgrading-packages-on-a-host-in-bulk.adoc
- guides/common/modules/proc_using-the-host-details-tab.adoc
Added new information to Upgrading Packages on a Host in Bulk and
Upgrading Hosts to Next Major RHEL Release. Added two new procedure
modules to address how to use the details tab and
enabling and
disabling repositories on hosts in the Managing Hosts guide.
> Update sections and add new procedures

- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
One of the steps of attaching the Pool ID in the Attaching the Satellite Infrastructure Subscription is optional when SCA is already enabled in the Satellite. The reason is the Capsule server is registered with the Satellite server and not with the Customer Portal. So, we also modified the note at the start of the section where we went ahead and documented about Customer Portal.
https://bugzilla.redhat.com/show_bug.cgi?id=2166372
> Modify note and a step in the SCA enabled case

- guides/common/modules/proc_configuring-installation.adoc
The path to unmounting ISO while installing the project is applicable to only EL7. While in the latest project version, it has to be relevant to EL8. Therefore, it was required to update it with the correct path considering the supported operating systems.
https://bugzilla.redhat.com/show_bug.cgi?id=2166016
> Correct the path to unmount ISO

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
Red Hat does not support LEAPP upgrades from RHEL 7 to RHEL 8 for systems that have FIPS enabled. As a workaround some users turn off FIPS to perform LEAPP upgrade and then turn it back on, however, this is not supported either and causes further issues. It is advisable to go with a fresh installation on a RHEL 8 system instead. Adding a note about supportability for LEAPP upgrade of FIPS enabled systems for clarification.
Bug link: https://bugzilla.redhat.com/show_bug.cgi?id=2159785
> Add note about support for LEAPP upgrade of FIPS systems

- guides/common/modules/proc_configuring-installation.adoc
In addition to the EL7 server, the project also supports EL8 and hence it is required to add the path for unmounting the ISO of EL8 as well.
https://bugzilla.redhat.com/show_bug.cgi?id=2166016
> Add EL8 in the path of unmounting ISO

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
The link to the post upgrade steps is missing in the upgrading RHEL 7 to RHEL 8 using LEAPP section. This results in some issues post upgrade (e.g. leapp setting the release version to 8.6). https://bugzilla.redhat.com/show_bug.cgi?id=2164027
> Add a link to the RHEL 7 to RHEL 8 post upgrade steps section

- guides/common/assembly_configuring-host-collections.adoc
- guides/common/modules/proc_viewing-errata-by-applicable-and-installable.adoc
The Errata card under the Overview tab under a host can toggle between
Applicable and Installable. This procedure describes how to do it and
what they mean.
> Add new procedure for errata card

- guides/common/modules/proc_creating-a-host.adoc
- guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
- guides/common/modules/proc_editing-the-system-purpose-of-multiple-hosts.adoc
RHEL installation guide appears to have changed structure and link to section about system purpose needs to be updated.
[BZ link](https://bugzilla.redhat.com/show_bug.cgi?id=2167488)
> Update link to system purpose

- guides/common/attributes-satellite.adoc
Downstream documentation (hammer guide) is not rendering correctly because of the missing attribute. Attaching screenshot below.
> Add attribute for RHSCL repo

- guides/common/modules/con_remote-execution-workflow.adoc
The `remote_execution_prefer_registered_through_proxy` cannot  be found in Administer > Settings, this setting is in fact `Prefer registered through {SmartProxy} for remote execution`. 
[BZ link](https://bugzilla.redhat.com/show_bug.cgi?id=2167486)
> Update name of REX setting

- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
In the previous PR, we modified the note while considering the SCA enabled in Customer Portal. But, the case is different for Proxy. If the SCA is enabled on the Server, you don't need to attach a subscription for the Proxy. Hence, we added the note in both contexts to avoid even a little confusion.
https://bugzilla.redhat.com/show_bug.cgi?id=2166372
> Modify note while attaching subscription

- guides/common/modules/proc_using-the-host-details-tab.adoc
There are new available details in the OS card under the Details tab in
a host. Specifically the kernel release. A line had been added to call
out the details available under the OS card.
> Add line about details in OS card

- guides/common/assembly_administering-hosts.adoc
- guides/common/modules/proc_viewing-host-details-from-a-content-host.adoc
Created a procedure to view the host details page from a content host.
The procedure involves going to the Administer
settings.
> Add host details view procedure

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_host-management-and-monitoring-using-cockpit.adoc
- guides/common/modules/proc_enabling-cockpit-on-server.adoc
- guides/common/modules/proc_managing-and-monitoring-hosts-using-cockpit.adoc
{Cockpit} renders lowercased in Satellite build titles. Added new attribute to fix this issue and to be consistent with Camel Case titles throughout the guides.
> Capitalize Cockpit attribute in titles

- guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
In configuring the iPXE to reduce the provisioning times, there was not any procedure documented for the foreman discovery method to work with UEFI systems. We added it for both, EFI systems and BIOS systems. In addition to this, we also added one more step to creating a system entry with iPXE workflow. A guide to selecting options for PXELoader is documented in this step to avoid the iPXE looping in certain cases.
https://bugzilla.redhat.com/show_bug.cgi?id=1996519
> Add procedure & a step in configuring iPXE

- guides/common/modules/proc_managing-and-monitoring-hosts-using-cockpit.adoc
A step in the Procedure mentions an outdated Web
Console button. A
change was required to reflect the new UI where the user must select a
vertical ellipsis. It is also optional for the user to select the
Legacy UI to choose the old Enable Web Console button if they wish.
> Update step with outdated Web Console button

- guides/doc-Planning_for_Project/topics/Host_Provisioning_Support.adoc
> Add RHEL 9 architectures to provisioning support

- guides/common/modules/proc_configuring-an-alternative-directory-to-execute-remote-jobs-on-clients.adoc
- guides/common/modules/proc_configuring-repositories-proxy.adoc
For some weird reason, the missing `+` caused the attribute not to expand. Adding it fixed a formatting issue at the same time. Screenshots from before and after adding `+` below.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2169868
Before:
After:
> Correctly render foreman-installer attribute

- guides/common/assembly_managing-activation-keys.adoc
- guides/common/assembly_managing-packages.adoc
- guides/common/modules/proc_upgrading-packages-on-a-host.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
Inspect individual commits for easier review.
Disclaimer: There are no links associated with the moved modules so moving them is safe.
cc @jeremylenz 
> Move host-related modules to Managing Hosts

- guides/common/modules/snip_generating-content.adoc
Starting from Foreman 3.5, Container Images can be exported as well from the project server in syncable format.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2167411
> Update list of exportable content

- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc
The current commands are not enough to renew the Proxy certificate which can be improved further. So, we added the --certs-update-server-ca option while deploying the custom SSL certificate to the Proxy server. In addition to this, we also added --certs-update-all to Project and Proxy both for the same section in the documentation. In the case where suggested commands do not work, --certs-update-all will help to update the internal Proxy certificates. However, it may not be needed for just the renewal process but in some cases, it is required to update all the certificates.
https://bugzilla.redhat.com/show_bug.cgi?id=2093128
> Add command in Proxy certificate renewal

- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
In the earlier PR, we added the note about Project Subscription and its relation to the server. However, when it comes to Project Server, the SCA should be enabled to end-user portal and Project itself. Therefore, the note has been correct according to the relevant contexts of the server.
https://bugzilla.redhat.com/show_bug.cgi?id=2169872
> Correct the note for Project Subscription

- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc
In the previous PR, we added the --certs-update-all which does the large change. While, these changes will do the changes as per the minimal requirements. Therefore, these changes are recommended over the previous ones by reporters and reviewers.
https://bugzilla.redhat.com/show_bug.cgi?id=2093128
> Correct the command in deploying SSL certs

- guides/common/attributes-satellite.adoc
Multi-page html links behave differently than single-page, thus the attributes cannot in current state be used link the proper sections of the guides.
Compare:
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.12/html-single/hammer_cli_guide/index#hammer-defaults
VS
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.12/html/hammer_cli_guide/index#hammer-defaults
Also moved Satellite Release Notes URL in the correct section of the attributes file under *not upstreamed*.
> Correct satellite guide URLs

- guides/common/modules/ref_examples-ldap-filters.adoc
While giving the example of LDAP filters while configuring External Authentication, a use case of a single user was missing. We added it with applicable filter data.
https://bugzilla.redhat.com/show_bug.cgi?id=2170700
> Add filter for a single user

- guides/common/modules/proc_setting-the-location-context.adoc
`hammer subscription list --location` is not a valid command. Replaced example with valid command and added new command description.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2172613
> Correct hammer command showcasing location option

- guides/doc-Administering_Project/master.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Managing_Configurations_Ansible/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Upgrading_and_Updating/master.adoc
Pantheon does not use html5 as backend anymore, the module is currently not being displayed.
> Render feedback module on Satellite

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- README.md
- guides/common/attributes.adoc
- web/content/index.adoc
- web/content/js/versions.js
- web/content/release-3.6.adoc
This adds links to the 3.6 branch as well as bumping the previous version number to 3.6.
<del>Currently I'm still working on the 3.6 branch, so this is still a draft</del>
> Reflect that Foreman 3.6 has branched

- guides/common/modules/proc_enabling-puppet.adoc
- guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc
- guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc
As part of a larger feature, this simplifies the options users need to pass to enable Puppet.
Right now this still depends on https://github.com/theforeman/foreman-installer/pull/828 and its dependencies to be merged. It's just to demonstrate the new way for end users.
> Refs #35985 - Update Puppet enablement options

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
- Performing the post-upgrade tasks after upgrading from EL 7 to EL 8 is extremely important.
- The current arrangement puts the "Verifying post-upgrade state" and "Performing post-upgrade tasks" sections together.
- This could result in users failing to perform the post-upgrade steps.
- Splitting the two steps into sub-steps to make the post-upgrade tasks step more visible.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2169351
> Split post-upgrade leapp steps into two

- guides/common/modules/proc_assigning-a-host-to-a-specific-organization.adoc
Trying to assign registered hosts to organization results in:
"Error: Unregister host before assigning an organization".
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2170837
CC @jeremylenz 
> Unregister host when assigning to a new org

- guides/common/modules/con_managing-errata.adoc
Corrected a typo that is reported in BZ-2173641.
> Corrected a typo reported in BZ-2173641

- guides/common/modules/snip_host-registration-steps.adoc
The step was meant for _Configuring Load Balancer_ therefore it must not be rendered for other contexts.
The step was removed in 3.5+, therefore this change applies only to 3.4-3.1.
https://bugzilla.redhat.com/show_bug.cgi?id=2173714
> Hide a load-balancing step out of LB context 3.4-3.1

- guides/common/modules/snip_generating-content.adoc
Removed "Container Images" from snip_generating-
content.adoc located in
modules/proc_exporting-the-library-environment-in-a- syncable-format.adoc.
This change was required because we do not support container images for
syncable formats.
> Remove Container Images from snip

- guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
orcharhino supports Puppet 7. (It was a mistake to exclude it.)
> Fix supported Puppet versions for orcharhino

- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
The present upgrade command where maintain package was not able to process the value correctly. As a result, the version of project upgraded is incorrect. The new maintain package and enablement of maintenance repos will be able to resolve it. Also, the rubygem maintain package installed from older repo didn't had the bug fixed. Therefore, the new commands will help end-users to upgrade to correct project version.
https://bugzilla.redhat.com/show_bug.cgi?id=2148435
> Update steps in upgrading Proxy

- guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc
PR https://github.com/theforeman/foreman-documentation/pull/2022 Fixed rendering feedback module on Satellite documentation but also caused the build-pdf test to fail. This issue did not emerge before merging the PR. Removing special unordered list styles fixes this issue. I do not believe the extra styles have to be included and would prefer build-pdf tests to pass instead (while keeping the source documentation as simple as possible).
CC @Lennonka 
> Pass build-pdf test for satellite build

- guides/common/modules/ref_system-requirements.adoc
We list some user accounts that are created by satellite that should not already exist or fetched from external entities. So here, the Redis was missing. It's applicable to even Proxy Installtion part. The same can be verified by the Redis Database server: /var/lib/redis:/sbin/nologin
https://bugzilla.redhat.com/show_bug.cgi?id=2165956
> Add redis in the list of users to avoid conflicts

- guides/common/modules/proc_setting-the-job-rate-limit-on-smartproxy.adoc
CC @adamruzicka 
Note: last line is displaying change because of the added newline.
> Apply job rate limit only to mqtt based jobs

- guides/common/assembly_using-report-templates.adoc
- guides/common/modules/proc_generating-a-list-of-installed-packages.adoc
A procedure was created for generating a list of
installed packages in
Report Templates.
> Add procedure for listing installed packages

- guides/common/modules/proc_synchronizing-ansible-collections.adoc
Links to older versions are of this guide are no longer valid.
> Fix link failing the the html-check test

- guides/common/modules/con_shellhooks-plugin.adoc
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2173600
> Highlight difference in shellhook dir vs URL

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
In creating keytab entry during the configuration of direct AD integration with GSS-Proxy, we can warn the end-user about connectivity between hosts and domain. This will save time for end-users.
https://bugzilla.redhat.com/show_bug.cgi?id=2159686
> Add warning while creating keytab entry

- guides/common/modules/proc_comparing-content-view-versions.adoc
Improved the procedure for comparing content view
versions to make more
sense to the user.
> Clarify procedure for content view comparison

- guides/common/modules/con_content-types-overview.adoc
- guides/doc-Managing_Content/master.adoc
OSTree content management is not available in Satellite 6.13
Please cherry-pick my commits into: None
> Hide OSTree content for Satellite on 3.5

- guides/doc-Release_Notes/redmine_release_notes
> Sort categories in the release notes

- guides/common/modules/proc_upgrading-hosts-to-next-major-rhel-release.adoc
Previously, it wasn't clear, how to handle remediation hints vs. commands and which issues can be selected to be fixed directly from the WebUI.
* TBD a separate PR for 2.5
> Clarify remediations in host Leapp upgrade

- guides/common/attributes-base.adoc
- guides/common/modules/proc_importing-container-images.adoc
In order to use the "managing container" section for multiple OS (e.g. importing a container image for Ubuntu), I want to introduce attributes to handle all OS-specific parameters.
Do you think the attributes should be part of the assembly or moved to the "attributes-base" file?
> Introduce attributes for "managing containers"

- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
The `Upgrading Capsule Servers` section has a step to update Content Views, which is similar to the last step in `Synchronising New Repositories` section. However, the `Upgrading Capsule Servers` section needs to reflect that the CV has to be promoted as well. Rewording the step so that it reflects the correct information.
Bugzilla link: https://bugzilla.redhat.com/show_bug.cgi?id=2169783
> Standardize wording for common steps in upgrade doc

- guides/common/modules/con_configuring-email-notifications.adoc
- guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
- guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
- guides/common/modules/proc_importing-kickstart-repositories.adoc
- guides/common/modules/proc_registering-hosts.adoc
- guides/common/modules/proc_renaming-server.adoc
- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
> Hide various links for orcharhino builds

- guides/common/modules/proc_creating-a-personal-access-token.adoc
- guides/common/modules/proc_revoking-a-personal-access-token.adoc
Apparently, publishing tool we use for Satellite documentation does not render the code block correctly when using italic marks <em> and </em>. The reason I used them in the first place was that the code refused to render correctly when using underscores. However, I only today discovered that doubling underscores solves this issue. Apologies to @maximiliankolb for not interpreting his [comment](https://github.com/theforeman/foreman-documentation/pull/2050#pullrequestreview-1339543486), in which he notified me about this option, correctly the first time.
> Fix rendering of italics in code block

- guides/common/assembly_configuring-external-authentication.adoc
- guides/common/assembly_managing-users-and-roles.adoc
- guides/common/modules/con_managing-personal-access-tokens.adoc
In #2050, I put section on Personal Access Tokens to Configuring External Authentication, but this was a mistake since PAT is not an external but internal authentication method. Instead, I am putting it in Managing Users and Roles, right after Managing SSH Keys section as this suits the content much better. I am also renaming the con file to preserve paralellism.
> Move Personal Access Tokens to correct assembly

- guides/common/assembly_building_cloud-images.adoc
- guides/common/assembly_registering-hosts.adoc
- guides/common/modules/con_how-puppet-integrates-with-project.adoc
- guides/common/modules/con_registering_hosts.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-manually.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
Add a section about installing and configuring Puppet agent during host registration.
> Installing Puppet agent during Registration

- guides/common/modules/proc_installing-puppet-agent-during-host-provisioning.adoc
Changes:
1. Rewrite of the workflow for downstream products that should use only puppet-agent shipped with the product.
2. Katello users should enable the puppetlabs*) repo using a CV/activation key as well.
3. puppetlabs*) enablement without activation keys is kept only for vanilla Foreman.
4. puppetlabs*) enablement without activation keys uses the non-versioned parameter `enable-puppetlabs-repo`, which enables the latest Puppet (that is version 7 currently)
*) puppetlabs are the official Puppet repositories at puppet.com
> Rewrite Installing Puppet agent during Provisioning

- guides/common/attributes-base.adoc
- guides/common/modules/con_content-filter-overview.adoc
- guides/common/modules/con_managing-content-views.adoc
- guides/common/modules/proc_importing-a-custom-gpg-key.adoc
- guides/common/modules/snip_host-registration-steps.adoc
This is the start to allow content specifically aimed at users managing Debian or SLES hosts. My PR does not change the output yet, because for all build targets, `:dnf:` is set and `:apt:` remains unset.
In downstream, I build all three big guides (managing content, provisioning hosts, configuring hosts) for multiple OS which set or unset specific attributes.
For the future, I could see a way of adding specific procedures in upstream docs twice: once for rpm and once for deb.
> Introduce "client-content-X" attributes

- guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
Improving for Satellite vs. non-Satellite builds and updating WebUI navigation.
https://bugzilla.redhat.com/show_bug.cgi?id=2172247
> Update ISOs and ISO download in PXE-less provisioning

- guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
> Improve sentence in PXE-less provisioning

- guides/common/modules/proc_configuring-capsule-default-certificate.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
In configuring the Proxy's default SSL certificate, the command for copying the archive file to the Proxy Server is incorrect as it has a typo. We are making corrections to that command because it generated the tar file in the previous step. The present command that is incorrect is throwing an error stating the tar file generated by the server is not present.
https://bugzilla.redhat.com/show_bug.cgi?id=2167827
> Correct the command for default SSL certificate

- guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc
- guides/common/modules/proc_enabling-red-hat-repositories.adoc
> remove "Satellite" from install guide non-satellite builds

- guides/common/modules/ref_system-requirements.adoc
We are documenting the principle of installation of the Project Server in FIPS mode in which the end-user cannot enable the FIPS mode after installation and vice-versa for non-FIPS mode. This was not clear enough earlier and therefore we added one more sentence to alert the end-user while installing the Project Server.
https://bugzilla.redhat.com/show_bug.cgi?id=2181262
> Add the FIPS mode principle

- guides/common/modules/ref_ports-and-firewall-requirements.adoc
Remove port 8443 because it is no longer used by any services on the Project Server itself, even for establishing an incoming connection. Use the 443 port instead for Content Host Registration as the features are still functional over the same port.
https://bugzilla.redhat.com/show_bug.cgi?id=2166014
> Move Content Host Registration port from 8443 to 443

- guides/doc-Planning_for_Project/topics/Configuration_Management_Support.adoc
Update a table of architectures for which RH provides Puppet agent. (According to Ohsnap)
> Fix Puppet agent supported architectures (Satellite)

- guides/doc-Planning_for_Project/topics/Introduction.adoc
Moving a Note where it belongs.
It was under Supported Client Architectures, but it's about Supported Usage (of Satellite components).
> Move Note to supported usage (Satellite)

- guides/common/modules/proc_installing-puppet-agent-during-host-provisioning.adoc
Puppet agent can be configured for non-integrated setup during Provisioning as well.
> Add Puppet params for non-integrated setup

- guides/common/assembly_managing-alternate-content-sources.adoc
- guides/common/modules/con_managing-alternate-content-sources.adoc
- guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
- guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
- guides/common/modules/proc_configuring-simplified-alternate-content-sources.adoc
Since there are three types of ACS, creating separate sections for each of the three. 
- Tweaked the existing concept module for ACS to include a generic introduction and to provide an overview of the three types. 
- Renamed the existing proc module so that it correctly mentions that it only talks about custom type ACS. 
- Added two separate proc modules to talk about RHUI and simplified ACSs.
> Add information about different types of ACS

- guides/common/modules/proc_downloading-the-binary-dvd-images.adoc
While downloading the DVD images of the Project, the Version point does not require mentioning the base operating system. Also, the Architecture point is not required at all. So, it seems that it needs to be removed.
https://bugzilla.redhat.com/show_bug.cgi?id=2178052
> Remove unnecessary points from Binary DVD images

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
In the Updating Disconnected Project section, the second step is to download the debug certificate from a connected Project server, however, instructions for creating the debug certificate are missing. Adding a link to the administering guide section that describes how to create the debug certificate.
> Add link for steps to create certificate

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
> Fix attribute for Administering Guide in the disconnected update section

- guides/common/modules/con_managing-red-hat-subscriptions.adoc
The + can only be used in lists to chain paragraphs.
It rendered as a literal + in here, it looked bad and it's been bugging me.
> Remove list para chainer 3.1

- guides/common/modules/con_registering_hosts.adoc
Subscription model is still kept, but the legacy entitlement-based subscription management is deprecated.
This was confusing.
> Correct wording of deprecation in Registration (Satellite)

- guides/common/modules/proc_cloning_satellite_server.adoc
- guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
With the new upgrade workflow, the maintenance module should be enabled during upgrade and cloning so that the next version Satellite repo is not required for upgrading. Adding a step in the upgrade and cloning guides for enabling the module for versions greater than 3.3 to prevent merge conflict due to changes in the file structure between these versions. BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2143451
> Add step to enable maintenance modules for later versions

- guides/common/modules/proc_resolving-package-dependency-errors.adoc
I didn't check exactly how this goes back, but I think very long.
> Fix typo: resoled -> resolved

- guides/common/attributes.adoc
Now that Foreman 3.6 has been released, 3.4 is end of life.
Should be merged after https://github.com/theforeman/foreman-documentation/pull/2079.
> Declare Foreman 3.4 as unsupported

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
Leapp has been upgraded and does not require reindexing the DB after a leapp upgrade. However, the fix hasn't been published in the upstream leapp yet. Hence adding an ifndef directive for Satellite, as Satellite no longer requires this step.
> Remove the reindex step for Satellite during leapp upgrade

- guides/common/modules/proc_registering-hosts.adoc
The arguments to enable the _Registration_ and _Templates_ plugins require the `true` value, otherwise the installer fails with an error like this: `Parameter foreman-proxy-registration is missing a value on the command line`
* **TODO** a separate PR for 2.5
> Fix a plugins enablement command (Host Registration on SmartProxy)

- guides/common/modules/proc_synchronizing-ansible-collections.adoc
In synchronizing Ansible Collections you should specify the list of collections you want to sync from the endpoint, as well as their versions in the Requirements.yml field. Failing to do so will sync everything from the endpoint.
https://bugzilla.redhat.com/show_bug.cgi?id=2185648
> Specify the list of collections

- guides/common/assembly_importing-content.adoc
- guides/common/modules/proc_changing-the-repository-sets-status-for-a-host-in-project.adoc
- guides/common/modules/proc_changing-the-repository-sets-status-in-project.adoc
New feature for Changing Repository Sets Status
added as a procedure
> Add Repository Sets as a new procedure

- guides/common/assembly_managing-packages.adoc
- guides/common/modules/proc_enabling-and-disabling-repositories-on-hosts.adoc
- guides/common/modules/proc_installing-packages-on-a-host.adoc
- guides/common/modules/proc_removing-packages-from-a-host.adoc
- guides/common/modules/proc_upgrading-packages-on-a-host.adoc
- guides/doc-Managing_Hosts/master.adoc
In the new version of Project, there are changes in the procedures of Installing, Removing and Upgrading the Packages of a Host. The applicable procedures are updated and added important information for end-users while Upgrading the packages.
https://issues.redhat.com/browse/SATDOC-747
https://www.youtube.com/watch?v=ykQFM7aFczY&t=1471s
> Update the procedures in package management

- guides/common/assembly_synchronizing-content-between-servers.adoc
- guides/common/modules/proc_exporting-a-content-view-version-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-a-content-view-version-incrementally-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-a-content-view-version-incrementally.adoc
- guides/common/modules/proc_exporting-a-repository-incrementally-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-the-library-environment-incrementally-in-a-syncable-format.adoc
- guides/common/modules/proc_using-upstream-server-to-sync-content-view-versions.adoc
New procedures were required for incremental exports and have been
created for the Managing Content Guide. This is a pull request taking
over for #2049. 
> Add procedures for incremental exports

- guides/common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc
- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
RH changes an older variant of the product name to "Satellite".
* **TODO** Another PR for 2.5 (Satellite 6.10)
> Rename Smart Management to Satellite

- guides/common/modules/proc_synchronizing-ansible-collections.adoc
At present the link for retrieving the Red Hat Certified Collections Sync URL and API token is broken and throws a 404 error. We have fixed this link by replacing it with an active link. Post PR being merged, the error should not exist anymore.
https://bugzilla.redhat.com/show_bug.cgi?id=2186785
> Fix broken link in Syncing Ansible Collections

- guides/common/modules/ref_system-requirements.adoc
While installing the Proxy, end-users often end-up installing a different version of it than that of the Project. Therefore, it became necessary to add a warning about the version that should not be different in any case. While setting up the Proxy, its version should match the present version of Project.
https://bugzilla.redhat.com/show_bug.cgi?id=2184445
> Add Warning to avoid mismatch in versions

- guides/common/modules/proc_tuning-apache-httpd-child-processes.adoc
- guides/doc-Tuning_Performance/master.adoc
> section for configuring no. of processes that can be launched by Apache httpd

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
With RHEL8, the reposync option "-r" has been replaced by either "--repoid" or "--repo". 
The documentation still shows the "-r" option, valid only for the RHEL7 yum package. 
As the repo IDs are mentioned in the command, replacing "-r" with "--repoid".
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2179018
> Rectify reposync option in the updating section

- guides/common/modules/con_download-policies-overview.adoc
There was no information about a Streamed Download Policy for Capsules so this change was needed to show that particular policy.
> Add Streamed Download Policy

- guides/common/assembly_configuring-external-idm-dns.adoc
With external authetication moved to Installing Server, this link also
in Installing Server now becomes xref.
But there are more issues. The assembly is included in three guides:
Installing Server, Installing Server Disconnected, and Installing Proxy.
Installing Server and Installing Server Disconnected have the same
context for satellite. I am opening a separate issue to deal with this
later. For now, I came up with a net of ifevals that works. It is not a
clean solution but I could not come up with any other.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2188809
> Fix link in installing server

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
The reposync command does not download a majority of the required packages if the foreman-protector plugin is enabled. This results in the disconnected Satellite update failing. Adding the option to disable the plugin so that the reposync command downloads all the necessary packages.
> Add the option to disable foreman-protector plugin

- guides/common/modules/proc_using-ansible-vault-with-project.adoc
`chown :MY_GROUP` is identical to `chgrp MY_GROUP` but there's a small change the users messes up. See also https://unix.stackexchange.com/a/164859
cc @sbernhard
> Use chgrp to adjust file ownership

- guides/common/modules/proc_configuring-the-freeipa-server-to-use-cross-forest-trust.adoc
The current AD attribute value in sssd/cross-forest trust is causing the problem on IDM client. Therefore, it is required to add the correct values and also add the command to verify it.
https://bugzilla.redhat.com/show_bug.cgi?id=2170698
> Add the AD user attributes value

- guides/common/attributes-satellite.adoc
Adding ProjectWebUI* attributes to the Satellite build, otherwise it renders incorrectly as "Foreman".
> Add ProjectWebUI attributes for Satellite build

- guides/common/attributes-satellite.adoc
On Satellite, we call this RHEL web console, not Red Hat web console, as can be seen for example here:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.7_release_notes/index#enhancement_the-web-console
> Fix the Cockpit attribute for Satellite

- guides/common/modules/ref_system-requirements.adoc
We need to add the missing umask of 0022 in the system requirements as it is already part of other older versions.
https://bugzilla.redhat.com/show_bug.cgi?id=2207694
> Add the missing umask

- guides/common/attributes-base.adoc
- guides/common/attributes-orcharhino.adoc
The upstream Team "Foreman developers" value implies plural, while other products use values that imply singular.
I suggest changing the Team for upstream to "Foreman community" to match the singular for cases like _{Team} recommends..._
Furthermore, I suggest using a non-breakable space in "ATIX AG".
> Improve :Team: attribute values

- guides/common/modules/proc_securing-the-dhcp-api.adoc
The package-install macro includes install, so it only needs to have the package name.
Fixes: 450433adfd378578d573b84adbe19b6b71807bfa
> Fix duplicate install command

- guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
If Pulp 2 to Pulp 3 migration fails with error "NoMethodError:
undefined method `link?' for nil:NilClass", there is a KB article on
the customer portal that will show the user how to fix the error. This
link was added to the Pre-Migration checks.
> Add KB article link for error fix

- guides/common/modules/con_how-to-synchronize-content-using-export-and-import.adoc
- guides/common/modules/proc_using-upstream-server-as-a-content-store.adoc
A note was added to show what you can do when you are unable to match upstream and downstream Satellite versions.
> Add note for matching upstream downstream server

- guides/common/modules/con_managing-alternate-content-sources.adoc
ACS that are attached to the internal smart proxy and to smart proxies with multiple org associations, affect all organizations across the Project. Adding a note to convey this information.
> Add a note about ACS and organizations

- guides/common/attributes-base.adoc
- guides/common/modules/ref_customizing-the-registration-templates.adoc
By default, the parameter value is set to false and vice versa for downstream, the mentioning the of parameter type was missing in the documentation. We added it for both, upstream and downstream along with its impact on insight clients and cloud reports at downstream.
https://bugzilla.redhat.com/show_bug.cgi?id=2167389
> Mention parameter type for customizing template

- guides/common/modules/con_managing-alternate-content-sources.adoc
The change merged in https://github.com/theforeman/foreman-documentation/pull/2169 had a small typo. The sentence should read as "Alternate content sources associated with the {ProjectServer}, or with {SmartProxyServers} attached to multiple organizations, will affect all organizations.". Adding the missing "attached" and turning it into a subordinate clause.
> Fix a typo in recently added note for ACS

- guides/common/modules/proc_registering-hosts.adoc
All registration fields except for **Activation Key** are optional.
Adding "Optional" for steps that were previously mentioned as mandatory.
https://bugzilla.redhat.com/show_bug.cgi?id=1992283
> Mark optional steps in Host Registration

- guides/common/assembly_performing-additional-configuration-on-capsule-server.adoc
- guides/common/modules/proc_booting-virtual-machines.adoc
- guides/common/modules/proc_chainbooting-ipxe-from-pxelinux.adoc
- guides/common/modules/proc_configuring-smart-proxy-for-host-registration-and-provisioning.adoc
- guides/common/modules/proc_provisioning-ubuntu-autoinstall-through-smart-proxies.adoc
- guides/common/modules/proc_registering-hosts.adoc
- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
- guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- Adds a module about SmartProxy configuration for registration/provisioning, incl. adding SmartProxy to _trusted proxies_ on ProjectServer
- Adds also a snippet with a prerequisite for the scenario that uses SmartProxy instead of ProjectServer for Registration/Provisioning
- Tries to smoothen it for orcharhino
> Configure SmartProxy for registration and provisioning

- guides/doc-Managing_Security_Compliance/master.adoc
Adds _Providing feedback..._ to _Managing Security Compliance_.
> Add feedback module to guide (Satellite)

- guides/README.md
I followed the procedure to install the tools required for building on RHEL and one of the commands gave me an error. This commit replaces that command with an alternative that worked for me.
The original cmd ('dnf -y groupinstall development-tools') gives this error on RHEL 8.7:
Module or Group 'development-tools' is not available
* [* ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.
> Replaced cmd to install Development Tools on RHEL

- guides/common/modules/ref_redhat-cloud-settings.adoc
At present, there is a mention of Project Cloud Token in the table of Cloud Settings placed in the Appendix section. It is incorrect as per the latest information in the Project WebUI. Also, the purpose of RHC ID is totally different than that of Cloud Token. Additionally, we removed the other two fields that are not present in the WebUI at present and should be removed from the table as well.
https://bugzilla.redhat.com/show_bug.cgi?id=2162925
> Correct the field in Project Cloud Settings table

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
> Fixed typo in proc_configuring-direct-ad-integration-with-gss-proxy.adoc

- guides/common/modules/proc_adding-custom-rpm-repositories.adoc
treeinfo skipping during sync time works the same as srpm skipping, so
it is documented as an option for the user.
> Add line for ignoring treeinfo

- Dockerfile
- Gemfile
- guides/common/Makefile
but it wants a super old sass which doesn't work on modern Ruby
pull in sass directly instead
Fixes: ac63a51ce4d5e9d46112639a5e2f459ae2fdd43d
> don't depend on compass and zurb, we don't use it

- guides/common/assembly_configuring-the-discovery-service.adoc
- guides/common/modules/proc_configuring-the-discovery-service.adoc
- guides/common/modules/proc_implementing-pxe-less-discovery.adoc
This was done on 2.5 in #1572 and it must be done for all newer versions as well.
> Hide Building Discovery Image for Satellite

- guides/common/modules/ref_predefined-roles.adoc
According to https://bugzilla.redhat.com/show_bug.cgi?id=1986664, the Manager role can edit global settings.
> Update Manager Role

- guides/common/modules/ref_examples-ldap-filters.adoc
> Add nested group to example LDAP filters

- guides/common/modules/ref_general-settings-information.adoc
This setting was removed in 3.5/6.13.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2212352
> Remove "show host power status" setting

- guides/common/modules/proc_registering-hosts.adoc
- guides/common/modules/proc_uploading-ostree-content-with-hammer-cli.adoc
> fix foreman devel and osbuild doc links

- guides/common/modules/proc_viewing-the-project-ansible-modules.adoc
by now everyone should have Ansible 2.10+
> always use `ansible-doc -l` to list modules in the collection

- guides/common/modules/con_provisioning-virtual-machines-on-kvm.adoc
This update aims to fix https://bugzilla.redhat.com/show_bug.cgi?id=2193414
The command to adding a user to a group is usermod, not useradd. Also, a root prompt was missing.
@Lennonka This BZ came from your queue, can you please review it? Also, I'd appreciate it if you could point me to the appropriate SME to check the update.
* [ x ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.
* [ x ] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [ x ] Foreman 3.6/Katello 4.8
* [ x ] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ x ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ x ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [ x ] …
> Replace `useradd` with `usermod` in Provisioning

- guides/common/modules/proc_applying-remote-scap-resources-in-a-disconnected-environment.adoc
- guides/common/modules/ref_inclusion-of-remote-scap-resources.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
Follow-up to #2213
"Fetch remote resources" cannot be used in disconnected environments, the remote resources must be downloaded manually and uploaded to hosts.
> Add Remote SCAP resources disconnected

- guides/common/modules/ref_variables-for-generation-of-conversion-data.adoc
In the managing host guide, we fixed the typo in the table of Variables for the Generation of Conversion Data as suggested by the reporter. Also, we took minor changes in the description of the listed variables in the table.
https://bugzilla.redhat.com/show_bug.cgi?id=2208368
> Modify variables and remove CentOS

- guides/common/modules/con_troubleshooting-postgresql.adoc
- guides/common/modules/con_troubleshooting-ruby.adoc
we need to call out the *wrong* versions, not the expected ones
> fix PostgreSQL (12→10) and Ruby (2.7→2.5) versions in troubleshooting

- guides/common/modules/proc_creating-an-activation-key.adoc
This update aims to fix [BZ#2211328](https://bugzilla.redhat.com/show_bug.cgi?id=2211328). 
* I added a decision tree to show different commands depending on whether SCA is or isn't enabled
* I switched the order of steps in the web UI equivalent of this decision tree in the same module (for consistency)
@bangelic I took the BZ from your BZ queue, so I'd appreciate it if you could take a look. I'll also appreciate a hint on who should do the SME review. Thanks!
> Adding a decision tree to proc for creating an activation key

- web/content/css/_asciidoc.scss
I noticed, that the page formatting makes the body/nav/footer overlap a bit, tried to fix this with this PR.
If you want to compensate the individual spacings differently, I can of course change it! (tried to keep it simple and easily distinguishable from where the compensations come)
As this is my 2nd PR I might still be doing something wrong, please just correct me if there is anything 🙂 
> Fix documentation page styling

- guides/common/modules/proc_creating-operating-systems.adoc
It wasn't clear how to import OS from RH CDN, so I added links to _Managing Content_ and did some tweaks around.
https://bugzilla.redhat.com/show_bug.cgi?id=2213394
> Import OS from CDN in Provisioning

- guides/common/modules/proc_synchronizing-ansible-collections.adoc
> [BLOCKER] Fix Ansible link Satellite

- guides/common/assembly_administering-hosts.adoc
- guides/common/assembly_synchronizing-content-between-servers.adoc
- guides/common/modules/proc_enabling-custom-repositories-on-content-hosts.adoc
A new procedure was required to show how to enable custom repositories
on content hosts using the specified web UI. This
procedure gives the
user the steps to enable any and all custom
repositories on content
hosts using the specified web UI.
> Add procedure for enabling custom repos

- guides/common/modules/con_backing-up-server-and-proxy.adoc
- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
The clone tool is meant for creating test instances for upgrades or migration to reduce any risk and possible downtime. However, some users use these tools to deploy new instances from existing ones. These instances might not be stable leading to failures after deployment. Adding a note to make the users aware of the use cases for these tools so that these are used as intended.
Bug link:
https://bugzilla.redhat.com/show_bug.cgi?id=2106222
> Add a note about usecases for the clone and backup tools for 3.1

- guides/common/modules/ref_troubleshooting-sync-errors.adoc
- guides/doc-Installing_Server/master.adoc
The purpose to split this file is downstream inclusion. Also, there were more than one heading per file which not a standard modularization practise. In addition to this, it will help reviewing the diff files more conveniently. Therefore, it became necessary to split this file, addressing many purposes.
> Split troubleshooting file 3.2

- guides/common/modules/proc_cloning_satellite_server.adoc
This update aims to fix [BZ#2178929](https://bugzilla.redhat.com/show_bug.cgi?id=2178929). I rephrased a step in a procedure to clone a server as suggested in the BZ.
@AkshayGadhaveRH I took the BZ from your queue, can you please review this PR?
> Reword cloning process overview (goferd has been deprecated)

- guides/common/modules/proc_enabling-and-disabling-repositories-on-activation-key.adoc
The procedure for enabling and disabling repositories on activation
keys was updated to reflect the simplification
for enabling and
disabling repositories.
> Update procedure for repos on AK

- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
This update attempts to address the following two BZs in the Overview, Concepts, and Deployment Considerations guide:
* https://bugzilla.redhat.com/show_bug.cgi?id=2216185 -- Removing a link to a very outdated pdf document in Red Hat Knowledgebase
* https://bugzilla.redhat.com/show_bug.cgi?id=2216192 -- Switching the order of two chapters on deploying the project
> Deployment guide ddf tweaks

- guides/common/modules/proc_executing-a-remote-job.adoc
This update aims to document the enhancement in [BZ#2203183](https://bugzilla.redhat.com/show_bug.cgi?id=2203183).
The buttons in the form for running jobs on hosts have been changed, as described [in the Foreman community](https://github.com/theforeman/foreman_remote_execution/pull/794).
> Rerun buttons

- guides/common/assembly_introduction-to-provisioning.adoc
- guides/common/modules/proc_creating-compute-profiles.adoc
- guides/common/modules/ref_supported-cloud-providers.adoc
- guides/common/modules/ref_supported-virtualization-infrastructure.adoc
Compute profiles are supported only for a certain compute resources in Satellite. **Should I add any other for Foreman/orcharhino?**
This info is not version specific.
https://bugzilla.redhat.com/show_bug.cgi?id=2172243
> Providers that can use compute profiles in Provisioning

- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
This is a follow-up on [PR#22761](https://github.com/theforeman/foreman-documentation/pull/2271). That PR removed a link to a pdf document in Red Hat Knowledgebase, but only from version 3.7. After taking a closer look at that pdf document, I realized it needs to be removed from the previous versions as well.
In this PR, I cherry-picked the commit accepted in PR#2276 and added it to branch 3.6. The commit also needs to be included in the branches for lower versions, as indicated in the checklist below.
> Remove reference to an outdated document

- guides/common/attributes-satellite.adoc
This update aims to fix [BZ#2192817](https://bugzilla.redhat.com/show_bug.cgi?id=2192817). 
"Container-native Virtualization" is now called "OpenShift Virtualization". This pull request updates the corresponding attribute in attributes-satellite.adoc.
> Update :KubeVirt: to OpenShift Virtualization

- guides/common/modules/ref_host-specific-variables.adoc
Deprecated since [Foreman 2.5](https://www.theforeman.org/manuals/2.5/index.html#Deprecations).
> Deprecate Puppet host macros

- guides/common/modules/proc_importing-syncable-exports.adoc
This PR addresses [BZ#2208315](https://bugzilla.redhat.com/show_bug.cgi?id=2208315). There is a mistake in a `hammer content-import` command that needs fixing.
> Fix 'hammer content-import' command

- guides/common/modules/proc_configuring-capsule-default-certificate.adoc
[BZ#2213065](https://bugzilla.redhat.com/show_bug.cgi?id=2213065) reports that an example cert file is referenced inconsistently within a single procedure. This PR attempts to fix that.
> Fix inconsistent capsule_cert example

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
When performing an in-place upgrade of the base OS from RHEL 7 to RHEL 8, it is important to unset the subscription-manager release at the end. Earlier this step was a part of the RHEL in-place upgrade docs, however this was removed in the later versions. Hence, mentioning this explicitly as a separate step.
Link to BZ comment: https://bugzilla.redhat.com/show_bug.cgi?id=2164027#c9
> Add a step to unset the subscription-manager release

- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
Currently the LB guide points to the Upgrading guide to upgrade smart proxies with LB setup. However, the commands for regenerating certificates for smart proxies with an LB setup, require an additional "--foreman-proxy-cname", which points to the load balancer, to be provided. Splitting each of the command into two substeps.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2143785
> Add commands to regenerate certificates for smart proxies with LB setup

- guides/common/modules/proc_enabling-capsule-in-UI.adoc
[BZ#2086843](https://bugzilla.redhat.com/show_bug.cgi?id=2086843) describes a problem customers are facing in (rare) setups where a Smart Proxy is added to the same location as a server with an embedded proxy.
This PR aims to address the problem by adding a note to the procedure for adding a Smart Proxy to a location.
> Note about capsule and embedded capsule in the same location

- guides/common/assembly_administering-hosts.adoc
- guides/common/modules/proc_creating-snapshots-of-a-managed-host.adoc
- guides/common/modules/proc_installing-the-snapshot-management-plugin.adoc
See https://github.com/theforeman/foreman-installer/blob/3.5-stable/config/katello-answers.yaml#L74 & https://github.com/ATIX-AG/foreman_snapshot_management/pull/87
```
--[no-]enable-foreman-plugin-snapshot-management                             Enable 'foreman_plugin_snapshot_management' puppet module (default: false)
```
> Add procedure to install foreman_snapshot_management

- guides/common/modules/proc_installing-postgresql.adoc
Pulpcore migration is failing on Project on the remote database. Upon troubleshooting, we found that the `postgresql-contrib` package was missing and should be installed along with PostgreSQL. Therefore, we added it alongside the pgsql installation command as it was already mentioned on the older docs of Katello. This will resolve the issue of installing the Project on the external databases.
https://bugzilla.redhat.com/show_bug.cgi?id=2216745
> Add postgresql-contrib package for ExternalDB

- guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
The older link redirects to the page Project Subscription Management page which is incorrect. The correct link is replaced.
https://bugzilla.redhat.com/show_bug.cgi?id=2208440
> Fix a link to Subscription Manifest

- README.md
I came across a peer review guide used internally at Red Hat, but available externally as well, and thought it could make a nice addition to README. It's been around for years, and as far as I can see, the things it recommends are aligned with Foreman docs conventions.
I imagine it could serve as a heads-up to any potential contributor from outside the regular writing team that they might want to expect wording and structure of their contributions to change before merging. In addition, I also simply consider this to be a good peer-review resource to keep at hand.
However, I don't feel particularly emotionally attached to this PR, so feel free to discard it if you disagree. I would be totally okay with that.
* For Foreman 3.0 or older, please create a …
> Add link to peer review guide to readme

- guides/common/assembly_restricting-hosts-access-to-content.adoc
- guides/common/modules/con_restricting-hosts-access-to-content.adoc
- guides/doc-Managing_Content/master.adoc
Previously, custom products were enabled by default. Now, they're going
to be disabled by default. A new concept module and assembly was
required to show the user strategies to restrict hosts access to
content.
> New assembly for restricting hosts content access

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
Keytab locations in steps 5 and 6 do not match, resulting in the right key to reside in a keytab that is not the one used by gssproxy, thus rendering kerberos auth with gssproxy permanently unsuccessful on Project.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2083336
> Fix keytab location

- guides/common/assembly_configuring-host-collections.adoc
- guides/common/modules/proc_generating-a-report-for-installable-and-applicable-errata.adoc
A new procedure was required to show the user how they can generate a
report for both Installable and Applicable errata.
> Add procedure for Installable Applicable Errata

- guides/common/modules/proc_configuring-remote-execution-for-pull-client-smart-proxy.adoc
- guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
- guides/common/modules/proc_enabling-connections-to-capsule.adoc
Using services is easier to read for users and a smaller chance of typos in port numbers. It also can enable helpers if needed.
It doesn't use the foreman-proxy for content proxies, since it runs on a non-standard port.
Currently untested, but here to start the discussion if this is something we want. From there on I also want to investigate what we open by default. For example, opening the DNS/DHCP/TFTP ports if we don't enable those services by default is redundant. Should we open them only if we tell users to enable the service, like we do with MQTT?
> Use FirewallD services where possible

- guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc
- guides/common/modules/proc_monitoring-puppet.adoc
Requested by RH QA. **Satellite only**
> Add note about enabled Puppet in Satellite (Admin)

- guides/common/modules/proc_creating-a-compliance-policy.adoc
The step was missing.
The button is labeled "New Policy" when no policies are present yet, and "New Compliance Policy" when there are policies already added.
> Add step to click the New Policy button

- guides/common/modules/proc_registering-hosts.adoc
There has been a recent change in Satellite 6.14,
where if you navigate
to Satellite WebUI -> Hosts -> Register Host, the
"Activation Keys" has
been moved to the "General" tab. In Satellite 6.13 and previous
Satellite versions, the "Activation Keys" option was present in the
"Advanced" tab which is now moved to the "Basic" tab. As a result,
point 18 should be moved up along with other options present for the
"General" tab.
> Move Activation Key point from no. 18 to no. 7

- guides/common/modules/proc_configuring-repositories.adoc
[BZ#2223197](https://bugzilla.redhat.com/show_bug.cgi?id=2223197) reports an unnecessary lead-in paragraph.
I updated the ifdef directive not to include satellite, so that the lead-in paragraph doesn't appear in the Satellite version of the guide.
> Tweak ifdef not to display a lead-in list for Satellite

- guides/common/modules/proc_configuring-repositories.adoc
[BZ#2223048](https://bugzilla.redhat.com/show_bug.cgi?id=2223048) reports an obsolete Note admonition. This PR removes that admonition.
> Remove an obsolete note

- guides/common/assembly_renewing-custom-ssl-certificate.adoc
- guides/common/modules/con_renewing-the-custom-ssl-certificate.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-server.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
- guides/doc-Administering_Project/master.adoc
Earlier, the process of renewing the Custom SSL certificate was not documented. Due to this, the end-users faced issues in the renewal process and end-up with errors. By documenting this process, the end-users can now carry out renewal by following the mentioned procedures for both, Project and Proxy Server.
https://bugzilla.redhat.com/show_bug.cgi?id=1802294
> Add the Custom SSL certificate renewal process

- .github/PULL_REQUEST_TEMPLATE.md
Let's not anymore :)
@mdolezel Can you confirm that we will not require modifications to Satellite 6.10 anymore?
@maximiliankolb Can you confirm that orcharhino will not require modifications to older branches?
> Not accepting PRs to Foreman older than 3.1 (PR template)

- guides/doc-Upgrading_Project/topics/proc_upgrading-a-disconnected-project-server.adoc
Some of the information listed in the disconnected upgrade procedure is outdated and needs to be removed. The below lines in the procedure are no longer required:
- Stopping the services: This was required as {foreman-maintain} had some difficulties with disconnected upgrades. However, this is now irrelevant and actually causes the upgrade_check to fail as services are no longer running.
- Running the `foreman-rake katello:upgrade_check` script manually: The explanation what "foreman-rake katello:upgrade_check" does is wrong and shouldn't be needed, as this check is now part of `foreman-maintain`.
- "Make sure all external Capsule Servers are assigned to an organization, otherwise they might get unregistered due to host-unification changes."; This was removed in BZ#1490043 - …
> Remove outdated information from the disconnected upgrade section

- guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
- guides/doc-Upgrading_Project/topics/proc_upgrading-a-disconnected-project-server.adoc
When creating a snapshot, stopping the services before taking the snapshot and then starting them after, is a good idea. Adding information about this in the upgrade guide.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2175369
> Add information about stopping and starting services

- guides/common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc
[BZ#2226802](https://bugzilla.redhat.com/show_bug.cgi?id=2226802) reports a broken xref link in Managing Content on the Red Hat Customer Portal: [Attaching Red Hat Subscriptions to Content Hosts](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13/html/managing_content/managing_red_hat_subscriptions_content-management#Attaching_Red_Hat_Subscriptions_to_Content_Hosts_content-management).
This PR addresses the problem by adding an empty line between two xrefs. It resolved the issue in my local downstream build.
(For the record, the [upstream version](https://docs.theforeman.org/3.7/Managing_Content/index-katello.html#Attaching_Red_Hat_Subscriptions_to_Content_Hosts_content-management) shows the xref as expected.)
* For Foreman 3.0 or …
> Adding an empty line as a workaround for a rendering issue downstream

- guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
[BZ#2185051](https://bugzilla.redhat.com/show_bug.cgi?id=2185051) requests specifying that using Samba is required to be able to create an HTTP keytab later in the process.
> Add a note about using Samba to join AD realm

- guides/common/modules/proc_synchronizing-all-repositories-in-an-organization.adoc
The current argument "awk -F, {'print $1'}" is working but it is recommended to use "--fields Id" to utilize the capability of Hammer completely. Hence, it is recommended to use the latter one.
https://bugzilla.redhat.com/show_bug.cgi?id=2226805
> Use --fields while syncing repos in organization

- guides/common/modules/ref_predefined-roles.adoc
Neither asciidoctor nor Antora handle footnotes in tables very well. Also, the information in the footnote is very easy to miss like this.
With this PR, the information from the footnote precedes the table, thus providing an introduction to the contents of the table.
I also took the liberty of tweaking the wording of the footnote a little, so that the whole section consistently uses the terminology "permissions granted" or "permissions provided" instead of "set of allowed actions".
> Rewrite footnote into table introduction

- guides/common/modules/proc_creating-a-host-group.adoc
- guides/common/modules/proc_registering-a-host-using-the-bootstrap-script.adoc
Back in the Pulp 2 days this was needed for Katello, but since Pulp 3 (so Katello 4) it's no longer a thing.
I still doubt these instructions. You can also go to the Foreman UI and create a new environment if needed. However, for now this is already an improvement.
> Drop chown apache instruction for Puppet environments

- guides/common/modules/con_using-extended-cron-lines.adoc
> Drop extra backtick from extended cronlines

- guides/common/attributes-base.adoc
- guides/common/attributes-foreman-deb.adoc
- guides/common/modules/con_configuring-external-authentication.adoc
- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
- guides/common/modules/ref_system-requirements.adoc
- guides/doc-Planning_for_Project/topics/Required_Technical_Users.adoc
This differs between Debian and Red Hat. By using an attribute we can make it consistent and easy to maintain.
This skips 2 instances because they should be removed by https://github.com/theforeman/foreman-documentation/pull/2343.
> Consistently use the correct Apache user

- guides/common/modules/proc_configuring-project-settings-for-keycloak-authentication-using-the-web-ui.adoc
When configuring settings for keycloak authentication, one does not create a new LDAP auth source. Instead, one only assigns locations and organizations to already created auth source on the external card.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2192360
> Clarify configuring settings for keycloak

- guides/common/modules/proc_creating-a-job-template.adoc
> Add Enable Ansible Callback in job template in Satellite 6.13 on 3.5

- guides/common/attributes-foreman-deb.adoc
- guides/common/attributes-foreman-el.adoc
- guides/common/modules/snip_guide-not-ready.adoc
- guides/doc-Administering_Project/master.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Deploying_Hosts_AppCentric/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Managing_Organizations_and_Locations/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Quickstart/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Upgrading_Project/master.adoc
Some guides aren't usable in some flavors. They aren't linked in the navigation, but this also makes sure the files don't have any content. That makes diffs smaller, which makes reviewing easier.
<del>Right now this is just a proof of concept and I haven't gone through all the guides.</del>
> Hide guides which aren't ready for consumption

- guides/common/modules/ref_system-requirements.adoc
The end-users must have the manifest in their customer portal account and the repo enabled and synced as it is the prerequisite to install the Project Server. When the Satellite was utilized as a proof-of-concept in a production environment, the capsule installation failed from their side. It was later discovered that the end-user didn't have a manifest in its customer portal account along with the mentioned repo being enabled. Hence, the added information in this PR can be accommodated in the system requirement section to bring a better installation experience.
https://bugzilla.redhat.com/show_bug.cgi?id=2211939
> Add manifest & repo details in system requirements

- guides/common/attributes.adoc
> mark 3.5 as unsupported

- guides/common/attributes.adoc
> mark 3.7 as stable

- guides/common/attributes.adoc
> mark 3.0 as unsupported

- guides/common/attributes.adoc
> mark 3.3 as unsupported

- guides/common/attributes.adoc
> mark 3.6 as stable

- guides/common/modules/proc_restoring-from-incremental-backups.adoc
There is no other procedure for creating a backup of the project, the `-i` argument should be removed from commands. Additionally, it applies to the sentence related to the same just below.
https://bugzilla.redhat.com/show_bug.cgi?id=2230825
> Remove -i argument in restoring backup of project

- guides/common/attributes-foreman-deb.adoc
- guides/common/attributes-foreman-el.adoc
- guides/common/attributes-katello.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
This introduces an install-os attribute to make it easy to share the document titles.
It also drops "external" from InstallingSmartProxyDocTitle in vanilla Foreman. This is because Foreman doesn't have a concept of "internal" Smart Proxy. In Katello you could argue there is, because you need some primary Pulp installation but with vanilla Foreman that terminology has never been used.
I'm not sure how much this should be cherry picked.
> Align upstream document titles

- guides/common/modules/con_registering_hosts.adoc
RHEL 6 is EOL and requires Extended Life Support. [BZ#2214813](https://bugzilla.redhat.com/show_bug.cgi?id=2214813)
RHEL 7 has to be at least 7.2 to work. [BZ#2188220](https://bugzilla.redhat.com/show_bug.cgi?id=2188220)
> Update supported OSs in Host Registration (Satellite only)

- .github/workflows/deploy.yml
check-html fails quite often, either because a link is temporarily not available or because the linkchecker tool is unstable.
having this block the actual publishing is wrong. we will see the "the link is bad" during PR phase, and if we decide to ignore it (for whatever) reason, we still should be able to publish.
> don't require check-html for publishing

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
- guides/doc-Upgrading_Project/topics/con_upgrading-prerequisites.adoc
Working on Release Notes in Satellite, I discovered that the attributes could use some tweaks.
This change just beautifies attribute names and shouldn't affect any upstream content.
> Improve RN doc attributes (mainly Satellite)

- .github/workflows/deploy.yml
that way pushes to the release branches won't show up as failed when check-html would have failed
> don't run check-html on pushes, only on PRs

- guides/common/modules/proc_configuring-capsule-default-certificate.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
By enabling the puppet server, you no longer need to have the command. At the runtime installation, this option is not observed because it has been deprecated.
https://bugzilla.redhat.com/show_bug.cgi?id=2211155
> Remove puppet-server-foreman-url

- guides/common/modules/con_composite-content-views-overview.adoc
- guides/common/modules/proc_importing-container-images.adoc
Added that Docker repositories are only applicable to the Repository
Restrictions paragraph. Changed "docker" to "Docker" in Importing
Container Images for consistency.
> Update repository restrictions

- guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
This setting is required and it needs to be done on the project server, not on the client.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2217895
> Move note into previous procedure

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
Missing brackets caused admonition to not render properly.
> Correctly format admonition in procedure

- guides/common/attributes-foreman-deb.adoc
- guides/common/attributes-foreman-el.adoc
- guides/common/modules/snip_guide-not-ready.adoc
- guides/doc-Administering_Project/master.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Deploying_Hosts_AppCentric/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Managing_Configurations_Ansible/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Managing_Organizations_and_Locations/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Quickstart/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Upgrading_and_Updating/master.adoc
This pick includes the Satellite feedback commit because it solves a lot of merge conflicts. Shouldn't affect anything since 3.6 is not used in downstream, but it made my life easier.
> [3.6] Hide guides which aren't ready for consumption

- guides/common/modules/con_backing-up-server-and-proxy.adoc
- guides/common/modules/snip_backup-usecase-note.adoc
- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/2296. Pushing separate PR due to a merge conflict for 3.4.
The clone tool is meant for creating test instances for upgrades or migration to reduce any risk and possible downtime. However, some users use these tools to deploy new instances from existing ones. These instances might not be stable leading to failures after deployment. Adding a note to make the users aware of the use cases for these tools so that these are used as intended.
> Add a note about usecases for the clone and backup tools for 3.4

- guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
Foreman requires an absolute path for local file repos on Foreman Server.
> Fix local file repo path

- guides/common/modules/proc_adding-kubevirt-connection.adoc
Claryfying what kind of value is required.
https://bugzilla.redhat.com/show_bug.cgi?id=2134096
> Clarify kubevirt hostname

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
As a part of the post-upgrade tasks after LEAPP upgrade from EL7 to EL8, some dnf commands are required to be executed on the system. However, since `foreman-maintain` locks packages, these commands fail. Adding steps to unlock and lock packages during the post-upgrade tasks.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2223931
> Add steps to unlock and lock packages

- guides/common/modules/proc_adding-openstack-connection.adoc
Originally, an update to a single step was requested, but the whole procedure required a refresh, because it was outdated in comparison to the UIs.
https://bugzilla.redhat.com/show_bug.cgi?id=1846066
> Update CR OpenStack procedure to match UI

- guides/doc-Upgrading_Project/topics/con_upgrade-paths.adoc
This line doesn't add anything. If anything, the description should be a link.
I do wonder if we should instead do the effort of making sure we can make it a link.
> Remove useless line about previous upgrade docs

- guides/common/attributes-titles.adoc
This is useful if you have multiple tabs open or link to it from something like Discourse.
I'm only selecting the support stable releases, but I wonder if we should pick it to all branches.
> Reflect the upgrade target in upgrading title

- guides/common/modules/ref_predefined-roles-available-in-project.adoc
In a recently merged PR, I misspelled the {ProjectWebUI} attribute. This PR addresses that error.
> Fix case in an instance of {ProjectWebUI}

- guides/common/modules/con_backing-up-server-and-proxy.adoc
Fixes: 03eff2adeaf8 ("Add a note about usecases for the clone and backup (#2296)")
> Remove spurious plus

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/foreman-3.6.2.adoc
> Update Foreman 3.6.2 Release Notes

- guides/doc-Managing_Content/master.adoc
As discussed on Monday: Improve https://docs.theforeman.org/3.7/Managing_Content/index-foreman-deb.html
> Show hint that you cannot manage content with Katello when using Foreman on Debian

- web/content/js/versions.js
- web/content/release-3.8.adoc
Various guides are hidden because they're not ready. These should not show up in the navigation.
Fixes: ddba2d718d91ade9bdfd3375f875cc883993449a ("Branch Foreman 3.8")
> Correct Foreman 3.8 navigation

- guides/common/modules/con_synchronizing-content-between-servers.adoc
There were no  instructions on how to change the export path so it was
suggested to include those instructions from the KB article at
https://access.redhat.com/solutions/7013903
> Add link to KB article for changing export path

- guides/common/modules/ref_predefined-roles.adoc
A follow-up on https://github.com/theforeman/foreman-documentation/pull/2346. While that PR introduced significant rewrites so it's more appropriate to introduce it for future versions only, improving a single description was requested for previous versions as well.
This PR proposes to backport the description for the predefined role of Organization admin to previous versions.
> Update description for Organization admin role

- guides/common/modules/proc_adding-an-amazon-ec2-connection-to-server.adoc
[BZ#2196328](https://bugzilla.redhat.com/show_bug.cgi?id=2196328) requests specifying the permissions required for a user to configure an AWS EC2 compute resource. This PR adds a prerequisite to the procedure.
> Document permissions required to provision Amazon EC2

- guides/doc-Updating_Project/master.adoc
- web/content/release-3.7.adoc
- web/content/release-3.8.adoc
- web/content/release-nightly.adoc
The updating procedure relies on code that's not implemented for upstream installations. By hiding it we can't confuse users with something that doesn't work.
It also reflects the correct links to the new upgrading guide.
This should replace https://github.com/theforeman/foreman-documentation/pull/2374.
This first commit should be picked into 3.8 & 3.7 because the changes were only made in those branches. The web changes in the second commit don't really matter.
> Hide updating guide upstream & correct links to upgrading guide

- guides/common/modules/proc_renaming-smart-proxy.adoc
Using the Shortname instead of FQDN for Proxy throws the error: `new-proxy is not a valid fully qualified domain name. Please use a valid FQDN and try again. No changes have been made to your system.`
https://bugzilla.redhat.com/show_bug.cgi?id=2215750
> Replace Proxy shortname with FQDN while renaming

- guides/common/assembly_preparing-environment-for-capsule-installation.adoc
- guides/common/assembly_preparing-environment-for-installation.adoc
- guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
- guides/common/modules/proc_enabling-connections-to-capsule.adoc
- guides/common/modules/snip_verify-firewall-settings.adoc
This should be the verification step in the Enabling Connections section for Project Server and Smart Proxy. Reading it as a separate section is irrelevant.
> Remove unnecessary section

- guides/common/modules/con_mirroring-policies-overview.adoc
A warning has been added for republishing metadata for repositories
with Complete Mirroring because the risk is too great and causes issues.
> Add warning republishing metadata and mirroring

- guides/common/modules/con_converting-a-host-to-rhel.adoc
> Remove Centos Linux 8

- guides/common/modules/proc_updating-disconnected-server.adoc
When using the `dnf reposync` command there's no need to install yum-utils. That's only needed when using the `reposync` command.
Fixes: ec4aea364e2d ("Split Updating Guide")
> Remove a redundant yum-utils installation

- guides/common/attributes-base.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
Do not use attributes such as "smart-proxy-context" because the name depends on the service, not a branded product.
Resolves https://github.com/theforeman/foreman-documentation/issues/2172
ping @lessfoobar
> Fix Smart Proxy DNS setting

- guides/common/assembly_monitoring-hosts-using-red-hat-insights.adoc
- guides/common/modules/proc_installing-red-hat-cloud-plug-in.adoc
I assume this plug-in is installed on Satellite by default.
For the second commit: I could not find the role on plain Foreman 3.7 and orcharhino. Can you confirm that it's part of the "Foreman Satellite plugin"? Or does it come from another plugin?
> Install Red Hat Insights plugin

- guides/common/modules/proc_importing-a-repository.adoc
We are performing steps for importing a repository, not a Library.
> Replace Library with repository

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/foreman-3.8.0.adoc
- guides/doc-Release_Notes/topics/foreman-contributors.adoc
Replaces https://github.com/theforeman/foreman-documentation/pull/2422 since @Griffin-Sullivan is on PTO and this allows the formal announcement to proceed.
> Add release notes for Foreman 3.8

- guides/common/modules/proc_enabling-puppet.adoc
Fixes: dd093af738ce ("Refs #35985 - Update Puppet enablement options")
This is only submitted against 3.7 because nightly and 3.8 need another fix.
> Correct multi line escaping

- .github/workflows/deploy.yml
- Dockerfile
- Gemfile
- README.md
- guides/Makefile
- guides/README.md
- guides/common/Makefile
As discussed earlier: we do not publish PDF documents in upstream or downstream, so we can stop building them to speed up GHA and save resources.
> Do not build PDF documents

- guides/common/modules/con_managing-content-views.adoc
In an earlier version of documentation, this opening sentence was
confusing. It has been rewritten to be clearer for all doc versions.
> Clarify opening sentence

- guides/common/modules/con_composite-content-views-overview.adoc
The original statement was incorrect. Docker
repositories will report
an error, not container repositories.
> Change container repo to docker repo

- web/content/index.adoc
Fixes: ddba2d718d91 ("Branch Foreman 3.8")
> Do not list Foreman 3.8 as a supported release

- guides/common/assembly_troubleshoot-dnf-modules.adoc
- guides/common/modules/con_troubleshooting-dnf-modules.adoc
- guides/common/modules/con_troubleshooting-postgresql.adoc
- guides/common/modules/con_troubleshooting-ruby.adoc
- guides/common/modules/proc_configuring-repositories-proxy.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
Project needs ruby:2.7 and postgresql:12 modules to work\get installed. If end-users proceed with enabling present el8 module in installing project and proxy, it will pop-up a huge warning related to conflict with ruby:2.5 and postgresql:10 modules. In the end, the command does enable the ruby:2.7 and postgresql:12 but the list of warnings itself is not a healthy status of the output and this occurrence should be prevented. However, in the document, these warnings are mentioned as expected and can be ignored but it should not be the standard practice of user experience. Hence, this warning can be easily avoided by enabling the required dependent modules along with the actual module.
https://bugzilla.redhat.com/show_bug.cgi?id=2126884
* For Foreman 3.0 …
> Add troubleshooting for ruby & pgsql

- guides/common/modules/snip_host-registration-steps.adoc
You must select which activation key(s) to use in the web UI before you
click Generate. This step was necessary to add.
> Add step for selecting activation keys

- guides/doc-Release_Notes/topics/foreman-3.8.0.adoc
> Update Foreman 3.8.0 release notes for RC2

- guides/common/modules/con_managing-red-hat-subscriptions.adoc
- guides/common/modules/proc_adding-red-hat-subscriptions-to-subscription-allocations.adoc
- guides/common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc
- guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
- guides/common/modules/proc_locating-a-red-hat-subscription.adoc
- guides/common/modules/proc_removing-red-hat-subscriptions-and-subscription-allocations.adoc
In all instances of subscription manifest, it is
capitalized and should
not be outside of section titles. All mentions
otherwise have been
changed to lower case.
Jira ticket-SAT-19849
https://issues.redhat.com/browse/SAT-19849
> Replace Subscription Manifest to lower case

- guides/common/modules/proc_configuring-logging-to-journal-or-file-based-logging.adoc
Since Foreman 3.8 the logging layout is automatically derived from the logging type. This means the `--foreman-logging-layout` parameter is no longer needed.
> Refs #36582 - Remove --foreman-logging-layout parameter

- guides/common/modules/ref_ports-and-firewall-requirements.adoc
[BZ#2233266](https://bugzilla.redhat.com/show_bug.cgi?id=2233266) reports confusion over Satellite outgoing communication returning back to Satellite. To address this issue, I want to add an explanation of this behavior.
Side note: I'm not very happy about fixing this problem by just slapping an admonition onto the section, but this part of the document is scheduled for a thorough editorial review in the upcoming weeks. So any readability issues that might also be contributing to users' confusion over the content will be fixed soon.
> Explain why outgoing traffic returns to Project

- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
Per [BZ#2236881](https://bugzilla.redhat.com/show_bug.cgi?id=2236881), the command to deploy a certificate on SmartProxy includes obsolete options. This PR updates the command.
> Update cmd to deploy a certificate on SmartProxy

- guides/common/modules/con_transport-modes-for-remote-execution.adoc
Satellite publishing tool has issues with 2 xrefs on the same line. For correct rendering, there needs to be only one xref per line.
> Fix xref rendering for Satellite

- guides/common/modules/snip_warning-maintain-config-noop.adoc
> noop option is in the installer, not maintain tool

- guides/common/modules/proc_registering-a-host.adoc
If Project is behind an HTTP proxy, configure the SubMan to connect through the proxy.
> Configure SubMan to connect via HTTP proxy for registration

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
Request to mention SmartProxy URLs if the user wants to provision through SmartProxy.
I've attempted a couple more minor formal improvements and stumbled on a problem...
> Improve VMware cloud-init/userdata section

- guides/common/modules/con_host-substatus-overview.adoc
- guides/common/modules/proc_executing-a-restorecon-template-on-multiple-hosts.adoc
- guides/common/modules/ref_example-restorecon-template.adoc
I believe that the host sub-status page is no longer accurate but I'd like to not add this to the scope for now. See https://github.com/theforeman/foreman-documentation/issues/2459
> Fix capitalization and mask for REX for restorecon example template

- guides/common/modules/proc_upgrading-hosts-to-next-major-rhel-release.adoc
The web UI no longer shows the Submit button at this point in the procedure. There are multiple options to finish running the job.
In this PR, I propose wording that avoids describing specific buttons. (The buttons themselves are described in the web UI through floating tooltips.)
> Update preupgrade leapp procedure to the new version of the job form

- guides/common/modules/con_unattended-use-customization-and-image-remastering.adoc
> Complete list of FDI kernel options

- guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
- guides/common/modules/proc_altering-the-privilege-elevation-method.adoc
dzdo (sudo alternative) was failing for Ansible jobs, because the required plugin isn't available in ansible-core that is [available for Project since 3.3](https://docs.theforeman.org/3.3/Upgrading_and_Updating/index-satellite.html#migrating-ansible-content_upgrade-guide)
> Alternate the method to elevate user privilege in REX

- guides/doc-Upgrading_Project/topics/proc_upgrading-a-disconnected-project-server.adoc
We are clearly mentioning the filename of repo in the procedure to modify but in its codeblock, the name is not matching.
> Fix typo in repo name

- guides/doc-Administering_Project/docinfo.xml
- guides/doc-Configuring_Load_Balancer/docinfo.xml
- guides/doc-Deploying_Project_on_AWS/docinfo.xml
- guides/doc-Installing_Proxy/docinfo.xml
- guides/doc-Installing_Server/docinfo.xml
- guides/doc-Installing_Server_Disconnected/docinfo.xml
- guides/doc-Managing_Configurations_Ansible/docinfo.xml
- guides/doc-Managing_Configurations_Puppet/docinfo.xml
- guides/doc-Managing_Content/docinfo.xml
- guides/doc-Managing_Hosts/docinfo.xml
- guides/doc-Managing_Security_Compliance/docinfo.xml
- guides/doc-Planning_for_Project/docinfo.xml
- guides/doc-Provisioning_Hosts/docinfo.xml
- guides/doc-Tuning_Performance/docinfo.xml
- guides/doc-Updating_Project/docinfo.xml
- guides/doc-Upgrading_Project/docinfo.xml
Improving the guide descriptions in `docinfo.xml` that appear on the Satellite product documentation splash page.
> Improve guide Subtitles in Satellite

- guides/common/modules/proc_updating-disconnected-server.adoc
[BZ#2238788](https://bugzilla.redhat.com/show_bug.cgi?id=2238788) reports a user was confused about how to name a file in the procedure for updating a disconnected server. This PR adds more details on that.
Because of the structural changes for the Updating guide, I'm only submitted this PR against 3.7 and later. After the wording gets acked, I will follow up with a PR for versions 3.6 and previous.
> Be more specific about creating a yum config file

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
[BZ#2236724](https://bugzilla.redhat.com/show_bug.cgi?id=2236724) asks to narrow down the list of required perl packages installed during vmware cloud-init provisioning. The goal is to keep the list of dependencies installed to a minimum.
> Narrow down the required perl packages

- guides/common/modules/con_managing-container-images.adoc
The initial DDF thought the first link for RHEL Atomic Host 7 was
invalid but it does work. Two newer links for RHEL 8 and RHEL 9 have
been added for users running RHEL 8 or RHEL 9 on their system.
> Add links in Managing Container Images

- guides/common/modules/ref_ports-and-firewall-requirements.adoc
[BZ#2233263](https://bugzilla.redhat.com/show_bug.cgi?id=2233263) and [BZ#2233264](https://bugzilla.redhat.com/show_bug.cgi?id=2233264) request adding links to Red Hat Customer Portal.
> Add RH CP links to resources for outgoing traffic

- guides/doc-Release_Notes/redmine_release_notes
Instead of trying to figure out which characters to escape, this uses the [inline passthrough macro](https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/).
> Use inline passthrough macro to avoid escaping

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
Currently, the warning is contradictory to the prerequisite. BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2232693
> Fix warning in configuring AD integration

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/katello-4.9.0.adoc
- guides/doc-Release_Notes/topics/katello-4.9.1.adoc
- guides/doc-Release_Notes/topics/katello-4.9.2.adoc
- guides/doc-Release_Notes/topics/katello-contributors.adoc
Also includes release notes for Katello 4.9.1
> Update release notes for Katello 4.9.2

- guides/common/modules/proc_importing-container-images.adoc
[BZ#2022803](https://bugzilla.redhat.com/show_bug.cgi?id=2022803) requests adding steps on importing container images not using repo discovery, but manually for existing products. This PR updates the procedure with these steps, while also making other minor edits to accommodate the new steps.
> Add steps for adding repo manually when importing container images

- guides/doc-Upgrading_Project/docinfo.xml
The upgrading title for Satellite varies from the upstream doc. Fixing this in the `docinfo.xml` file.
> Fix Upgrading doc title

- guides/common/modules/proc_restoring-a-backup-of-a-server-on-el8.adoc
foreman_maintain does that since 1.1.10
> no need to reindex the db manually after restore

- guides/common/modules/proc_performing-a-backup-without-pulp-content.adoc
It is not impossible to restore backup without pulp. However, this is not recommended.
Rewording to convey correct information.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2227276
> Remove the strong negative usage for backup restoration

- guides/common/modules/proc_updating-disconnected-server.adoc
Apart from `check-upstream-repository` and `repositories-validate`, there is a suggestion to add `repositories-setup` in the whitelist while executing the Upgrade command on the Project Server to update it to the next minor version.
https://bugzilla.redhat.com/show_bug.cgi?id=2242367
> Add repositories-setup in whitelist while upgrading

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
cloud.cfg is missing the SSH module for VMWare cloud-init 20 and newer.
Also, we can tell the user to remove all SSH keys in a clearer way.
https://bugzilla.redhat.com/show_bug.cgi?id=2237783
> Update code samples in VMware cloud-init

- .github/workflows/deploy.yml
- .github/workflows/linkchecker.yml
otherwise it prevents previews from being built without a good reason
> move linkchecker to an own workflow file

- guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc
3.1-3.3 will probably have conflicts when picking…
> fix chrony link after rhel docs update

- guides/doc-Release_Notes/topics/foreman-3.8.0.adoc
- guides/doc-Release_Notes/topics/foreman-contributors.adoc
> Update release notes for Foreman 3.8 GA

- guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
On RHEL 8.x, 'dnssec-keygen' is provided by the 'bind-utils' package. Simply 'Bind' package does not fulfill the required packages. This change is applicable to only EL8.
https://bugzilla.redhat.com/show_bug.cgi?id=2243039
> Replace outdated bind package for EL8

- guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
On EL 8.x, 'dnssec-keygen' is provided by the 'bind-utils' package. Simply 'Bind' package does not fulfill the required packages. This change is applicable to only EL8. On EL 7.x, the current packages mentioned are correct and need no further modification. However, we have enhanced some commands for a better user experience in CLI.
https://bugzilla.redhat.com/show_bug.cgi?id=2243039
> Distinguish bind packages for EL8 and EL7

- guides/common/modules/proc_registering-a-host.adoc
The optional step for selecting a lifecycle environment is not needed
starting in Satellite 6.15.
> Remove optional step for 6.15

- guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
- guides/common/modules/proc_renaming-smart-proxy.adoc
Output should not differ much. Using an attribute is IMO much nicer than duplicate content.
> Use attribute to reduce duplicate content

- guides/common/modules/proc_configuring-pcp-data-collection.adoc
The `ln -s` command in the monitoring guide seems to use the arguments in the wrong order.
> Correct `ln` call when installing Foreman's hotproc config

- guides/common/modules/proc_cloning_satellite_server.adoc
The current wording seems to suggest that the clone tool does not work only for smart proxies installed on EL 8 systems. However, the tool does not work on smart proxies at all. Rewording to convey this information.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2227044
> Rectify note about cloning Smart Proxy

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
HTTPS cannot be used in these cases. The user must enter HTTP URLs.
> Fix URL schemes in VMware cloud-init

- guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
- guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
- guides/common/modules/proc_configuring-project-with-an-alternate-cname.adoc
- guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
Earlier this section was removed but the decision is now reconsidered and we are now restoring it with better information that should be considered by end-users when they are creating and deploying custom SSL certificates.
This reverts commit 00f5ac352aff4d4819c602681dd25a2dd51b615e.
https://bugzilla.redhat.com/show_bug.cgi?id=2226794
> Further enhance creating the custom SSL certs

- guides/common/modules/con_using-repository-sources.adoc
- guides/common/modules/proc_synchronizing-templates-with-an-existing-repository.adoc
While working on #2414, I did not realize that I forgot to write introduction to Using Repository Sources subchapter. The sections then went under *Configuring the Templates Plugin* which was mildly related so the procedures did not stick out as misplaced. After reviewing PR again I noticed an empty introduction module.
I also rephrased introduction in a subsequent module to not repeat the same thing twice in the docs.
> Fill in missing introduction module

- guides/common/modules/proc_configuring-repositories.adoc
- guides/doc-Quickstart/master.adoc
This change is required for Satellite, where we have `proc_configuring-repositories.adoc` also in the QuickStart guide and while we do not use the guide, it builds as a part of the downstream pipeline so this change is required at the very least downstream. The reason I am putting it here is to prevent desynchronization in the future.
> Fix reference rendering in satellite

- guides/common/modules/proc_configuring-a-finish-template-for-amazon-ec2.adoc
This is done automatically by REX.
Includes https://github.com/theforeman/foreman-documentation/pull/2329, so currently a draft.
> Remove remote_execution_ssh_keys parameter step

- guides/common/modules/ref_system-requirements.adoc
The current link is obsolete. Replaced the new link.
https://bugzilla.redhat.com/show_bug.cgi?id=2243681
> Fix Certified Hypervisor link

- guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-smart-proxy-server.adoc
* Rename file to align with upstream terminology
* Revert 41a0b96 partially to ensure the docs match the stdout from "katello-certs-check" on Foreman + Satellite
* Use proper attribute for Smart Proxy FQDN vs Smart Proxy name
Follow-up PR to https://github.com/theforeman/foreman-documentation/pull/2517 
Sorry for the trouble @ekohl Please review to ensure both issues are addressed.
> Use attribute as shell variable

- guides/common/modules/proc_using-red-hat-insights.adoc
This section discusses how the hosts are automatically deleted from the Insights Inventory simultaneously when deleted from the Project Server.
https://issues.redhat.com/browse/SAT-18017
> Add automatic hosts deletion in Insights Inventory

- guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
- guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
- guides/common/modules/proc_configuring-users-os-for-keycloak-authentication-with-cac-cards.adoc
- guides/common/modules/proc_disabling-cockpit-on-project.adoc
- guides/common/modules/proc_exporting-templates.adoc
- guides/common/modules/proc_installing-smart-proxy-upstream.adoc
- guides/common/modules/proc_migrating-to-external-databases.adoc
- guides/common/modules/proc_performing-a-snapshot-backup.adoc
- guides/common/modules/proc_preparing-cloud-init-images-in-rhv.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
- guides/common/modules/proc_rex-pull-based-transport.adoc
- guides/common/modules/proc_setting-the-job-rate-limit-on-smartproxy.adoc
- guides/common/modules/proc_updating-disconnected-server.adoc
- guides/common/modules/ref_white-listing-and-skipping-steps-when-performing-backups.adoc
* Add newlines for commands with more than one option
* Remove unnecessary "+" signs between list items
* Sort options in alphabetical order
* Use EL attribute for OS refers to Enterprise Linux, not RHEL specifically
* Use "SmartProxyServer" instead of "external Smart Proxy" (affects upstream only)
I have used `rg "^\{pro"`, `rg "^\{pack"`, `rg "^\{inst"` and `rg "^hammer"` to find those files. I fixed some other minors issues while editing the files.
> Add "#" prefix to commands

- guides/common/assembly_managing-ansible-content.adoc
- guides/common/modules/con_managing-ansible-content.adoc
- guides/doc-Managing_Content/master.adoc
[BZ#2237906](https://bugzilla.redhat.com/show_bug.cgi?id=2237906) points out missing resources for importing Ansible collections in the content guide. This PR creates a new assembly for Managing Content which reuses a procedure already included in Managing Configurations with Ansible. The changes involve adding a few new includes and a little fluff to serve as the assembly introduction.
> Document importing ansible collections in the content guide

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
We're creating a new downstream Satellite guide. We need to add title and URL attributes for it.
The title was agreed upon in our team. The URL must match the title in snake_case.
> Add conversions appliance guide info

- guides/common/modules/con_converting-a-host-to-rhel.adoc
Need this for the new Conversions guide.
> Include external links in Converting Hosts

- guides/common/assembly_converting-a-host-to-rhel.adoc
- guides/common/modules/con_converting-a-host-to-rhel.adoc
- guides/common/modules/ref_ansible-variables-for-conversion.adoc
This reference module title needed simplification as much as clarification.
Long due :)
> Rename C2R ref module

- guides/common/modules/ref_capsule-storage-requirements.adoc
[BZ#2238123](https://bugzilla.redhat.com/show_bug.cgi?id=2238123) requests setting the right expectation for postgres size on SmartProxy.
> pgsql on smartproxy can grow significantly

- guides/common/modules/ref_capsule-storage-requirements.adoc
This PR is a follow-up on https://github.com/theforeman/foreman-documentation/pull/2546 to get the fix on 3.3 and below. I had to make a slight change to the wording and include it above the actual storage requirements to make it work for the Satellite build. It's probably not the prettiest solution but in my opinion, good enough for older releases.
> PostgreSQL on smartproxy can grow significantly

- guides/common/modules/ref_capsule-storage-requirements.adoc
This PR is a follow-up on https://github.com/theforeman/foreman-documentation/pull/2546 and https://github.com/theforeman/foreman-documentation/pull/2554 to get the fix on 3.1.
There was a merge conflict because 3.1 doesn't use a variable for the PostgreSQL directory.
> Enlarge PostgreSQL database on Smart Proxy Server

- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/2521.
The current wording seems to suggest that the clone tool does not work only for smart proxies installed on EL 8 systems. However, the tool does not work on smart proxies at all. Rewording to convey this information.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2227044
> Rectify note about cloning Smart Proxy for 3.3

- guides/common/modules/proc_configuring-repositories-el.adoc
- guides/common/modules/proc_enabling-puppet.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
- guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
- guides/doc-Quickstart/master.adoc
> Resolves 2333 "Specify Puppet version requirement"

- guides/common/modules/proc_creating-a-location.adoc
- guides/common/modules/proc_creating-an-organization.adoc
- guides/common/modules/proc_creating-operating-systems.adoc
- guides/common/modules/proc_installing-webhooks-plugin.adoc
- guides/doc-Deploying_Project_on_AWS/topics/AWS_Prerequisites.adoc
`$ rg "Optional: [a-z]"`
I was unsure during a review if it's ". Optional: Do X" or ". Optional: do X", so I've checked. The results were clearly in favor of the capitalized version.
> Capitalize words after optional prefix

- guides/common/attributes-satellite.adoc
- guides/common/linkchecker.ini
- guides/doc-Administering_Project/docinfo.xml
- guides/doc-Administering_with_Ansible/docinfo.xml
- guides/doc-Configuring_Load_Balancer/docinfo.xml
- guides/doc-Deploying_Project_on_AWS/docinfo.xml
- guides/doc-Installing_Proxy/docinfo.xml
- guides/doc-Installing_Server/docinfo.xml
- guides/doc-Installing_Server_Disconnected/docinfo.xml
- guides/doc-Managing_Configurations_Ansible/docinfo.xml
- guides/doc-Managing_Configurations_Puppet/docinfo.xml
- guides/doc-Managing_Content/docinfo.xml
- guides/doc-Managing_Hosts/docinfo.xml
- guides/doc-Managing_Security_Compliance/docinfo.xml
- guides/doc-Monitoring_Project/docinfo.xml
- guides/doc-Planning_for_Project/docinfo.xml
- guides/doc-Provisioning_Hosts/docinfo.xml
- guides/doc-Tuning_Performance/docinfo.xml
- guides/doc-Updating_Project/docinfo.xml
- guides/doc-Upgrading_Project/docinfo.xml
For .xml files I used:
find . -type f -iname "*.xml" | xargs sed -i 's/6\.14/6\.15/g'
> Bump up Satellite to 6.15

- guides/common/attributes.adoc
With Foreman 3.8 as a stable release, Foreman 3.6 is now unsupported.
> Declare Foreman 3.6 as unsupported

- guides/common/modules/proc_changing-email-notification-settings-for-a-host.adoc
The current procedure is not correct as there is no Additional Information tab on the host detail page. This tab is located on the host edit page.
Also added instructions to change host's owner who receives the email notifications in question.
https://bugzilla.redhat.com/show_bug.cgi?id=2212587
> Fix viewing or changing email notification settings

- guides/doc-Release_Notes/topics/katello.adoc
I suggest to keep the structure based on headings in all versions in case there are external links in the sense of "docs.theforeman.org/katello-release-notes/$Version#deprecations".
Follow-up PR to https://github.com/theforeman/foreman-documentation/pull/2481/files#diff-a3acd643a9303d35f8f0d8c49bd0099a29f8576e1fa1648475da1258c8fad7deL10
> Readd deprecations heading for external links

- guides/common/modules/proc_installing-postgresql.adoc
> manually create the hstore extension for pulpcore externaldb

- guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
users will have it installed by now
> don't mention postgresql-evr during upgrade

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
- guides/doc-Upgrading_Project/topics/con_upgrade-paths.adoc
Cosmetic cleanup of the "Upgrade to previous version" Doc Title and link. (Follow-up to #2576)
> Fix upgrading-to-previous version link (Satellite) 3.8+3.7

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
- guides/doc-Upgrading_Project/topics/con_upgrade-paths.adoc
This needs to be introduced, because we now include version number in the doc title.
Now it produces the correct link, but the target isn't available yet, because Sat 6.14 docs aren't published yet.
> Fix upgrading-to-previous version link (Satellite)

- guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc
We're removing Direct Documentation Feedback from the RH Customer Portal.
**Do not merge before Nov 8!**
> Remove DDF option from Feedback (Satellite)

- guides/common/modules/ref_advanced-settings-in-the-job-wizard.adoc
Time span is being removed in Foreman 3.9.
> Remove the time span setting

- guides/doc-Upgrading_Project/topics/con_introduction-upgrading-project.adoc
> Remove unnecessary warning from Upgrading Guide

- guides/common/linkchecker.ini
Now that Satellite 6.14 was released we can start checking 6.14 links.
> Start checking Satellite 6.14 links

- guides/common/attributes-satellite.adoc
Please cherry-pick my commits accordingly:
`Fix Upgrading guide URL for Satellite`
`Fix UpgradingPreviousDoc URL`
no cherry-picks
> Fix upgrading guide links

- guides/common/assembly_configuring-email-notifications.adoc
- guides/common/modules/con_configuring-email-notifications.adoc
- guides/common/modules/ref_email-notification-types.adoc
Changes in this PR lay the groundwork for documenting new email notification types:
* I renamed the reference section "Notification Types" to "Email Notification Types" to make its purpose clearer.
* I renamed and removed some notification types in the outdated list.
* I added tips for where to find the complete list, to help users if/when the list changes with future releases.
> Update module on Email notification types

- guides/common/modules/ref_general-settings-information.adoc
`append_domain_name_for_hosts` is being replaced with `display_fqdn_for_hosts`. This PR updates a reference list of Web UI settings accordingly.
> 'Append domain names' replaced by 'Display FQDN'

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
We need to rename this due to Marketing requirements.
> Rename Conversions thingy

- guides/common/modules/ref_email-notification-types.adoc
This PR adds four new types of email notifications (based on https://projects.theforeman.org/issues/17748). Additionally, I changed the markup used for the list of notifications and made minor tweaks to ensure the list is ordered alphabetically.
> New email notifications for failed bg actions

- guides/common/modules/con_content-filter-examples.adoc
BZ#222893[https://bugzilla.redhat.com/show_bug.cgi?id=2222893#c1] requests documenting that filters can cause CV publish tasks to take much longer. This PR adds this as a note in a section describing filter examples.
(I'm using Content Views in uppercase because the whole section does so.)
> CV publish with filters takes much longer

- guides/doc-Upgrading_and_Updating/master.adoc
- guides/doc-Upgrading_and_Updating/topics/introduction_updating_satellite.adoc
The procedure to update the content hosts was removed from the Upgrading and Updating guide, however, content hosts are still mentioned in the chapter title. Removing this mention as it is confusing to the user.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2209380
> Remove mentions of Content Host from the updating section

- guides/common/modules/con_converting-a-host-to-rhel.adoc
Documents https://github.com/theforeman/foreman_remote_execution/pull/840, i.e. Convert2RHEL analyze template
> Add pre-conversion check in Convert2RHEL

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
Once more for a downstream-only guide.
We have to include "Satellite" in the title and URL of the guide.
The attributes aren't used anywhere yet.
> Fix Conversions title (Satellite only)

- guides/common/modules/con_prerequisites-for-vmware-provisioning.adoc
VMware vCenter Server 8 hasn't been properly tested yet, so we should explicitly state which vCenter versions are supported in Foreman. See also: https://bugzilla.redhat.com/show_bug.cgi?id=2247345#c6
Originally, I wanted to create a RH KB article, but it's probably better to include it in the docs directly for upstream.
> Supported VMware vCenter versions in Provisioning

- guides/common/modules/proc_creating-a-report-template-to-monitor-entitlements.adoc
`pools` only works with non-SCA organizations so a note 
has been added
where it is mentioned.
> `pools` only works with non-SCA organizations so a note

- guides/common/assembly_installing-capsule-server.adoc
- guides/common/assembly_installing-satellite-server-disconnected.adoc
- guides/common/assembly_installing-server-connected.adoc
- guides/common/modules/con_using-fapolicyd-on-server.adoc
- guides/common/modules/proc_installing-fapolicyd-on-server.adoc
For version 3.9 and above, we have started supporting fapolicyd on the Project Server and SmartProxy Server. The procedure to install and enable faplicyd for both remains the same. You can install fapolicyd along with the fresh installation of Project or SmartProxy or install it on existing Project or SmartProxy.
> fapolicyd on Project and SmartProxy [Priority]

- guides/common/assembly_importing-content.adoc
- guides/common/modules/proc_refreshing-content-counts-on-smart-proxy.adoc
- guides/common/modules/proc_refreshing-smart-proxy-counts.adoc
A new procedure for refreshing content counts for
SmartProxies/Capsules
was needed and has been added to the Content Management Guide.
> Add procedure for refreshing content counts

- guides/common/modules/proc_creating-an-installation-medium-for-debian.adoc
- guides/common/modules/proc_creating-an-operating-system-for-debian.adoc
- guides/common/modules/proc_creating-operating-systems.adoc
- guides/common/modules/snip_creating-os-on-orcharhino.adoc
orcharhino Server contains a shellscript that runs an Ansible playbook that contains Ansible roles to add and/or update existing operating system entries and associated templates on orcharhino Server.
> Use shellscript to add operating systems

- guides/common/attributes-foreman-el.adoc
- guides/common/attributes-katello.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_troubleshooting-postgresql.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
- guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
- guides/doc-Upgrading_Project/topics/proc_upgrading-smartproxy-server.adoc
No CP should be needed, this is for Foreman 3.9
Pulpcore 3.39 is almost definitely losing its module stream, so it will no longer be needed in the docs.
Don't merge until after https://github.com/theforeman/puppet-pulpcore/pull/315 get in.
> Remove references to Pulpcore module stream for Pulpcore 3.39

- guides/common/modules/proc_creating-an-activation-key.adoc
- guides/common/modules/proc_updating-subscriptions-associated-with-an-activation-key.adoc
The "Content > Activation keys" step is replaced with "Content >
Lifecycle > Activation Keys." in two sections of the Managing Content
guide. "Lifecycle" was missing.
> Add lifecycle to procedure step

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
RHEL 8.8 has new tomcat packages which are marked as upgradable by the recent Leapp. This breaks Satellite installations. The fix is to tell LEapp not to update the Tomcat packages. Adding a step to skip the Leapp transaction for Tomcat.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2250254
> Add step to skip tomcat from leapp upgrade

- guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
Presently, in setting up the Project in the IPv6 network, we mention only the IPv4 type of HTTP Proxy server which is incorrect. Because, the HTTP Proxy server configured with IPv4 only cannot communicate with the Project configured in the IPv6 network, except CDN. Hence, it should support both, IPv4 and IPv6.
> Revise the type of HTTP Proxy mentioned

- guides/common/modules/proc_importing-kickstart-repositories.adoc
In the appendix for **Importing Kickstart Repositories for Red Hat
Enterprise Linux 7**, the step that states "Copy the kickstart files from
the ISO image:" uses the word "images" in the command line. It was
recommended to remove the word from the command line and you will copy
the packages in addition to the images. See
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2208077
> Remove images from command line

- guides/common/modules/proc_installing-the-load-balancer.adoc
Since katello-agent has been removed in the guides for 6.15, the
reference to the AMQP port needs to be removed as well since it is
related to the katello-agent feature.
> Remove AMQP port

- web/content/index.adoc
- web/content/js/versions.js
> Update Foreman 3.9 to supported

- guides/common/assembly_restoring-server-or-smart-proxy-from-a-backup.adoc
- guides/common/modules/con_backup-and-restore-smart-proxy-using-a-virtual-machine-snapshot.adoc
- guides/common/modules/proc_synchronizing-an-external-smart-proxy.adoc
- guides/common/modules/proc_synchronizing-content-from-project-server-to-smart-proxy-servers.adoc
> Add sync modes for Smart Proxy Servers

- guides/common/modules/snip_host-registration-steps.adoc
Clarify that LB has to be set for registration before the user can select the LB during global registration.
> Add LB prerequisite

- guides/common/modules/proc_enabling-puppet.adoc
We got a customer request to clarify the value of this argument when enabling Puppet.
This change is only applicable in 3.7 and older.
> Clarify value of Puppet server foreman URL 3.7

- guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
Presently, in setting up the Project in the IPv6 network, we mention only IPv4 type of HTTP Proxy server which is incorrect. Because, HTTP Proxy server configured with IPv4 only cannot communicate with Project configure in IPv6 network, except CDN.
Hence, it should support both, IPv4 and IPv6.
(cherry picked from commit 28d8c905c5bc6a9aea3315d2e8ceb0fcb0ba9d2c)
> Reword IPv4 and IPv6 HTTP Proxy requirement (#2608)

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/foreman-3.9.1.adoc
> Add release notes for Foreman 3.9.1

- guides/common/modules/proc_configuring-remote-execution-for-pull-client-on-project-server.adoc
Rendered docs for Satellite: https://docs.theforeman.org/nightly/Installing_Server/index-satellite.html#configuring-remote-execution-for-pull-client-on-satellite-server_satellite
In orcharhino, this should say "either orcharhino Server or orcharhino Proxies". It is not visible in upstream.
> Clarify target of MQTT subscriptions

- guides/common/modules/con_performing-post-upgrade-tasks.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_discovery_parent.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_discovery_subnet_with_a_template_capsule.adoc
Per [BZ#2106016](https://bugzilla.redhat.com/show_bug.cgi?id=2106016), this PR is intended to clarify that a procedure related to upgrading the Discovery service is actually optional.
* The procedure introduction is rephrased to clarify its use case.
* A link is labeled as an additional resource and moved to a more suitable place.
* An internal table of contents is removed because it duplicates the automated ToC.
This PR targets version 3.3 because the procedure is not present in later versions.
If this PR gets merged, I will follow up with another one against version 3.1.
> Clarify that Template SmartProxy procedure for upgrading Discovery is not always required

- guides/common/modules/con_configuring-host-collections.adoc
- guides/common/modules/proc_creating-hosts-on-vmware.adoc
- guides/common/modules/proc_registering-a-host.adoc
We have attributes that indicate if Katello is present or not. This makes it easier for both users and maintainers.
> Remove specific mentions of "if you use Katello"

- guides/common/modules/proc_troubleshooting-erb-templates.adoc
- guides/common/modules/proc_using-autocompletion-in-templates.adoc
This change is required for the new vertical navigation. It was probably missed during an earlier update.
https://bugzilla.redhat.com/show_bug.cgi?id=2256016
> Fix navigation in Managing Hosts

- guides/doc-Provisioning_Hosts/master.adoc
Fixes: e5243c4dd2a66eb078d5a970e291e636abe6d335 ("Update list of permissions a non-admin user requires (#2292)")
> Hide required permissions appendix when guide isn't ready

- web/content/js/versions.js
- web/content/release-3.9.adoc
These guides don't render anything other than a warning that they're not ready, so not helpful to users. It's best to not give the illusion they are.
> Hide guides that aren't ready from the navigations

- guides/common/modules/proc_creating-a-vmware-user.adoc
This vCenter permission is required for successful provisioning with cloud-init.
https://bugzilla.redhat.com/show_bug.cgi?id=2256509
> Add missing permission for VMware provisioning with cloud-init

- guides/common/modules/proc_adding-lifecycle-environments.adoc
See https://community.theforeman.org/t/how-to-do-same-things-as-complete-sync-of-smartproxy-with-hammer/34777/2?u=maximilian
> Run complete sync to Smart Proxy Server via CLI

- guides/common/modules/proc_configuring-remote-execution-for-pull-client-on-project-server.adoc
In the Installation Guide, we use 1883/tcp port in the firewall-cmd but in the Capsule Guide, we use mqtt service. Both do the same job but the commands are different. Hence, we should keep it consistent and I prefer -add-service=mqtt to align with the procedure. And, according to https://github.com/firewalld/firewalld/blob/main/config/services/mqtt.xml#L5
> Keep firewall-cmd for mqtt consistent

- guides/common/modules/proc_adding-lifecycle-environments.adoc
In Foreman+Katello, a "complete sync" does not rely on already existing metadata. Instead, the content is synchronized as if there was no metadata existing.
In the Web UI, it's called "Complete Sync"; for Hammer CLI, you use "--skip-metadata-check".
"skipping checks on metadata" or "without checking metadata" is technically correct.
Fixes https://github.com/theforeman/foreman-documentation/pull/2664#issuecomment-1889317012
> Fix wording on sync to Smart Proxy Server

- guides/doc-Configuring_Load_Balancer/master.adoc
Setting the load balancer for registration by using the `--foreman-proxy-registration-url` installer argument is not supported until Foreman 3.5.
https://bugzilla.redhat.com/show_bug.cgi?id=2255528
> Remove unsupported LB feature 3.4

- guides/common/modules/con_performing-post-upgrade-tasks.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_discovery_parent.adoc
- guides/doc-Upgrading_and_Updating/topics/upgrading_discovery_subnet_with_a_template_capsule.adoc
To follow up on PR https://github.com/theforeman/foreman-documentation/pull/2658, I'd like to introduce the same changes to Foreman 3.1 as well.
> Clarify that Template SmartProxy procedure for upgrading Discovery is not always required (branch 3.1)

- guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
> Fix URL to download generic bootdisk

- guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
Earlier in the last release version, we had no services to add for the firewall. But with the latest version i.e. going to be released, we add services and ports in the firewall. But, the firewall command does not accept the services and ports together in a single instance and is therefore split here. Also, adding --permanent to the command in the first place replaces the requirement of a new step for making it persistent.
https://bugzilla.redhat.com/show_bug.cgi?id=2253246
> Fix firewall commands for ports and services

- guides/common/modules/proc_adding-installation-media.adoc
Pulling Installation Media over the NFS protocol is technically possible, however, it's untested (at least in Satellite) and it doesn't work in the fully-automated way. Therefore, I'm suggesting to remove NFS mentions for downstream in order to set the right expectations for our customers. However, I'd keep it in upstream builds with a note.
https://bugzilla.redhat.com/show_bug.cgi?id=1896771
> Clean up Install Media over NFS protocol in Provisioning

- guides/common/modules/proc_enabling-connections-to-capsule.adoc
This applies to Proxy Server as well:
https://github.com/theforeman/foreman-documentation/pull/2630
> Fix firewall commands for ports & services - Proxy

- guides/common/modules/con_content-types-overview.adoc
- guides/doc-Managing_Content/master.adoc
OSTree content management is not available in any Satellite and is not planned to be included.
> Hide OSTree content for Satellite

- guides/common/modules/proc_creating-a-report-template.adoc
> Fix link rendering in downstream Satellite

- guides/common/modules/proc_uploading-ostree-content-with-hammer-cli.adoc
OSbuild.org has changed their docs and we need to update this external link to OStree image builder.
Urgent because it's breaking our builds and makes bad UX.
**Please check that it's the suitable target.**
> Fix link osbuild.org [URGENT]

- guides/common/modules/proc_configuring-installation.adoc
Since Foreman 3.1 Puppet hasn't been enabled in the Katello scenario, but it is in vanilla Foreman. It also rephrases the installer managed parts to avoid the implication that Puppet runs as a deamon.
> Refs #33337 - Reflect Puppet isn't enabled by default

- guides/common/assembly_preparing-environment-for-installation.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
This section was part of Performing Additional Configuration but it should be kept under the Preparing Environment section. The reason is that end-users will look for setting pre-defined tuning profiles well in advance while they are preparing the project installation environment.
https://bugzilla.redhat.com/show_bug.cgi?id=2244184
> Rearrange the tuning profile section

- guides/common/modules/con_types-of-provisioning-templates.adoc
RH does not support provisioning of other OS than RHEL. + cosmetic improvements
> Disclaim other OSs for Satellite

- guides/doc-Planning_for_Project/master.adoc
We need to display the Glossary for all builds, because we started referring to it in upstream builds. Follow-up to #2706 
> Show Glossary for all builds

- guides/common/modules/ref_ports-and-firewall-requirements.adoc
Earlier, no ports were mentioned in the document about allowing incoming traffic to Satellite from the Client for Global Registration. We added those ports now. Also, we modified the description for Content Host Registration. I have made some adjustments in the table sequence for better readability.
https://bugzilla.redhat.com/show_bug.cgi?id=2247445
> Add ports to allow incoming traffic

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_viewing-the-project-ansible-modules.adoc
The current link is incorrect and leads to endless loading. We have replaced the correct link. Also, the link was a bare URL and did not have the link text. Hence, I have tried to add it with module-level attributes to satisfy different builds.
https://bugzilla.redhat.com/show_bug.cgi?id=2260347
> Fix link of Ansible Modules and add the Link Text

- guides/common/modules/proc_configuring-installation.adoc
In Foreman organizations don't have labels. This is added by Katello via an extension of the model.
I only selected supported branches, but I think it applies all the way back.
> Reflect that only Katello has organization labels

- .github/PULL_REQUEST_TEMPLATE.md
Satellite 6.11 reached EOL on Jan 31, 2024.
> End support for Satellite 6.11

- guides/common/modules/proc_adding-a-host-to-a-host-collection.adoc
- guides/common/modules/proc_adding-hosts-to-a-host-collection-in-bulk.adoc
- guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
- guides/common/modules/proc_configuring-simplified-alternate-content-sources.adoc
- guides/common/modules/proc_creating-a-content-view.adoc
- guides/common/modules/proc_creating-a-host-collection.adoc
- guides/common/modules/proc_creating-a-host.adoc
- guides/common/modules/proc_creating-a-job-template.adoc
- guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
- guides/common/modules/proc_executing-a-remote-job.adoc
- guides/common/modules/proc_monitoring-remote-jobs.adoc
- guides/common/modules/ref_capsule-storage-requirements.adoc
- guides/common/modules/ref_rendering-a-restorecon-template.adoc
- guides/common/modules/ref_supported-operators-for-granular-search.adoc
Some places contain invisible U+00a0 character where regular space should have been used. This character can render copied command unusable.
find . -type f -iname "*.adoc" | xargs sed -i 's/\xc2\xa0/ /g'
> Replace invisible unicode character with space

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc
- guides/common/modules/proc_adding-kubevirt-connection.adoc
Small fixes for KubeVirt/OpenShift Virtalization in the "Provisioning hosts" guide.
> Provisioning VMs on KubeVirt

- guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
In #2721 I changed this line to remove the invisible unicode character, but I did not notice that the attribute changed while cherry-picking.
> Revert changed attribute to fix build

- guides/common/modules/proc_configuring-installation.adoc
This makes it clear why the installer manages the files. Rather than presenting it as a downside, it explains why it's a feature.
The part about DHCP and DNS is dropped since there are no instructions to set up DHCP and DNS here. If anything, they should be presented in the correct chapters.
Builds on https://github.com/theforeman/foreman-documentation/pull/2690 and currently a draft because of that.
> Rewrite paragraph on installer managed files

- guides/common/modules/proc_registering-a-host.adoc
A note was required to describe what happens to a
content source when
there are Capsules behind a load balancer.
> Add note about Capsules behind load balancers

- guides/common/modules/con_limitations-of-installation-in-an-ipv6-network.adoc
- guides/common/modules/con_resolving-package-dependencies.adoc
- guides/common/modules/proc_adding-custom-rpm-repositories.adoc
- guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
- guides/common/modules/proc_configuring-project-settings-for-keycloak-authentication-using-the-cli.adoc
- guides/common/modules/proc_configuring-simplified-alternate-content-sources.adoc
- guides/common/modules/proc_configuring-tls-for-secure-ldap.adoc
- guides/common/modules/proc_logging-in-to-the-project-CLI-using-keycloak.adoc
- guides/common/modules/proc_renaming-server.adoc
- guides/common/modules/proc_testing-email-notifications.adoc
- guides/common/modules/ref_example-settings-for-ldap-connections.adoc
- guides/common/modules/ref_permissions-required-to-provision-hosts.adoc
```
find . -type f -iname '*.adoc' | xargs sed -i 's/[ \t]*$//'
```
> Remove trailing whitespaces from files

- guides/common/modules/con_registering-hosts-by-using-global-registration.adoc
- guides/common/modules/proc_changing-the-default-download-policy.adoc
- guides/common/modules/proc_changing-the-provisioning-password-hashing-algorithm.adoc
- guides/common/modules/proc_cloning_satellite_server.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc
- guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc
- Change `[[anchor-id]]` to `[id="anchor-id"]` for files in `guides/common/modules` to comply with current Asciidoc formatting
- No changes to files in `guides/doc-Planning-for-Project` because that guide has its own modularization issue.
> Update obsolete anchor IDs

- guides/common/modules/proc_adding-a-subnet.adoc
- guides/common/modules/proc_enabling-remote-execution.adoc
orcharhino comes, by default, with foreman_remote_execution installed. Users cannot unselect or uninstall this during/after the installation.
* Fix emphasis for foreman-installer command
* Fix issue with trailing backslash for Hammer CLI command
Proof: image 8 on https://docs.orcharhino.com/or/docs/sources/installation_and_maintenance/installing_orcharhino_server.html#orcharhino_Installer_GUI
> Remove optional REX plug-in for orcharhino

- guides/common/modules/proc_acd-developers.adoc
- guides/doc-Deploying_Hosts_AppCentric/master.adoc
I am sure all other code and documentation is also made with love!
> Remove ACD developers from docs

- guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
The `Upgrading {SmartProxy} Servers Using Remote Execution in the {ProjectWebUI}` section has been left out of the post 2.5 versions. However, this is still relevant in the later versions. Adding it back in for 3.1, will push separate PRs for other versions to avoid merge conflicts due to file structure changes.
BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2248524
> Re-add the section to upgrade Smart Proxy using remote execution

- guides/common/assembly_configuring-provisioning-resources.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-provisioning.adoc
- guides/common/modules/ref_kinds-of-provisioning-templates.adoc
WebUI uses a "Kind" of provisioning template.
https://bugzilla.redhat.com/show_bug.cgi?id=2228095
Also, this module looks more like the reference content type than concept.
> Replace Type with Kind for prov. templates

- guides/common/modules/proc_setting-up-job-templates.adoc
This setting has been [removed in Foreman 3.0](https://projects.theforeman.org/issues/26068).
https://bugzilla.redhat.com/show_bug.cgi?id=2127802
> Remove old Ansible setting

- guides/common/modules/proc_setting-a-default-encrypted-root-password.adoc
Just "python" isn't available on later EL OS (RHEL 8.8) by default and the command throws an error.
https://bugzilla.redhat.com/show_bug.cgi?id=2254446
> Use python3 to encrypt password

- guides/common/modules/proc_adding-a-bonded-interface.adoc
If adding a secondary bonded interface, the user must set it as Managed, otherwise the configuration isn't applied.
https://bugzilla.redhat.com/show_bug.cgi?id=2169092
> Set secondary bonded interface as Managed

- guides/common/modules/proc_creating-an-activation-key-short.adoc
- guides/common/modules/proc_creating-an-activation-key-to-consume-the-content-view.adoc
> Fix location of Activation Keys in vertical nav

- guides/common/modules/proc_importing-report-templates-using-the-api.adoc
> fix FQND typo in templates docs

- guides/common/modules/con_using-infoblox-as-dhcp-and-dns-providers.adoc
- guides/common/modules/proc_installing-the-dhcp-infoblox-module.adoc
- guides/common/modules/proc_installing-the-dns-infoblox-module.adoc
It seems counter-intuitive that the IPAM method to use with the Infoblox DHCP provider is "DHCP" and not "External IPAM", when, technically, Infoblox is an "external" DHCP service.
https://bugzilla.redhat.com/show_bug.cgi?id=2134225
> Add IPAM method for Infoblox

- guides/common/assembly_backing-up-server-and-proxy.adoc
- guides/common/modules/con_content-filter-overview.adoc
- guides/common/modules/proc_configuring-http-proxy-to-connect-to-cdn.adoc
- guides/common/modules/proc_configuring-ipxe-to-reduce-provisioning-times.adoc
- guides/common/modules/ref_skipping-steps-when-performing-backups.adoc
* Replace blacklist and whitelist according to inclusive language guidelines.
* Only generic text is changed.
* Command blocks are unchanged.
> Fix inclusive language issues

- guides/common/modules/con_making-open-source-more-inclusive.adoc
- guides/doc-Administering_Project/master.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Managing_Configurations_Ansible/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Monitoring_Project/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Updating_Project/master.adoc
- guides/doc-Upgrading_Project/master.adoc
Added the downstream "inclusive language" module for Satellite docs only.
> Add inclusive language module for Satellite

- guides/common/modules/proc_configuring-server-to-synchronize-content-over-a-network.adoc
The original steps in the procedure tell the user to click Sync Now to
synchronize the repositories but some steps are missing before the user
can do that. Those steps have been added.
> Clarify steps in procedure for Sync Now

- guides/common/modules/con_performing-post-upgrade-tasks.adoc
- guides/doc-Upgrading_Project/master.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/2697 for master. Custom templates created from default templates need to be cloned again after upgrade to ensure that any changes in the default templates apply to custom template as well. BZ link : https://bugzilla.redhat.com/show_bug.cgi?id=2257737
> Add message about cloning templates for master

- guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
- guides/common/modules/proc_adding-a-passphrase-to-ssh-key-used-for-remote-execution.adoc
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2170031
> Add procedure to add passphrase to SSH key used for REX

- guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
- guides/common/modules/proc_using-an-imagebuilder-image-for-provisioning.adoc
- guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc
* Replace "via" with "through"
> Reword "a HTTP proxy/server" to "an HTTP proxy/server"

- guides/common/modules/con_making-open-source-more-inclusive.adoc
`[preface]` is needed for this kind of chapter to make it unnumbered. Same as in [Providing feedback](https://github.com/theforeman/foreman-documentation/blob/b0e5e1e2e97ae2330a80b07b87e589bcf533238e/guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc?plain=1#L1)
> Add [preface] to inclusivity chapter (Sat only)

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
User: "Is it a good idea to wipe the cfg files out to add/change these options?"
SME: "Not unless you have a backup."
https://bugzilla.redhat.com/show_bug.cgi?id=2239040
> Keep backup of orig cfg files

- guides/common/modules/ref_port-and-firewall-requirements.adoc
- guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc
This removes duplication by using the already defined smartproxy_port attribute. It also adds notes about optional plugins.
> Simplify firewall tables using smartproxy_port attribute

- guides/common/modules/proc_updating-smart-proxy.adoc
The Smart Proxy repo needs to be updated to have the latest updated packages before performing the update. Ading a step at the beginning to sync the repo and publish and promote the CV that the Smart Proxy uses.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2254225
> Add a step to synchronize Smart Proxy repo before updating

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_managing-packages-on-the-base-operating-system.adoc
Co-authored-by: Maximilian Kolb <mail@maximilian-kolb.de>
(cherry picked from commit 98b323ff5cc7bc19109ef3a1d256ce08bcbb0a5d)
> Use satellite-maintain to handle package updates (#2582)

- guides/common/modules/proc_managing-packages-on-the-base-operating-system.adoc
We're getting build errors on the Admin guide because of attributes for a guide that doesn't exist for versions 3.6 and below. This PR aims to fix those errors by re-introducing attributes appropriate for these versions.
> Updating guide doesn't exist in this version

- guides/common/assembly_introduction-to-provisioning.adoc
- guides/common/modules/con_network-boot-provisioning-workflow.adoc
- guides/common/modules/ref_required-boot-order-for-network-boot.adoc
Incremental improvement of the Provisioning guide.
For now, I'm just trying to make stuff less bad. :)
> Split host boot order (Provisioning)

- guides/common/modules/con_host-substatus-overview.adoc
Cherry-picked from #2526. Removed `RHEL lifecycle`, which was added in 3.9.
> List all sub-statuses

- guides/doc-Upgrading_Project_Disconnected/master.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/2780 for Disconected Upgrade guide. Custom templates created from default templates need to be cloned again after upgrade to ensure that any changes in the default templates apply to custom template as well.
BZ link : https://bugzilla.redhat.com/show_bug.cgi?id=2257737
> Add message about cloning templates for disconnected upgrade guide

- guides/common/modules/ref_system-requirements.adoc
Earlier in the SmartProxy Guide, the FIPS point rendered Project and not the SmartProxy. I have tried to fix that.
(cherry picked from commit f490c0982281a03757c643d17680d33df77ec28c)
> Fix FIPS content for SmartProxy Guide

- guides/common/modules/proc_upgrading-smartproxy-server.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/2784, but for upgrading.
The Smart Proxy repo needs to be updated to have the latest updated packages before performing the upgrade. Ading a step at the beginning to sync the repo and publish and promote the CV that the Smart Proxy uses.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2254225
> Add a step to synchronize Smart Proxy repo before upgrading

- guides/common/modules/proc_updating-smart-proxy.adoc
- guides/common/modules/proc_upgrading-smartproxy-server.adoc
The Smart Proxy repo name is mentioned in plain text, fixing the syntax,
> Fix the syntax for the Smart Proxy repo name

- guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
When generating a certificate signing request, adding DN information increases trust. Although this is optional, users can benefit from this information.
There are two ways of doing this:
- Add the configuration to the openssl.cnf file.
- Provide the details when prompted by the command.
However, in the docs, we specifically ask the user to provide "prompt = no", this will tell the openssl command to not prompt for these details. So, adding this to the `openssl.cnf` file under the `[ req_distinguished_name ]` section.
BZ link:https://bugzilla.redhat.com/show_bug.cgi?id=2256000
> Add information about Distinguished Names

- guides/common/modules/proc_overriding-ansible-variables-in-project.adoc
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2215453
> Add warning to overriding Ansible variables
