guides/Makefile, guides/README.md, guides/common/Makefile, guides/doc-Provisioning_Guide/topics/Resources.adoc
This section starts without explaining all those resources. How about this?
=> New explanatory section in Resources

guides/doc-Provisioning_Guide/topics/Resources.adoc
There is a tiny difference between two "kinds" of finish scripts which we discussed at
https://github.com/theforeman/community-templates/pull/601
and I am leaving a short note about it here.
=> Added a note about finish script differences

guides/doc-Provisioning_Guide/master.adoc, guides/doc-Provisioning_Guide/topics/Cloud-GCE.adoc, guides/doc-Provisioning_Guide/topics/Resources.adoc
Added downstream as part of
Bug 1728725 - [RFE] Add documentation for Provisioning Cloud Instances in GCE
https://bugzilla.redhat.com/show_bug.cgi?id=1728725
=> Add content about provisioning on GCE

guides/doc-Provisioning_Guide/topics/Networking.adoc
Users are constantly running into this issue upstream.
=> Considerations about DNS nameservers

guides/README.md, guides/common/Makefile, guides/common/attributes.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Introduction.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc, guides/doc-Provisioning_Guide/topics/Resources.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc, guides/doc-Provisioning_Guide/topics/app_create_images.adoc
This pr contains the following:
* New variables
* Few guidelines that we must follow while reviewing/creating other guides
* Changed and added few contents from the upstream guide.
=> Provisioning guide

guides/doc-Provisioning_Guide/topics/Virt-Libvirt.adoc
Libvirt part, few changes here and there. Notably user data flag is not shown for libvirt as it does not support it.
=> Upstreamize libvirt section

guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc
* Add ifevals for Satellite-specific
* Add ifevals for Foreman-specific
=> Add markup for Foreman Amazon EC2 compute resource

.gitignore, guides/README.md, guides/common/Makefile
Two changes needed in the Makefile in order to build on MacOS. I use my old Macbook for "evening browsing", so will likely be using that to do some work here and there.
=> Added support for MacOS

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc
Fixed the prereqs and references to the activation key for VMware.
=> Update VMware prereqs and attributes

guides/common/attributes.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc, guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc, guides/doc-Provisioning_Guide/topics/app_create_images.adoc
=> Removed dot chars from attributes

guides/doc-Provisioning_Guide/topics/app-Deploy_FIPS_hosts.adoc
Upstreamized content for FIPS templates
=> [WIP] upstreamize fips topic

guides/doc-Provisioning_Guide/topics/Infoblox_Integration.adoc
As part of
Bug 1756996 - Add info that IPAM is not supported
https://bugzilla.redhat.com/show_bug.cgi?id=1756996
=> Add Infoblox IPAM limitation statement

guides/doc-Provisioning_Guide/topics/Networking.adoc
As part of #29
Use of --foreman-proxy-dns-server in the Networking chapter #29
=> Update foreman-proxy-dns-server address

guides/doc-Provisioning_Guide/topics/app-init_script.adoc
=> Upstreamize content init appendix

guides/doc-Provisioning_Guide/topics/Cloud-GCE.adoc
=> Upstreamize Google Cloud topic

guides/doc-Provisioning_Guide/topics/Cloud-OpenStack.adoc
Fixed a few grammar problems. Couldn't resist.
=> Upstreamize Openstack provisioning docs

guides/README.md, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Infoblox_Integration.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc
As part of issue 
Explain DHCP options #34 
https://github.com/theforeman/foreman-documentation/issues/34
I also fixed some incorrect attributes that threw errors on build.
=> Added section on DHCP options

.travis.yml, guides/Makefile, guides/README.md, guides/common/Makefile, guides/common/attributes.adoc, guides/doc-Provisioning_Guide/master.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc, guides/doc-Provisioning_Guide/topics/Cloud-GCE.adoc, guides/doc-Provisioning_Guide/topics/Cloud-OpenStack.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc, guides/doc-Provisioning_Guide/topics/Provisioning_Contexts.adoc, guides/doc-Provisioning_Guide/topics/Resources.adoc, guides/doc-Provisioning_Guide/topics/Virt-Libvirt.adoc, guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc, guides/doc-Provisioning_Guide/topics/app-Deploy_FIPS_hosts.adoc, guides/doc-Provisioning_Guide/topics/app_create_images.adoc, guides/upstreamize.rb
=> Introduce BaseURL attribute

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc, guides/doc-Provisioning_Guide/topics/Cloud-GCE.adoc, guides/doc-Provisioning_Guide/topics/Cloud-OpenStack.adoc, guides/doc-Provisioning_Guide/topics/Common_Compute_Resource_Prereqs.adoc, guides/doc-Provisioning_Guide/topics/Virt-Libvirt.adoc, guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc
As part of Issue #23
I could have genericized the other two bullets, but I want to allow some flexibility. 
I think Google Compute resource is missing a reference to a Capsule Server. 
Please take a look.
=> Create a file for reuse of common prereqs

guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc
As part of
Bug 1761021 - [DDF] probably this should be
/usr/share/foreman-proxy/.ssh/id_rsa_foreman_proxy.pub
https://bugzilla.redhat.com/show_bug.cgi?id=1761021
=> Fix directory name

guides/doc-Provisioning_Guide/topics/Virt-Libvirt.adoc, guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc
The `hammer compute-profile` command exists in the upstream for quite long time.
In this PR I'm trying to fill the gaps related to the usage of the compute profiles via CLI.
=> Add hammer CP command

guides/doc-Provisioning_Guide/topics/Introduction.adoc
Could not ressist, this is not a good introduction.
=> Improve introduction workflow

guides/doc-Provisioning_Guide/topics/Resources.adoc
Bug 1769405 - Documention unclear on which repos need to be added to update clients and capsules
https://bugzilla.redhat.com/show_bug.cgi?id=1769405
=> Update a section title in a link

guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc
As part of
Bug 1767117 - Adding the *Boot disk based* step by step in our official
guide
https://bugzilla.redhat.com/show_bug.cgi?id=1767117
=> Add information about boot-disk provisioning

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc, guides/doc-Provisioning_Guide/topics/Resources.adoc, guides/doc-Provisioning_Guide/topics/app-init_script.adoc
Added some DHCP troubleshooting information 
Rearranged the resources and created networking resources and provisioning resources
Add info about IPAM to resources section
=> * Add DHCP troubleshooting and update resources/IPAM

guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc, guides/doc-Provisioning_Guide/topics/Resources.adoc
As part of
Bug 1761028 - [DDF] You can download a foreman private ssh key if you
edit your AWS compute resource and choose "SSH Keys" tab. It's
https://bugzilla.redhat.com/show_bug.cgi?id=1761028
=> Update for SSH key issue

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
As part of
Bug 1796064 - [Provisioning Guide] fix broken anchor in Bare_Metal.adoc
file
https://bugzilla.redhat.com/show_bug.cgi?id=1796064
=> Fix broken anchor

guides/common/modules/enabling_the_satellite_tools_repository.adoc, guides/common/modules/proc_configuring-an-external-dhcp-server.adoc, guides/common/modules/proc_configuring-satellite-to-synchronize-content-with-a-local-cdn-server.adoc, guides/common/modules/proc_importing-kickstart-repositories.adoc, guides/common/modules/proc_reverting-satellite-to-download-content-from-red-hat-cdn.adoc
syncing latest downstream changes
=> updating installation guide & common folder

guides/common/attributes.adoc, guides/doc-Provisioning_Guide/master.adoc, guides/doc-Provisioning_Guide/topics/Virt-Kubevirt.adoc
As part of
Bug 1796408 - [Provisioning Guide] Move Kubevirt docs upstream
https://bugzilla.redhat.com/show_bug.cgi?id=1796408
=> Add KubeVirt provisioning to upstream

guides/doc-Provisioning_Guide/topics/app-Deploy_FIPS_hosts.adoc
As part of
https://bugzilla.redhat.com/show_bug.cgi?id=1796866
=> Add changes from BZ#1685639 upstream

guides/doc-Provisioning_Guide/topics/Resources.adoc
As part of
Bug 1796866 - [Provisioning Guide] Add three MRs to upstream
https://bugzilla.redhat.com/show_bug.cgi?id=1796866
=> Add Bug 1712468 to the upstream version

guides/doc-Provisioning_Guide/topics/Virt-RHV.adoc, guides/doc-Provisioning_Guide/topics/app-Deploy_FIPS_hosts.adoc, guides/doc-Provisioning_Guide/topics/app_create_images.adoc
Resolving outstanding issues in BZ#1796835
As part of
Bug 1796835 - [Provisioning Guide] Sync upstream with downstream versions of the guide
https://bugzilla.redhat.com/show_bug.cgi?id=1796835
=> Bz#1796835 ii

guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc
Bug 1778077 - [RFE] Update docs about HTTP proxy for repositories
https://bugzilla.redhat.com/show_bug.cgi?id=1778077
=> Changed link for HTTP proxy in EC2 docs

guides/common/modules/configuring_satellite_external_tftp_firewall.adoc, guides/common/modules/enabling_client_connections_to_satellite.adoc, guides/common/modules/proc_configuring-an-external-dhcp-server.adoc, guides/common/modules/proc_enabling-connections-from-capsule-to-satellite.adoc, guides/common/modules/proc_enabling-connections-to-capsule.adoc, guides/common/modules/proc_restricting-access-to-mongod.adoc, guides/common/modules/proc_verifying-firewall-settings.adoc, guides/common/modules/ref_supported-operating-systems.adoc, guides/common/modules/snip_firewalld.adoc, guides/common/modules/using_external_databases.adoc, guides/common/modules/verifying_external_dns.adoc, guides/doc-Provisioning_Guide/topics/Resources.adoc
adding conditionals for operating systems
add snippet for firewall-cmd usage
=> Bz#1797957

guides/doc-Installing_Satellite_Server_Connected/master.adoc
Update the TOC to include certain sections only for Satellite
As part of 
Bug 1797957 - Write upstream/downstream conditions for Installing Satellite Server (Connected) guide
https://bugzilla.redhat.com/show_bug.cgi?id=1797957
=> Bz#1798125 ii

guides/common/assembly_installing-capsule-server.adoc, guides/common/modules/proc_adding-life-cycle-environments.adoc, guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc, guides/common/modules/proc_registering-to-satellite-server.adoc, guides/common/modules/proc_restricting-access-to-mongod.adoc, guides/common/modules/proc_uninstalling-capsule-server.adoc, guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc, guides/common/modules/ref_system-requirements.adoc
As part of
Bug 1797970 - Write upstream/downstream conditions for Installing
Capsule guide
https://bugzilla.redhat.com/show_bug.cgi?id=1797970
=> Add notes for Katello users

guides/common/modules/configuring_satellite_external_idm_dns.adoc, guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc, guides/common/modules/proc_enabling-openscap.adoc, guides/common/modules/proc_enabling-power-management-on-managed-hosts.adoc, guides/common/modules/proc_enabling-remote-execution.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc
As part of
Bug 1801745 - [upstream] write ifevals for the satellite-installer
command for Capsule installation guide
https://bugzilla.redhat.com/show_bug.cgi?id=1801745
=> Adding attribute to --scenario capsule

guides/common/modules/AWS_Deployment_Scenarios.adoc, guides/common/modules/con_ports-and-firewalls-requirements.adoc, guides/common/modules/configuring_satellite_external_idm_dns.adoc, guides/common/modules/configuring_satellite_http_proxy.adoc, guides/common/modules/downloading_installing_satellite_disconnected.adoc, guides/common/modules/enabling_client_connections_to_satellite.adoc, guides/common/modules/enabling_the_satellite_tools_repository.adoc, guides/common/modules/installing_overview.adoc, guides/common/modules/performing_initial_configuration_sat_server_answerfile.adoc, guides/common/modules/ports_prerequisites.adoc, guides/common/modules/ports_prerequisites_satellite_disconnected.adoc, guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc, guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-hosts.adoc, guides/common/modules/proc_installing-capsule-server-packages.adoc, guides/common/modules/proc_registering-to-satellite-server.adoc, guides/common/modules/proc_resolving-package-dependancy-errors.adoc, guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc, guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc, guides/common/modules/ref_system-requirements.adoc, guides/common/modules/synchronizing_the_satellite_tools_repository.adoc, guides/common/modules/using_external_databases.adoc
As part of
Bug 1797957 - Write upstream/downstream conditions for Installing
Satellite Server (Connected) guide
https://bugzilla.redhat.com/show_bug.cgi?id=1797957
=> Add ifevals for Katello and Red Hat only content

guides/doc-Provisioning_Guide/master.adoc, guides/doc-Provisioning_Guide/topics/Cloud-Azure.adoc, guides/doc-Provisioning_Guide/topics/Common_Compute_Resource_Prereqs.adoc
Bug 1774400 - [RFE] Add documentation for provisioning cloud instances in Microsoft Azure compute resource
https://bugzilla.redhat.com/show_bug.cgi?id=1774400
=> Add the Provisioning Cloud Instances in Microsoft Azure Resource Manager chapter

guides/common/modules/proc_adding-life-cycle-environments.adoc
As part of
Bug 1800485 - [DDF] It would be great, to have a link or explanation,
what's the difference between Optimized and Complete Sync
https://bugzilla.redhat.com/show_bug.cgi?id=1800485
=> Add ifevals for xref or link to cross reference

guides/common/modules/proc_registering-to-satellite-server.adoc
As part of
Bug 1804137 - Change command for installing katello-ca-consumer
https://bugzilla.redhat.com/show_bug.cgi?id=1804137
=> Update commands to download and install katello-ca-consumer

guides/common/attributes.adoc, guides/common/modules/configuring_satellite_external_idm_dns.adoc, guides/common/modules/using_insights_with_satellite_server.adoc
As part of
Bug 1802497 - [upstream] add attribute for satellite-maintain packages
for upstream/downstream
https://bugzilla.redhat.com/show_bug.cgi?id=1802497
=> add attribute for satellite-maintain packages install

guides/common/modules/proc_registering-to-satellite-server.adoc
As part of
Bug 1804137 - Change command for installing katello-ca-consumer
https://bugzilla.redhat.com/show_bug.cgi?id=1804137
=> Apply @spetrosi's feedback

guides/common/assembly_configuring-capsule-custom-server-certificate.adoc, guides/common/assembly_configuring-satellite-custom-server-certificate.adoc, guides/common/assembly_installing-capsule-server.adoc, guides/common/attributes.adoc, guides/common/modules/AWS_Prerequisites.adoc, guides/common/modules/con_ports-and-firewalls-requirements.adoc, guides/common/modules/creating_and_installing_manifests.adoc, guides/common/modules/enabling_client_connections_to_satellite.adoc, guides/common/modules/proc_adding-life-cycle-environments.adoc, guides/common/modules/proc_configuring-capsule-default-certificate.adoc, guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc, guides/common/modules/proc_configuring-repositories.adoc, guides/common/modules/proc_creating-a-custom-certificate.adoc, guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc, guides/common/modules/proc_enabling-power-management-on-managed-hosts.adoc, guides/common/modules/proc_installing-capsule-server-packages.adoc, guides/common/modules/proc_registering-to-satellite-server.adoc, guides/common/modules/ref_supported-operating-systems.adoc, guides/common/modules/ref_system-requirements.adoc, guides/doc-Installing_Capsule_Server/master.adoc, guides/doc-Installing_Satellite_Server_Connected/master.adoc
As part of
Bug 1797970 - Write upstream/downstream conditions for Installing
Capsule guide
https://bugzilla.redhat.com/show_bug.cgi?id=1797970
=> Final changes for Capsule upstreaming

guides/common/modules/supported_browsers.adoc
State that project supports recent versions of Firefox and Chrome
Bug 1784252 - Need to update supported browser details in the installation guide
https://bugzilla.redhat.com/show_bug.cgi?id=1784252
=> Update Supported Browsers 

guides/common/attributes.adoc, guides/common/modules/performing_initial_configuration_sat_server_answerfile.adoc, guides/common/modules/performing_initial_configuration_sat_server_manual.adoc, guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
Bug 1804223 - P1 Feedback on Installing from a Connected Network
https://bugzilla.redhat.com/show_bug.cgi?id=1804223
=> 6.7 beta P1 feedback

guides/common/modules/ref_system-requirements.adoc
Bug 1796622 - [DDF] Does this mean Disk space or RAM? Unclear. Context means Disk space, but this should be clarified
https://bugzilla.redhat.com/show_bug.cgi?id=1796622
=> Clarify that memory means RAM to avoid any confusion

guides/doc-Provisioning_Guide/topics/Cloud-GCE.adoc
Bug 1777312 - [RFE] Add Hammer commands for provisioning with GCE
https://bugzilla.redhat.com/show_bug.cgi?id=1777312
=> Add CLI commands to Provisioning Cloud Instances in GCE

guides/common/Makefile
attempting to update linkchecker for new content management error
=> Add ignore for file:///modules

guides/satellite-sync.sh
Here is the sync script for upstream/downstream use
=> Adding upstream/downstream sync script

guides/common/attributes.adoc, guides/common/modules/proc_installing-the-katello-agent.adoc, guides/doc-Content_Management_Guide/master.adoc, guides/doc-Content_Management_Guide/topics/Creating_an_Application_Life_Cycle.adoc, guides/doc-Content_Management_Guide/topics/Importing_Red_Hat_Content.adoc, guides/doc-Content_Management_Guide/topics/Introduction.adoc, guides/doc-Content_Management_Guide/topics/Managing_Activation_Keys.adoc, guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc, guides/doc-Content_Management_Guide/topics/Managing_Subscriptions.adoc, guides/doc-Content_Management_Guide/topics/Using_ISS.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
Make CMG work for both upstream and downstream
=> Bz#1816749

guides/satellite-sync.sh
I tested it and it works fine.
=> Update the sync script to include CMG

guides/doc-Content_Management_Guide/topics/Managing_Activation_Keys.adoc
Bug 1827497 - [Sat6.6+] Improve the "3 possible scenarios for subscribing with activation keys" in Sat6.6/6.7 in Content Management Guide
https://bugzilla.redhat.com/show_bug.cgi?id=1827497
=> Clarify info subs auto-attachment

guides/doc-Provisioning_Guide/topics/Resources.adoc
A user asked, this is confusing so hopefully this fixes it.
=> Improve cloud-init explanation

guides/doc-Deploying_on_AWS/docinfo.xml, web/index.html
Also added a subtitle for downstream
https://bugzilla.redhat.com/show_bug.cgi?id=1829310
=> Added AWS guide to index file

guides/common/attributes.adoc, guides/common/modules/proc_enabling-the-satellite-tools-repository.adoc, guides/common/modules/proc_installing-the-katello-agent.adoc, guides/common/modules/proc_synchronizing-the-satellite-tools-repository.adoc, guides/doc-Provisioning_Guide/topics/app-init_script.adoc
Bug 1835718 - Make the wording of Satellite Tools repository consistent throughout the guides
https://bugzilla.redhat.com/show_bug.cgi?id=1835718
=> Fix Satellite Tools repo wording to use an attribute

guides/doc-Managing_Hosts/master.adoc, guides/upstreamize.rb
Bug 1835683 - [upstream] Move the Managing Hosts upstream
https://bugzilla.redhat.com/show_bug.cgi?id=1835683
=> Some further corrections to the Managing Hosts guide

guides/doc-Managing_Hosts/topics/Running_Jobs_on_Hosts.adoc
Bug 1832870 - Update docs with fifi feedback
https://bugzilla.redhat.com/show_bug.cgi?id=1832870
=> Add AWS link for REX

guides/upstreamize.rb
=> Improve upstreamize script - options statement

guides/doc-Managing_Hosts/topics/Adding_Systems_to_System_Groups.adoc, guides/doc-Managing_Hosts/topics/Creating_System_Groups.adoc, guides/doc-Managing_Hosts/topics/Generating_Host_Monitoring_Reports.adoc, guides/doc-Managing_Hosts/topics/Host_Management_without_Goferd.adoc, guides/doc-Managing_Hosts/topics/Integrating_Satellite_and_Ansible_Tower.adoc, guides/doc-Managing_Hosts/topics/Removing_System_Groups.adoc, guides/doc-Managing_Hosts/topics/Running_Jobs_on_Hosts.adoc, guides/doc-Managing_Hosts/topics/Synchronizing_Templates.adoc, guides/doc-Managing_Hosts/topics/Template_Writing.adoc, guides/doc-Managing_Hosts/topics/proc_adding-a-bmc-interface.adoc, guides/doc-Managing_Hosts/topics/proc_adding-a-bonded-interface.adoc, guides/doc-Managing_Hosts/topics/proc_creating-a-host-group.adoc, guides/doc-Managing_Hosts/topics/proc_creating-a-host-in-satellite.adoc, guides/doc-Managing_Hosts/topics/proc_exporting_report_templates.adoc, guides/doc-Managing_Hosts/topics/proc_exporting_report_templates_api.adoc, guides/doc-Managing_Hosts/topics/proc_importing_report_templates_api.adoc, guides/doc-Managing_Hosts/topics/proc_installing-and-configuring-the-puppet-agent.adoc, guides/doc-Managing_Hosts/topics/proc_integrating_satellite_with_red_hat_web_console.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-satellite-using-the-bootstrap-script.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-satellite.adoc, guides/doc-Managing_Hosts/topics/proc_registering-an-atomic-host-to-satellite.adoc, guides/doc-Managing_Hosts/topics/ref_advanced-bootstrap-script-configuration.adoc, guides/doc-Managing_Hosts/topics/ref_template_macros.adoc
Bug 1835683 - [upstream] Move the Managing Hosts upstream
https://bugzilla.redhat.com/show_bug.cgi?id=1835683
=> Run the new upstreamize.rb on the Managing Hosts guide

guides/doc-Administering_Red_Hat_Satellite/master.adoc
=> Add TOC numbering for the Admin guide

guides/doc-Provisioning_Guide/topics/Infoblox_Integration.adoc
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1811688
PR for 6.7 branch,
=> Replace hard coded password in curl command with variable

guides/doc-Managing_Hosts/topics/proc_removing-a-host-from-satellite.adoc
Clarify that removing hosts from **Content Hosts** and **All Hosts** pages does the same thing - removes hosts completely
https://bugzilla.redhat.com/show_bug.cgi?id=1848181
=> Clarify hosts removal

guides/doc-Administering_Red_Hat_Satellite/topics/proc_integrating-satellite-with-red-hat-single-sign-on-for-external-authentication.adoc
=> Hide tech preview upstream

guides/common/assembly_provisioning-virtual-machines-rhv.adoc, guides/common/modules/proc_configuring-an-external-dhcp-server.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/ssh-keys.adoc, guides/doc-Managing_Hosts/topics/Administering_Hosts.adoc, guides/doc-Managing_Hosts/topics/Template_Writing.adoc, guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc, guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc
Bug 1841101 - Add a note that it is required to enable dhcp-no-override on dnsmasq
https://bugzilla.redhat.com/show_bug.cgi?id=1841101
=> Add DHCP override note

guides/doc-Managing_Hosts/topics/Host_Management_without_Goferd.adoc
Bug 1851052 - [Docs] Notify RHV customers to NOT remove katello-agent
https://bugzilla.redhat.com/show_bug.cgi?id=1851052
=> Add a note to not remove katello-agent for RHV users #2 

guides/common/attributes.adoc, guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Debian/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml
Bug 1850561 - Update attributes.adoc and docinfo files for 6.8
https://bugzilla.redhat.com/show_bug.cgi?id=1850561
=> Change version in attributes and docinfo.xml to 6.8 Beta

guides/common/attributes.adoc, guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc, guides/common/modules/proc_configuring-server-for-kvm-connections.adoc, guides/common/modules/proc_using-insights-with-satellite-server.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/Configuring_Identity_Management.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/Maintenance.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/adding_rhel_system_roles.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/configuring-idm-authentication-on-satellite-server.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/creating-a-complete-permission-table.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/enrolling-satellite-server-with-the-ad-server.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/proc_integrating-satellite-with-red-hat-single-sign-on-for-external-authentication.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc, guides/doc-Content_Management_Guide/topics/Managing_Custom_File_Type_Content.adoc, guides/doc-Content_Management_Guide/topics/appendix-NFS_Share.adoc, guides/doc-Managing_Hosts/topics/Running_Jobs_on_Hosts.adoc, guides/doc-Managing_Hosts/topics/Synchronizing_Templates.adoc, guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc, guides/doc-Provisioning_Guide/topics/proc_installing-the-discovery-service.adoc, guides/upstreamize.rb
Bug 1825798 - [RFE] Document that satellite-maintain package feature on Capsule`
https://bugzilla.redhat.com/show_bug.cgi?id=1825798
=> Use attribute for yum when manipulating packages from Capsules

guides/doc-Managing_Hosts/topics/Running_Jobs_on_Hosts.adoc
Bug 1825798 - [RFE] Document that satellite-maintain package feature on Capsule
https://bugzilla.redhat.com/show_bug.cgi?id=1825798
=> Fix yum install in Managing Hosts guide

guides/doc-Administering_Red_Hat_Satellite/topics/impersonating-a-different-user-account.adoc
Bug 1852359 - [Docs] [Administering Red Hat Satellite] Update references to the impersonation UI label
https://bugzilla.redhat.com/show_bug.cgi?id=1852359
=> Update docs to correspond to a new UI label name

.github/workflows/deploy.yml, web/CNAME
@lzap as one couldn't test it -- it didn't work ;-)
=> properly add the cname at the right spot

guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
Bug 1813311 - Document UEFI HTTP boot provisioning
https://bugzilla.redhat.com/show_bug.cgi?id=1813311
=> Create procedure for UEFI HTTP Boot provisioning

guides/common/attributes.adoc
Bug 1866385 - Update attributes.adoc and docinfo files for 6.8 Beta
https://bugzilla.redhat.com/show_bug.cgi?id=1866385
=> Change the ProductVersion attribute for the 6.8-beta branch

guides/common/attributes.adoc
Bug 1866385 - Update attributes.adoc and docinfo files for 6.8 Beta
https://bugzilla.redhat.com/show_bug.cgi?id=1866385
=> Update repositories attributes for 6.8 Beta release

guides/common/assembly_provisioning-cloud-instances-azure.adoc, guides/common/modules/proc_adding-azure-connection.adoc, guides/common/modules/proc_adding-images-to-server.adoc, guides/common/modules/proc_creating-image-only-hosts.adoc
[RFE] Support shared images on Azure
https://bugzilla.redhat.com/show_bug.cgi?id=1827584
=> Add docs updates for Azure provisioning using custom images

guides/doc-Managing_Hosts/topics/Adding_Systems_to_System_Groups.adoc, guides/doc-Managing_Hosts/topics/Removing_Systems_from_System_Groups.adoc
* Add note about auditing of host collection
Fixes #256 
See: 
https://community.theforeman.org/t/missing-audit-record-for-host-collection-changes/20390/3?u=mcorr
=> Add ifeval to remove broken link

guides/common/assembly_provisioning-cloud-instances-azure.adoc, guides/common/modules/proc_adding-azure-connection.adoc, guides/common/modules/proc_adding-images-to-server.adoc, guides/common/modules/proc_creating-image-only-hosts.adoc
=> Apply changes from PR258 about Azure provisioning using custom images.

guides/doc-Provisioning_Guide/topics/Networking.adoc
This is constantly being asked, finally it is making its way into docs.
=> Add info about multiple DHCP subnets

guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc, guides/common/modules/proc_configuring-external-dns.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1873814
=> 1873814 - foreman-proxy belongs to named group

guides/common/attributes.adoc, guides/doc-Managing_Hosts/topics/host_management_and_monitoring_using_red_hat_web_console.adoc, guides/doc-Managing_Hosts/topics/proc_integrating_satellite_with_red_hat_web_console.adoc, guides/doc-Managing_Hosts/topics/proc_managing_and_monitoring_hosts_using_red_hat_web_console.adoc, guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc
=> Add attribute and upstreamize web console/cockpit docs

guides/common/assembly_configuring-an-alternate-cname.adoc, guides/common/modules/proc_configuring-hosts-to-use-an-alternate-cname-for-content-management.adoc, guides/common/modules/proc_configuring-project-with-an-alternate-cname.adoc, guides/common/modules/proc_configuring-satellite-with-an-alternate-cname.adoc, guides/doc-Installing_Server_on_Red_Hat/master.adoc
Bug 1828219 - [RFE] Document using multi-homed
https://bugzilla.redhat.com/show_bug.cgi?id=1828219
=> Add section that configures alternate CNAME

guides/common/attributes.adoc, guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Debian/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml
Bug 1883526 - Update attributes.adoc and docinfo files for 6.8
https://bugzilla.redhat.com/show_bug.cgi?id=1883526
=> Update docinfo.xml and attributes.adoc files for 6.8 version

guides/common/assembly_preparing-environment-for-installation-in-ipv6-network.adoc, guides/common/assembly_preparing-environment-for-satellite-installation-ipv6.adoc, guides/common/modules/con_limitations-of-installation-in-an-ipv6-network.adoc, guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc, guides/common/modules/proc_configuring-for-uefi-http-boot-ipv6-provisioning.adoc, guides/doc-Installing_Server_on_Red_Hat/master.adoc
Bug 1826824 - [RFE] IPv6 support
https://bugzilla.redhat.com/show_bug.cgi?id=1826824O
=> Add content about installing project on IPv6

guides/doc-Managing_Hosts/master.adoc, guides/doc-Managing_Hosts/topics/proc_Upgrading_RHEL7_Hosts_to_RHEL8.adoc, guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc
Bug 1716931 - [RFE] Initiate upgrade from RHEL 7 to RHEL 8 using LEAPP
https://bugzilla.redhat.com/show_bug.cgi?id=1716931
=> Add draft procedure for RHEL7 to RHEL8 clients upgrade with LEAPP

guides/doc-Deploying_on_AWS/topics/AWS_Use_Case_Considerations.adoc
Bug 1823868 - Need to clarify that Multi-homed satellite setup is not supported
https://bugzilla.redhat.com/show_bug.cgi?id=1823868
=> Note support status of Project and Smart Proxies

guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
=> Security iPXE info only applies to Satellite

guides/common/modules/ref_dynamic_partition_example.adoc, guides/doc-Provisioning_Guide/master.adoc
=> Add dynamic kickstart example and info

guides/common/modules/ref_dynamic_partition_example.adoc
as part of issue #74
If you get time Sergei, you should create a section in help with examples of FCC templates and formatting. 
I have already erased all this from my mind and when we grow, we don't want to inconvenience developers with this.
=> update some missed errors

guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc
Bug 1887695 - Instruct to use Immediate policy for discovery rebuild
https://bugzilla.redhat.com/show_bug.cgi?id=1887695
=> Add a prerequisite to change download policy to immediate

guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Prerequisites.adoc
Very minor updates to try out making a PR to Foreman docs.
=> Minor updates to aws deploy guide

guides/doc-Administering_Red_Hat_Satellite/topics/adding_rhel_system_roles.adoc
=> Fix attribute for foreman-installer

guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc
Fixes #276
Hope this captures: 
https://github.com/theforeman/foreman-documentation/issues/276
Thanks, 
Melanie
=> Add note about EC2 Finish template using SSH

guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
=> Add {ProductVersion} attribute to link

guides/doc-Provisioning_Guide/topics/proc_creating-hosts-from-discovered-hosts.adoc
Bug 1887666 - Improve discovery provisioning setup
https://bugzilla.redhat.com/show_bug.cgi?id=1887666
=> Add prerequisites to creating hosts from discovery

guides/common/modules/con_about-running-jobs-on-hosts.adoc, guides/common/modules/con_remote-execution-workflow.adoc, guides/common/modules/con_ssh-key-for-remote-execution-overview.adoc, guides/common/modules/proc_configuring-an-alternative-directory-to-execute-remote-jobs-on-clients.adoc, guides/common/modules/proc_setting-up-job-templates.adoc, guides/doc-Configuring_Ansible/master.adoc
Add ifevals for Ansible context
=> Add Adam Ruzicka's feedback

web/index.html
After this is published downstream, I will do all the links!
=> add link to Foreman Ansible config guide

guides/doc-Provisioning_Guide/topics/Networking.adoc
This happens quite often, I think it is a good idea to have it here.
=> Add orchestrate rake tasks to Troubleshooting

guides/doc-Provisioning_Guide/topics/configuring_the_discovery_service.adoc, guides/doc-Provisioning_Guide/topics/proc_installing-the-discovery-service.adoc
it has been SCLed a few releases ago
=> correct proxy discovery plugin name

guides/doc-Provisioning_Guide/topics/Networking.adoc
Add a single space after the inline code.
=> Fix inline code

guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc
Small PR to fix the `ls` command.
[source: man page](https://linux.die.net/man/1/ls)
=> Fix ls command

guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc
It is important that DNS is working both on Server and Smart Proxy.
=> Add a note about DNS for provisioning

guides/doc-Managing_Hosts/topics/Administering_Hosts.adoc
Bug 1901920 - [RFE] Document setting system purpose on multiple hosts
via bulk action
https://bugzilla.redhat.com/show_bug.cgi?id=1901920
=> Document editing the system purpose of multiple hosts

README.md
This PR extends the readme with a most basic explanation of the source file prefixes and conventions regarding variable user input.
Feel free to extend/comment/rewrite.
@melcorr
=> Add structure and conventions to readme

guides/doc-Deploying_on_AWS/topics/AWS-registering-hosts-using-the-bootstrap-script.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Installing_Capsule_on_AWS.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Prerequisites.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Use_Case_Considerations.adoc
This PR converts the "Deploying on AWS" guide to follow the one sentence per line idea.
See #326
=> Convert to one sentence per line

guides/common/assembly_installing-satellite-server-connected.adoc, guides/common/assembly_installing-satellite-server-disconnected.adoc, guides/common/attributes.adoc, guides/common/modules/con_provisioning-contexts.adoc, guides/common/modules/con_provisioning-templates.adoc, guides/common/modules/proc_adding-life-cycle-environments.adoc, guides/common/modules/proc_registering-to-satellite-server.adoc, guides/common/modules/proc_using-a-synced-kickstart-repository.adoc, guides/common/modules/snip_common-compute-resource-prereqs.adoc, guides/doc-Configuring_Load_Balancer/topics/Promoting_SCAP_Content_to_Clients.adoc, guides/doc-Content_Management_Guide/topics/Importing_Red_Hat_Content.adoc, guides/doc-Content_Management_Guide/topics/Managing_ISOs_and_Files.adoc, guides/doc-Content_Management_Guide/topics/Using_ISS.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Use_Case_Considerations.adoc, guides/doc-Managing_Hosts/topics/Administering_Hosts.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-satellite-using-the-bootstrap-script.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-satellite.adoc, guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc, guides/doc-Planning_Guide/topics/Deployment_Scenarios.adoc, guides/doc-Planning_Guide/topics/Introduction.adoc, guides/doc-Provisioning_Guide/topics/app_create_images.adoc, guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc, guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc
=> Edit links to the Content Management guide

guides/common/attributes.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Use_Case_Considerations.adoc
=> Edit ilnks to the Configuring with Load Balancer guide

guides/common/attributes.adoc, guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc, guides/common/modules/ref_satellite-ports-and-firewalls-requirements.adoc, guides/doc-Content_Management_Guide/topics/Using_ISS.adoc, guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
=> Edit links to the Planning guide

guides/common/modules/ref_system-requirements.adoc, guides/doc-Planning_Guide/topics/Introduction.adoc
=> Fixes 1911570 - SELinux in disabled is not supported

guides/doc-Managing_Hosts/master.adoc, guides/doc-Managing_Hosts/topics/Registering_Hosts.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-project-using-the-global-registration-template.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-satellite-manually.adoc, guides/doc-Managing_Hosts/topics/ref_customizing-the-global-registration-and-host-registration-templates.adoc
Bug 1903684 - [RFE] Document registering hosts to Satellite by running
curl on the hosts
https://bugzilla.redhat.com/show_bug.cgi?id=1903684
=> Document registering hosts to Foreman by running curl on the hosts

guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc, guides/common/modules/ref_satellite-ports-and-firewalls-requirements.adoc, guides/doc-Planning_Guide/topics/Capsule_Server_Overview.adoc
Bug 1896012 - [RFE] Include a comprehensive overview of connections
https://bugzilla.redhat.com/show_bug.cgi?id=1896012
=> Change link to point to the new KCS solution for port matrix

guides/common/attributes.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1918485
=> Update version numbers in attributes.adoc for 6.9-beta release

guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml, guides/doc-Provisioning_Guide/docinfo.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1918485
=> Update version number in docinfo.xml to 6.9 Beta for the upstream guides

guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml, guides/doc-Provisioning_Guide/docinfo.xml
Cherrypicked from https://github.com/theforeman/foreman-documentation/pull/381
=> Bz#1918485 docinfo 6.9beta

guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-project-using-the-global-registration-template.adoc
Hello
See discussion https://github.com/theforeman/foreman-documentation/pull/386
Thank you
=> Selecting SmartProxy is not optional  in Global Reg procedure

guides/doc-Managing_Hosts/topics/Template_Writing.adoc
[RFE] Document how to find template writing reference document in the Satellite web UI
https://bugzilla.redhat.com/show_bug.cgi?id=1901937
=> Add section about template writing reference in the web UI.

web/layouts/shortcodes/guide-list.html
it was pointing to the server guide
=> Fix proxy install guide link

guides/common/assembly_installing-capsule-server.adoc, guides/common/modules/proc_creating-a-custom-certificate.adoc, guides/common/modules/proc_enabling-capsule-in-UI.adoc, guides/common/modules/ref_capsule-storage-requirements.adoc, guides/doc-Managing_Hosts/topics/Template_Writing.adoc
Updates backported from master. Somehow last two cherry-picks didn't make it to the SATELLITE-6.9-beta branch and now got included in this PR.
=> Bz1902037 install capsule 6.9beta

.github/workflows/deploy.yml, guides/common/attributes.adoc
The next major version pair 2.4/4.0.
I am still having issues with that if statement, looks like the startsWith does not recognize that glob. It can only be used in the "on" statement. I wonder if I remove the test and only test owner if this is what I want:
* it triggers only for master and X.Y branches
* for pull requests artifacts are built
* for theforeman owner site is also deployed
Do not merge yet.
=> Update versions to 2.4/4.0

guides/common/attributes.adoc
=> Update ProductVersion attribute to 6.9-beta

guides/common/modules/proc_configuring-your-deployment-to-run-ansible-roles.adoc
=> Fix broken link in Ansible guide

web/layouts/404.html
I had a typo in the JS code, it's not `index.html`!
=> Improve 404 redirect path

web/content/version-2.3/index.md
Mostly I want to see if web/ deploys fine. But this is something we could start doing for every release.
=> Added headline fetures for 2.3

guides/common/assembly_migrating-from-internal-databases-to-external-databases.adoc, guides/common/assembly_using-external-databases.adoc, guides/common/modules/con_applying-custom-configuration.adoc, guides/common/modules/proc_configuring-hosts-to-use-an-alternate-cname-for-content-management.adoc, guides/common/modules/proc_configuring-satellite-manually.adoc, guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc, guides/common/modules/proc_migrating-to-external-databases.adoc, guides/common/modules/ref_capsule-storage-requirements.adoc, guides/common/modules/ref_storage-guidelines.adoc, guides/common/modules/ref_storage-requirements.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/Monitoring_Capsules.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/log-files-provided-by-satellite.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/proc_estimating-the-size-of-a-backup.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/proc_performing-a-snapshot-backup.adoc, guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc, guides/doc-Content_Management_Guide/topics/appendix-NFS_Share.adoc, guides/doc-Planning_Guide/topics/Glossary.adoc
Contains https://github.com/theforeman/foreman-documentation/pull/390 which should go in first
=> Update pulp 3

README.md, guides/README.md
I had a go at updating the guidelines to make some things, like the templates, more visible. Happy to make any changes/add info/remove info as you like. I think this looks pretty okay for now, but let me know your thoughts on how you ideally want it to look.
=> Update contributing guidelines

guides/doc-Content_Management_Guide/master.adoc, guides/doc-Content_Management_Guide/topics/QuickStart.adoc
* Add numbers to chapters
* Add ifdef
* Add to Introduction
* Retain one sentence per line
* Keep conventions & style
=> Standardize new Content management intro

guides/common/attributes.adoc, guides/doc-Upgrading_and_Updating/master.adoc, guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/introduction_updating_satellite.adoc, guides/doc-Upgrading_and_Updating/topics/synchronizing_the_new_repositories.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_clients.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc
There might be more. 
Will let link checker do the work.
=> Fix broken links

guides/doc-Upgrading_and_Updating/master.adoc, web/layouts/shortcodes/guide-list.html
=> Added menu to upgrade guide

web/layouts/shortcodes/guide-list.html
Forgot to close parenthesis on links. I'm an idiot. 
=> Add parenthesis I left out

guides/doc-Content_Management_Guide/topics/QuickStart.adoc
=> Add content view workflow to Quickstart document

guides/common/assembly_installing-capsule-server.adoc, guides/common/modules/proc_configuring-capsule-container-gateway.adoc, guides/doc-Content_Management_Guide/master.adoc, guides/doc-Content_Management_Guide/topics/Containers_interacting_with_registry.adoc
This PR adds some information about the Container Gateway.
=> Add Container Gateway info

guides/common/attributes.adoc, guides/doc-Content_Management_Guide/topics/Managing_ISOs_and_Files.adoc
Minor PR to fix to spelling errors.
=> Fix spelling

guides/doc-Provisioning_Guide/topics/proc_creating-discovery-rules.adoc
Only merge when/if https://github.com/theforeman/foreman/pull/8072 is merged
Thanks!
=> Added discovery counter helper macro

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
=> Adding initial docs for the new import/export

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
This MR fixes a couple of minor spelling errors and rewords one sentence. This might be in conflict with #475 🤷  I can simply rebase whatever gets merged second.
=> Fix various minor spelling errors

guides/common/assembly_provisioning-cloud-instances-azure.adoc, guides/common/assembly_provisioning-cloud-instances-gce.adoc, guides/common/assembly_provisioning-virtual-machines-kubevirt.adoc, guides/common/modules/con_provisioning-contexts.adoc, guides/common/modules/con_provisioning-overview.adoc, guides/common/modules/con_provisioning-templates.adoc, guides/common/modules/con_provisioning-workflow.adoc, guides/common/modules/con_types-of-provisioning-templates.adoc, guides/common/modules/proc_adding-installation-media.adoc, guides/common/modules/proc_cloning-provisioning-templates.adoc, guides/common/modules/proc_creating-architectures.adoc, guides/common/modules/proc_creating-hardware-models.adoc, guides/common/modules/proc_creating-image-only-hosts.adoc, guides/common/modules/proc_creating-network-or-image-based-hosts.adoc, guides/common/modules/proc_creating-partition-tables.adoc, guides/common/modules/proc_installing-the-azurerm-plugin.adoc, guides/common/modules/proc_setting-the-provisioning-context.adoc, guides/common/modules/proc_using-a-synced-kickstart-repository.adoc, guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc, guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc, guides/doc-Provisioning_Guide/topics/Networking.adoc, guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc, guides/doc-Provisioning_Guide/topics/configuring_the_discovery_service.adoc, guides/doc-Provisioning_Guide/topics/proc_building-a-discovery-image.adoc, guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc, guides/doc-Provisioning_Guide/topics/proc_implementing-pxe-less-discovery.adoc, guides/doc-Provisioning_Guide/topics/proc_installing-the-discovery-service.adoc, guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc
This PR adapts provisioning documentation files for usage in the documentation of the downstream product orcharhino.
=> Adapt provisioning guide

web/content/_index.md
SSIA
Let me know what I missed
=> Add downstream documentation links

guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
=> [CP] Additional upgrade instructions for Katello 4.0/Foreman 2.4.

guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml, guides/doc-Provisioning_Guide/docinfo.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1951584
=> Update version numbers in docinfo.xml for 6.9 GA release

.github/PULL_REQUEST_TEMPLATE.md, README.md, guides/common/linkchecker.ini, web/content/2.3.md, web/content/2.4.md, web/content/_index.md, web/content/versions.md
I am following the https://github.com/theforeman/foreman-documentation#branching-new-release instructions. Slightly updated them because there was a change from the last version.
I am going to branch off 2.4 and push and let it build. Will comment once this is ready to be merged.
List of PRs I have identified (maybe) should go into 2.4/4.0. We were a bit late for this release due to huge changes on Katello side:
=> Branching 2.4 manual set

guides/doc-Managing_Hosts/topics/proc_registering-a-host-to-project-using-the-global-registration-template.adoc
=> Add curly brackets to foreman-installer

guides/common/modules/proc_configuring-repositories.adoc
=> Add line to enable PostgreSQL 12 module on EL8

guides/common/modules/proc_configuring-repositories-el.adoc
=> enable ansible repo on el8

guides/common/modules/proc_configuring-repositories-proxy.adoc, guides/common/modules/proc_configuring-repositories.adoc
=> Use centos-release-scl-rh instead of foreman-release-scl

guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
* [ x] Foreman 2.4
* [ x] Foreman 2.3 (Satellite 6.9)
* [ x] Foreman 2.1 (Satellite 6.8)
=> Corrected command line to disable/enable repositories

guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc
Buttons are ~usually~ by convention in bold font and capitalized, i.e. surrounded by `*`.
I've used `git grep -i -n "click submit"` & `git grep "click \*submit"` to find this.
=> Fix highlighting for submit button

guides/common/assembly_using-puppet-for-configuration-management.adoc, guides/common/modules/con_puppet-architecture.adoc, guides/common/modules/con_puppet-introduction.adoc, guides/common/modules/proc_puppet-configuring-a-puppet-class.adoc, guides/common/modules/proc_puppet-importing-a-puppet-module.adoc, guides/common/modules/proc_puppet-installing-a-puppet-module-from-puppet-forge.adoc, guides/common/modules/proc_puppet-managing-puppet-modules-with-r10k.adoc, guides/common/modules/proc_puppet-overriding-puppet-parameters-individual-host.adoc, guides/common/modules/proc_puppet-overriding-puppet-parameters-location-based.adoc, guides/common/modules/proc_puppet-overriding-puppet-parameters-organization-based.adoc, guides/common/modules/proc_puppet-prerequisites.adoc, guides/common/modules/proc_puppet-run-puppet-once-using-ssh.adoc, guides/common/modules/proc_puppet-updating-a-puppet-module.adoc, guides/common/modules/proc_puppet-using-puppet-classes-host-group.adoc, guides/common/modules/proc_puppet-using-puppet-classes-individual-host.adoc, guides/common/modules/proc_puppet-using-puppet-classes-puppet-config-group.adoc, guides/common/modules/proc_puppet-using-puppet-classes.adoc, guides/common/modules/ref_puppet-additional-resources.adoc, guides/common/modules/ref_puppet-parameter-hierarchy.adoc, guides/doc-Managing_Hosts/master.adoc
Hi everyone!
This PR adds  `Puppet for configuration management` to the 'managing hosts' guide.
Feedback is welcome. I know there are missing sections and I would like to add them at a later stage.
Have a nice week.
=> Add puppet for configuration management

guides/common/modules/con_puppet-architecture.adoc, guides/common/modules/con_remote-execution-workflow.adoc, guides/common/modules/proc_configuring-the-fallback-to-any-smartproxy-setting.adoc, guides/common/modules/proc_puppet-managing-puppet-modules-with-r10k.adoc, guides/common/modules/proc_puppet-overriding-puppet-parameters-location-based.adoc, guides/common/modules/proc_puppet-prerequisites.adoc, guides/common/modules/proc_puppet-updating-a-puppet-module.adoc, guides/common/modules/proc_puppet-using-puppet-classes.adoc, guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc, guides/common/modules/ref_ports-and-firewall-requirements.adoc, guides/doc-Managing_Hosts/topics/Template_Writing.adoc, guides/doc-Planning_Guide/topics/Capsule_Server_Overview.adoc, guides/doc-Planning_Guide/topics/Glossary.adoc, guides/doc-Planning_Guide/topics/Introduction.adoc
This PR is a response to @ekohl's feedback on #550
=> Rework Puppet

guides/common/assembly_provisioning-cloud-instances-azure.adoc, guides/common/modules/proc_adding-azure-connection.adoc, guides/common/modules/proc_adding-azure-details-to-a-compute-profile.adoc
=> Update provisining guide with updated Azure info and Gov Cloud

web/layouts/shortcodes/guide-list.html
=> Add webhooks working title

guides/common/modules/con_provisioning-workflow.adoc
We do not provide description of production host boot sequence.
=> Improve provisioned host workflow

guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
Reported in https://community.theforeman.org/t/upgrade-docs/24121
=> Add stop services step

guides/common/modules/proc_installing-satellite-ansible-modules-via-rpm.adoc, guides/common/modules/proc_listing-using-satellite-ansible-modules.adoc
This PR adapts the usage of FAM for our downstream product orcharhino.
=> Adapt FAM for orcharhino

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc
For https://bugzilla.redhat.com/show_bug.cgi?id=1975098
=> Host registration - update 'setup rex & insights'

guides/common/modules/ref_system-requirements.adoc
SSIA FAIK only Red Hat Satellite QA team does that.
=> FIPS is only tested on RHEL

guides/doc-Provisioning_Guide/topics/configuring_the_discovery_service.adoc
=> Note about discovery naming scheme

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
=> Fix some broken attribute wrapping

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
=> Add correct wrapper for attribute usage

guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc
=> Update bare metal pxe loaders for non-satellite installations

guides/common/docinfo.html
I think it is a good idea to make this a link so users can actually click to github for possible contributions.
=> Make Nightly ribbon a link

web/content/_index.md, web/layouts/partials/footer.html
See the individual commits for details. In short:
* It changes the link order on the index
* It links to latest official docs rather than nightly
* Corrects the source link
* Add a full license text to the repo
=> Correct index + footer

guides/doc-Managing_Hosts/topics/Registering_Hosts.adoc
Red Hat, not Red Han
Bug 1963222 - Typo in the documentation
https://bugzilla.redhat.com/show_bug.cgi?id=1963222
=> Red Hat, not Red Han

guides/common/attributes-orcharhino.adoc
This PR removes unused attributes specifically for build target 'orcharhino'.
See also #616.
=> Remove unused orcharhino attributes

guides/doc-Managing_Hosts/topics/Synchronizing_Templates.adoc
SSIA see https://bugzilla.redhat.com/show_bug.cgi?id=1983146
=> Exporting templates use priv temps

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc
For https://github.com/theforeman/foreman/pull/8634/
=> Host registration - update packages field

guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc, guides/common/assembly_job-template-examples-and-extensions.adoc, guides/common/modules/con_about-running-jobs-on-hosts.adoc, guides/common/modules/con_remote-execution-workflow.adoc, guides/common/modules/proc_configuring-a-keytab-for-kerberos-ticket-granting-tickets.adoc, guides/common/modules/proc_configuring-a-kickstart-template-to-distribute-ssh-keys-during-provisioning.adoc, guides/common/modules/proc_configuring-an-alternative-directory-to-execute-remote-jobs-on-clients.adoc, guides/common/modules/proc_configuring-kerberos-authentication-for-remote-execution.adoc, guides/common/modules/proc_configuring-the-fallback-to-any-smartproxy-setting.adoc, guides/common/modules/proc_configuring-the-global-smartproxy-remote-execution-setting.adoc, guides/common/modules/proc_creating-a-job-template.adoc, guides/common/modules/proc_distributing-keys-for-remote-execution-manually.adoc, guides/common/modules/proc_executing-a-remote-job.adoc, guides/common/modules/proc_monitoring-remote-jobs.adoc, guides/common/modules/proc_setting-up-job-templates.adoc, guides/common/modules/proc_using-the-api-to-obtain-ssh-keys-for-remote-execution.adoc, guides/common/modules/ref_customizing-templates.adoc, guides/common/modules/ref_example-including-power-options-in-a-job-template.adoc, guides/common/modules/ref_example-of-executing-restorecon-on-multiple-hosts.adoc, guides/common/modules/ref_example-rendering-of-the-restorecon-template.adoc, guides/common/modules/ref_example-restorecon-template.adoc, guides/doc-Managing_Hosts/topics/Host_Management_without_Goferd.adoc
This PR fixes various whitespace: it remove unnecessary empty lines, adds lines above and below including other `.adoc` files, and removes one instance of two spaces in inline text.
=> Fix various whitespace

guides/common/modules/proc_puppet-configuring-a-puppet-class.adoc, guides/common/modules/proc_puppet-using-puppet-classes-individual-host.adoc
Fixup for https://github.com/theforeman/foreman-documentation/pull/630 🙈
=> Fix yaml source highlighting

guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc, guides/doc-Managing_Hosts/topics/Template_Writing.adoc, guides/doc-Managing_Hosts/topics/proc_adding-a-bonded-interface.adoc, guides/doc-Managing_Hosts/topics/proc_creating_a_report_template.adoc, guides/doc-Managing_Hosts/topics/proc_creating_a_report_template_for_entitlements.adoc, guides/doc-Managing_Hosts/topics/proc_importing_report_templates.adoc, guides/doc-Managing_Hosts/topics/proc_importing_report_templates_api.adoc, guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc, guides/doc-Managing_Hosts/topics/ref_customizing-the-registration-templates.adoc, guides/doc-Managing_Hosts/topics/using_report_templates.adoc
PR to fix various formatting issues as well as anchors.
=> Fix formatting

guides/common/modules/proc_puppet-prerequisites.adoc
=> Fix link to content management guide

guides/doc-Provisioning_Guide/topics/proc_using-an-imagebuilder-image-for-provisioning.adoc
This PR removes a no longer necessary conditional for orcharhino.
=> Remove conditional for orcharhino

guides/common/attributes-orcharhino.adoc
This PR bumps the orcharhino version to 5.9.
=> Bump orcharhino version

guides/common/attributes.adoc, web/content/3.0.md, web/content/_index.md, web/content/versions.md
=> Branch docs for Foreman 3.0

guides/doc-Managing_Hosts/topics/con_overview-of-hosts-in-satellite.adoc
This PR extends the list of supported compute resource providers and sorts it alphabetically.
=> Extend list of supported compute resources

guides/common/attributes.adoc
=> Set 3.0/4.2 versions

web/content/3.0.md
fixes #668
I'm unsure how to test this without merging. 
=> Add quotes to the path to render it properly

web/README.md
=> Update readme for instructions on previewing the site locally

guides/common/attributes-katello.adoc, guides/common/modules/proc_using-the-api-to-obtain-ssh-keys-for-remote-execution.adoc, guides/doc-Configuring_Load_Balancer/topics/Promoting_SCAP_Content_to_Clients.adoc
=> Correct Smart Proxy port usage

guides/common/modules/proc_adding-rhel-system-roles.adoc
🙃 
Please check if this has been cherry-picked onto other branches.
=> Fix ifdef satellite

web/layouts/partials/header.html
The Home button should behave the same in small as in wide views.
=> Correct Home link in navigation

guides/common/modules/ref_puppet-additional-resources.adoc
Github actions is failing.... This PR should fix that!
=> Fix broken link to puppet.com

guides/common/attributes-base.adoc, guides/common/attributes.adoc, guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml, guides/doc-Provisioning_Guide/docinfo.xml
Changes in attributes, attributes-base, and docinfo files for each upstream title.
https://issues.redhat.com/browse/SATDOC-452
=> Update Satellite product versions for 6.10-beta

guides/common/modules/proc_removing_an_application_instance.adoc
This PR documents a new checkbox to select/deselect all hosts when deleting an application instance in ACD.
=> Add checkbox to select all hosts when deleting an app instance

guides/common/modules/proc_configuring-repositories-deb.adoc, guides/common/modules/proc_installing-the-satellite-server-packages.adoc, guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
=> several smaller improvements to the debian docs

guides/common/modules/proc_acd_installation.adoc
This PR extends the ACD installation instructions for SmartProxyServers.
=> Add ACD installation on SmartProxyServer

guides/common/assembly_converting-a-host-with-convert2rhel.adoc
=> Fix spelling of if

guides/common/modules/con_salt-architecture.adoc, guides/common/modules/proc_puppet-configuring-a-puppet-class.adoc, guides/common/modules/proc_salt-configuring-salt.adoc, guides/common/modules/proc_salt-importing-salt-states.adoc, guides/common/modules/ref_salt-additional-resources.adoc
A few rewordings for Salt plus exented Salt terminology.
=> Reword salt

guides/common/assembly_configuring-external-idm-dns.adoc, guides/common/assembly_provisioning-virtual-machines-kvm.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/scap-content.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/security-content-automation-protocol.adoc, guides/doc-Provisioning_Guide/topics/app_create_images.adoc, guides/doc-Upgrading_and_Updating/topics/migrating_pulp_content.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc
This PR includes all the changes from #663 and #707 , _including the modifications made after review_.
ttps://issues.redhat.com/browse/SAT-4175
=> feedback to pulp3 migration guide

guides/common/sass/fonts/_overpass.scss
=> Fix url for overpass font

guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc
changes from #635 do not appear to have been cherry-picked, so I'm creating PRs against pat release branches
=> change from PR #635

guides/common/modules/proc_enabling-openscap.adoc, guides/common/modules/proc_installing-openscap-plugin.adoc, guides/common/modules/proc_running-openscap-scans.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/Security_Compliance_Management.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/configuring-a-host-for-openscap.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/configuring-a-host-group-for-openscap.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/security-content-automation-protocol.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/uploading-extra-scap-content.adoc
This PR adds a procedure to install OpenSCAP plugin, to run OpenSCAP scans, and a Hammer CLI procedure to upload extra SCAP content.
=> Extend OpenSCAP section

guides/common/assembly_provisioning-virtual-machines-kvm.adoc
More context: https://projects.theforeman.org/issues/33270
=> Note about unsupported storage libvirt types

guides/common/modules/proc_creating-a-custom-file-type-repository.adoc, guides/common/modules/proc_creating-a-local-file-repository.adoc, guides/common/modules/proc_creating-a-remote-file-repository.adoc
=> Fix spelling of HTTP proxy

guides/common/assembly_importing-content.adoc, guides/common/attributes-base.adoc, guides/common/linkchecker.ini, guides/common/modules/proc_adding-custom-deb-repositories.adoc, guides/common/modules/proc_adding-custom-deb-repository-example-for-debian-11.adoc, guides/common/modules/proc_adding-custom-rpm-repositories.adoc, guides/common/modules/proc_extracting-gpg-public-key-fingerprints-from-release-files.adoc
This PR adds procedures to manage content for Debian and Ubuntu. I will add additional procedures at a later stage/with a separate PR.
=> Add procedures to manage DEB content

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_parent.adoc
Trying to figure out why 2.5 does not build & why there was no GHA workflow.
=> Fix 2.5 gha

guides/common/assembly_converting-a-host-with-convert2rhel.adoc, guides/common/modules/proc_converting-hosts-with-convert2rhel.adoc, guides/common/modules/proc_creating-a-host-activation-key.adoc, guides/common/modules/proc_installing-convert2rhel.adoc, guides/common/modules/proc_preparing-the-host-group.adoc, guides/common/modules/proc_registering-hosts-for-conversion.adoc, guides/doc-Content_Management_Guide/master.adoc, guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc
PR #674 was not cherry-picked into 2.5, and as it has been a while
I queued up the changes in a new PR to avoid conflicts.
=> adds convert2RHEL content

guides/common/attributes-base.adoc, guides/common/attributes-satellite.adoc, guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml, guides/doc-Provisioning_Guide/docinfo.xml
Updates attributes and docinfo files for each upstream title in the Satellite doc set
=> updates Satellite version to 6.10 in attributes and docinfo files

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
* [x ] Foreman 2.5 (Satellite 6.10)
=> - Added warning on hammer import/export commands being changed

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
https://github.com/theforeman/foreman-documentation/pull/811
=> cherry pick 811 into 2.5

guides/common/attributes-base.adoc, guides/common/attributes-satellite.adoc, guides/common/attributes.adoc, guides/doc-Administering_Red_Hat_Satellite/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Content_Management_Guide/docinfo.xml, guides/doc-Deploying_on_AWS/docinfo.xml, guides/doc-Installing_Proxy_on_Red_Hat/docinfo.xml, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.xml, guides/doc-Installing_Server_on_Red_Hat/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Planning_Guide/docinfo.xml, guides/doc-Provisioning_Guide/docinfo.xml, guides/doc-Upgrading_and_Updating/docinfo.xml
Updates attributes and docinfo files changing 6.10-beta to 6.10 where appropriate.
=> updates Satellite versions in 2.5

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
This PR is an extension to https://github.com/theforeman/foreman-documentation/pull/808. I feel like I gave bad advice to @calvingsmith.
=> Do not split sentences with code blocks

guides/common/modules/proc_creating-an-installation-medium-for-debian.adoc, guides/common/modules/proc_creating-an-operating-system-for-debian.adoc, guides/doc-Provisioning_Guide/master.adoc
This PR adds two procedures to provision hosts running Debian and Ubuntu.
=> Add procedure to create operating system entry for Debian

guides/common/modules/proc_adding-scc-accounts.adoc, guides/common/modules/proc_importing-suse-products.adoc, guides/common/modules/proc_installing-the-scc-manager.adoc, guides/common/modules/proc_synchronizing-suse-content.adoc
Follow-up PR to https://github.com/theforeman/foreman-documentation/pull/776
=> Fix procedures to manage SUSE content

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
applies https://patch-diff.githubusercontent.com/raw/theforeman/foreman-documentation/pull/837.patch
=> patches 2.5 with changes from #837

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
* For Foreman 2.5, a separate PR request will be filed once this is approved
=> BZ 2010987: Add brief details about upgrade Sat 6.10

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
=> BZ 2010987: Add brief details about upgrade Sat 6.10 on 2.5

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
Tidy up paragraph
https://issues.redhat.com/browse/SATDOC-501
=> Corrected wording in chunnking paragraph

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
Attribute was not rendering correctly
Attribute rendering incorrectly
https://issues.redhat.com/browse/SATDOC-502
=> Corrected attribute

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_capsules_separately_from_satellite.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_clients.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc
Hello
I was asked to review the upgrading guide, here are some minor things I noticed while reading.
=> Feedback for upgrading section

guides/common/modules/proc_installing-postgresql.adoc, guides/common/modules/proc_migrating-to-external-databases.adoc
=> Pulpcore database in PostgreSQL should have the 'pulp' user

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
Upgrade guide for Capsules is missing information
https://issues.redhat.com/browse/SATDOC-509
=> Added additional information for Capsule upgrade

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_capsules_separately_from_satellite.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_clients.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_satellite_server_prerequisites.adoc
Hello
A cherry-pick from https://github.com/theforeman/foreman-documentation/pull/855
Thank you
=> [cherry-pick] Feedback for upgrading section

guides/common/modules/con_provisioning-workflow.adoc
[BZ1996571](https://bugzilla.redhat.com/show_bug.cgi?id=1996571)
* For Foreman 2.3 and 2.5, separate PR requests will be filed
=> BZ 1996571: Note the default to destroy associated VM on host delete

guides/common/modules/con_provisioning-workflow.adoc
=> BZ 1996571: Note the default to destroy associated VM on host delete on 2.5

guides/common/assembly_using-puppet-for-configuration-management.adoc, guides/common/modules/proc_creating-a-puppet-environment.adoc, guides/common/modules/proc_editing-a-puppet-class.adoc
This PR add two procedures to "using Puppet for configuration management".
=> Add two procedures for Puppet

guides/common/modules/proc_host_registration_steps.adoc
This PR sorts out various inconsistency that were part of b88b60bff56e067a7c62057a0010719a1d541cdf.
=> Untangle host registration procedure

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc, guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc, guides/doc-Planning_Guide/topics/Deployment_Scenarios.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
=> 2.5 - suggest changing ISS to "{Project}'s Inter-Server Sync" for consistency across foreman, ocharino and satellite

guides/common/modules/proc_applying-errata-to-a-host-centos7.adoc, guides/common/modules/proc_applying-errata-to-a-host-debian.adoc, guides/common/modules/proc_applying-errata-to-a-host-rhel7.adoc, guides/common/modules/proc_applying-errata-to-a-host-rhel8.adoc, guides/common/modules/proc_applying-errata-to-a-host.adoc
This PR adds two new procedures to apply errata to hosts running Debian/Ubuntu or CentOS7.
=> Rework procedure to apply errata to a managed host

guides/common/modules/con_provisioning-contexts.adoc, guides/common/modules/proc_cloning-provisioning-templates.adoc, guides/common/modules/proc_setting-the-provisioning-context.adoc
Small PR to remove xrefs to the context menu page.
=> Remove xrefs to context menu for orcharhino

guides/common/attributes.adoc
Do not merge yet until 6.10 is announced.
=> Update Satellite links to 6.10

guides/common/assembly_logging-and-reporting-problems.adoc, guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc
Fix for PR 865 that got merged too soon.
=> Rework logging and reporting problems

guides/doc-Managing_Hosts/topics/proc_registering-a-host.adoc
(Oopsie, missed this)
Follow-up to #780
=> Update procedure Registering a Host to RH Satellite on 2.5

guides/common/assembly_logging-and-reporting-problems.adoc, guides/common/modules/proc_configuring-logging-to-journal.adoc, guides/common/modules/proc_enabling-debug-logging.adoc, guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc, guides/common/modules/proc_restarting-services.adoc, guides/common/modules/proc_retrieving-status-of-services.adoc
This PR fixes various attribute errors in code blocks, for example: https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#_increasing_the_logging_level_on_foreman
=> Use attribute for foreman-maintain

guides/common/modules/proc_adding-custom-deb-repositories.adoc
Small PR to fix description of what "Restrict to architecture" does.
See also https://projects.theforeman.org/issues/34041
=> Fix restrict to architecture description

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
=> Adding conditional to upgrade guide

guides/doc-Managing_Hosts/topics/ref_customizing-the-registration-templates.adoc
Fixed an incorrectly formatted list.
=> Corrected Snippets List Format

guides/common/assembly_managing-content-views.adoc, guides/common/modules/proc_creating-a-content-filter-for-apt-content.adoc, guides/common/modules/proc_creating-a-content-filter-for-yum-content.adoc, guides/common/modules/proc_creating-a-content-view.adoc, guides/common/modules/proc_importing-a-content-view-version.adoc
This PR adds a procedure to use content filters for APT content & contains various other smaller fixes and improvements.
=> Add content filter for APT content & various minor improvements

guides/Makefile
cc @melcorr 
If this does not work, we should revert the last commit to master. my bad!
=> Temporary disable link checker

guides/common/modules/con_introduction-to-organization-and-location-context.adoc
=> Fix spelling of mutually

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
=> Add more serious warning about Katello 4.0 upgrades

guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
=> Added info about BIOS mode - as per BZ#1996519

guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
=> Added missing ifdef for Satellite

guides/common/modules/proc_setting-a-default-encrypted-root-password.adoc, guides/doc-Managing_Hosts/topics/Administering_Hosts.adoc
IMPORTANT This change will be included in v3.2, not before.
=> DEMO104: Root password inheritance

guides/common/assembly_using-puppet-for-configuration-management.adoc, guides/common/attributes-satellite.adoc, guides/common/modules/proc_enabling-puppet.adoc, guides/common/modules/proc_prerequisites-for-puppet.adoc, guides/doc-Installing_Server_on_Red_Hat/master.adoc, guides/doc-Managing_Hosts/master.adoc
=> Add Puppet enablement procedure

guides/common/attributes.adoc
=> update docs for 3.1 to be stable and refer to 3.1 repos

guides/common/Makefile, guides/common/assembly_using-foreman-webhooks.adoc, guides/common/modules/con_shellhooks-plugin.adoc, guides/common/modules/proc_creating-a-webhook.adoc, guides/common/modules/ref_webhooks-available-events.adoc
SSIA
* 3.1
* 2.5 (or let me know and I will file PR - I have a customer case)
=> Extend webhooks table with doc reference

guides/common/modules/proc_creating-a-compliance-policy.adoc, guides/common/modules/proc_preparing-a-cloud-init-template.adoc, guides/common/modules/proc_setting-the-fips-enabled-parameter.adoc, guides/common/modules/proc_uploading-a-tailoring-file.adoc
(cherry picked from commit 0e6458f35b142598a4455ed496607fb15b9b0d17)
=> Fix spelling (#940)

guides/common/assembly_migrating-from-internal-databases-to-external-databases.adoc, guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc
(cherry picked from commit 4695b8d907b8db5a4536c19f3651d10b7d11ae04)
=> Modularize administering foreman guide (#945)

guides/common/modules/proc_loading-the-default-openscap-content.adoc
(cherry picked from commit 6ca008053e15a5470fcb50fcf379252b41237473)
=> BZ2029060: Upload default OpenSCAP content using Hammer (#937)

guides/common/modules/ref_webhooks-available-events.adoc
=> Fix webhooks table hash entries

.github/workflows/deploy.yml
There are few more places where we use the old GHA.
=> Improve setup-ruby GHA

guides/common/modules/con_tailoring-files.adoc
=> Fix OpenSCAP Workbench link error

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
2.5 only version of https://github.com/theforeman/foreman-documentation/pull/883/files
@jlsherrill
=> Add notes about volume sizes before Pulp3 migration

.github/workflows/deploy.yml, guides/common/modules/con_tailoring-files.adoc
This is to see if 3.1 will build with Ruby 3.
=> Use Ruby 3 in CI

guides/common/modules/con_tailoring-files.adoc
This reverts commit d122f3f3db9e92434312bab83b8e9194a680d44d.
SSIA That was quick this time.
=> Revert "Fix OpenSCAP Workbench link error"

guides/doc-Release_notes/master.adoc, guides/doc-Release_notes/topics/foreman-3.1.0.adoc, guides/doc-Release_notes/topics/foreman-contributors.adoc, guides/doc-Release_notes/topics/foreman.adoc, guides/doc-Release_notes/topics/katello-4.3.0.adoc
This does not add the Katello 4.3 specific notes nor the Katello contributors, but at least it's a start.
=> Add Foreman 3.1 and Katello 4.3 release notes

guides/common/modules/proc_installing-acd-on-smart-proxy.adoc
(cherry picked from commit 529ab24e905b4b4bc2bc47c250d0270036e03358)
=> Fix broken xref

guides/common/modules/proc_salt-authenticating-salt-minions-using-salt-autosign-grains.adoc
(cherry picked from commit 3b3ca1927203632a236c03fd9650446f61bc291a)
=> Remove Salt reactor configuration step

guides/common/modules/proc_renaming-smart-proxy.adoc
=> Hide link to BZ for orcharhino builds

guides/common/assembly_maintaining-server.adoc, guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc, guides/doc-Administering_Red_Hat_Satellite/master.adoc
This builds on https://github.com/theforeman/foreman-documentation/pull/979 and is yet another step towards solving https://github.com/theforeman/foreman-documentation/issues/676, but it's still a long way to go.
=> Admin Guide: Further hiding of irrelevant or broken parts

guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc
=> Bz#2041923

guides/doc-Managing_Hosts/topics/proc_upgrading-rhel7-hosts-to-rhel8.adoc
=> Fixed a broken link in the chapter about upgrades

.github/workflows/deploy.yml
Do not merge, need to test guides building for 3.0
=> Fix 3.0 branch building (WIP)

web/content/release-2.4.adoc
Forgot to add this.
https://docs.theforeman.org/release/2.4
=> Add missing 2.4 langing page

web/content/js/nav.js
(cherry picked from commit c29c5dc84f5663283fa2fc5c901a5f7c2c279212)
Please review again; I had to resolve merge conflicts during the cherry-pick.
@ekohl
=> Add converting to rhel guide to navigation

guides/common/assembly_configuring-provisioning-resources.adoc, guides/common/assembly_introduction-to-provisioning.adoc, guides/common/modules/con_configuring-provisioning-resources.adoc, guides/common/modules/con_introduction-to-provisioning.adoc
=> Modularize provisioning guide

guides/common/modules/proc_enabling-puppet.adoc
=> Remove duplicate by default

guides/common/modules/proc_configuring-capsule-default-certificate.adoc, guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Satellite_Server.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_without_Puppet_for_Load_Balancing.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_without_Puppet.adoc
=> BZ2036273: Remove wrong option from example commands in Smart Proxy 3.0

guides/common/modules/proc_configuring-capsule-default-certificate.adoc, guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-capsule-server.adoc, guides/doc-Administering_Red_Hat_Satellite/topics/Renaming_a_Satellite_Server.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_with_Puppet_for_Load_Balancing.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Custom_SSL_Certificates_and_without_Puppet_for_Load_Balancing.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_with_Puppet.adoc, guides/doc-Configuring_Load_Balancer/topics/Configuring_Capsule_Server_with_Default_SSL_Certificates_for_Load_Balancing_without_Puppet.adoc
=> BZ2036273: Remove wrong option from example commands in Smart Proxy 2.5

.github/workflows/deploy.yml, Gemfile, guides/common/Makefile
So the ccutil patch was cherrypicked into 3.1: ae618bc467f1a53b7759faf000b939f0b61e1a47
But it did not work, I meant to file a PR to test and fix it. So this PR should do it.
Don't merge until green :)
=> Build via ccutil (CP 3.1)

guides/common/Makefile, guides/doc-Installing_Proxy/images/common, guides/doc-Installing_Proxy_on_Debian/images/common, guides/doc-Installing_Proxy_on_Red_Hat/images/common, guides/doc-Installing_Server/images/common, guides/doc-Installing_Server_on_Debian/images/common, guides/doc-Installing_Server_on_Red_Hat/images/common
SSIA
Ask for rebase before merging please, bigger changes of the Makefile and GHA can cause issues.
=> Fix missing images directories

guides/common/modules/proc_creating-a-suse-operating-system.adoc
This PR adds parameters for SLES operating systems.
=> Add OS parameters for SLES

guides/common/modules/proc_creating-a-suse-operating-system.adoc
(cherry picked from commit ba5055075772313db8e6c45931de4ef0524593f0)
=> Add OS parameters for SLES (#1036)

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
Additional inormation has been added and the order of steps in the procedure altered.
Include More Information Regarding Concerns During the Pulp 2 to Pulp 3 Migration
https://issues.redhat.com/browse/SATDOC-544
=> Revise and add content to Pulp migration instructions.

guides/common/header.adoc, guides/doc-Administering_Red_Hat_Satellite/master.adoc, guides/doc-Administering_with_Ansible/master.adoc, guides/doc-Application_Centric_Deployment/master.adoc, guides/doc-Configuring_Ansible/master.adoc, guides/doc-Configuring_Load_Balancer/master.adoc, guides/doc-Content_Management_Guide/master.adoc, guides/doc-Converting_a_Host_to_RHEL/master.adoc, guides/doc-Deploying_on_AWS/master.adoc, guides/doc-Installing_Proxy/master.adoc, guides/doc-Installing_Satellite_Server_Disconnected/master.adoc, guides/doc-Installing_Server/master.adoc, guides/doc-Managing_Hosts/master.adoc, guides/doc-Managing_Organizations_and_Locations/master.adoc, guides/doc-Planning_Guide/master.adoc, guides/doc-Provisioning_Guide/master.adoc, guides/doc-Quickstart_Guide/master.adoc, guides/doc-Release_notes/master.adoc, guides/doc-Upgrading_and_Updating/master.adoc
=> Enable TOC rendering for all builds

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
=> Added Pre-Migration Recommendations to Section 3.1.1. per SATDOC-530

guides/common/assembly_managing-ostree-content.adoc, guides/common/attributes-satellite.adoc, guides/common/modules/con_managing-ostree-content.adoc, guides/common/modules/proc_importing-ostree-content.adoc, guides/common/modules/proc_managing-ostree-content-with-content-views.adoc, guides/common/modules/proc_uploading-ostree-content-with-hammer-cli.adoc, guides/doc-Content_Management_Guide/master.adoc
=> Managing OSTree content in Content Management Guide

guides/common/attributes-base.adoc, guides/common/modules/proc_building-a-discovery-image.adoc
See individual commits for details.
=> Correct version numbers and avoid ProductVersion in upstream

guides/doc-Configuring_Load_Balancer/topics/Promoting_SCAP_Content_to_Clients.adoc
This will be useful once Puppet guide is published on RH Customer Portal.
Cherry-pick to:
=> Fix Puppet link

guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
=> Fix capitalization of the

guides/common/modules/proc_configuring-for-uefi-http-boot-ipv6-provisioning.adoc
=> Add other EL 8 distros to ipv6 provisioning

guides/common/modules/con_content-management-types-overview.adoc
=> Add provisioning templates to content types

guides/common/assembly_using-puppet-smart-parameters.adoc, guides/common/modules/con_using-puppet-smart-class-parameters.adoc, guides/common/modules/con_using-puppet-smart-parameters.adoc
=> Rename using puppet smart class parameters file

guides/common/modules/proc_restrict-custom-repository-RHEL9.adoc, guides/doc-Planning_Guide/topics/Provisioning_Concepts.adoc
=> Whitespace

guides/common/modules/proc_restoring-from-a-full-backup.adoc
=> Fix the restorecon command options

guides/common/modules/proc_adding-a-bonded-interface.adoc, guides/common/modules/proc_applying-errata-to-a-host-collection.adoc, guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc, guides/common/modules/proc_creating-image-only-hosts.adoc, guides/common/modules/proc_promoting-a-content-view-across-all-life-cycle-environments-within-an-organization.adoc, guides/common/modules/proc_synchronizing-all-repositories-in-an-organization.adoc, guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc
Sort alphabetically and use "my" instead of nothing or "your org/loc".
=> Rework Hammer CLI parameters

guides/common/assembly_configuring-satellite-custom-server-certificate.adoc, guides/common/modules/con_content-management-types-overview.adoc, guides/common/modules/con_introduction-to-content-management.adoc, guides/common/modules/con_iss-scenarios.adoc, guides/common/modules/con_managing-content-views.adoc, guides/common/modules/con_provisioning-cloud-instances-on-openstack.adoc, guides/common/modules/con_provisioning-contexts.adoc, guides/common/modules/con_provisioning-virtual-machines-in-vmware.adoc, guides/common/modules/proc_adding-server-as-a-dynamic-inventory-item.adoc, guides/common/modules/proc_configuring-selinux-to-ensure-access-on-custom-ports.adoc, guides/common/modules/proc_creating-a-composite-content-view.adoc, guides/common/modules/proc_creating-a-remote-file-repository.adoc, guides/common/modules/proc_promoting-content-across-the-application-life-cycle.adoc, guides/common/modules/proc_registering-a-host-using-the-bootstrap-script.adoc, guides/common/modules/proc_registering-an-atomic-host.adoc, guides/common/modules/proc_using-activation-keys-for-host-registration.adoc, guides/common/modules/ref_capsule-ports-and-firewalls-requirements.adoc, guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc, guides/common/modules/ref_ports-and-firewall-requirements.adoc, guides/doc-Planning_Guide/topics/Deployment_Considerations.adoc, guides/doc-Upgrading_and_Updating/topics/migrating_a_self_registered_satellite.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
=> Fix usage of attributes (ProjectName) 3.1

guides/common/modules/con_provisioning-templates.adoc
Icon for supported templates
Filtering of templates.
Cloning supported templates
[doc] - Provisioning Improvements
https://issues.redhat.com/browse/SAT-6406
* [ X] Foreman 3.1
=> Added description of Provisioning improvements

guides/common/modules/con_content-management-types-overview.adoc
* I'll file another PR for 3.1
=> Add OSTree content type

guides/common/modules/con_content-management-types-overview.adoc
=> Add OSTree content type 3.1

guides/common/modules/proc_adding-a-default-http-proxy.adoc, guides/common/modules/proc_changing-the-method-the-bootstrap-script-uses-to-download-the-consumer-rpm.adoc, guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc
=> don't use _something_ in escaped URLs 

guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
* [x ] Foreman 3.2
* [ x] Foreman 3.1
=> Fix command to install satellite-clone

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
=> Added Pulpcore database user

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
=> Added Puplcore user to a procedure

guides/common/modules/proc_configuring-repositories.adoc
=> Fix repo Id

guides/common/modules/con_configuring-the-discovery-service.adoc, guides/common/modules/proc_installing-the-discovery-service.adoc, guides/common/modules/proc_synchronizing-suse-content.adoc
=> Remove links to orcharhino docs

guides/common/assembly_managing-users-and-roles.adoc, guides/common/assembly_restoring-server-or-smart-proxy-from-a-backup.adoc, guides/doc-Upgrading_and_Updating/master.adoc
⚠️  needs a real review to see if my change behaves the way I expect it to.
=> Fix leveloffset

guides/common/modules/proc_adding-installation-media.adoc
IMHO using "medium's path" is not possible because medium is not a person.
=> Reword path of the installation medium

guides/common/modules/con_content-filter-overview.adoc, guides/common/modules/proc_creating-a-content-filter-for-apt-content.adoc, guides/common/modules/proc_creating-a-content-filter-for-yum-content.adoc
Three small changes; see the each individual commits.
=> Content filters yum apt

guides/common/modules/proc_importing-a-content-view-version.adoc
=> Fix Hammer CLI command to import content views

guides/common/modules/con_network-boot-provisioning-workflow.adoc
We no longer advertise EFI chainloading as the way to do EFI provisioning.
https://github.com/theforeman/foreman/pull/9123
=> Add efibootmgr information for EFI

guides/common/modules/ref_storage-requirements.adoc
=> Fix path to postgresql in storage requirement section

guides/common/modules/proc_configuring-repositories.adoc
=> Configuring repositories on Sat serverce connected - fix repo ID

guides/common/modules/ref_storage-requirements.adoc
=> Fix pgsql path in the storage requirements section

guides/common/attributes-orcharhino.adoc
=> Bump orcharhino version to 5.12

guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
=> Remove steps to install BIND

guides/common/modules/proc_increasing-the-logging-levels-to-help-with-debugging.adoc, guides/common/modules/ref_log-file-directories.adoc
=> Expand logging sections

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2056737
This concerns a topic that is published for disconnected Satellite only.
=> BZ#2056737: Configure Ansible repository (Sat only)

guides/common/modules/proc_downloading-the-binary-dvd-images.adoc
=> Fixed the name of a download menu

guides/common/assembly_converting-a-host-with-convert2rhel.adoc, guides/common/modules/con_converting-a-host-to-rhel-with-convert2rhel.adoc, guides/common/modules/proc_assigning-conver2rhel-role-to-host.adoc, guides/common/modules/proc_assigning-convert2rhel-role-to-host.adoc, guides/common/modules/proc_creating-variables-for-convert2rhel-role.adoc, guides/common/modules/proc_importing-convert2rhel-ansible-role.adoc, guides/common/modules/proc_registering-hosts-for-conversion.adoc, guides/common/modules/proc_running-convert2rhel-ansible-playbook.adoc
Updated initial descriptions.
[Foreman demo] #104 Automating Preparation for Convert2RHEL data
https://issues.redhat.com/browse/SATDOC-524
=> Automating Convert2RHEL

guides/common/attributes.adoc
=> Fix the ProductVersion attribute

guides/common/modules/con_content-management-types-overview.adoc, guides/common/modules/con_provisioning-contexts.adoc, guides/common/modules/con_provisioning-templates.adoc, guides/common/modules/con_using-products-and-repositories.adoc, guides/common/modules/proc_adding-life-cycle-environments.adoc, guides/common/modules/proc_assigning-a-host-to-a-specific-organization.adoc, guides/common/modules/proc_creating-an-activation-key.adoc, guides/common/modules/proc_importing-a-custom-gpg-key.adoc, guides/doc-Deploying_on_AWS/topics/AWS_Use_Case_Considerations.adoc
Various small commits to fix various small issues like broken links.
=> Rework content management

web/content/js/versions.js, web/content/release-3.1.adoc, web/content/release-3.2.adoc, web/content/release-nightly.adoc
Closes https://github.com/theforeman/foreman-documentation/issues/1165
I don't know if this needs cherry-picking. I assume no.
cc @ekohl
=> Add Managing Organizations and Locations to menu

guides/common/modules/proc_extracting-gpg-public-key-fingerprints-from-release-files.adoc
=> Rephrase Release file verification

guides/common/attributes-satellite.adoc, guides/common/modules/proc_exporting-a-repository-incrementally.adoc, guides/common/modules/proc_exporting-a-repository.adoc, guides/common/modules/proc_importing-a-repository.adoc, guides/common/modules/ref_iss-import-export-cheat-sheet.adoc, guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
=> Export/import of a single repository 2.5

guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
=> Changed mentions of Sat 7.0 to Sat 6.11

guides/common/assembly_installing-capsule-server.adoc
=> Added content to a section that was blank

guides/common/modules/proc_importing-a-custom-gpg-key.adoc, guides/common/modules/proc_importing-custom-ssl-certificates.adoc
=> Hammer content credentials command

guides/common/assembly_converting-a-host-with-convert2rhel.adoc
=> Added the whitespace and a comma after attribute

guides/doc-Upgrading_and_Updating/topics/upgrading_clients.adoc
I broke 3.1 with https://github.com/theforeman/foreman-documentation/commit/7219ef0441321cc73a2de8228e92d7f25e996337 🙈
=> Remove single endif

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
Replace line with correct instruction
Error in Preparing to Migrate Content to Pulp 3 Procedure
https://issues.redhat.com/browse/SATDOC-720
=> Replaced incorrect instruction

guides/doc-Content_Management_Guide/topics/Using_ISS.adoc
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2061594
=> Export/import compatibility between versions 2.5

guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
=> Replaced the command for synchronization of the upgraded Capsule

guides/common/modules/proc_importing-ansible-roles.adoc
=> Fixing small format issue in Ansible docs

guides/doc-Planning_Guide/topics/Introduction.adoc
=> Drop EL7 from planning guide

guides/common/modules/ref_storage-requirements.adoc
=> Drop EL7 from storage requirements

guides/common/modules/proc_configuring-repositories.adoc, guides/common/modules/proc_installing-the-satellite-server-packages.adoc, guides/common/modules/ref_supported-operating-systems.adoc
=> Drop EL7 from the nightly quickstart installation guide

guides/common/modules/proc_verifying-firewall-settings.adoc
=> Drop EL7 firewalld guide link from verify firewalld settings

guides/common/assembly_installing-capsule-server.adoc
=> Fixed repo name to reflect that it's a Capsule server

guides/common/assembly_importing-content.adoc, guides/common/modules/con_mirroring-policies-overview.adoc, guides/common/modules/proc_changing-the-mirroring-policy-for-a-repository.adoc
=> Mirroring policy

guides/common/modules/proc_cloning-a-host-collection.adoc, guides/common/modules/proc_creating-a-host-collection.adoc
=> Added double quotes to the ID of two modules

guides/common/modules/proc_configuring-repositories.adoc, guides/common/modules/proc_installing-the-satellite-server-packages.adoc, guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc, guides/common/modules/proc_verifying-firewall-settings.adoc, guides/common/modules/ref_storage-requirements.adoc, guides/common/modules/ref_supported-operating-systems.adoc, guides/doc-Planning_Guide/topics/Introduction.adoc
=> Reverse el7 deprecation

guides/README.md, guides/doc-Administering_Red_Hat_Satellite/docinfo.html, guides/doc-Administering_with_Ansible/docinfo.html, guides/doc-Application_Centric_Deployment/docinfo.html, guides/doc-Configuring_Ansible/docinfo.html, guides/doc-Configuring_Load_Balancer/docinfo.html, guides/doc-Content_Management_Guide/docinfo.html, guides/doc-Converting_a_Host_to_RHEL/docinfo.html, guides/doc-Deploying_on_AWS/docinfo.html, guides/doc-Installing_Proxy/docinfo.html, guides/doc-Installing_Satellite_Server_Disconnected/docinfo.html, guides/doc-Installing_Server/docinfo.html, guides/doc-Managing_Hosts/docinfo.html, guides/doc-Managing_Organizations_and_Locations/docinfo.html, guides/doc-Planning_Guide/docinfo.html, guides/doc-Provisioning_Guide/docinfo.html, guides/doc-Quickstart_Guide/docinfo.html, guides/doc-Release_notes/docinfo.html, guides/doc-Upgrading_and_Updating/docinfo.html
SSIA
I also conveted spaces to tabs for the README as majority of it was on tabs.
Also I think that the docinfo.html symlink is actually not necessary, need to test maybe ccutil will require it. So build might fail.
=> Add Adding new guide README instructions

guides/common/attributes.adoc
=> Changed attributes for Satellite to version 6.11

guides/README.md
See https://github.com/theforeman/foreman-documentation/pull/1214#issuecomment-1106443054
=> Document how to use linkchecker

guides/common/modules/proc_adding-custom-deb-repositories.adoc, guides/common/modules/proc_adding-custom-deb-repository-example-for-debian-11.adoc
See https://github.com/Katello/katello/pull/10069
Cherry-picking: I am unsure. cc @manisha15 cc @sjha4
=> Document flat repository structure for deb repositories

guides/common/assembly_administer-settings-information.adoc, guides/common/assembly_administer-settings.adoc, guides/common/modules/ref_ansible-settings.adoc, guides/common/modules/ref_authentication-settings.adoc, guides/common/modules/ref_boot-disk-settings.adoc, guides/common/modules/ref_configuration-management-settings.adoc, guides/common/modules/ref_content-settings.adoc, guides/common/modules/ref_discovered-settings.adoc, guides/common/modules/ref_email-settings.adoc, guides/common/modules/ref_facts-settings.adoc, guides/common/modules/ref_general-settings-information.adoc, guides/common/modules/ref_notifications-settings.adoc, guides/common/modules/ref_project-task-settings.adoc, guides/common/modules/ref_provisioning-settings.adoc, guides/common/modules/ref_redhat-cloud-settings.adoc, guides/common/modules/ref_remote-execution-settings.adoc, guides/common/modules/ref_template-sync-settings.adoc, guides/common/ref_ansible-settings.adoc, guides/doc-Administering_Red_Hat_Satellite/master.adoc, guides/doc-Administering_Red_Hat_Satellite/ref_content-settings.adoc
=> Added settings description files

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
=> Added options for enabling SSL

guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
=> Fixed typo in a command

guides/common/attributes.adoc
=> Update common attributes for Foreman 3.3

.github/PULL_REQUEST_TEMPLATE.md, Makefile, guides/common/attributes.adoc, web/content/index.adoc, web/content/js/versions.js, web/content/release-3.3.adoc
=> Update master for Foreman 3.3

guides/common/modules/con_applying-custom-configuration.adoc, guides/common/modules/proc_exporting-the-library-environment.adoc, guides/common/modules/proc_providing-an-alternative-fqdn-for-the-host.adoc, guides/common/modules/ref_ports-and-firewall-requirements.adoc
TIP: Review using `git diff master -w` :)
=> Remove double whitespace

guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
=> document new katello-candlepin-db-ssl parameter

guides/common/modules/proc_salt-authenticating-salt-minions-using-host-names.adoc
See also https://github.com/theforeman/foreman_salt/pull/136#discussion_r627233869
=> Add saltuser to foreman-proxy group

guides/common/modules/proc_salt-using-content-management.adoc
=> Fix title of link

guides/common/modules/proc_adding-custom-deb-repositories.adoc, guides/common/modules/proc_adding-custom-rpm-repositories.adoc, guides/common/modules/proc_creating-a-custom-file-type-repository.adoc, guides/common/modules/proc_creating-a-local-file-repository.adoc, guides/common/modules/proc_creating-a-remote-file-repository.adoc, guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
Resolves https://github.com/theforeman/foreman-documentation/issues/1184 and some other issues. See individual commits for an easier review.
=> Rework various procedures to add repositories

guides/common/modules/con_dynflow-tuning.adoc, guides/common/modules/con_introduction-to-performance-tuning.adoc, guides/common/modules/con_puma-workers-and-threads-recommendation.adoc, guides/common/modules/con_smartproxy_performance_tests.adoc, guides/common/modules/proc_benchmarking-raw-db-performance.adoc, guides/common/modules/proc_configuring-project-environment-for-performance.adoc, guides/common/modules/proc_configuring-puma-db-pool.adoc, guides/common/modules/proc_configuring-the-maximum-asynchronous-input-output-requests.adoc, guides/common/modules/proc_configuring-the-open-files-limit-for-apache-httpd.adoc, guides/common/modules/proc_deploying-an-application-instance.adoc, guides/common/modules/proc_disabling-dns-dhcp-tftp-for-unmanaged-networks.adoc, guides/common/modules/proc_managing-ssh-keys-for-a-user.adoc, guides/common/modules/proc_viewing-general-smart-proxy-information.adoc, guides/common/modules/ref_performance-tuning-system-requirements.adoc
For the best reviewing experience, see my individual commits.
=> Performance tuning

guides/doc-Release_notes/redmine_release_notes
=> Fix typo in redmine_release_notes script

guides/common/modules/proc_adding-errata-to-a-host.adoc, guides/common/modules/proc_applying-installable-errata.adoc, guides/common/modules/proc_inspecting-available-errata.adoc, guides/common/modules/proc_removing-a-package-from-a-host.adoc, guides/common/modules/proc_upgrading-a-package.adoc
Change any instances of reference to the three dots icon to the correct term, 'vertical ellipsis'.
=> Replace any instances of 'three dots' with 'vertical ellipsis'

guides/common/assembly_managing-content-views.adoc, guides/common/modules/proc_deleting-multiple-content-view-versions.adoc
Adding information about the procedure for bulk deleting versions of a CV. Demoed in #106.
Related JIRA: https://issues.redhat.com/browse/SATDOC-620
=> Add information about content view versions bulk deletion

guides/common/modules/proc_configuring-server-to-sync-content-using-exports.adoc, guides/common/modules/proc_configuring-server-to-synchronize-content-over-a-network.adoc, guides/common/modules/proc_importing-custom-ssl-certificates.adoc
Further improvements to Inter-Server Sync.
Relates to issue #1232
=> Improve ISS Installing Sat Disconnected

guides/doc-Release_notes/master.adoc, guides/doc-Release_notes/topics/foreman-3.1.2.adoc, guides/doc-Release_notes/topics/foreman-3.1.3.adoc
=> Foreman 3.1.2 and 3.1.3 release notes

guides/doc-Release_notes/master.adoc, guides/doc-Release_notes/topics/foreman-3.2.0.adoc, guides/doc-Release_notes/topics/foreman-3.2.1.adoc
=> Foreman 3.2.0 and 3.2.1 release notes

guides/common/assembly_maintaining-server.adoc, guides/common/modules/proc_deleting_a_task_by_id.adoc
This PR adds a procedure to delete tasks by ID.
=> Add procedure to remove task by ID

guides/common/modules/proc_configuring-repositories-el.adoc, guides/common/modules/proc_configuring-repositories.adoc
=> use the right repositories for upstream el8 installs

guides/common/modules/proc_installing-the-satellite-server-packages.adoc
Procedures in section 3.4 are now visible.
https://issues.redhat.com/browse/SAT-9421
=> Minor fixes from SAT-9421

guides/common/attributes-satellite.adoc
=> satellite-specific attribute renamed

guides/doc-Release_notes/master.adoc, guides/doc-Release_notes/topics/foreman-3.3.0.adoc
=> Release notes for Foreman 3.3.0

guides/common/modules/proc_registering-hosts.adoc
=> REX pull setup on registration

guides/common/attributes-satellite.adoc
=> Rename Planning Guide in Satellite

guides/common/modules/ref_content-settings.adoc
=> Add a new global Setting - Allow deleting repos in published CVs

web/content/index.adoc
=> correct "(supported)" in the index

guides/common/modules/proc_upgrading-el7-to-el8.adoc, guides/common/modules/proc_upgrading-project-from-el7-to-el8.adoc, guides/doc-Upgrading_and_Updating/master.adoc
Added conditional information for upgrading Satellite from RHEL 7 to RHEL 8 per SAT-6752. Removed 'No outstanding updates" bullet in Prerequisites. Updated file name and anchor to be consistent.
@evgeni please review at your earliest convenience
=> Added condition for Satellite Upgrading to RHEL8

guides/common/modules/ref_system-requirements.adoc
Added the required OS in the system requirement section before the
document is available generally.
Need to update 1.1 System Requirements section
https://bugzilla.redhat.com/show_bug.cgi?id=2097801
=> Update the system requirement section

web/content/js/versions.js
=> Update the state of releases in versions.js

guides/common/assembly_installing-capsule-server.adoc, guides/common/modules/proc_installing-capsule-server-packages.adoc
See the individual commits for explanations.
Obsoletes: #1208
=> several fixes for rendering of the proxy install guides

guides/common/modules/con_permissions-for-remote-execution.adoc, guides/common/modules/ref_predefined-roles.adoc
=> Add remote execution permission

guides/doc-Release_notes/master.adoc, guides/doc-Release_notes/topics/katello-4.5.0.adoc, guides/doc-Release_notes/topics/katello-contributors.adoc, guides/doc-Release_notes/topics/katello.adoc
=> Add initial Katello 4.5.0 changelog entries

guides/common/attributes.adoc, guides/common/modules/con_migrating-project-to-el8.adoc, guides/common/modules/proc_creating-a-backup-of-a-server-on-el7.adoc, guides/common/modules/proc_restoring-a-backup-of-a-server-on-el8.adoc, guides/common/modules/ref_performing-a-fresh-installation-of-a-server-on-el8.adoc, guides/doc-Upgrading_and_Updating/master.adoc, guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
=> Migrating/cloning - upgrading guide

.github/workflows/deploy.yml
=> deploy PR preview to surge.sh

guides/common/attributes-typography.adoc, guides/common/attributes.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
FYI, I'm merging and cpicking right away, we need to trigger downstream sync :D
[x] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.
=> Vamp up typography!

guides/common/attributes-satellite.adoc
=> Update guide URLs in Satellite

guides/common/attributes-satellite.adoc
=> Update guide URLs in Satellite - Part 2

.github/workflows/deploy.yml
Turns out, one can't post comments from an action if the PR is opened from a fork, which breaks the workflow :(
=> don't try to comment the surge link

guides/common/attributes-satellite.adoc
=> Fix title URLs Satellite

.github/workflows/preview.yml
=> fix preview link

.github/workflows/preview.yml
=> don't try to comment if the trigger was not successful

.github/workflows/deploy.yml, .github/workflows/preview.yml
=> compute diff against base branch

guides/common/modules/proc_salt-authenticating-salt-minions-using-salt-autosign-grains.adoc, guides/common/modules/proc_salt-enabling-salt-report-uploads.adoc
=> Adjust Salt config paths for Salt plugin 4.0+

.github/download_workflow_run_artifact.js, .github/workflows/deploy.yml, .github/workflows/preview.yml
=> pick preview 3.1

.github/download_workflow_run_artifact.js, .github/workflows/deploy.yml, .github/workflows/preview.yml
=> pick preview 3.3

.github/download_workflow_run_artifact.js, .github/workflows/deploy.yml, .github/workflows/preview.yml
=> pick preview 3.2

.github/workflows/preview.yml
=> generate a HTML version of the diff

guides/common/modules/proc_inspecting-available-errata.adoc
Add information about the interactive pie chart included in the installable errata card on the new host page.
=> Update information about installable errata card

guides/common/assembly_installing-server-connected.adoc, guides/common/attributes-orcharhino.adoc, guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc, guides/common/modules/proc_configuring-installation.adoc
=> use installer-log-file everywhere possible

guides/common/modules/proc_configuring-puma-workers.adoc
The table was rendered incorrectly.
=> Fixing columns in the table

guides/doc-Performance_Tuning_Guide/master.adoc
=> Fixing how headings are organized to make it easier to browse

guides/common/assembly_administering-hosts.adoc, guides/common/modules/con_provisioning-cloud-instances-on-google-compute-engine.adoc, guides/common/modules/con_provisioning-cloud-instances-on-microsoft-azure-resource-manager.adoc, guides/common/modules/con_provisioning-cloud-instances-on-openstack.adoc, guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc, guides/common/modules/con_provisioning-virtual-machines-on-kvm.adoc, guides/common/modules/con_provisioning-virtual-machines-on-ovirt.adoc, guides/common/modules/proc_adding-images-to-server.adoc, guides/common/modules/proc_adding-vmware-images-to-server.adoc, guides/common/modules/proc_associating-a-virtual-machine-from-a-hypervisor.adoc
For the best reviewing experience, see my individual commits.
=> Improve various aspects of compute resources

guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc, guides/doc-Administering_Project/master.adoc, guides/doc-Administering_with_Ansible/master.adoc, guides/doc-Configuring_Ansible/master.adoc, guides/doc-Configuring_Load_Balancer/master.adoc, guides/doc-Deploying_Project_on_AWS/master.adoc, guides/doc-Installing_Proxy/master.adoc, guides/doc-Installing_Server/master.adoc, guides/doc-Installing_Server_Disconnected/master.adoc, guides/doc-Managing_Configurations_Puppet/master.adoc, guides/doc-Managing_Content/master.adoc, guides/doc-Managing_Hosts/master.adoc, guides/doc-Performance_Tuning_Guide/master.adoc, guides/doc-Planning_for_Project/master.adoc, guides/doc-Provisioning_Hosts/master.adoc, guides/doc-Upgrading_and_Updating/master.adoc
=> Add RH feedback module to all relevant guides

web/content/release-3.2.adoc, web/content/release-3.3.adoc
Fixes: 7a80d77464ce0277113947210c054b1757cb4334
=> Correct links on landing pages

guides/common/attributes-base.adoc, guides/common/attributes-satellite.adoc, guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc
=> Correct client repo URL for RHEL 8

guides/common/assembly_provisioning-virtual-machines-vmware.adoc, guides/common/modules/proc_adding-a-vmware-connection-to-server.adoc, guides/common/modules/proc_adding-vmware-details-to-a-compute-profile.adoc, guides/common/modules/proc_adding-vmware-images-to-server.adoc, guides/common/modules/proc_creating-hosts-on-vmware.adoc, guides/common/modules/proc_deleting-a-vm-on-vmware.adoc, guides/common/modules/proc_importing-a-virtual-machine-from-vmware.adoc, guides/common/modules/proc_installing-vmware-plugin.adoc
=> Extend procedures for VMware

guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc
=> Update disconnected upgrade to reflect changed ISO structure

guides/common/modules/proc_adding-rhel-system-roles.adoc, guides/common/modules/proc_assigning-an-ansible-role-to-a-host-group.adoc, guides/common/modules/proc_assigning-ansible-roles-to-an-existing-host.adoc, guides/common/modules/proc_changing-the-order-of-ansible-roles.adoc, guides/common/modules/proc_configuring-your-deployment-to-run-ansible-roles.adoc, guides/common/modules/proc_importing-ansible-roles.adoc, guides/common/modules/proc_overriding-ansible-variables.adoc, guides/common/modules/proc_removing-ansible-roles-from-a-host.adoc, guides/common/modules/proc_running-ansible-roles-in-check-mode.adoc, guides/common/modules/proc_running-ansible-roles-on-a-host-group.adoc, guides/common/modules/proc_running-ansible-roles-on-a-host.adoc
These should be only UX improvements in the GUI.
=> Improve workflows of Ansible roles

guides/common/assembly_importing-content.adoc, guides/common/modules/proc_restrict-custom-repository-RHEL9.adoc, guides/common/modules/proc_restricting-custom-repositories-to-RHEL-9.adoc
(cherry picked from commit 1c3404af517a63c4849e5bb912620e230f20f7bf)
original PR: https://github.com/theforeman/foreman-documentation/pull/1510
=> Rename file to match title (cherry-pick for 3.2)

guides/common/modules/proc_configuring-project-for-performance.adoc
=> Add bit for no perf difference beween rhel7 and 8

guides/common/modules/proc_assigning-an-ansible-role-to-a-host-group.adoc, guides/common/modules/proc_assigning-ansible-roles-to-an-existing-host.adoc, guides/common/modules/proc_importing-ansible-roles.adoc
Minor corrections and improvements
=> Fine tune Ansible procedures

web/content/js/versions.js
looks like a follow up to https://github.com/theforeman/foreman-documentation/pull/1525
cc @ekohl
=> Fix linked guides

guides/common/attributes-satellite.adoc
=> Update satellite attributes to RH Satellite version 6.12

guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
* [ x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.
* [ x] Foreman 3.3/Katello 4.5
* [ x] Foreman 3.2/Katello 4.4
=> Update available RHEL versions

guides/common/modules/proc_configuring-puma-workers.adoc, guides/doc-Performance_Tuning_Guide/master.adoc
This is to cherry-pick some more commits to `3.1` (Foreman 3.1/Katello 4.3)
=> Restructure Performance Tuning Guide (#1445)

guides/doc-Administering_Project/docinfo.xml, guides/doc-Administering_with_Ansible/docinfo.xml, guides/doc-Configuring_Ansible/docinfo.xml, guides/doc-Configuring_Load_Balancer/docinfo.xml, guides/doc-Deploying_Project_on_AWS/docinfo.xml, guides/doc-Installing_Proxy/docinfo.xml, guides/doc-Installing_Server/docinfo.xml, guides/doc-Installing_Server_Disconnected/docinfo.xml, guides/doc-Managing_Configurations_Puppet/docinfo.xml, guides/doc-Managing_Content/docinfo.xml, guides/doc-Managing_Hosts/docinfo.xml, guides/doc-Performance_Tuning_Guide/docinfo.xml, guides/doc-Provisioning_Hosts/docinfo.xml, guides/doc-Upgrading_and_Updating/docinfo.xml
=> Updated docinfo files for Satellite guides for version 6.12

guides/common/modules/ref_system-requirements.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_a_disconnected_satellite.adoc, guides/doc-Upgrading_and_Updating/topics/upgrading_overview.adoc
=> Add mixed server pre-req 

guides/common/modules/con_smartproxy_performance_tests.adoc
=> Add missing section name to smart proxy sync test paragraph

.github/PULL_REQUEST_TEMPLATE.md, Makefile, guides/common/attributes.adoc, web/content/index.adoc, web/content/js/versions.js, web/content/release-3.4.adoc
=> Update master for the Foreman 3.4

guides/common/modules/con_postgresql-tuning.adoc
=> Use GB in custom hiera

guides/doc-Release_Notes/master.adoc, guides/doc-Release_Notes/topics/katello-4.6.0.adoc, guides/doc-Release_Notes/topics/katello-contributors.adoc, guides/doc-Release_Notes/topics/katello.adoc
(cherry picked from commit 971b3a9e1a20b50b24e6cf1dd35c1c2ed58f7aaf)
=> Add katello 4.6 branching docs

guides/doc-Release_Notes/master.adoc, guides/doc-Release_Notes/topics/foreman-3.4.0.adoc, guides/doc-Release_Notes/topics/foreman.adoc
=> Release notes for Foreman 3.4 RC1

guides/doc-Planning_for_Project/docinfo.xml
=> Update the docinfo file for Planning guide for Sat version 6.12

guides/common/attributes-base.adoc, guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc, guides/common/modules/proc_configuring-installation.adoc, guides/common/modules/proc_configuring-repositories.adoc, guides/common/modules/proc_installing-the-satellite-server-packages.adoc, guides/common/modules/proc_registering-to-red-hat-subscription-management.adoc, guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc, guides/common/modules/proc_verifying-dns-resolution.adoc, guides/common/modules/proc_verifying-firewall-settings.adoc, guides/common/modules/ref_capsule-storage-requirements.adoc, guides/common/modules/ref_storage-guidelines.adoc, guides/common/modules/ref_storage-requirements.adoc, guides/common/modules/ref_supported-operating-systems.adoc, guides/common/modules/ref_system-requirements.adoc
=> Drop EL7 from Installing Server guide for Foreman and Katello

guides/common/modules/proc_upgrading-project-in-place-using-leapp.adoc
=> move all hints how to fix "leapp preupgrade" issues under one point

guides/doc-Release_Notes/topics/foreman-3.4.0.adoc
=> Release notes for Foreman 3.4 RC2

guides/common/assembly_using-external-databases.adoc, guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc, guides/common/modules/con_postgresql-as-an-external-database-considerations.adoc, guides/common/modules/proc_installing-postgresql.adoc, guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
=> Switch external database guide to install on EL8

CONTRIBUTING.md, guides/README.md
Three small extensions to our conventions and contributing guidelines. cc @Lennonka
=> Extend contributing
