- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- Change guide title capitalization from title case to sentence case
> Change capitalization of guide titles

- guides/common/modules/proc_creating-a-user.adoc
During peer review for https://github.com/theforeman/foreman-documentation/pull/2861, there was a suggestion to include a piece of information in the procedure module for creating a user. It's a good idea, but more work needs to be done within that procedure modules to make it happen.
EDIT: In this PR, I propose the following changes to the procedure to create a user.
* Update UI labels (it looks like they changed in the web UI, but not in the docs)
* Delete steps that are clear from the web UI (like "use enter First Name and Surname to enter first name and surname")
* Split the procedure into two parts: one that shows how to find the page to create a user; another that highlights notable account details to enter
* Minor edits to the CLI part of the procedure
This is an effort to reduce …
> Reduce doc bloat in procedure for creating a user

- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Planning_for_Project/topics/Configuration_Management_Support.adoc
- guides/doc-Planning_for_Project/topics/Content_Management_Support.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Scenarios.adoc
- guides/doc-Planning_for_Project/topics/Glossary.adoc
- guides/doc-Planning_for_Project/topics/Host_Provisioning_Support.adoc
- guides/doc-Planning_for_Project/topics/Hosts.adoc
- guides/doc-Planning_for_Project/topics/Introduction.adoc
- guides/doc-Planning_for_Project/topics/Org_Loc_and_Lifecycle_Environments.adoc
- guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc
- guides/doc-Planning_for_Project/topics/Required_Technical_Users.adoc
As a a follow-up on a series of PRs by @apinnick, I'd like to update several more headings in Planning_for_Project to sentence case. I think these were missed before because the content is stored in topics/ in the directory for the guide, not in common/modules/.
> Change headings to sentence case for deployment topics

- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
I noticed a procedure module that includes a verification step as an `Optional` last step of the procedure itself. The [template for procedure modules](https://redhat-documentation.github.io/modular-docs/#con-creating-procedure-modules_writing-mod-docs) recommends to use a `.Verification` heading for this purpose. I find it quite useful for scannability, especially when applied consistently. See for example [RHEL Security Hardening](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/security_hardening/index#proc_installing-the-system-with-fips-mode-enabled_assembly_installing-the-system-in-fips-mode) and search for various instances of `Verification`.
In this PR, I propose a minor edit to introduce `.Verification` into the procedure for configuring a host …
> Apply '.Verification' to a verification step

- guides/README.md
@maximiliankolb recently pointed out that pinging `@docs` on the Foreman Community Forum doesn't really happen that much. Therefore, I think that adding a reference to Matrix might be a good idea.
> Add reference to foreman-doc Matrix room to README

- guides/doc-Upgrading_and_Updating/master.adoc
- guides/doc-Upgrading_and_Updating/topics/introduction_updating_satellite.adoc
A follow-up on https://github.com/theforeman/foreman-documentation/pull/2569 where cherry-picking into 3.5 was not possible due to a merge conflict.
This PR removes the mention of content hosts from the procedure heading and introduction. It should be the last thing required to close [BZ#2209380](https://bugzilla.redhat.com/show_bug.cgi?id=2209380).
> Remove mentions of Content Hosts from updating

- guides/common/modules/proc_overriding-ansible-variables-in-project.adoc
The current formulation is not correct. A user must be able to see the attribute that the host is being matched against, not the Ansible var. Tested on Satellite 6.15.
> Fix prerequiste in Overriding Ansible vars

- guides/common/modules/con_content-flow-in-project.adoc
- guides/doc-Planning_for_Project/topics/Introduction.adoc
- Puppet Forge is no longer a supported content source.
- This PR removes it from the planning guide.
> Remove Puppet Forge content source

- guides/common/assembly_installing-satellite-server-disconnected.adoc
- guides/common/assembly_using-external-databases.adoc
- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_active-directory-with-cross-forest-trust.adoc
- guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
- guides/common/modules/con_using-freeipa.adoc
- guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
- guides/common/modules/proc_configuring-for-uefi-http-boot-ipv6-provisioning.adoc
- guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
- guides/common/modules/proc_configuring-host-based-authentication-control.adoc
- guides/common/modules/proc_configuring-repositories-proxy.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/common/modules/proc_configuring-the-base-operating-system-with-offline-repositories.adoc
- guides/common/modules/proc_installing-fapolicyd-on-server.adoc
- guides/common/modules/proc_installing-the-load-balancer.adoc
- guides/common/modules/proc_preparing-a-host-for-external-databases.adoc
- guides/common/modules/proc_synchronizing-the-system-clock-with-chronyd.adoc
- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
- guides/common/modules/proc_verifying-dns-resolution.adoc
- guides/common/modules/ref_capsule-storage-requirements.adoc
- guides/common/modules/ref_storage-requirements.adoc
- guides/common/modules/ref_supported-operating-systems.adoc
- guides/common/modules/ref_system-requirements.adoc
- guides/common/modules/snip_step-verify-enabled-repolist.adoc
- guides/common/modules/snip_verify-firewall-settings.adoc
Added EL9 support for Project and Proxy both.
NOTE: Versions in Repositories render incorrectly which should not be a problem for upstream. For Downstream, this will not be published without the correct version.
This applies to Foreman 3.10/Katello 4.12. (GA Soon)
> Add EL9 Support in Project and SmartProxy Installation

- guides/common/modules/con_projectserver-operating-system.adoc
- guides/common/modules/proc_configuring-repositories.adoc
- guides/common/modules/ref_supported-operating-systems.adoc
- guides/doc-Planning_for_Project/topics/Introduction.adoc
contains #2894 to avoid merge-conflicts
> add Ubuntu 22.04

- guides/doc-Upgrading_and_Updating/topics/cloning_satellite_server.adoc
There are some issues in the cloning process that cause it to fail viz.:
- The `rsync` command copies Pulp data to /var/lib/pulp/pulp which is wrong.
- The RHEL8 BaseOS repo too should be enabled on the target server.
- The Prerequisites should expressly mention that the storage on the target should be at least as much as the source.
- The command to enable the remote execution plugin is incorrect as at this point the upgrade hasn't taken place.
BZ link:
https://bugzilla.redhat.com/show_bug.cgi?id=2169707
> Fix issues in the cloning process

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/katello-4.12.0.adoc
- guides/doc-Release_Notes/topics/katello-contributors.adoc
- guides/doc-Release_Notes/topics/katello.adoc
Added Katello 4.12 release notes and contributors.
> Katello 4.12 Release Notes

- guides/common/modules/proc_adding-proxmox-images-to-server.adoc
minor copy and paste error :upside_down_face: 
> Fix typo in Proxmox procedure

- guides/common/assembly_provisioning-virtual-machines-rhv.adoc
- guides/common/modules/proc_installing-ovirt-plugin.adoc
current assumption: Plug-in for RHV is installed on Satellite by default.
Refs https://community.theforeman.org/t/ovirt-integration-into-foreman-3-8/37376
> Add procedure to install oVirt compute resource

- guides/common/modules/con_provisioning-cloud-instances-on-google-compute-engine.adoc
- guides/common/modules/proc_creating-hosts-from-discovered-hosts.adoc
- guides/common/modules/snip_prerequisite-networking-for-provisioning.adoc
GCE provisioning was missing a networking prerequisite.
> Add Networking prerequisite as snippet

- guides/common/modules/proc_configuring-the-discovery-service.adoc
This is a quick fix for current docs requested in a bug report.
https://bugzilla.redhat.com/show_bug.cgi?id=2263570
Note that I'm rewriting Discovery chapter properly in the PR #2890.
> Add missing step for PXE config

- guides/common/modules/con_prerequisites-for-bare-metal-provisioning.adoc
- guides/common/modules/con_provisioning-methods-in-project.adoc
- guides/common/modules/con_unattended-use-customization-and-image-remastering.adoc
- guides/common/modules/con_using-pxe-to-provision-hosts.adoc
- guides/common/modules/proc_adding-a-bmc-interface.adoc
- guides/common/modules/proc_creating-hosts-from-discovered-hosts.adoc
- guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
- guides/common/modules/proc_creating-hosts-with-unattended-provisioning.adoc
- guides/common/modules/proc_implementing-pxe-less-discovery.adoc
- guides/common/modules/proc_using-an-imagebuilder-image-for-provisioning.adoc
- guides/common/modules/ref_permissions-required-to-provision-hosts.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
* Clarifiy enabling BMC Smart Proxy per subnet
* Simplify enabling BMC on Smart Proxies
* Sort options in alphabetical order
> Rework procedure to enable BMC on Smart Proxies

- guides/common/attributes.adoc
> Switch Foreman 3.8 DocState to unsupported

- guides/common/attributes.adoc
- guides/doc-Release_Notes/topics/foreman-3.10.0.adoc
> Update Foreman 3.10 release notes for GA

- web/content/index.adoc
- web/content/js/versions.js
> Update /web for Foreman 3.10 GA

- guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
- guides/common/modules/proc_using-ansible-job-templates-for-package-and-errata-actions.adoc
- guides/common/modules/proc_using-ansible-provider-for-package-and-errata-actions.adoc
A new procedure was created for using Ansible job
templates for package
and errata actions.
> New procedure for Ansible job templates

- guides/common/attributes-base.adoc
- guides/common/attributes-katello.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/ref_system-requirements.adoc
- guides/doc-Quickstart/master.adoc
After reviewing the quickstart guide it looks ready to be consumed. It only had one small error for the memory requirement.
I didn't look at the navigation yet.
> Mark quickstart guide as ready

- .mailmap
This allows git to map multiple addresses correctly to a single name, which is useful in properly identifying the various authors. Some entries may look redundant, but they assign a proper (single) name where people have used multiple names with the same email address. For example, one with diacritics and one without.
> Update git mailmap

- guides/common/attributes-titles.adoc
- guides/common/modules/proc_running-installer.adoc
- guides/doc-Quickstart/master.adoc
- Fixed title (quickstart > quick start)
- Moved installer procedure to a module
> Updates for Quick start guide

- guides/common/assembly_installing-capsule-server.adoc
- guides/common/assembly_installing-satellite-server-disconnected.adoc
In f187b7dfa0bb399ffd6d59c644b0dd48f769eb80 it was already hidden for the installing server guide, but this also hides it for other guides where it's included.
This came up while reviewing the Installing Foreman Proxy on Debian/Ubuntu with @apinnick.
I think it raises the question if this is the best way of hiding things. Would it make sense to have something like an assembly for this?
> Hide fapolicyd sections on all Debian guides

- guides/common/modules/proc_adding-a-remote-console-connection-for-a-host-on-proxmox.adoc
You can only access hosts running on Proxmox through remote console if they use a specific VGA option.
> Require standard VGA for VNC to hosts on Proxmox

- guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc
On an existing installation the foreman-installer command can be used, without any additional options like the scenario. In fact, it's recommended. Given the position in the guide (under "additional") we can assume it's an existing installation. This also allows us to merge the instructions for servers and proxies.
> Merge the DNS/DHCP/TFTP sections between server/proxy

- guides/common/modules/proc_configuring-remote-execution-for-pull-client-on-project-server.adoc
- guides/common/modules/proc_configuring-remote-execution-for-pull-client-smart-proxy.adoc
This always uses foreman-installer without additional arguments. That can be used on existing installations and from the context it's clear that this is only applicable in those installations.
It's similar to https://github.com/theforeman/foreman-documentation/pull/2932.
These files are all very similar, but I don't have time to see if we can merge them.
* `guides/common/modules/proc_configuring-remote-execution-for-pull-client-smart-proxy.adoc`
* `guides/common/modules/proc_rex-pull-based-transport.adoc`
* `guides/common/modules/proc_configuring-remote-execution-for-pull-client-on-project-server.adoc`
* `guides/common/modules/proc_increasing-host-limit-for-pull-based-rex-transport.adoc`
> Consistently use foreman-installer to reconfigure REX mode

- guides/common/modules/con_converting-a-host-to-rhel.adoc
- It's not clear what the original link pointed to because the subscription product changed its name and unpublished old docs without setting up redirects. This seems to be the most relevant manifest/subscriptions link.
- If the link can be cherrypicked to older versions, that would probably be better than a 404.
- This link should not change for a while. "1-latest" is intended to be a stable permanent version.
> Fix broken link to "Using manifests"

- guides/common/modules/con_transport-modes-for-remote-execution.adoc
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2269398
> Add option to switch back to SSH REX mode

- guides/common/modules/proc_running-an-ansible-playbook.adoc
- guides/doc-Managing_Configurations_Ansible/master.adoc
We have an old customer request for this use case.
The job template *should* be available in all maintained versions.
> Add running Ansible playbook in Foreman

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/foreman-3.9.2.adoc
> Update release notes for Foreman 3.9.2

- guides/common/attributes-orcharhino.adoc
orcharhino Proxies now follow Katello and Satellite:
````
$ rg smartproxy_port guides/common/attributes*
guides/common/attributes-satellite.adoc
115::smartproxy_port: 9090
guides/common/attributes-orcharhino.adoc
46::smartproxy_port: 9090
guides/common/attributes-katello.adoc
10::smartproxy_port: 9090
````
> Overwrite SmartProxy port for orcharhino

- guides/common/modules/ref_automatic-contexts-for-discovered-hosts.adoc
Old changes in global settings require this update.
Tested on Foreman 3.9 and Foreman 3.3.
> Update contexts for discovered hosts

- guides/common/modules/proc_cloning_satellite_server.adoc
if it was enabled, it remains enabled, so no need to enable it again
> stop enabling rex after cloning

- .github/PULL_REQUEST_TEMPLATE.md
> document Satellite 6.15 as released based on 3.9

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
- guides/common/linkchecker.ini
- guides/common/modules/con_upgrade-paths.adoc
> Add future downstream version to applicable files

- guides/doc-Release_Notes/topics/foreman.adoc
This package has been dropped from Foreman's packaging and users need to take manual action.
I think a manual pick to 3.10 is best. There we should mention that it will be dropped with Foreman 3.10.1.
> Refs #37334 - Add keycloak-httpd-client-install EL9 removal warning

- guides/doc-Release_Notes/topics/foreman.adoc
This reverts commit 5ca070d0f723f3070e062366dca9d91fb762874e.
According to #37334, this has been fixed for Foreman 3.11. Because we will branch docs for Foreman 3.11 based on "master", we have to revert this.
**I have merged this by mistake to "master".**
> Revert "Refs #37334 - Add keycloak-httpd-client-install EL9 removal warning (#2970)"

- guides/common/modules/proc_reclaiming-space-from-on-demand-repositories.adoc
As described in the linked issue I added a note about deleted repositories.
> Adding note into Reclaiming space from on demand repositories

- guides/common/modules/proc_adding-amazon-ec2-details-to-a-compute-profile.adoc
- guides/common/modules/proc_adding-openstack-details-to-a-compute-profile.adoc
- guides/common/modules/proc_creating-compute-profiles.adoc
Added CLI steps for these guides: 
creating compute profiles
adding amazon ec2 details to a compute profile 
adding openstack details to a compute profile
* [yes] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.
(Im not sure what this means)
> Added the CLI steps in provisioning guide

- guides/common/modules/proc_reclaiming-space-from-on-demand-repositories.adoc
This fixes the Note added in https://github.com/theforeman/foreman-documentation/pull/2991.
> Add missing new lines to a note

- guides/common/modules/ref_storage-requirements.adoc
Fix for BZ https://bugzilla.redhat.com/show_bug.cgi?id=2277211
> Extend /usr partition size to 10 GB

- guides/common/modules/proc_creating-a-content-view.adoc
Relevant issue is https://github.com/theforeman/foreman-documentation/issues/1635
I have changed the note into a warning and deleted mentions of the remove option. 
My thought process for removing mentions of Remove is that relevant information about deleting one or multiple versions is [here](https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Deleting_Multiple_Content_View_Versions_content-management), a few chapters below.
I left the mention of Delete because i could not find it mentioned anywhere else in the documentation and changed the paragraph to a Warning, because it seemed more like a warning to the user.
> Changing the note in Creating a content view

- guides/common/modules/ref_configuring-logging-levels-with-hammer-cli.adoc
A code block is missing a substitution step for attribute references. As a result, {foreman-maintain} is not displayed as expected.
To be cherry-picked only up to 3.7, the file doesn't exist for 3.6 and earlier.
> Fix foreman-maintain attribute that is not rendered correctly

- guides/doc-Upgrading_and_Updating/topics/updating_satellite_server_to_next_minor_version.adoc
As mentioned in issue #2889 i have deleted mentions of Content Host from prerequisites.
> Deleted mention of Content Host from prereqs

- guides/doc-Upgrading_and_Updating/master.adoc
- guides/doc-Upgrading_and_Updating/topics/introduction_updating_satellite.adoc
As mentioned in issue #2889 i have deleted mentions of Content Host in heading and introduction.
> Deleting mentions of Content Host in heading and introduction.

- guides/common/modules/proc_updating-disconnected-server.adoc
Fixing two issues with the repo configuration for disconnected updating guide:
- The BaseOS repository should be enabled.
- SSLverify should be enabled for the Project repo.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2278161
> Fix repo config for disconnected update

- guides/common/modules/con_content-filter-overview.adoc
_"There are also five types of content to filter:"_ No, there are not! :)
I propose a minor change in wording to eliminate the need to specify the exact number of content types because that's very difficult to maintain.
> De-specify the number of available content filter types

- guides/common/modules/proc_remediating-compliance-failures.adoc
https://github.com/theforeman/foreman_openscap/pull/546 adds a compliance remediation wizard. This PR updates the procedure on remediating compliance failures to reference the wizard.
> Document compliance remediation wizard

- guides/common/modules/proc_adding-custom-rpm-repositories-el.adoc
Fix https://community.theforeman.org/t/sync-yum-puppet-com-repository-fails-invalid-remote-url/37365
> Error: An invalid remote URL was provided: https://yum.theforeman.org/client/nightly/el9/
> Fix rpm repo url for client

- guides/common/attributes-orcharhino.adoc
Pulp serves content under "FQDN/pulp/content". Historically, it was (also) "FQDN/pulp/repos". Looking at "git grep", this seems to be the only outlier.
> Unify URL for pulp content on Foreman/Katello

- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
- guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
foreman_hooks is deprecated and will be removed with Foreman 3.11. See https://github.com/theforeman/foreman_hooks
This PR is a response to https://github.com/theforeman/foreman-documentation/pull/2950#discussion_r1560682095
> Remove deprecated plugin foreman_hooks

- guides/common/modules/proc_disabling-cockpit-on-project.adoc
- guides/common/modules/proc_enabling-cockpit-on-server.adoc
There is now proper support to disable the REX cockpit plugin. This is in the form of the ensure parameter. It also modifies the enable command since the installer may have remembered the ensure=absent part.
I'd like QE to verify and ACK this before we merge it.
> Refs #36090 - Use installer support to remove REX cockpit

- guides/common/assembly_managing-ostree-content.adoc
- guides/common/modules/con_managing-ostree-content.adoc
- guides/common/modules/proc_importing-ostree-content.adoc
- guides/common/modules/proc_installing-ostree-content-from-server.adoc
- guides/common/modules/proc_uploading-ostree-content-with-hammer-cli.adoc
The properties will first be available in Katello 4.13.
I also looked if there is already a global attribute for subman, but doesn't look like so.
> Add new OSTree properties and add brief usage path

- guides/common/modules/proc_importing-ansible-roles-and-variables.adoc
Before 713b1563b31b7e977b6117bd2108b9c11e11e182, the docs stated that this process takes longer if some Ansible roles have been imported from Smart Proxy Servers before.
> Drop unnecessary sentence

- guides/common/modules/proc_extracting-gpg-public-key-fingerprints-from-release-files.adoc
I already had twice the issue to make the connection between the `gpg --verify Release.gpg Release` commands output and the `gpg --recv-keys`, so this change extends that part.
And recently we noticed, that the receiving from `hkp://keyserver.ubuntu.com` does not work anymore -> switches this to `hkps://`
> Clarify GPG public key extraction process and update keyserver URIs

- .github/workflows/deploy.yml
- guides/Makefile
- guides/common/Makefile
This removes a lot of logic from the GitHub Action and reuses infrastructure we already have in place. It also allows running in parallel.
It does give up the checks for images and images/common, but those are rather uncommon given how uncommon it is to introduce new guides.
> Implement ccutil as a make rule

- guides/doc-Release_Notes/topics/foreman.adoc
> Remove upgrade warning for pre-3.11 branching

- guides/common/modules/con_managing-red-hat-subscriptions.adoc
Users need to know that Satellite users on a
disconnected network
create manifests on the Customer Portal. Connected users create
manifests on the Hybrid Cloud Console, following the recent migration.
A link for creating manifests on a connected network has been added to
the second paragraph of Managing Red Hat subscriptions in Managing
Content.
> Add link for creating manifests

- guides/common/assembly_provisioning-virtual-machines-vmware.adoc
- guides/common/modules/proc_installing-vmware-plugin.adoc
The VMware provider is installed by default in Satellite.
The navigation to verify the CR provider is installed has been fixed too.
> Fix install VMware

- guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
- guides/common/modules/snip_generating-content.adoc
It was decided that certain steps in generating content are not
necessary due to conflicting statements about
importability of syncable
exports.
> Remove steps from generating content

- README.md
We would like to be notified when a new branch is created because of cherry-picking. :)
> Add notify team to branching instructions in the main README

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
in 8.9 we had to remove it
in 8.10 we need to keep it
pray there won't be a 8.11
> force leapp to keep tomcat instead of removing it

- Dockerfile
- Gemfile
- Makefile
- guides/Makefile
- guides/README.md
- guides/scripts/extract_links_toc
- guides/upstream_filename_to_satellite_link.json
This commit adds the ability to generate a TOC file that can be used to test documentation links.
This is done in the theme PR: https://github.com/RedHatSatellite/foreman_theme_satellite/pull/31
> Add ability to generate TOC file for testing links

- guides/common/modules/con_host-substatus-overview.adoc
OVAL is not supported in sat 6.16.
> Remove mentions of OVAL content management support

- README.md
- web/releases/2.4.adoc
- web/releases/2.5.adoc
- web/releases/3.0.adoc
- web/releases/3.1.adoc
- web/releases/3.10.adoc
- web/releases/3.11.adoc
- web/releases/3.2.adoc
- web/releases/3.3.adoc
- web/releases/3.4.adoc
- web/releases/3.5.adoc
- web/releases/3.6.adoc
- web/releases/3.7.adoc
- web/releases/3.8.adoc
- web/releases/3.9.adoc
- web/releases/nightly.adoc
While I tried to somehow find a way to set asciidoctor attributes, I couldn't find a way. The data source already rendered it as .adoc.erb which means it first applies ERB and then asciidoctor. This allows us to use the item's data source and removes duplication, making branching easier.
> Use ERB variables for easier branching

- guides/common/modules/con_unattended-use-customization-and-image-remastering.adoc
While customizing an FDI for Satellite 6.11, I failed to find in the docs how to feed multiple DNS to the `fdi.pxdns` parameter. This PR attempts to address that.
I came across https://projects.theforeman.org/issues/22332 which has the same ask, but the suggestion of `;` as separator did not work for me. Using `,` as separator does work for me.
These verification were done by using `discovery-remaster` from foreman-discovery-image-3.8.2-1.el7sat.noarch
Because the DHCP server my testhost queries does give me both an IP and a gateway, but not the DNSes I want; I only set `fdi.pxdns` but neither `fdi.pxip` nor `fdi.pxgw` while testing.
```bash …
```
> Fixes Foreman Support #22332 - document multiple pxdns

- guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
- guides/doc-Upgrading_Project/topics/proc_upgrading-a-disconnected-project-server.adoc
If we run the command provided in the current document, it connects to postgres instead of the pulpcore database. Changing the DB name command so that it connects to pulpcore.
> Fix the DB command in the upgrade guides

- .github/PULL_REQUEST_TEMPLATE.md
Satellite 6.12 [reached EOL on May 31, 2024](https://access.redhat.com/support/policy/updates/satellite/), so we're proposing retirement of the unsupported branches 3.3 and 3.4 for cherry picks.
TODO: Notify Matrix after merge
> Retire branches 3.3 and 3.4 in the PR template

- Dockerfile
I assume building the docs locally by using the container image broke with a change to the Gemfile, but this is only a guess.
tested locally:
````
$ podman build --tag tmp:2 --file Dockerfile .
$ rm -fr guides/build && podman run --rm -v $(pwd):/foreman-documentation:Z tmp:2 make html BUILD=katello
````
> Fix building docs using container image

- guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc
With migration from Bugzilla to Jira, we need to update the way users can provide feedback.
**This has to be merged on June 5, not sooner!**
Requested in: https://issues.redhat.com/browse/SAT-25170
> Update feedback module in Satellite

- guides/common/assembly_importing-content.adoc
ifdef is handled in "master.adoc" for the managing content chapter which only provides content for Katello, Satellite, and orcharhino builds.
> Remove unnecessary ifdef in assembly

- guides/common/assembly_configuring-inter-server-synchronization.adoc
- guides/common/assembly_introduction-to-managing-content.adoc
- guides/common/assembly_overview-of-hosts.adoc
- guides/common/modules/con_configuring-inter-server-synchronization.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
Would it be OK if we add a "+1" leveloffset to [Content types in Foreman](https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Content_Types_in_Foreman_content-management) and [Browsing Hosts in Foreman web UI](https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#Browsing-Hosts-in-foreman_web_UI_managing-hosts)?
> Use assemblies

- guides/common/assembly_job-template-examples-and-extensions.adoc
No module in the "assembly_job-template-examples-and-extensions.adoc" assembly overwrites the "context" attribute. Therefore, it is not required to store the original value as "parent-context".
> Remove unnecessary attribute parent-context

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_host-management-and-monitoring-using-cockpit.adoc
- guides/common/modules/proc_disabling-cockpit-on-project.adoc
- guides/common/modules/proc_enabling-cockpit-on-server.adoc
- guides/common/modules/proc_managing-and-monitoring-hosts-using-cockpit.adoc
- guides/common/modules/proc_using-an-imagebuilder-image-for-provisioning.adoc
The name of the product (Cockpit in upstream) in Red Hat Enteprise Linux is the RHEL web console. See the title:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_systems_using_the_rhel_9_web_console/index (I'm maintaining nowadays).
In some cases, the article was missing, in some cases was even redundant in the upstream version of the docs ("the Cockpit"). Because of the differentiation, we need three attributes:
{Cockpit} -> RHEL web console (for the adj. role and the cases where the article already is)
{CockpitL} -> the RHEL web console (lowercased article)
{CockpitA} -> The RHEL web console (uppercased article when starting a sentence)
For non-Satellite docs, all three attributes are replaced just by the Cockpit value.
Please cherry-pick my commits …
> PR: use attributes to address the missing article in the RHEL web console term

- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-smart-proxy-server.adoc
> remove stray quote from custom proxy certs instructions

- guides/common/modules/proc_configuring-dns-dhcp-and-tftp.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
- guides/common/modules/proc_configuring-kerberos-authentication-for-remote-execution.adoc
- guides/common/modules/proc_configuring-network-services.adoc
- guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
- guides/common/modules/proc_configuring-smart-proxy-for-host-registration-and-provisioning.adoc
- guides/common/modules/proc_configuring-your-project-to-run-ansible-roles.adoc
- guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
- guides/common/modules/proc_enabling-openscap.adoc
- guides/common/modules/proc_enabling-power-management-on-hosts.adoc
- guides/common/modules/proc_installing-acd-on-server.adoc
- guides/common/modules/proc_installing-acd-on-smart-proxy.adoc
- guides/common/modules/proc_installing-google-gce-plugin.adoc
- guides/common/modules/proc_migrating-to-external-databases.adoc
- guides/common/modules/proc_setting-the-load-balancer-for-host-registration.adoc
On existing installations it's preferable to simply use foreman-installer with the options you wish to change. This replaces it where possible.
Includes https://github.com/theforeman/foreman-documentation/pull/2942.
> Replace installer-scenario attribute with foreman-installer when possible

- guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
After discussion with SME, the ifndef condition for Satellite needed to
be removed because it was determined the most important information was
hidden and needed to be in the Satellite docs.
> Remove ifndef condition

- guides/common/assembly_importing-content.adoc
- guides/common/modules/proc_synchronizing-ubuntu-expanded-security-maintenance-content.adoc
> Add procedure to sync Ubuntu ESM content

- guides/common/modules/proc_running-an-ansible-playbook.adoc
Requested by https://issues.redhat.com/browse/SAT-25285
> Add limitation of host params in Ansible playbook jobs

- guides/common/modules/proc_configuring-smart-proxy-for-host-registration-and-provisioning.adoc
- guides/common/modules/proc_setting-the-load-balancer-for-host-registration.adoc
The Smart Proxy on port 8000 listens on HTTP, not HTTPS.
Fixes: ad381579919a ("Register hosts through a load balancer")
> Use the correct protocol for template-url option

- guides/common/attributes-base.adoc
- guides/common/linkchecker.ini
- guides/common/modules/con_converting-a-host-to-rhel.adoc
- guides/common/modules/con_managing-container-images.adoc
- guides/common/modules/con_monitoring-hosts-using-red-hat-insights.adoc
- guides/common/modules/con_provisioning-cloud-instances-on-openstack.adoc
- guides/common/modules/con_provisioning-virtual-machines-on-ovirt.adoc
- guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
- guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
- guides/common/modules/proc_synchronizing-ansible-collections.adoc
- guides/common/modules/proc_using-insights-with-satellite-server.adoc
- guides/common/modules/ref_migrating-ansible-content.adoc
This is the result of runnning:
```
sed -i 's|https://access.redhat.com/documentation/en-us/|{RHDocsBaseURL}|' $(rg https://access.redhat.com/documentation/ guides/common/modules/ -l)
```
This should make it easier to switch to https://docs.redhat.com/
> Use RHDocsBaseURL where possible

- web/releases/3.11.json
Attempts to fix the following:
Foreman 3.11 should pair with Katello 4.13, not 4.12.
> Change 4.12 (RC) to 4.13 (RC)

- guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
- guides/doc-Managing_Content/master.adoc
After the Prerequisistes in the Importing a Red Hat subscription
manifest into Satellite Server section, we need to recommend users to
create a manifest from access.redhat.com or via
console.redhat.com.
> Recommendation for connected and disconnected user

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
Follow up to #2966.
Absence of the attributes is complicating further cherry picks, eg. #3021, #3082
The attributes don't replace any URLs, they are only defined in this PR.
> Introduce RH*DocsBaseURL attributes to 3.10-3.5

- .github/PULL_REQUEST_TEMPLATE.md
It might help avoid undesirable squashes when merging.
> Add a no-squash request to PR template

- guides/common/modules/proc_performing-a-full-backup.adoc
https://issues.redhat.com/browse/SAT-21300 requests adding "lightweight guidance" on backing up Project on an NFS share. This PR adds a short section to the procedure module for a full backup that covers the most important points of an NFS share backup.
> Add guidance for backups to NFS share

- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
RHEL 7 isn't advisable to use because the Satellite Utils repository is designated only for RHEL 8.
To be merged before #3086.
> Remove RHEL 7 option from file type remote source

- guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
The package is designated for a newer Python version. (Verified.)
> Update Pulp Manifest package name for Sat 6.15

- guides/common/modules/proc_installing-postgresql.adoc
Postgres authentication defaults to SCRAM and md5 is no longer supported. Changing the postgres documentation to reflect this.
JIRA link:
https://issues.redhat.com/browse/SAT-24619
> Change authentication to SCRAM

- guides/common/assembly_configuring-provisioning-resources.adoc
- guides/common/modules/proc_creating-an-operating-system-for-debian.adoc
- guides/common/modules/proc_creating-operating-systems.adoc
> Do not set minor OS version for Debian and Ubuntu

- guides/common/attributes-base.adoc
- guides/common/modules/con_content-views-in-project.adoc
I would like some guidance/suggestions on the wording.
Example URLs for you to check on your local instance:
* https://katello.example.com/pulp/content/Example/content_views/RHEL_9/12.0/content/dist/rhel9/9.3/x86_64/
* https://katello.example.com/pulp/content/Example/Production/Composite_AlmaLinux_8/custom/AlmaLinux_8/BaseOS/
The content is hidden for Satellite because I assume that you don't want to document how to consume content with subscription-manager. To change this, I'd need to make sure that the repo URLs work for both "custom" and "RH" content by using attributes.
> Show URL repos structure of content on Katello

- guides/common/attributes-base.adoc
- guides/common/linkchecker.ini
It is time. (I think.)
UPDATE: All Red Hat documentation traffic should now get redirected to the new docs site at docs.redhat.com. With this PR, I'm changing `:RHDocsBaseURL:` to reflect that and use docs.redhat.com for all RH links rather than rely on redirects from the previous access.redhat.com.
> RH has moved its docs to docs.redhat.com

- guides/common/modules/proc_creating-repositories-to-synchronize.adoc
Tested locally; URL works and repo names did not change:
> Use CentOS Stream 9 as repo discovery example URL

- CONTRIBUTING.md
- guides/common/assembly_supported-usage-and-versions-of-project-components.adoc
- guides/common/modules/con_client-operating-systems.adoc
- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
- guides/common/modules/proc_configuring-project-for-performance.adoc
- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-hosts.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-manually.adoc
- guides/common/modules/proc_preparing-cloud-init-images-in-rhv.adoc
- guides/common/modules/ref_supported-clients-in-registration.adoc
- guides/common/modules/snip_supported-client-operating-systems.adoc
current assumption for other build targets:
* Satellite continues to support RHEL 7 as OS for clients with "ELS" until 2028
RHEL 7 is still supported: it's the extended life support (ELS) phase. The support will last for the next 4 years. :heavy_check_mark: 
* orcharhino continues to support RHEL 7 and Oracle Linux 7 until June 2028 as OS for clients. :heavy_check_mark: 
There are some instances that mention EL6, so I've kept EL7 if it was next to them.
* I am unsure how to best find all instances that relate to CentOS 7.
* We will not cherry-pick this change.
> CentOS 7 EoL

- guides/common/modules/con_converting-a-host-to-rhel.adoc
The guide has been retitled and the links aren't passing the linkchecker builds.
> Update RHEL 8 C2R links

- guides/common/assembly_provisioning-cloud-instances-azure.adoc
- guides/common/assembly_provisioning-cloud-instances-ec2.adoc
- guides/common/assembly_synchronizing-template-repositories.adoc
https://issues.redhat.com/browse/SAT-25665 This PR hides a few procedures for uninstalling Foreman plug-ins for Satellite builds.  Satellite depends on these plug-ins and they cannot be uninstalled. 
> Hide plug-in uninstallation procedures for Satellite

- guides/common/modules/ref_system-requirements.adoc
The link targets are missing, links had to be updated.
> Update RHEL FIPS mode links

- guides/common/assembly_synchronizing-template-repositories.adoc
- guides/doc-Administering_Project/master.adoc
- guides/doc-Managing_Hosts/master.adoc
The chapter doesn't belong into _Managing hosts_, but into _Administering Project_.
And we can hide plug-in enablement for Sat, because it's enabled by default.
> Move TemplateSync and hide enablement

- guides/common/modules/proc_using-container-registries.adoc
Containers are able to be pushed to Satellite's
container registry.
This command for pushing containers was needed to show the user how to
do so.
The Update Using Container Registries .adoc file is updated to reflect this.
Related to PR #3023 and this [Jira ticket](https://issues.redhat.com/browse/SAT-18579).
> Document Container Push Workflow

- guides/common/modules/proc_configuring-network-services.adoc
The dns-forwarders option is an array of values. Previously it was just a string but now it's validated to be an IP or `$ip port $port`. This prevents users from specifying an invalid value which could cause BIND to refuse to start up.
The `ip;ip` value was abusing an internal implementation detail. It was never intended to work, but prior to the stricter validation it happened to work. The correct way is to repeat the parameter with the various values.
> Refs #37604 - Fix foreman-proxy-dns-forwarders option

- guides/common/modules/ref_supported-browsers.adoc
Satellite officially only supports a few languages. Others are available, but incomplete. For upstream we don't list all languages because the list is even more inconsistent.
It should be noted that with the next release we'll add Korean to the list, but for now Red Hat's translators haven't worked on that for a long time so it's incomplete.
> Update translated languages

- guides/common/modules/ref_system-requirements.adoc
In all other places we link to 1-latest instead of 2023.
It makes me wonder if we need an attribute like for RHEL's docs.
> Consistently link to subscription_central/1-latest

- guides/common/assembly_installing-capsule-server.adoc
- guides/common/assembly_preparing-smartproxyservers-for-load-balancing.adoc
Satellite has different instructions for the proxy repositories while all the rest has the same basic instructions. This matches the ifdef with an ifndef, effectively creating an else condition.
> Consistently cover all build flavors

- guides/common/modules/proc_connecting-to-an-amazon-ec2-instance-using-ssh.adoc
Rather than using various small steps, this uses a single command to run psql as the postgres user. You can also pass a database to open.
I'd like to note that this procedure in itself is problematic. This really isn't a normal procedure that any user can (or should) execute. Direct database access is frowned upon. Also, we should be encrypting the data at rest so that this is possible is IMHO a bug in itself.
> Use a direct command to open a database shell

- guides/common/modules/con_making-open-source-more-inclusive.adoc
- guides/doc-Administering_Project/master.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Managing_Configurations_Ansible/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Monitoring_Project/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Updating_Project/master.adoc
- guides/doc-Upgrading_Project/master.adoc
With the launch of docs.redhat.com, the conscious language module is no longer required as the inclusivity statement is a part of the footnotes. E.g.: https://docs.redhat.com/en/documentation/red_hat_satellite/6.15/html/installing_satellite_server_in_a_connected_network_environment/index Removing the CLP module for all releases and from all guides.
> Remove CLP module from documentation

- CONTRIBUTING.md
Add "Product" and "Ansible Playbook" to Capitalization section of Contributing.md
> Add Product, Ansible Playbook to Contributing

- guides/common/modules/con_importing-kickstart-repositories.adoc
For two reasons:
- local TOCs aren't well maintainable
- the user can see them in the global TOC (at least in Satellite and I hope for a 3-level TOC in Foreman in future)
> Remove local TOC

- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-server.adoc
The custom certificate in the command to renew the certificate is `/root/project_cert/project_key.pem`, however, this should be `/root/project_cert/project_cert_key.pem`.
JIRA: https://issues.redhat.com/browse/SAT-24132
> Fix certificate name in procedure for custom cert

- guides/common/modules/snip_supported-client-operating-systems.adoc
Requested by https://issues.redhat.com/browse/SAT-26077
> Support RHEL-convertible OSs in host registration for Satellite

- guides/common/modules/ref_supported-clients-in-registration.adoc
Due to cherry-pick conflicts in #3113 
> Support convertible OSs in Satellite 3.11

- guides/common/assembly_importing-content.adoc
- guides/common/modules/proc_recovering-corrupted-content-on-a-smart-proxy.adoc
A CLI procedure was needed for repairing corrupted content on a
SmartProxy. There are 3 optional parameters for
repairing corrupted
content as well as a global fix.
> Hammer CLI procedure for corrupted content

- guides/common/modules/snip_glossary-term-smart-proxy.adoc
The concept of an "integrated" or "external" Smart Proxy has never been used outside of Katello. In vanilla Foreman all Smart Proxies are equal.  Some just happen to run on the same server as Foreman, but even that's optional. Advanced users can use `--no-enable-foreman-proxy` to the installer to disable this.
Within Katello there is a slight nuance and that's the role of Pulp. Each Smart Proxy Pulp plugin can identify itself as a mirror. Typically this is true for every Smart Proxy that's not on the Foreman server while it's false for the one on the Foreman server. If the number of non-mirrors isn't equal to 1 then Katello has a problem.
On a technical level there is no code difference and it's just a simple configuration flag. It would also be perfectly valid to separate out the …
> Avoid the integrated SmartProxy for non-Katello

- guides/common/modules/con_updating-project-to-next-patch-version.adoc
- guides/common/modules/proc_managing-packages-on-the-base-operating-system.adoc
- guides/common/modules/proc_updating-disconnected-server.adoc
- guides/common/modules/proc_updating-server.adoc
- guides/common/modules/proc_updating-smart-proxy.adoc
- guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
- guides/doc-Updating_Project/master.adoc
It must be confusing that we call z-stream "minor version" when it should be called "patch version". This has been bugging me for quite some time.
> Fix x.y.z version terminology

- guides/common/modules/proc_creating-an-image-for-amazon-ec2.adoc
Debian 10 "Buster" is EoL but the Debian project offers multiple cloud images for multiple cloud providers similar to Canonical.
> Update URL for Debian cloud images

- guides/common/assembly_managing-errata.adoc
- guides/common/modules/proc_creating-custom-provisioning-snippets.adoc
- guides/common/modules/proc_running-custom-code-while-applying-errata.adoc
Refs 2064ec7457b3d41b72c2d48b7df9371f8b09d053 in katello
Closes #3157
> Fixes #37654 - Use custom snippets to apply errata

- guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
- guides/doc-Planning_for_Project/topics/Configuration_Management_Support.adoc
- guides/doc-Planning_for_Project/topics/Deployment_Considerations.adoc
The Puppetserver service compiles manifests into a catalog. The agent retries this catalog and applies it. Manifests don't leave the Puppetserver process.
Puppetserver does a lot more, so this is still an inaccurate description but less than it used to be. For example, if the Certificate Authority component is enabled it also deals with certificates and it's a fileserver used by the Puppet Agent. The Puppet Agent also sends its facts and reports to Puppetserver.
We could also copy https://www.puppet.com/docs/puppet/8/server/about_server.html
> Puppet is configured in an agent-server architecture, in which a primary server node manages the configuration information for a fleet of agent nodes. Puppet Server acts as the primary server node. Puppet Server is a Ruby and Clojure application …
> Correct Puppetserver description in glossary

- guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
- guides/common/modules/proc_migrating-to-external-databases.adoc
This way they are all consistent with eachother. They follow:
* manage
* host
* name
* user
* password
Missing parameters were added for consistency.
> Move the external DB installer parameters around

- guides/common/modules/proc_renaming-smart-proxy.adoc
> Use global registration after renaming Smart Proxy Server

- guides/common/modules/proc_installing-postgresql.adoc
Postgres authentication defaults to SCRAM and md5 is no longer supported. The changes done in https://github.com/theforeman/foreman-documentation/pull/3107 require an additional step. Adding in the missing step.
JIRA link:
https://issues.redhat.com/browse/SAT-24619
> Add step for SCRAM auth

- guides/common/modules/proc_enabling-the-project-client-name-repository-for-rhel-7-and-rhel-6.adoc
- guides/common/modules/proc_enabling-the-project-client-name-repository-for-rhel-9-and-rhel-8.adoc
- guides/common/modules/proc_synchronizing-the-project-client-name-repository-for-rhel-7-and-rhel-6.adoc
- guides/common/modules/proc_synchronizing-the-project-client-name-repository-for-rhel-9-and-rhel-8.adoc
A necessary follow-up on #3143 otherwise we would have "Red Hat Red Hat" in these places.
> Remove Team from refs to Client repo name 3.11-3.7

- guides/common/modules/ref_dynamic_partition_example.adoc
This command does not take any arguments. [zerombr ref](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/automatically_installing_rhel/index#zerombr_kickstart-commands-for-handling-storage)
Requested in Jira: [SAT-26926](https://issues.redhat.com/browse/SAT-26926)
> Remove argument from zerombr

- guides/common/assembly_getting-started-with-ansible.adoc
- guides/common/assembly_provisioning-cloud-instances-azure.adoc
- guides/common/assembly_using-foreman-webhooks.adoc
- guides/common/modules/proc_creating-a-shellhook-to-print-arguments.adoc
- guides/common/modules/proc_upgrading-hosts-to-next-major-release.adoc
Satellite has a set of mandatory plugins and the satellite meta-package ensures these are installed. Previously some were ensured by the installer but starting Satellite 6.16 this list is complete. The next step is to remove them from the installer, but some documentation procedures still told users to use these redundant options.
While this should be safe to cherry pick to Satellite 6.15, I'm a bit hesitant. Technically you'd rely on defaults in the installer to be correct while in 6.16 the packaging guarantees it. On the other hand, for ansible we we only `foreman-proxy-plugin-ansible` being enabled by default.
For now I've only selected the upstream supported versions to reduce potential cherry pick issues. There's also a small change that provides the instructions for azure on …
> Drop plugin installation instructions on Satellite

- guides/common/modules/proc_creating-architectures.adoc
Since Foreman 3.5 the i386 architecture is no longer seeded by default, only x86_64 is ensured.
> Refs #35528 - Reflect that i386 isn't provisioned by default

- guides/upstream_filename_to_satellite_link.json
I manually verified what was linked on https://docs.redhat.com/en/documentation/red_hat_satellite/6.15
I couldn't find a way to determine this automatically. I looked at docinfo.xml but there's no destination there so I'm assuming it's coded somewhere in a conversion script. [foreman_theme_satellite](https://github.com/RedHatSatellite/foreman_theme_satellite) will also use this same info when https://github.com/RedHatSatellite/foreman_theme_satellite/pull/58 is merged so those will need to be kept in sync.
> Add Monitoring_Project to upstream_filename_to_satellite_link.json

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
https://issues.redhat.com/browse/SAT-26357 requests clarifying a procedure step to restart and enable gssproxy.service.
Doing a bit of archeology, I found the commit that introduced `--now` to that step: https://github.com/theforeman/foreman-documentation/commit/a4be0ab11f53cc4ff1302b41816c41dd40874daa  It seems that in case of this particular step, asking users to restart && enable (without --now) might help prevent some raised eyebrows.
> Drop --now after restarting gssproxy

- guides/common/modules/proc_enrolling-server-with-the-ad-server.adoc
Both https://issues.redhat.com/browse/SAT-22855 and https://issues.redhat.com/browse/SAT-26355 request adding the packages to the list of packages required for direct integration with AD.
UPDATE: Confirmed in https://github.com/theforeman/foreman-documentation/pull/3149#discussion_r1688125085.
> Update package list for direct AD integration

- guides/common/assembly_managing-content-views.adoc
- guides/common/modules/proc_copying-a-content-view.adoc
It was requested that we include a procedure for 
copying content views
since there was only a solution article available with 
a short
description for copying a content view. This procedure 
gives a more
detailed set of steps.
> Add procedure for copying a content view

- guides/common/attributes-base.adoc
- guides/common/modules/con_resolving-package-dependencies.adoc
- guides/common/modules/proc_applying-errata-to-hosts-el.adoc
- guides/common/modules/proc_installing-proxy-packages.adoc
- guides/common/modules/proc_installing-server-packages-el.adoc
The dnf upgrade command lists dnf update as a deprecated alias.
I split this off from https://github.com/theforeman/foreman-documentation/pull/2936 to reduce its scope.
> Replace deprecated use of dnf update

- guides/common/attributes-satellite.adoc
> Add comment to update json in downstream

- guides/common/modules/con_using-pxe-to-provision-hosts.adoc
Changes split from #3161
The SB feature isn't ready for Sat, so it's better to merge these improvements separately.
> Improve intro for PXE provisioning concept

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/attributes.adoc
- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
- guides/doc-Upgrading_Project/master.adoc
- guides/doc-Upgrading_Project_Disconnected/master.adoc
Adding information about the process to upgrade the underlying OS from EL8to9. Repurposed the older RHEL7to8 LEAPP module from 3.1 for 8to9 LEAPP upgrade.
> Add section for RHEL8to9 in-place upgrade using LEAPP

- guides/common/modules/proc_configuring-direct-ad-integration-with-gss-proxy.adoc
The assembly on direct AD integration includes instructions on configuring GPOs in the form of an IMPORTANT admonition box. We can turn it into a regular procedure step instead and throw in a reference to sssd-ad(5) for good measure. Confirmed in https://github.com/theforeman/foreman-documentation/pull/3149#discussion_r1688116978.
> Integrate GPO information into the direct AD integration proc

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
What: I'm proposing to move the expected contents of a PR from CONTRIBUTING.md directly to the PR template. This PR only moves two bullet points (the _what_ and the _why_) because I find that the rest is unclear or very difficult to enforce anyway. If you feel we should include the dropped bullet points as well, feel free to suggest more headings.
Why: Any documentation works best when presented at the moment when users need it. And I don't think adding these two points to the PR template makes it too cumbersome.
> Migrate PR requirements to the PR template

- guides/common/assembly_configuring-repositories.adoc
- guides/common/assembly_installing-capsule-server.adoc
- guides/common/assembly_installing-server-connected.adoc
- guides/common/assembly_preparing-smartproxyservers-for-load-balancing.adoc
- guides/common/modules/con_configuring-repositories.adoc
- guides/common/modules/proc_configuring-repositories-foreman-deb.adoc
- guides/common/modules/proc_configuring-repositories-foreman-el.adoc
- guides/common/modules/proc_configuring-repositories-katello.adoc
- guides/common/modules/proc_configuring-repositories-orcharhino.adoc
- guides/common/modules/proc_configuring-repositories-satellite.adoc
- guides/doc-Quickstart/master.adoc
The procedure to enable repositories is very specific to every build flavor. Trying to squeeze this into a single file makes it very complicated. This makes maintenance easier and doesn't really duplicate that much.
This PR is split off from https://github.com/theforeman/foreman-documentation/pull/3104 to verify it's just an internal refactor and doesn't have any impact on the resulting guides. It may also be easier to review this standalone, but I'll leave that up to others.
> Split proc_configuring-repositories.adoc into several files

- guides/common/assembly_configuring-external-authentication.adoc
- guides/common/modules/con_configuring-external-authentication.adoc
- guides/common/modules/con_important-user-and-group-account-information-for-active-directory-accounts.adoc
I propose to move a few paragraphs about AD user accounts to a separate module. No changes in wording except for a slight adjustment to the heading of the module; other than that, this really is just about the move.
The content I'm moving is currently included in the introduction to an assembly. That is no place for detailed concept or feature explanations.
This PR is just about moving the content out of the introduction to a place further down the assembly. Although the wording could use some improvement, I don't intend to address that gap in this PR.
I want to move the content out of the introduction in preparation for another PR that will introduce changes to the assembly's introduction and heading.
> Move AD account info into its own module

- guides/common/modules/proc_registering-project-as-a-client-of-keycloak.adoc
The correct command to use when resetting Keycloak authentication is foreman-installer, not foreman-maintain.
This is a mistake I made in a previous PR.
Thanks to @lhellebr for pointing this out.
> Fix command to reset Keycloak authentication

- README.md
I'm adding a new step to the branching procedure to include rebasing the new branch on top of master.
During the latest branching, the new branch initially missed a few commits from master. Adding the step could help prevent that next time.
No.
> Add a rebase step to branching instructions

- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/common/modules/proc_upgrading-smartproxy-server.adoc
There may be more spots that need EL9.
> Add EL9 links to the nightly upgrade guide

- guides/doc-Release_Notes/README.md
The script lives in theforeman.org repo because that's where it has historically lived. That repository also contains the mailmap to ensure multiple identities (different spelling or email) are mapped to a single name.
Something to consider: this doesn't update Katello and the script isn't really suited for that right now. I debated merging the two into one big list of contributors. Simply include Katello contributors as Foreman contributors.
Another note: we need to update the procedures to reuse this:
https://github.com/theforeman/theforeman-rel-eng/blob/ebfe21978af75a30a96d3716ddbd403d7b53aac3/procedures/foreman/release.md.erb#L102
https://github.com/theforeman/theforeman-rel-eng/blob/ebfe21978af75a30a96d3716ddbd403d7b53aac3/procedures/katello/release.md.erb#L35
Fixes #1767 
Please …
> Document how to populate foreman-contributors.adoc

- guides/common/modules/proc_creating-a-local-source-for-a-custom-file-type-repository.adoc
- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
"pulp-manifest" is packaged in pulpcore_packaging. The RPM package name depends on the Python version. Using the RPM capability, you can install "pulp-manifest" independent of the package name.
This is part of Pulpcore 3.49 -> Katello 4.13 -> Foreman 3.11.
Refs PR-1070 in pulpcore-packaging
````
[pulpcore]
name=pulpcore
baseurl=https://yum.theforeman.org/pulpcore/3.49/el8/x86_64/
enabled=1
gpgcheck=0
sslverify=0
...
Installing:
python3.11-pulp_manifest                                      noarch                                   3.0.0-5.el8                                         pulpcore                                       21 k
Installing dependencies:
...
````
> Use RPM capability in favor of package name

- guides/common/modules/proc_downloading-python-packages-to-a-host-from-a-python-repository.adoc
- guides/common/modules/proc_installing-python-packages-from-server.adoc
- guides/common/modules/proc_synchronizing-python-repositories.adoc
Tested on Foreman 3.11 that "Upstream Authentication Token" is gone; "Verify SSL" is present, and that the values for "Package Types" have changed.
Synchronized from pypi.org:
* "django ~= 5.1" + "bdist_wheel" -> "Django-5.1-py3-none-any.whl"
* "django ~= 5.1" + "sdist" -> "Django-5.1.tar.gz"
Ensure docs match the Foreman Web UI.
Docs were outdated.
I think we should consolidate the wording for "SSL Verify" in a follow-up PR:
````
$ rg "Verify SSL"
guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
20:. Select *Verify SSL* to verify that the SSL certificates of the repository are signed by a trusted CA.
guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
30:. If SSL verification is required, enable *Verify SSL* and select the SSL CA certificate. …
```
> Update procedure to sync Python-type content

- guides/doc-Release_Notes/topics/foreman.adoc
Foreman 3.12 supports Puppet 8. While the manual hasn't been updated, this helps to announce RC1.
https://projects.theforeman.org/issues/37686 was the last blocker.
> Add Puppet 8 as a headline feature

- guides/common/modules/proc_logging-in-to-project-configured-with-keycloak-as-an-authentication-source.adoc
- guides/common/modules/proc_registering-project-as-a-client-of-keycloak.adoc
This PR adds a couple of more commands and clarification bits to the procedure for configuring Keycloak.
QE is testing the procedures to configure the Quarkus distribution of Keycloak as an external authentication source.
No.
> Update Quarkus-based Keycloak procedures

- guides/common/modules/con_prerequisites-for-using-discovery.adoc
- guides/common/modules/ref_troubleshooting-discovery.adoc
> Improve Discovery troubleshooting

- guides/common/modules/con_upgrading-prerequisites.adoc
- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
As the latest release supports only SCA mode, it is required that all orgs be migrated to SCA before upgrade. Adding this as a prerequisite
JIRA: https://issues.redhat.com/browse/SAT-26365
> Add SCA migration prerequisite

- guides/common/modules/con_upgrade-paths.adoc
- guides/common/modules/con_upgrading-project.adoc
- guides/common/modules/proc_configuring-repositories-foreman-deb.adoc
- guides/common/modules/proc_performing-post-upgrade-tasks.adoc
- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/doc-Upgrading_Project/master.adoc
Content is based on Foreman Manual for 3.11:
https://theforeman.org/manuals/3.11/index.html#3.6Upgradeto3.11
Make "Upgrade Server" available for "Foreman on Debian/Ubuntu".
Before, it was only available in the Foreman Manual. Before we can make docs.theforeman.org official, we need to provide basic upgrade instructions for the Community.
Downsides: we now have two places where we define the set of operating systems for `foreman-deb` -> I have added comments to both files.
Follow up task: Add instructions to upgrade Smart Proxy Servers on Debian/Ubuntu
> Add procedure to upgrade Foreman on Deb

- web/releases/3.11.adoc
- web/releases/3.11.json
- web/releases/3.12.adoc
- web/releases/3.12.json
- web/releases/nightly.adoc
- web/releases/nightly.json
Show URLs in navigation & minor renaming of links on the overview page in a second commit.
Because I forgot it in https://github.com/theforeman/foreman-documentation/pull/3225
> Show URL to newly rendered upgrade guide for Foreman on Debian/Ubuntu in navigation

- guides/common/modules/proc_creating-a-complete-permission-table.adoc
Moving the package requirement to prerequisites. The package exists only in Foreman, there's no need to install it in Satellite. + Additional beautification.
In Satellite, installing the package is not only unneccessary but also impossible, it doesn't exist.
Not sure about the package in orcharhino.
> Improve creating permissions table

- guides/common/assembly_configuring-external-authentication.adoc
- guides/common/modules/con_configuring-keycloak-quarkus-authentication-for-project.adoc
- guides/common/modules/con_configuring-keycloak-wildfly-authentication-for-project.adoc
The default distribution of Keycloak is now based on Quarkus. While we have the procedures for Quarkus-based Keycloak in place, we are still not clear on whether we should label the Wildfly-based Keycloak procedures as deprecated or whether we can actually support the Quarkus-based Keycloak procedures.
This PR introduces a note that describes the support level and provides links to docs about migrating Keycloak.
https://issues.redhat.com/browse/SAT-27194
UPDATE: I've been adding commits as the discussion around the support levels evolved. The latest state doesn't use the term "deprecated" for the procedures to configure the Wildfly distribution of Keycloak (because it's actually Keycloak that was deprecated, not the procedure in Satellite docs) and also excludes the Quarkus-based …
> Clarify the support level for the Quarkus distribution of Keycloak

- guides/common/modules/proc_synchronizing-templates-with-an-existing-repository.adoc
Attempting to update the Git global config for the `foreman` user fails due to insufficient permissions. Adding steps to manually create the config file as well as set the appropriate permissions on the file ensures that it gets updated as expected.
https://issues.redhat.com/browse/SAT-27104
The proposed solution might be considered hacky by some but it looks like [SAT-27349](https://issues.redhat.com/browse/SAT-27349) should make the whole section obsolete in a future version.
> Manually set global Git configuration in proc to sync templates with an existing repo

- guides/common/modules/proc_assigning-roles-to-a-user.adoc
I'm updating the checkbox label for setting administrator privileges in user account settings.
See Administer > Users > _username_ > Roles.
I'm requesting cherry-picks down to 3.9 only because I can't currently verify on earlier versions and the issue is not _that_ critical.
> Update the label for Administrator privileges when defining roles

- guides/common/modules/proc_configuring-email-notification-preferences.adoc
The procedure to configure email notifications for a user is missing details on which permission is required.
https://issues.redhat.com/browse/SAT-27647 and https://issues.redhat.com/browse/SAT-27616
With the exact permission missing, users might instead be tempted to grant a broader set of permissions (admin level) in an effort to troubleshoot the problem. We should try to avoid that.
The error message displayed when the user account doesn't have the required permission is not very helpful:
I might look into expanding the error message next if I have the capacity for it.
> Add permission required for email notifications

- guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
The checksum number `sha1` is no longer secure and modern systems support file checksums greater than `sha1`. It has been replaced with the correct checksum values.
> Change checksum number

- guides/common/assembly_managing-dns-on-smart-proxies.adoc
- guides/common/modules/con_managing-dns-by-using-smartproxy.adoc
- guides/common/modules/proc_configuring-dns-nsupdate.adoc
This takes the idea that there should be a central place with documentation on all DNS providers. Not spread over multiple guides. It starts with the `dns_nsupdate` provider, but this should be completed with all of the providers.
This is split off from https://github.com/theforeman/foreman-documentation/pull/2933 to keep the scope limited. Infoblox turned out to be much harder than expected.
> Document dns_nsupdate provider in managing DNS section

- guides/common/modules/proc_updating-disconnected-server.adoc
- guides/common/modules/proc_updating-server.adoc
- guides/common/modules/proc_updating-smart-proxy.adoc
making `--target-version` use 6.15.z, not 6.15._z_, as the command expects a literal z not the Z-stream version
Because they are correct
3.11+ doesn't need this, as there the command doesn't take any target version anymore
> use literal .z, not italic (to replace) in target-version option

- guides/common/modules/proc_exporting-a-repository.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
The command for exporting a repository resulted in 
error until a flag
for organization was added. The organization's name has 
been added to
the command to fix the error. See https://issues.redhat.com/browse/SAT-26583.
> Add organization to export repo without error

- guides/common/modules/con_using-ldap.adoc
The same change as in https://github.com/theforeman/foreman-documentation/pull/3277, but for branches 3.10 and earlier.
N/A
N/A
> Foreman expects LDAP server to follow RFC2307

- guides/common/modules/proc_logging-in-to-the-projectwebui-with-freeipa-credentials-in-chrome.adoc
A minor change to make sure the asterisks in a command included in a code block are preserved.
Right now, the asterisks are interpreted as bold text.
Another PR is coming soon for 3.10 and earlier.
> Prevent asterisk substitution in a code block

- guides/common/modules/proc_using-freeipa-credentials-to-log-in-to-the-ProjectWebUI-with-a-Chrome-browser.adoc
A minor change to make sure the asterisks in a command included in a code block are preserved.
Right now, the asterisks are interpreted as bold text.
https://github.com/theforeman/foreman-documentation/pull/3282 applies the same fix on 3.11 and later.
> Prevent asterisk substitution in a code block (3.10 and earlier)

- guides/common/modules/proc_enabling-and-disabling-repositories-on-activation-key.adoc
Document missing filter on AK page.
follow-up to Katello PR https://github.com/Katello/katello/pull/11114
Can I consolidate this? What's our preferred way?
````
$ rg "dropdown list" | wc -l
1
$ rg "dropdown menu" | wc -l
12
$ rg "drop-down menu" | wc -l
7
$ rg "drop-down list" | wc -l
5
````
> Filter repository by Status on Activation Key page

- guides/common/assembly_configuring-external-authentication-and-enabling-single-sign-on-and-two-factor-authentication.adoc
- guides/common/assembly_configuring-external-services.adoc
I'm moving an assembly on managing a FreeIPA's host lifecycle out of the assembly on configuring external authentication.
The assembly doesn't describe configuring authentication so it doesn't belong in a chapter on external authentication, even though it mentions FreeIPA. I can't say for sure if I'm moving it to the right place, though.
I'd like to resolve this before I continue with https://github.com/theforeman/foreman-documentation/pull/3294.
> Move assembly on managing the lifecycle of a host enrolled with FreeIPA

- guides/common/attributes-base.adoc
- guides/common/attributes-foreman-deb.adoc
- guides/common/modules/proc_installing-postgresql.adoc
- guides/common/modules/proc_migrating-to-external-databases.adoc
remove DB RPM package and DB itself after migrating to external DB. otherwise, unnecessary data remains on Foreman Server.
Fixes https://github.com/theforeman/foreman-documentation/issues/2131
> Cleanup DB after migrating to external DB

- guides/common/modules/ref_content-settings.adoc
The CDN SSL version was determined not to be needed in 
the content
settings reference module. There is no mention of it in 
the
documentation and if it was mentioned, it would have 
been removed.
> Remove CDN SSL version

- CONTRIBUTING.md
- guides/README.md
I propose updating the project's contributing guidelines with a bullet point explaining that each PR must have the `style review done` and `tech review done` labels set before anyone can merge it.
The idea came up during Red Hat's docs team retrospective when we met to evaluate the process we followed for the Foreman 3.12 release. The issues we discussed and hope to address with this PR include:
* Uncertainty surrounding whether a PR has been properly reviewed and is ready to be merged.
* Accountability about who is responsible for reviewing what.
* Transparency about who has already reviewed a PR and where feedback was provided.
@Lennonka suggested it would be a good idea to completely disable the ability to merge PRs that don't have these labels. That would be great if GH supports that …
> Require review labels before merging

- guides/common/modules/con_importing-the-project-client-name-repository.adoc
It changes from `Red Hat Red Hat Satellite Client 6` to `Red Hat Satellite Client 6` when describing the client repository.
Previously it rendered as `Red Hat Red Hat Satellite Client 6` which is confusing.
This change was introduced in 620b1bd28aa3. I can see it wasn't cherry picked in the PR and the commit is only in `master` and `3.12`. I noticed it when @evgeni was sharing his screen and I thought it was 6.15, but now I can't find it there anymore.
> Avoid Red Hat Red Hat in the Satellite client repository name

- guides/common/modules/proc_synchronizing-the-new-repositories.adoc
Removing "Red Hat" occurence
To avoid duplicit "Red Hat" in repo name
> Avoid RH RH duplicity in Client repo name

- guides/doc-Release_Notes/topics/katello.adoc
A headline feature for container push was missed.
> Add container push to Katello 4.14 headline features

- guides/common/attributes-satellite.adoc
- guides/upstream_filename_to_satellite_link.json
Adjusting the URL fragment for a new guide to match its title.
Downstream tooling needs the two to match.
N/A
> Fix URL fragment for Configuring user auth

- guides/doc-Release_Notes/topics/katello.adoc
In the previous PR https://github.com/theforeman/foreman-documentation/pull/3319/ , the container push headline feature was put in the wrong spot. This corrects that (and adds a little more text).
> Fix container push headline feature location

- guides/common/assembly_registering-hosts.adoc
- guides/common/modules/proc_registering-a-host.adoc
- guides/common/modules/proc_running-ansible-roles-during-host-registration.adoc
Adding a procedure how to run Ansible roles upon host registration and a note in _Registering a host_.
We got a request from our support team that users weren't aware of this option and it should be documented.
> Add running Ansible roles upon host registration

- guides/common/modules/proc_calling-the-api-in-python.adoc
- guides/common/modules/proc_calling-the-api-in-ruby.adoc
Introducing attribute substitution into a few API examples. This also involves excluding a few `{`s that are supposed to be rendered verbatim.
The API examples are rendered incorrectly, see also https://github.com/theforeman/foreman-documentation/pull/3328#issuecomment-2382588825.
N/A
> Fix attribute substitution in API examples

- guides/common/modules/ref_json-response-format.adoc
Replacing "2013" with "2024" in several API request examples.
Using "2013" makes the examples look old.
N/A
> Update time stamps in example API requests

- guides/common/modules/proc_registering-a-host.adoc
I'm describing alternative ways of registering a host: CLI, Ansible, API.
https://issues.redhat.com/browse/SAT-28377 requested adding the Hammer command and API resource that correspond to the existing web UI procedure as users weren't aware of their existence and were unable to look them up. Then on top of that, prompted by a conversation with @evgeni, I thought it might be a good idea to add a reference to the corresponding Ansible module too.
The CLI, Ansible, and API "procedures" are very minimal by design. Users have very good reference documentation available to them (`--help`, `ansible-doc`, and built-in API reference) and I don't want to duplicate it in the guides.
I'm requesting cherry-picks down to 3.7 only because that's what …
> Document CLI, Ansible, and API for registering a host

- guides/common/modules/con_api-cheat-sheet.adoc
I'm trying to sanitize the API cheat sheet to remove all references of the possibility to run API requests via Proxies.
The section currently includes an Important box notifying the users about the deprecated functionality. However, why not just drop the references altogether if we don't want users to do this? This was originally proposed in https://issues.redhat.com/browse/SAT-28361.
N/A
> Drop references to API requests via Proxy

- web/releases/3.12.json
- web/releases/nightly.json
Adding a new guide, Configuring User Authentication (https://github.com/theforeman/foreman-documentation/pull/3294), to docs.theforeman.org navigation.
N/A
N/A
> Add Configuring user authentication guide to navigation

- guides/common/attributes-foreman-deb.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/modules/ref_utilities-for-processing-log-information.adoc
Move all deployment targets to use `sos report`
`foreman-debug` is unmaintained, partially broken on EL9 (at least the Katello integration is) and not installed by default since Foreman 3.10: https://projects.theforeman.org/issues/37022
I intend to completely remove that tool, but first docs need to be updated not to refer to it :)
> don't mention foreman-debug, only sos report

- guides/common/modules/con_network-boot-provisioning-workflow.adoc
- guides/common/modules/proc_building-a-custom-discovery-image.adoc
- guides/common/modules/proc_configuring-an-external-dhcp-server.adoc
- guides/common/modules/ref_host-specific-variables.adoc
- guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc
$ fd -e adoc | xargs sed -i "s/bootloader/boot loader/g"
Reverted change to URL manually.
Make vale happy: change "bootloader" to "boot loader".
prerequisite to https://github.com/theforeman/foreman-documentation/pull/3272/files
> Fix spelling of boot loader

- guides/common/modules/proc_calling-the-api-in-ruby.adoc
- guides/common/modules/proc_managing-puppet-modules-with-r10k.adoc
- guides/common/modules/ref_customizing-job-templates.adoc
- guides/common/modules/ref_example-including-power-options-in-a-job-template.adoc
- guides/common/modules/ref_example-restorecon-template.adoc
- guides/common/modules/ref_rendering-a-restorecon-template.adoc
$ rg "source, Ruby"
$ rg "source,Ruby"
$ rg "source,ruby"
unify the way we enforce syntax highlighting for Ruby.
I am currently working on automation around this; fewer variance helps a lot!
rendered docs should be identical.
> Unify macro for Ruby code blocks

- guides/common/modules/proc_exporting-report-templates-using-the-api.adoc
- guides/common/modules/proc_importing-report-templates-using-the-api.adoc
* Use one argument per line
removing the example password "redhat" due to branding issues and consistency.
consistency.
we have both "last argument | next command" and "last argument \ \n | next command". Any preference?
> Use generic example password

- guides/common/modules/proc_registering-a-host.adoc
I cross-checked the existing web UI procedure for registering a host with the page in the web UI and identified the parts of the documented procedure that can be dropped because they are actually documented in the web UI. Additionally, I'm making minor changes to the wording in order to make the procedure even shorter.
The current procedure is _very_ long (22 steps!). Making sure we don't duplicate the web UI elements (obvious input fields, tooltips, etc.) will go a long way towards making the procedure shorter.
I wanted to do this because in https://github.com/theforeman/foreman-documentation/pull/3329, I'm introducing information on how to perform the action from the CLI, using Ansible, or using API. Without trimming the web UI procedure, the new additions would be lost at the end of a …
> Reduce doc bloat in registering a host

- guides/common/modules/con_configuring-kerberos-single-sign-on-with-freeipa-in-project.adoc
I'm clarifying that in a setup with a cross-forest trust between FreeIPA and AD, different login methods are available to FreeIPA and AD users.
The current description might be interpreted in a way that suggests that either FreeIPA or AD users can use any of the listed login methods.
N/A
> Clarify that AD users in a cross-forest trust env with FreeIPA cannot login with Kerberos

- guides/common/assembly_registering-hosts.adoc
- guides/common/modules/proc_configuring-a-host-for-registration.adoc
- guides/common/modules/proc_registering-a-host.adoc
A host needs to be configured a certain way before it can be registered by using Global Registration and that isn't properly documented at the present time.
We have a _Configure a host for registration_ module, but we don't use it in the _Managing Hosts_ guide currently, which we should. Originally, it covered only the NTP synchronization.
Also, we should provide a prerequisite so that the user can make a secured curl call right away. The CA certificate config is now also included in the pre-registration configuration.
Because it's better to tell the user how the host must be configured for registration beforehand instead of explaining it when it's "too late".
Depends on #3193
> Configure host for global registration

- guides/common/modules/proc_adding-a-bonded-interface.adoc
Fixes #73
explanation for naming scheme
old GH issue
> Clarify naming scheme of bonded interfaces

- guides/common/modules/proc_testing-email-delivery.adoc
Adding a troubleshooting bullet point regarding test emails not being delivered.
https://issues.redhat.com/browse/SAT-27822
N/A
> Add troubleshooting test email delivery (postfix)

- guides/common/modules/ref_troubleshooting-project-by-using-hammer.adoc
Updating the example output of `hammer ping`.
As reported in https://issues.redhat.com/browse/SAT-28362, the output of hammer ping in the most recent versions differs significantly from what we currently document.
~~I'm requesting cherry-picks down to 3.9 only because I currently don't have any test environments for the earlier versions. Considering that we're only talking about example CLI output, I think these cherry picks are enough, but if anyone disagrees, I can check all the other supported versions too.~~
> Update output of hammer ping

- guides/common/modules/proc_importing-ostree-content.adoc
This adds depth OSTree property.
There was another property for the OSTree repositories added ([#37853](https://projects.theforeman.org/issues/37853)).
The current target is Katello 4.15, so it shouldn't need any backporting, if it surprisingly still gets into 4.14 I will make sure to mention it 👍🏻 
Thank you 🙂
> Add depth option for OSTree repositories

- guides/common/modules/con_api-overview.adoc
- guides/common/modules/con_browsing-hosts-in-foreman-webui.adoc
- guides/common/modules/proc_adding-a-microsoft-azure-connection.adoc
- guides/common/modules/proc_adding-errata-to-an-incremental-content-view.adoc
- guides/common/modules/proc_applying-remote-scap-resources-in-a-disconnected-environment.adoc
- guides/common/modules/proc_configuring-capsule-default-certificate.adoc
- guides/common/modules/proc_configuring-smart-proxy-for-host-registration-and-provisioning.adoc
- guides/common/modules/ref_oauth-request-format.adoc
- guides/common/modules/ref_overview-of-individual-loggers.adoc
Hide link to RH KB for non-Satellite builds
branding.
First commit unified the usage of admonitions.
> Unify admonition syntax & hide KB article for orcharhino

- guides/common/modules/con_configuring-project-with-external-idm-dns.adoc
- guides/common/modules/con_managing-dhcp-by-using-smartproxy.adoc
- guides/common/modules/con_managing-dns-by-using-smartproxy.adoc
- guides/common/modules/con_registering-hosts-and-setting-up-host-integration.adoc
- guides/common/modules/con_smartproxy-networking.adoc
- guides/common/modules/proc_configuring-capsule-default-certificate.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-smart-proxy-server.adoc
- guides/common/modules/proc_renaming-smart-proxy.adoc
- guides/common/modules/proc_resetting-custom-ssl-certificate-to-default-self-signed-certificate-on-smartproxy.adoc
- guides/common/modules/proc_reverting-to-internal-dns-service.adoc
- guides/common/modules/ref_port-and-firewall-requirements.adoc
- guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc
- guides/common/modules/snip_host-registration-steps.adoc
- guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc
Fixing several broken links found in Installing Proxy.
We received a list of broken links in https://issues.redhat.com/browse/SAT-27794. About half of these actually needed fixing, the other ~half was just references to guides for a future d/s release.
EDIT: Apart from just fixing the broken links, I also changed some of them into xrefs in cases when the target was in the same guide.
> Fix broken links in Installing Proxy

- guides/common/assembly_monitoring-hosts-by-using-red-hat-insights.adoc
- guides/common/modules/proc_adding-an-ansible-playbook.adoc
- guides/common/modules/proc_enabling-rh-cloud-and-insights-client-reports-on-hosts.adoc
- guides/common/modules/proc_excluding-hosts-from-rh-cloud-and-insights-client-reports.adoc
- guides/common/modules/ref_content-settings.adoc
add procedure to opt-in to uploading reports to RH cloud.
on orcharhino, users register hosts with RHEL and non-RHEL OS, but they should only set the parameter for RHEL OS.
> Opt in to RH insights

- guides/common/modules/con_how-puppet-integrates-with-project.adoc
- guides/common/modules/proc_configuring-repositories-deb.adoc
- guides/common/modules/proc_configuring-repositories-el.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-provisioning.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
- guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
Declare offical support for Puppet 8 to configure hosts.
Foreman 3.12 supports Puppet 8: [source: release notes](https://docs.theforeman.org/3.12/Release_Notes/index-katello.html#_puppet_8_support)
* Partially untested; instructions are based on steps for Puppet 7.
* Do we want to make a recommendation to use Puppet 8?
> Support puppet 8

- guides/common/assembly_configuring-active-directory-as-an-external-identity-provider-for-project.adoc
- guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
- guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc
I'm removing a reference to configuring Internet Explorer for Kerberos SSO. After that, the remaining content in the module can't really stand on its own so I'm merging it with another module.
Internet Explorer is being deprecated for years now. Its latest version is still officially supported, but in a very limited way with Microsoft Edge now being the recommended browser for Windows users.
Initially, I thought about replacing the entry about IE with a similar one about Edge. But then I thought that we probably don't need to (or even shouldn't) document third-party software unless absolutely necessary. Microsoft Edge users should use Microsoft docs for that.
> Drop Internet Explorer reference

- Dockerfile
Gem versions follow GHA in foreman-documentation for PR 3104 that introduces tabs which require "asciidoctor-tabs".
add "asciidoctor-tabs" to container image.
prerequisite to testing #3104 locally
I have tested removing "rubygem-asciidoctor" as RPM without success. even if it's not perfect, it works as is.
> Allow tabs for container-based builds

- guides/common/modules/con_registering-hosts-and-setting-up-host-integration.adoc
Adding a secondary ID to the assembly for registering hosts.
Another PR recently changed the ID which broke a UI link: https://github.com/theforeman/foreman-documentation/pull/3327#discussion_r1791397965
N/A
> Change ID to fix a broken UI link

- guides/common/modules/proc_adding-a-default-http-proxy.adoc
- guides/common/modules/proc_adding-an-http-proxy.adoc
- guides/common/modules/proc_configuring-http-proxy-to-connect-to-cdn.adoc
- guides/common/modules/proc_configuring-provisioning-callback-for-a-host.adoc
- guides/common/modules/proc_configuring-pxe-files-proxy.adoc
- guides/common/modules/proc_importing-an-ansible-playbook-by-name.adoc
- guides/common/modules/proc_passing-arguments-to-shellhook-script-using-curl.adoc
* Fix curl arguments: some were duplicate (both "-k" and "--insecure" which is the same)
* Somewhat unfiy the HTTP proxy example names and URLs; always say "http-proxy", not "proxy" to clearly differentiate betwen Smart Proxies and HTTP proxies.
Better readability
I have verified all curl arguments via man page.
> Fix curl arguments and HTTP proxy examples

- web/releases/3.12.json
- web/releases/nightly.json
Fixing capitalization in JSON navigation entries for the Configuring user authentication guide.
https://github.com/theforeman/foreman-documentation/pull/3301/files originally introduced the entries but I got the capitalization wrong so the guides don't actually show.
https://docs.theforeman.org/nightly/Configuring_user_authentication/index-katello.html currently gives Page not found
vs
https://docs.theforeman.org/nightly/Configuring_User_Authentication/index-katello.html actually displays the guide
N/A
> Fix capitalization in web navigation

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_installing-standalone-hammer.adoc
Adding a procedure to configure standalone Hammer on EL 9.
https://issues.redhat.com/browse/SAT-27900
I used https://github.com/theforeman/foreman-documentation/blob/master/guides/common/modules/proc_preparing-a-host-for-external-databases.adoc as a template for how to structure a procedure for EL8 /EL 9.
> Add steps to configure standalone Hammer on EL 9

- guides/common/modules/proc_disabling-registration-to-insights.adoc
Simplifying the module about disabling RH Insights.
The scenario for this procedure was unclear and contained also a step to enable Insights, which was confusing. I've attempted to clarify the use case and simplify the procedure.
https://issues.redhat.com/browse/SAT-27612
> Simplify disabling RH Insights

- guides/common/modules/proc_migrating-project-or-smartproxy-using-backup.adoc
In the Migrating using Backup and Restore section, it needs to be specifically pointed out that the target system should have the same config as the source. This is easy to miss in the linked docs and can cause the migration to fail. Hence mentioning it explicitly in the procedure module.
JIRA: https://issues.redhat.com/browse/SAT-27958
> Mention that target should have same config as source

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
The Subscription-manager release unset step is required for connected upgrades and not for disconnected. Fixing the conditional.
JIRA link:
https://issues.redhat.com/browse/SAT-28162
> Subscription-manager release unset for connected

- .github/workflows/vale.yml
Workaround for https://github.com/errata-ai/vale-action/issues/128
Does not need style review because it does not affect doc content.
> Pin Ubuntu to 22.04 in vale.yml to work around a bug

- guides/common/modules/proc_cloning_satellite_server.adoc
Removing entitlement-mode subscription steps from cloning, esp. pool attachment
https://issues.redhat.com/browse/SAT-27778
Not sure how far this needs to be cherry picked. cc @jeremylenz 
> Remove entitlement-mode subscription steps from cloning

- guides/common/modules/ref_cli-help.adoc
Show a link to Hammer CLi guide unconditionally:
* Hammer CLI guide is part of foreman-documentation since d7fbafe289fb37ef94fcd24062fde671fcd64614.
* In downstream orcharhino docs, the file path will be changed.
I am in the process of incorporating Hammer CLI guide in orcharhino downstream docs.
> Show link to Hammer CLI guide for all builds

- .github/workflows/vale.yml
Vale action no longer installs asciidoctor by default. See https://github.com/errata-ai/vale-action/issues/128#issuecomment-2405758847
> Update vale.yml to also install asciidoctor

- guides/common/modules/con_upgrading-prerequisites.adoc
As PostgreSQL is upgraded from 12 to 13 during the upgrade process, it is necessary to maintain enough space for this. Adding this as a prerequisite to the upgrade.
Ref: https://github.com/theforeman/foreman_maintain/blob/master/definitions/checks/disk/available_space_postgresql13.rb
JIRA: https://issues.redhat.com/browse/SAT-28667
> Add PostgreSQL space requirement in prerequisites

- guides/common/modules/proc_changing-the-environment-of-a-host.adoc
Content View details card changed to Content View 
environment card
while changing the environment of a host in Satellite 
6.16.
> Change details to environment

- guides/common/modules/proc_installing-standalone-hammer.adoc
- guides/doc-Hammer_CLI/master.adoc
Installing Hammer CLI on an EL 8 hosts that is not orcharhino Server or orcharhino Proxy Server does requires the ruby:2.7 DNF module and access to orcharhino content from orcharhino Server or orcharhino Proxy Servers.
working on Hammer CLI guide for orcharhino downstream.
Tested downstream.
> Install Hammer CLI on separate hosts (orcharhino only)

- guides/image-sources/foreman.pstyle
- guides/image-sources/prov-create-host-pxe.iuml
- guides/image-sources/prov-first-local-boot-pxe.iuml
- guides/image-sources/prov-initial-configuration.iuml
- guides/image-sources/prov-installation-media.iuml
- guides/image-sources/provisioning-installer-pxeboot.plantuml
- guides/image-sources/puppet-run.iuml
Adding a sequence diagram of installer-based provisioning with PXE boot. Using PlantUML to build the diagram.
Preparation for improvements of _Provisioning hosts_. The diagram will be used later to explain the workflow of the provisioning method.
* Some files (.iuml, .pstyle) are expected to be reused in mutiple diagrams.
* Continuation of https://github.com/theforeman/foreman-documentation/pull/3069
> Add diagram of installer-based provisioning with PXE boot

- guides/common/modules/con_postgresql-as-an-external-database-considerations.adoc
- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
- guides/common/modules/proc_upgrading-the-external-database.adoc
The external database should be upgraded from PostgreSQL 12 to 13. Mentioning this in the ext DB upgrade chapter.
JIRA: https://issues.redhat.com/browse/SAT-28273
> Mention that the external database should be upgraded

- guides/common/modules/proc_importing-a-content-view-version.adoc
- guides/common/modules/proc_importing-a-repository.adoc
- guides/common/modules/proc_importing-into-the-library-environment.adoc
- guides/common/modules/snip_extract-directory-imported-project-server.adoc
- guides/common/modules/snip_note-imported-project-server.adoc
A new note was needed for 3 sections to tell the user 
that they can
clear the imports directory. A snippet was created.
> Add new note snippet

- guides/common/modules/con_registering-hosts-by-using-global-registration.adoc
- guides/common/modules/proc_registering-a-host.adoc
- guides/common/modules/ref_registration-methods.adoc
Documents https://github.com/theforeman/foreman/pull/9808
As documentation for https://github.com/theforeman/foreman/pull/9808 was prematurely merged in https://github.com/theforeman/foreman-documentation/pull/2376 and reverted in https://github.com/theforeman/foreman-documentation/pull/2793, @Lennonka kindly created https://github.com/theforeman/foreman-documentation/pull/2914 to re-add documentation for https://github.com/theforeman/foreman/pull/9808 once it is merged. Additionally I created https://github.com/theforeman/foreman-documentation/pull/3163 as follow-up PR to https://github.com/theforeman/foreman-documentation/pull/2914.
Due to heavy rewriting of the module, we decided to close https://github.com/theforeman/foreman-documentation/pull/2914 as well as …
> Refs #36688 - Option to use wget for host registration

- guides/common/modules/proc_enabling-the-templatesync-plugin.adoc
- guides/common/modules/proc_exporting-templates.adoc
- guides/common/modules/proc_importing-templates.adoc
I'm replacing an xref to a Template Sync reference module in Managing Hosts with an external link to a Template Sync reference module in Administering Project. The module the xref points to was removed in https://github.com/theforeman/foreman-documentation/pull/3397.
https://github.com/theforeman/foreman-documentation/pull/3397 broke things on 3.11, 3.10, and 3.9 because the affected assembly exists in a different guide there so the xref that works on 3.12 and later doesn't work on 3.11 and earlier.
An alternative is to revert https://github.com/theforeman/foreman-documentation/pull/3397 on the broken branches.
> Replace xref with link for template sync reference

- guides/common/modules/proc_calling-the-api-in-python.adoc
Replacing `&` with `&amp;`
Trying to fix broken XML build in Pantheon
* [ x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.
> Replacing '&' with '&amp;'

- Gemfile
- guides/common/Makefile
- guides/common/assembly_configuring-repositories.adoc
- guides/common/assembly_installing-capsule-server.adoc
- guides/common/assembly_installing-server-connected.adoc
- guides/common/assembly_preparing-smartproxyservers-for-load-balancing.adoc
- guides/common/modules/con_configuring-repositories.adoc
- guides/common/modules/con_projectserver-operating-system.adoc
- guides/common/modules/proc_configuring-repositories-foreman-deb.adoc
- guides/common/modules/proc_configuring-repositories-foreman-el.adoc
- guides/common/modules/proc_configuring-repositories-katello.adoc
- guides/common/modules/proc_configuring-repositories-orcharhino.adoc
- guides/common/modules/proc_configuring-repositories-satellite.adoc
- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/common/modules/ref_supported-operating-systems.adoc
- guides/doc-Quickstart/master.adoc
- guides/doc-Release_Notes/topics/foreman.adoc
With Foreman 3.11.4 we can consider Debian 12 supported. This cherry picks the patches from master and adds a release note. Because in master it's written for asciidoctor-tabs, those commits are included here.
I intend to submit a similar PR for the 3.12 branch.
> Debian 12 support for Foreman 3.11 & repository config in tabs

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
Users would like to review the Leapp known issues before beginning the upgrade from EL 8 to 9. Adding a link to the same.
JIRA: https://issues.redhat.com/browse/SAT-17113
> Add link to Leapp known issues

- guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
Moving an existing prerequisite from the list of prerequisites to the step where the information is relevant. (It's not really a prerequisite anyway.)
https://issues.redhat.com/browse/SAT-27001 notes that in its original place, the information can be easily overlooked.
> Make a disconnected upgrade requirement harder to overlook

- guides/common/modules/con_upgrade-paths.adoc
- guides/common/modules/con_upgrading-overview.adoc
- guides/common/modules/con_upgrading-prerequisites.adoc
- guides/common/modules/con_upgrading-project.adoc
- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
- guides/common/modules/proc_upgrading-smartproxy-server.adoc
- guides/common/modules/snip_prerequisites-upgrading-project-server.adoc
- guides/doc-Upgrading_Project/master.adoc
- guides/doc-Upgrading_Project_Disconnected/master.adoc
* Adding a high-level summary of the upgrade process loosely based on [Upgrade paths](https://docs.theforeman.org/3.3/Upgrading_and_Updating/index-katello.html#upgrade_paths) in version 3.3. ~~("Loosely" because rather than re-create the original list of steps, I rather propose to add a very general summary in its place and include the other, more detailed steps as part of the assembly that actually describes upgrading.)~~
* Removing the introduction for the upgrade assembly (`guides/common/modules/con_upgrading-project.adoc`) because it's out-of-date.
* Enhancing the upgrade procedures with a few bits of information based on the old Upgrade paths section and the removed assembly introduction, to make sure we still keep the important parts.
https://issues.redhat.com/browse/SAT-29113 …
> Document high-level steps for upgrading

- guides/common/modules/proc_adding-an-amazon-ec2-connection-to-server.adoc
- guides/common/modules/proc_configuring-a-host-for-registration.adoc
I'm removing (external) links to a chronyd section in the installation guide.
The section doesn't exist anymore, it was removed in https://github.com/theforeman/foreman-documentation/pull/3345 and https://github.com/theforeman/foreman-documentation/pull/3413.
The reference in Managing Hosts doesn't exist on 3.8 and below. The one in Provisioning Hosts is in all branches.
> Remove links to a chronyd section in Installing

- guides/common/modules/con_upgrade-paths.adoc
minor formatting and style chnage
Follow-up to https://github.com/theforeman/foreman-documentation/pull/3408
-
see https://github.com/theforeman/foreman-documentation/pull/3408#issuecomment-2454449870
> Formatting: One sentence per line

- guides/common/modules/proc_cloning_satellite_server.adoc
- guides/common/modules/proc_configuring-keycloak-settings-for-authentication-with-cac-cards.adoc
- guides/common/modules/proc_creating-a-content-view-filter-for-errata.adoc
- guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
- guides/common/modules/proc_restoring-from-a-full-backup.adoc
- guides/common/modules/proc_restoring-from-incremental-backups.adoc
- guides/common/modules/proc_synchronizing-smart-proxy-directly-from-red-hat-cdn.adoc
- guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
- guides/common/modules/ref_template-macros.adoc
- guides/common/modules/snip_prerequisites-upgrading-project-server.adoc
- guides/doc-Deploying_Project_on_AWS/topics/AWS_Use_Case_Considerations.adoc
* Replace ’ with '
* Fix attribute usage
* Reword thing's attribute to attribute of thing
Found issues in downstream doc builds.
I believe I found this due to a combination of locales and aspell. Example that I found in downstream docs: "XING’s privacy" vs "XING's privacy" with "XING" as spelling exception. Note that this is just a theory though.
> Use single quote as apostrophe

- guides/common/attributes-base.adoc
- guides/common/modules/con_introduction-to-salt.adoc
- guides/common/modules/con_salt-architecture.adoc
- guides/common/modules/proc_providing-the-salt-client-to-salt-minions.adoc
- guides/doc-Managing_Configurations_Salt/master.adoc
Replacing links to repo.saltproject.io with up-to-date links and dropping parts of the obsolete Salt content.
The old URL for Salt package repositories is no longer available, which breaks quite a few things on our side. More details in https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/.
@maximiliankolb was kind enough to provide a patch to take my PR further than just updating the broken links.
~~I'm not sure at all whether the new links are the right ones, all I can verify is that they work. Whether they actually take users where they need to go is a different matter.~~
> Salt repo update

- guides/common/modules/proc_adding-vmware-details-to-a-compute-profile.adoc
- guides/common/modules/proc_adding-vmware-images-to-server.adoc
Properly capitalizing "VMware" instead of "Vmware" where possible.
VMware is the proper capitalization of the compute resource.
There are also 2 occurences in [this CLI procedure](https://docs.theforeman.org/nightly/Provisioning_Hosts/index-katello.html#cli-adding-vmware-vsphere-connection_vmware-provisioning). However, since it is a literal value for the `--provider` argument, I hesitate to change the capitalization because it may go unrecognized. Value verified with the Hammer reference that also capitalizes it as "Vmware". I think we should keep it consistent with Hammer help/reference.
Please cherry-pick my commits into: **As far as without conflicts.**
> Fix VMware capitalization

- guides/common/modules/con_kickstart-workflow.adoc
- guides/common/modules/proc_creating-a-host.adoc
- guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
- guides/common/modules/proc_editing-the-system-purpose-of-multiple-hosts.adoc
- guides/common/modules/ref_kinds-of-provisioning-templates.adoc
- guides/common/modules/ref_storage-requirements.adoc
Fixing broken links to RHEL docs found by linkchecker.
> Update links to RHEL docs

- guides/common/assembly_synchronizing-template-repositories.adoc
- guides/common/modules/con_importing-and-exporting-templates.adoc
- guides/common/modules/con_synchronizing-template-repositories.adoc
- guides/common/modules/con_using-repository-sources.adoc
- guides/common/modules/proc_exporting-templates.adoc
- guides/common/modules/proc_importing-templates.adoc
- guides/common/modules/proc_synchronizing-templates-with-a-local-directory.adoc
- guides/common/modules/proc_synchronizing-templates-with-an-existing-repository.adoc
I propose to drop some of the existing introductions and extend the others with a few more details. Additionally, I noticed that one of the introductions did not include Ansible as one of the tools to import templates so I added a reference to it.
Currently, the template sync assembly uses two "container" assemblies (one for configuring repos, the other for import/export procedures). But I think these just add complexity to the structure without offering a clear benefit. Removing them will certainly make things easier for us to maintain (fewer files, fewer includes).
At the same time, consolidating the explanatory information in the remaining introductions ensures that each of the introductions has something meaningful to say.
* We do not accept PRs for …
> Review introductions to template sync procedures

- guides/common/modules/snip_steps-needs-reboot.adoc
> hide "dnf needs-restarting" on Satellite, foreman-maintain does hint

- guides/common/modules/proc_registering-a-host.adoc
Fixing capitalization.
https://github.com/theforeman/foreman-documentation/pull/3428#discussion_r1832107472
N/A
> Fix capitalization of "Ansible module"

- guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
Adding a link to a KCS article.
Entitlement-based subscription management has been removed. 
You must use Simple Content Access (SCA), which simplifies the entitlement 
experience for administrators. 
https://access.redhat.com/subscription_mgmt_guide_for_RHEL
> Add link to Admin Guide for SCA

- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Managing_Content/master.adoc
It was determined that Appendix B for Importing 
Kickstart Repositories
was not necessary for the Content Management Guide so 
it was removed. 
> Remove Appendix B from the Content Management guide

- guides/common/modules/proc_registering-a-host.adoc
If you register a host that requires content from Foreman+Katello and you have that content already synchronized to your Foreman+Katello instance and that content is published unprotected, then you can use the Katello API to get the associated GPG public key for Yum repositories and the Pulp Deb Signing Key for Deb content.
Examples:
* Your host runs Debian 12 and needs "subscription-manager" from oss.atix.de and additional Deb repositories to satisfy all dependencies of "subscription-manager" and "katello-host-tools".
* Your host runs AlmaLinux 9 but has no internet access and no mounted ISO image. You will have to provide BaseOS, AppStream, and the Foreman Client repository through your Smart Proxy to enable offline host registration.
With GPG public keys, package managers can verify …
> Use Katello API for GPG pub keys of custom content

- web/content/css/_asciidoc.scss
Fixing problem with misplaced headings when clicking an item in the TOC
UX improvement for Foreman Docs.
Previously, when you clicked an item in the table of contents, the browser scrolled to the top of the page and the actual heading was hidden behind the navigation bar.
With this fix, the heading is visible.
> Fix hidden headings behind navigation bar [upstream only]

- guides/common/modules/proc_registering-a-host.adoc
- guides/common/modules/snip_prerequisites-content-for-sles.adoc
Add table to help users with registering SLES hosts to Foreman+Katello
current table in downstream only contains the repositories but not the way to get there content > products > _a product_ > _a repository_.
table is already part of orcharhino downstream docs; it's only added the products that contain the required repositories
* https://docs.orcharhino.com/or/docs/sources/guides/suse_linux_enterprise_server/managing_hosts/registering_hosts.html#Registering_Hosts_Using_the_Bootstrap_Script
* https://www.suse.com/lifecycle#suse-linux-enterprise-server-15
no diff is to be expected because the snippet is only included for SLES. If you have an idea on how to provide this to upstream Katello users, please let me know.
* We do not accept PRs for Foreman …
> Add list of required SUSE content for host registration

- guides/common/modules/proc_configuring-smart-proxy-server-with-custom-ssl-certificates-to-generate-and-sign-puppet-certificates.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-default-ssl-certificates-to-generate-and-sign-puppet-certificates.adoc
Fixing a command to generate certs on Puppet CA SmartProxy
It was reported as incorrect and suggested another command instead.
https://issues.redhat.com/browse/SAT-28859
- I have verified that the command exists on a Puppet server (Satellite 6.16/Puppet server 8).
- I have tried to run the command. 
- First, I had to stop Puppet server before it would run.
- Then got a report of different set of files already existing on my instance. So I used this output to update the list of files that is in the docs.
- The bug was reported for Satellite 6.15, so I assume that the command is also relevant for Puppet server 7, ie. for all maintained relases.
- The suggested command is actually used in [the other procedure with default certs](https://theforeman-foreman-documentation-preview-pr-3398.surge.s …
> Fix command to generate Puppetserver CA certs for load balancer

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/katello-4.15.0.adoc
- guides/doc-Release_Notes/topics/katello.adoc
Adding release docs for Katello 4.15 so we can get RC1 out.
> Katello 4.15 release docs

- guides/common/assembly_managing-content-views.adoc
- guides/common/modules/proc_synchronizing-a-content-view-to-a-smartproxy.adoc
A CLI procedure for synchronizing a content view has been added to the
Content Management Guide related to
https://issues.redhat.com/browse/SAT-13027.
> Add CLI procedure for syncing content view

- guides/doc-Release_Notes/topics/foreman.adoc
Fixing asciidoc syntaxa.
The [URL macro](https://docs.asciidoctor.org/asciidoc/latest/macros/url-macro/) was used incorrectly as `label[url]` instead of `url[label]`.
> Fix the asciidoc URL syntax in Foreman's headline features

- guides/common/assembly_introduction-to-provisioning.adoc
- guides/common/modules/ref_supported-clients-in-registration.adoc
- guides/common/modules/ref_supported-host-platforms-in-provisioning.adoc
- guides/common/modules/snip_supported-client-architectures.adoc
Adding listing of operating systems and architectures that are supported for host provisioning.
Previously undocumented.
- I'm making an assumption that Foreman supports the same things in provisioning as in global registration.
- Architectures for RHEL verified with: [RHEL 9 Requirements](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/interactively_installing_rhel_from_installation_media/system-requirements-and-supported-architectures_rhel-installer#system-requirements-and-supported-architectures_rhel-installer), [RHEL 8 Requirements](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/interactively_installing_rhel_from_installation_media/system-requirements-and-supported-architectures_rhel-installer#system-requirements-and-supported-architec …
> Add supported platforms in provisioning

- guides/common/modules/proc_registering-a-host.adoc
Fixing permissions required to register a host
The `create_hosts` permission is insufficient. The user must have the role *Register hosts* or equivalent.
Requested in https://issues.redhat.com/browse/SAT-29409
- The *Register hosts* role lists 19 permissions and it's a default role provided by Foreman. Instead of listing all permissions, I'm just mentioning the role or its equivalent. I believe that a user admin would be able figure out the rest based on this info.
> Fix permissions required to register a host

- guides/common/modules/proc_exporting-a-content-view-version-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-a-content-view-version-incrementally.adoc
- guides/common/modules/proc_exporting-a-content-view-version.adoc
- guides/common/modules/proc_exporting-a-repository-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-a-repository-incrementally-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-a-repository-incrementally.adoc
- guides/common/modules/proc_exporting-a-repository.adoc
- guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
- guides/common/modules/proc_exporting-the-library-environment-incrementally.adoc
- guides/common/modules/proc_exporting-the-library-environment.adoc
- guides/common/modules/snip_content-types-export.adoc
- guides/common/modules/snip_content-types-syncable-export.adoc
- guides/common/modules/snip_generating-content.adoc
- guides/common/modules/snip_syncable-exports.adoc
You can export all supported content types in "importable" format which is the default. You cannot export Ansible, Deb, or Docker content in "syncable" format.
* Add snippet for supported content to export content
* Add snippet for supported content to export content in syncable format
* Hide Deb content for Satellite
* List content types in alphabetical order
* Support exporting Deb content
It was not clear that Foreman+Katello supports exporting/importing Deb content but not Deb content in syncable format.
**alternative implementation idea**: add a small concept file that lists supported content types for export in importable format and exports in syncable formats. That would have the benefit of us not including the snippets a dozen times. Downside: users would have to read more than …
> Clarify support content types for exports

- guides/common/modules/proc_creating-a-custom-file-type-repository.adoc
Refs Redmine issue 37929
Refs katello PR 11184 on GitHub
docs for "Download Policy" list
it was added to katello recently: https://github.com/Katello/katello/pull/11184
wording is identical to custom rpm/deb repositories
no cherry-picks
> Document download policy for file-type content

- guides/common/assembly_using-pxe-to-provision-hosts.adoc
- guides/common/modules/con_using-pxe-to-provision-hosts.adoc
- guides/common/modules/proc_configuring-smart-proxy-to-provision-secure-boot-enabled-hosts.adoc
This adds a section about new SecureBoot support. It only works in combination with the following patchset:
https://github.com/theforeman/foreman/pull/9864
https://github.com/theforeman/smart-proxy/pull/877
RFC: https://community.theforeman.org/t/add-secureboot-support-for-arbitrary-distributions/32601/1
> Add SecureBoot support for arbitrary operating systems to "Grub2 UEFI" PXE loaders

- .github/PULL_REQUEST_TEMPLATE.md
Retiring branches older than 3.7
Because [Satellite 6.13 becomes EOL on November 30, 2024](https://access.redhat.com/support/policy/updates/satellite/)
@maximiliankolb orcharhino okay with that?
> Retire branches older than 3.7

- guides/common/modules/con_api-overview.adoc
- guides/common/modules/con_hammer-cli-overview.adoc
I'm removing conditionals that include links to Hammer and API guides for Satellite only.
The ifdefs are there because previously, these guides were available for Satellite only. That changed with https://github.com/theforeman/foreman-documentation/pull/3212 and https://github.com/theforeman/foreman-documentation/pull/3212.
There might be more links like this in the docs set but I came across these two and thought I'd fix them right away rather than wait till I have time to search for others.
No further because the modules don't exist on lower branches.
> Include Hammer and API guides for all builds

- guides/common/modules/con_api-overview.adoc
- guides/common/modules/con_hammer-cli-overview.adoc
This reverts https://github.com/theforeman/foreman-documentation/pull/3455, to be included in branches 3.11, 3.10, and 3.9.
When cherry-picking https://github.com/theforeman/foreman-documentation/pull/3455, I didn't realize that the Hammer and API guides are not available for all builds on these branches.
Sorry!
> Revert "Include links to Hammer and API guides for all builds (#3455)"

- guides/common/assembly_managing-errata.adoc
- guides/common/modules/proc_creating-an-incremental-content-view-version-by-adding-deb-packages.adoc
Add Hammer CLI instructions on how to add packages to a CV version.
Refs https://community.theforeman.org/t/incremental-update-not-working/38811/6?u=maximilian
-
> Create incremental CVs by adding Deb packages

- guides/common/modules/con_content-flow-in-project.adoc
- guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc
Add two missing content types
https://github.com/theforeman/foreman-documentation/issues/2775
> Add missing supported content types to Planning guide

- guides/common/assembly_importing-content.adoc
- guides/common/modules/con_structured-apt-content.adoc
- guides/common/modules/proc_enabling-structured-apt-content.adoc
docs for Foreman+Katello to provide structured APT content
docs for https://github.com/Katello/katello/pull/11058
the PR is based on a KB article in ATIX Service Portal.
> Document structured APT content

- hammer_cli_reference/README.adoc
- hammer_cli_reference/inventory.yaml
- hammer_cli_reference/playbook.yaml
docs on how to create/update/review Hammer CLI reference files for katello.
as a preparation to another PR to add a Hammer CLI reference for latest greatest Katello.
The first and only goal is to create a reproducer for Hammer CLI reference files for Foreman+Katello "develop" with all possible Hammer CLI plugins.
> Add reproducer for Hammer CLI reference

- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc
Removing a step from the procedure to deploy a custom SSL certificate to the server.
The installer has [a hook](https://github.com/theforeman/foreman-installer/blob/develop/hooks/pre_commit/20-certs_update.rb) that runs katello-certs-check itself, so the step is not needed anymore. This was pointed out in https://github.com/theforeman/foreman-documentation/pull/3484#discussion_r1867617788
N/A
> Simplify deploying a custom ssl cert on server

- guides/common/modules/proc_resetting-custom-ssl-certificate-to-default-self-signed-certificate-on-project.adoc
- guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
Removing one reference to `scenarios.d/` and clarifying two others in a way that (hopefully) ensures that users will not update its contents.
EDIT: One of the references to `scenarios.d/` was resolved separately in https://github.com/theforeman/foreman-documentation/pull/3486.
https://github.com/theforeman/foreman-documentation/issues/190
I couldn't find a way to completely avoid mentioning scenarios.d/ in all of the existing occurrences.
> Avoid or clarify /etc/foreman-installer/scenarios.d references

- guides/common/modules/proc_configuring-tls-for-secure-ldap.adoc
I'm updating the procedure to configure TLS for LDAP authentication:
* Restarting httpd is not needed
* We can also simplify the instructions for uploading the LDAP certificate
I noticed https://issues.redhat.com/browse/SAT-19821 and https://github.com/theforeman/foreman-documentation/pull/2409/ and thought "why not?"
A separate PR will probably be needed for some of the older branches due to conflicts but https://github.com/theforeman/foreman-documentation/pull/2409/ suggests that we should get the fixes there too.
> Update procedure to configure TLS for LDAP

- guides/common/modules/con_using-ldap.adoc
- guides/common/modules/proc_configuring-tls-for-secure-ldap.adoc
I'm updating the procedure to configure TLS for LDAP external authentication on branches 3.10 and lower to (more or less) match the equivalent procedure on newer branches.
https://github.com/theforeman/foreman-documentation/pull/3499 couldn't be cherry-picked but contains important updates.
https://github.com/theforeman/foreman-documentation/pull/3499 also added a link to RHEL docs for details on adding certs to the system-wide truststore. I'm not adding the link in this PR because for 3.10, I would need to add links to RHEL8 and RHEL9 and for 3.9 and earlier RHEL8 only. I think the section will work fine without the link.
> Update TLS LDAP procedure

- guides/common/modules/proc_adding-a-vmware-connection-to-server.adoc
- guides/common/modules/proc_adding-rhv-connection.adoc
fix spelling and order
to make vale happy
found while working on https://github.com/theforeman/foreman-documentation/pull/3469/files
> Fix spelling of data center

- guides/common/modules/snip_host-names-for-http-proxy.adoc
Removing *.akamaiedge.net from the list of hosts that Foreman must be able to access to reach Red Hat CDN.
While cdn.redhat.com is hosted by Akamai, *.akamaiedge.net itself doesn't need to be listed as a prerequisite. Because the domain doesn't belong to Red Hat, it can confuse some users, which is why it seems better to remove it. The relationship between CDN and Akamai is explained in the RH KBase article linked elsewhere in the section.
> Drop *.akamaiedge.net from list of CDN prereqs

- guides/common/assembly_using-kernelcare.adoc
- guides/common/modules/proc_creating-kernelcare-repositories-el.adoc
- guides/common/modules/proc_live-patching-hosts-using-kernelcare.adoc
Drop "os_major" as attribute in `guides/common/assembly_using-kernelcare.adoc` and any included files
This simplifies overwriting the attribute in downstream docs because we build the guide for each host OS: [example 1](https://docs.orcharhino.com/or/docs/sources/guides/red_hat_enterprise_linux/managing_hosts/kernelcare.html#Creating_KernelCare_Repositories_for_Red%20Hat%20Enterprise%20Linux_7_managing-hosts) and [example 2](https://docs.orcharhino.com/or/docs/sources/guides/almalinux/managing_hosts/kernelcare.html#Creating_KernelCare_Repositories_for_AlmaLinux_9_managing-hosts).
I also dropped the limitation to EL 7-9 because we do not document any other OS name + OS version anyway.
> Use common Client OS attributes for KernelCare

- guides/common/modules/con_importing-the-project-client-name-repository.adoc
- guides/common/modules/con_project-api-compared-to-hammer-cli.adoc
- guides/common/modules/proc_logging-in-to-hammer-cli-with-freeipa-credentials.adoc
- guides/common/modules/proc_synchronizing-the-project-client-name-repository.adoc
- guides/common/modules/ref_preparing-smartproxyservers-for-load-balancing-additional-resources.adoc
$ rg -i "DocURL" | rg "link"
remove `link:` macro from links that use `{xDocURL}` attributes
the combination of that macro and the attributes breaks things in downstream for me.
changes are cherry-picked from a downstream-only stable branch -> no tech review/ACK by anyone from ATIX necessary
> Remove link macro from DocURL attributes

- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
- guides/common/modules/proc_setting-an-alternative-directory-for-remote-execution-jobs-in-pull-mode.adoc
Updating documentation on configuring Rex in pull mode, introducing substeps based on which version of yggdrasil is available on the host.
https://github.com/theforeman/foreman-packaging/pull/11317
~~Draft because I still need to cover:~~
~~* https://github.com/theforeman/foreman-packaging/pull/11317#discussion_r1822445063~~
~~* Add a new prerequisite to enable Appstream to the procedure for registering hosts/rex pull client.~~
> Introduce substeps for rex pull mode based on yggdrasil version

- guides/common/modules/con_prerequisites-for-vmware-provisioning.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
- guides/common/modules/proc_configuring-dynamic-dns-update-with-tsig-authentication.adoc
- guides/common/modules/proc_reverting-to-internal-dns-service.adoc
hide links for orcharhino builds
due to weird downstream issues
changes are cherry-picked from a downstream-only stable branch -> no tech review/ACK by anyone from ATIX necessary
> Hide several links for orcharhino builds

- guides/common/assembly_deployment-path.adoc
- guides/common/assembly_using-external-databases.adoc
- guides/common/modules/con_adding-a-red-hat-subscription-to-project.adoc
- guides/common/modules/con_configuring-project-server-with-external-database.adoc
- guides/common/modules/con_defining-your-content-library.adoc
- guides/common/modules/con_using-external-databases.adoc
minor follow-up changes to https://github.com/theforeman/foreman-documentation/pull/3456
because.
please review commit by commit.
no cherry-picks.
> Follow-up PR to "deployment paths PR"

- guides/common/attributes-base.adoc
- guides/common/modules/proc_providing-the-salt-client-to-salt-minions.adoc
- guides/doc-Managing_Configurations_Salt/master.adoc
This reverts commit ba67ea7de5d2556e7486894631b9b80ed4d307dc.
* Updated the upstream URL for Salt Minions
* For Katello, also show URL for Salt Minions on Debian/Ubuntu
* Resolved minor merge conflicts in
* guides/common/modules/con_introduction-to-salt.adoc
* guides/common/modules/con_salt-architecture.adoc
the upstream repos for Salt Minions are working again:
* https://packages.broadcom.com/artifactory/saltproject-deb with "stable" and "main"
* https://packages.broadcom.com/artifactory/saltproject-rpm
"simple" revert
cherry-pick to 3.13 if possible
> Revert "Consume Salt Minion from upstream (#3411)"

- guides/common/modules/proc_using-container-registries.adoc
New prerequisite in a procedure.
Not clearly explained that a product must exist to push a repository.
> Add prerequisite for product existing

- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
Satellite Utils repo incorrectly refers to RHEL 8 where 
it should
mention RHEL 9. A new attribute was created for 
Satellite Utils for
RHEL 9. See https://issues.redhat.com/browse/SAT-26200
> Use RHEL 9 when creating a remote source for custom file type

- guides/common/modules/snip_tip-file-repositories-by-atix.adoc
orcharhino provides several file-type repositories to deploy hosts in disconnected environments.
source: ATIX Service Portal
Previously, this was a downstream-only commit.
> Update list of Client OS for file-type content

- guides/common/modules/con_projectserver-operating-system.adoc
- guides/common/modules/proc_configuring-repositories-foreman-deb.adoc
- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/common/modules/ref_supported-operating-systems.adoc
- guides/doc-Release_Notes/topics/foreman.adoc
Foreman nightly has dropped Debian 11 packages and this reflects it in the documentation.
https://community.theforeman.org/t/drop-debian-11-ruby-2-7-and-nodejs-14-support-in-foreman-3-14/40503
> Drop support for running on Debian 11

- guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
I'm adding a plus sign to fix a broken ordered list in versions 3.8 and earlier.
https://issues.redhat.com/browse/SAT-30254 reports an incorrectly displayed attribute:
N/A
> Add a missing plus sign to ensure list continuation

- guides/common/modules/con_converting-a-host-to-rhel.adoc
Removing manual steps from convert2rhel prerequisites
The Ansible role takes care of those steps.
Bug [SAT-30149](https://issues.redhat.com/browse/SAT-30149) (public)
> Remove manual steps from prerequisites - convert2rhel

- guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
- guides/common/modules/con_ssl-authentication-overview.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-smart-proxy-server.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-server.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
~~Replacing `{context}` with hard-coded `satellite` in a cross-guide link.~~
Dropping `{context}` from a section ID. The section is not reused so `{context}` is actually not needed. And it doesn't really work in cross-guide links anyway.
The link in [Renewing a SSL certificate on Foreman server](https://docs.theforeman.org/nightly/Administering_Project/index-katello.html#Renewing_a_Custom_SSL_Certificate_on_foreman_admin) doesn't take users to the target section in the installation guide. This is because the link contains the `{context}` variable which gets translated to `admin` instead of `katello`/`orcharhino`/`satellite`.
https://issues.redhat.com/browse/SAT-30253
> Fix a broken link

- guides/common/modules/proc_troubleshooting-remote-jobs-timing-out-after-yggdrasil-update.adoc
- guides/doc-Managing_Hosts/master.adoc
Users can now end up with different versions of yggdrasil on their host. This PR adds steps to troubleshoot potential issues and remedy them.
This was originally included in https://github.com/theforeman/foreman-documentation/pull/3492 but we should cherry-pick the troubleshooting part to earlier versions, hence a separate PR.
More packages should get names as epic as [yggdrasil](https://en.wikipedia.org/wiki/Yggdrasil).
> Add troubleshooting rex timeout due to yggdrasil version

- guides/common/modules/proc_troubleshooting-remote-jobs-timing-out-after-yggdrasil-update.adoc
- guides/doc-Managing_Hosts/master.adoc
See https://github.com/theforeman/foreman-documentation/pull/3516
See https://github.com/theforeman/foreman-documentation/pull/3516 
I opened https://github.com/theforeman/foreman-documentation/pull/3516 for nightly, 3.13, and 3.12: the migration package will get included upstream there.
For 3.11 and below, this will be applicable only to Satellite where the client repo is unversioned.
> Add troubleshooting rex timeout due to yggdrasil version (3.11 and earlier)

- guides/common/modules/proc_configuring-tls-for-secure-ldap.adoc
* Hide link to RHEL docs for Foreman on Deb
* Note that Debian/Ubuntu only accept ".crt" as file extension
fixes [3500](https://github.com/theforeman/foreman-documentation/issues/3500)
> Set SSL certificate paths based on platform OS

- guides/common/assembly_importing-content.adoc
- guides/common/modules/con_converting-a-host-to-rhel.adoc
- guides/common/modules/proc_adding-custom-rpm-repositories-el.adoc
- guides/common/modules/ref_best-practices-for-patching-content-hosts.adoc
Fixes for https://github.com/theforeman/foreman-documentation/issues/3475
> Fix "content management issues"

- guides/common/modules/proc_installing-the-discovery-service.adoc
Updating the operating system versions on which the Discovery images are based.
The newest FDI is now based on EL 9.
[SAT-27541](https://issues.redhat.com/browse/SAT-27541) (private)
> Update Discovery image base

- .github/PULL_REQUEST_TEMPLATE.md
Add EL major version to GitHub PR template
for convenience
source: https://docs.theforeman.org/3.13/Installing_Server/index-katello.html
no cherry-picks necessary
> Show supported EL major version in PR template

- guides/common/modules/con_requirements-for-installation-in-an-ipv6-network.adoc
Updating the requirement for the IPv6 DHCP server
Satellite 6.17 has to comply with US Gov. requirement for IPv6 support
IPv6 is not limited to GRUB2 anymore and will use a different DHCP provider in future. Therefore, dropping mentions of those specifics from the wording.
Related to #3532
> Update DHCPv6 server requirement

- guides/common/assembly_preparing-environment-for-installation.adoc
- guides/common/modules/proc_requirements-for-installation-in-an-ipv4-network.adoc
Adding details on requirements for installation in an IPv4 network.
https://issues.redhat.com/browse/SAT-29764 requests adding this.
I started working on this in https://github.com/theforeman/foreman-documentation/pull/3545 but actually want to get it merged in a separate PRs due to different cherry-pick requirements.
N/A
> Add IPv4 installation requirements

- guides/common/assembly_administer-settings-information.adoc
- guides/common/assembly_backing-up-server-and-proxy.adoc
- guides/common/assembly_restoring-server-or-smart-proxy-from-a-backup.adoc
- guides/common/modules/con_backup-and-restore-smartproxyserver-by-using-a-virtual-machine-snapshot.adoc
- guides/common/modules/con_maintaining-server.adoc
- guides/common/modules/proc_estimating-the-size-of-a-backup.adoc
- guides/common/modules/proc_managing-tasks.adoc
- guides/common/modules/proc_monitoring-services.adoc
- guides/common/modules/proc_performing-a-full-backup.adoc
- guides/common/modules/proc_performing-an-incremental-backup.adoc
- guides/common/modules/proc_performing-an-online-backup.adoc
- guides/common/modules/proc_viewing-general-smart-proxy-information.adoc
- guides/common/modules/ref_authentication-settings.adoc
- guides/common/modules/ref_email-notification-types.adoc
- guides/common/modules/ref_webhooks-available-events.adoc
- guides/doc-Administering_Project/master.adoc
* Estimate disk usage for backups is Katello-only
* Backups without Pulp are Katello-only
* Hide Pulp database for Foreman because it's Katello-only
* Do not sync content to Smart Proxy Servers for Foreman Content on Smart Proxy Servers is Katello-only.
* Hide Katello-specific events for Foreman
* Hide Pulp for non-Katello
* Hide Pulp mirror for Foreman
* Show content and content settings for Katello only
closes 676
> Publish Administering Foreman for all flavours

- web/content/css/_nav.scss
This makes the dropdown lists in the top navigation bar scrollable.
https://github.com/theforeman/foreman-documentation/issues/2752
> Make guide dropdown scrollable

- web/releases/3.12.json
- web/releases/3.13.json
I forgot to add this to the navigation with https://github.com/theforeman/foreman-documentation/pull/3515 Guides are now built and published:
* https://docs.theforeman.org/3.12/Administering_Project/index-foreman-deb.html
* https://docs.theforeman.org/3.13/Administering_Project/index-foreman-deb.html
* https://docs.theforeman.org/3.12/Administering_Project/index-foreman-el.html
* https://docs.theforeman.org/3.13/Administering_Project/index-foreman-el.html
no cherry-picks necessary
> Show Administering Foreman for 3.12 and 3.13

- guides/common/modules/ref_options-in-managed-dhcpv4.adoc
Fixing how the `next-server` DHCP option is determined when it isn't defined
https://github.com/theforeman/foreman-documentation/pull/3532#discussion_r1890805941
- Original behavior removed in Foreman 2.5
Please cherry-pick my commits into: N/A -- see #3561 for CPs
> Fix next-server behavior

- guides/common/modules/con_performing-post-upgrade-tasks.adoc
Adding a step in the post-upgrade guide to include code/macro changes to be applied to custom templates.
> Add a step in post-upgrade

- guides/common/modules/proc_enabling-red-hat-repositories.adoc
fix link in https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Enabling_Red_Hat_Repositories_content-management
* broken: https://docs.theforeman.org/nightly/Installing_Server/index-katello.html#adding-a-default-http-proxy_katello
* fixed: https://docs.theforeman.org/nightly/Installing_Server/index-katello.html#adding-a-default-http-proxy_foreman
Also converted to sentence case. Found while reviewing https://github.com/theforeman/foreman-documentation/pull/3545
> Fix broken link for default HTTP proxy

- guides/common/modules/con_dhcp-options.adoc
> Fix next-server behavior 3.13-3.7

- guides/common/modules/con_converting-a-host-to-rhel.adoc
Adding an option to convert2rhel to convert to a RHEL version in the Extended Lifecycle Support (ELS) phase.
This currently applies to RHEL 7, but I tried to write it in version-neutral terms for future times.
Documents https://github.com/theforeman/foreman_ansible/pull/746,  https://github.com/theforeman/foreman_remote_execution/pull/933, and https://github.com/theforeman/foreman_remote_execution/pull/937
> Add ELS option to convert2rhel

- .github/workflows/preview.yml
In 242dde2bc3e9aecd70829cfe872da247db7400d3 I tried to combine multiple downloads into a single command because from the man page made me think that. In practice it says:
> accepts at most 1 arg(s), received 3
This splits it back in to 3 separate commands as it previously was.
Becaue I broke things in #3579.
I'm sorry.
> Use multiple gh run download commands

- guides/common/assembly_managing-content-views.adoc
- guides/common/modules/proc_synchronizing-a-content-view-to-a-smart-proxy-server.adoc
I came to fix the example user input but stayed to fix the attribute.
You can synchronized a CV to a Smart Proxy Server but not from your Foreman Server onto your Smart Proxy that's on your Foreman Server.
> Fix attribute for Smart Proxy Server

- .github/workflows/preview.yml
In 242dde2bc3e9aecd70829cfe872da247db7400d3 I forgot to add $ to the variable, so it was taking it literally. This is something I tried to fix in 313e77e4229b120955cf18a2295d3e836cb923ee but didn't.
Still broken.
If this doesn't work it's probably best to revert the changes.
> Correctly invoke gh run download

- guides/common/modules/proc_registering-project-as-a-client-of-keycloak.adoc
Removing a reference to `foreman-installer --reset-foreman-keycloak`.
~~After discussing the purpose and expected effect of  `foreman-installer --reset-foreman-keycloak`, there was a suggestion to drop the note until we can investigate its behavior more closely.~~
`--reset-foreman-keycloak` doesn't disable Keycloak authentication as currently documented but rather makes the installer ignore previously generated files.
N/A
> Drop note about keycloak reset

- .github/workflows/preview.yml
Provide env vars to use `gh` in GHA
Original error message:
````
Run gh run download '' -n pr
gh run download '' -n pr
shell: /usr/bin/bash -e {0}
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
````
Refs 71b572445ab8a4ab156e5a9e66463ce57b76b6fa (PR 3587 on GitHub)
no cherry-picks.
> Provide env var to use gh CLI in GHA

- guides/common/modules/proc_registering-a-host.adoc
Returning selected info about optional fields in the Register Host interface of the Satellite UI.
https://issues.redhat.com/browse/SAT-28703
> Restore info on relevant optional fields in Register Host interface

- .github/workflows/preview.yml
Turns out gh already unpacks the artifact so the unzip steps are no longer needed. This also means we need multiple indivual commands because they need to be extract to different directories.
https://github.com/theforeman/foreman-documentation/pull/3588#issuecomment-2598421476
I promise I'm trying to make things easier ;)
I also verified I can download manually:
```console
$ gh run download --repo theforeman/foreman-documentation '12830208840' --name foreman-docs-web-master --dir ~/tmp-docs/preview
$ gh run download --repo theforeman/foreman-documentation '12830208840' --name foreman-docs-html-provide_env_var --dir ~/tmp-docs/preview/master
$ ls ~/tmp-docs
preview
$ ls ~/tmp-docs/preview/
404.html  CNAME  css  favicon.ico  img  index.html  js  master  release
```
Please cherry-pick my …
> Rely on gh run download to extract the artifacts

- .github/workflows/preview.yml
In 078bc30e4d6912068d14851e4244b2ec0af9ae91 I reintroduced a typo in the variable because of a merge conflict, making it end up as an empty string again. It happened to work because it was the last run (default behavior) but there's no guarantee this is correct.
> Stop in the workflow run ID to gh run download

- guides/common/modules/proc_registering-a-host.adoc
Adding a note to global registration for users who need to edit the registration command
New feature allows users to search certain resources not only by ID but also by name.
This feature was introduced to ease transition from the bootstrap script to global registration.
Documents https://github.com/theforeman/foreman/pull/10351
[SAT-28832](https://issues.redhat.com/browse/SAT-28832) (private)
- I couldn't find any better place.
- I think a formal Note is in order to emphasize this info but feel free to disagree.
> Add note about resources searchable by title

- guides/common/modules/con_upgrading-prerequisites.adoc
Migrating to SCA is a one-time thing and has been a part of the earlier version. Removing it as it is not required in later versions.
JIRA:
https://issues.redhat.com/browse/SAT-27580
Earlier PR for reference:
https://github.com/theforeman/foreman-documentation/pull/3228
> Remove SCA prerequisite

- guides/common/modules/proc_configuring-projectserver-to-synchronize-content-over-a-network.adoc
- guides/common/modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc
https://issues.redhat.com/browse/SAT-28286
> Use same manifest for upstr and downstr servers; add relevant links

- guides/common/modules/proc_creating-a-lifecycle-environment-path.adoc
Updating command language.
The language in two different commands appears redundant.
> Change command for Lifecycle and Environment Path

- guides/common/modules/proc_configuring-for-uefi-http-boot-ipv6-provisioning.adoc
- guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
- guides/doc-Planning_for_Project/topics/Provisioning_Concepts.adoc
As the title says: it drops the manual instruction to install/update the grub2-efi package.
As far as I can tell this was needed in the past because RHEL 7.9 contained an updated grub2-efi with support for HTTPBoot. Now that EL7 has been dropped, this is irrelevant and any installed version will do. The installer when enabling the tftp feature the already guarantees that the package is installed so the instruction can be dropped.
I only selected Foreman 3.13 as a cherry pick so we don't modify existing Satellite releases, but it's probably safe there as well.
> Drop instructions to update grub2-efi

- guides/common/modules/proc_adding-a-default-http-proxy.adoc
- guides/common/modules/proc_adding-an-http-proxy.adoc
Replacing manual configuration of the default content HTTP proxy with a new option to configure the global setting automatically.
Documents https://github.com/theforeman/foreman/pull/10372, https://github.com/Katello/katello/pull/11183, and https://github.com/Katello/katello/pull/11266
https://issues.redhat.com/browse/SAT-28860 (public)
- Not sure if there are any other places where an update is needed.
> Add option set new HTTP proxy as default

- guides/common/modules/proc_creating-an-activation-key.adoc
- guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
We removed system purpose addons in Katello, this is a PR to remove and references from the docs.
We removed addons here https://github.com/Katello/katello/pull/11196
N/A
> Remove system purpose addons references

- guides/common/modules/con_prerequisites-for-vmware-provisioning.adoc
- guides/common/modules/proc_creating-a-vmware-user.adoc
Removing VMware vCenter Server versions 6.x
They are EOL and no longer tested nor supported in Satellite
[SAT-30483](https://issues.redhat.com/browse/SAT-30483) (public)
- Do we want to keep them in upstream?
> Remove VMware vCenter 6.x (EOL)

- guides/common/modules/con_kickstart-workflow.adoc
Updating a link to RHEL docs to point to the latest major version.
https://github.com/theforeman/foreman-documentation/pull/3598/files#r1923189288
I don't think we need to list all supported versions (7-9), let's stick with the latest major as discussed in https://github.com/theforeman/foreman-documentation/issues/3448
> Update link to RHEL docs from 8 to 9

- guides/common/assembly_using-network-boot-to-provision-hosts.adoc
- guides/common/assembly_using-pxe-to-provision-hosts.adoc
- guides/common/modules/con_using-network-boot-to-provision-hosts.adoc
- guides/common/modules/con_using-pxe-to-provision-hosts.adoc
- guides/common/modules/proc_configuring-smart-proxy-to-provision-secure-boot-enabled-hosts.adoc
Adding Secure Boot support for Satellite and RHEL.
[SAT-23035](https://issues.redhat.com/browse/SAT-23035) Epic
- Please, take a look at the preview.
- I'm trying to reuse the module from #2145, but I'm not entirely sure it fits.
Please cherry-pick my commits into: N/A - for 3.14
> Add Secure Boot for Satellite and RHEL

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_installing-the-load-balancer.adoc
"Installing the load balancer" currently uses the `client-package-install` attribute even though the procedure is not expected to be performed on a client. At the same time, the existing `project-package-install` attribute is not a good fit either because HAProxy is installed on a host without doesn't yet use satellite-maintain to install packages.
This introduces a new `server-package-install` attribute that resolves to `dnf install`.
https://github.com/theforeman/foreman-documentation/pull/3598/files#r1922720268
N/A
> Replace client-install with server-install for LB

- guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-server.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
This fixes the same link as https://github.com/theforeman/foreman-documentation/pull/3547 (by removing {context}) on 3.11.
https://github.com/theforeman/foreman-documentation/pull/3547#issuecomment-2577559732
N/A
> Fix broken links by removing {context}

- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
Adding RHEL 10 hosts to the procedure for configuring a REX pull client.
https://issues.redhat.com/browse/SAT-27076
https://issues.redhat.com/browse/SAT-28102
N/A
> Update REX pull client procedure for EL 10 hosts

- guides/common/modules/proc_configuring-a-cross-forest-trust-between-freeipa-and-active-directory-for-project.adoc
- guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc
- guides/common/modules/proc_installing-the-load-balancer.adoc
I'm removing a few references to running servers and proxy servers on RHEL 8. Some of them are links to RHEL 8 docs in places where it's now only RHEL 9 that should be linked.
I checked all guides to see if there is anything left that we should remove.
N/A
> Drop references to servers on RHEL 8

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_installing-the-load-balancer.adoc
Simplifying `server-package-install` to `package-install`.
In https://github.com/theforeman/foreman-documentation/pull/3605, I introduced `server-package-install` as an attribute for installing packages on the base platform of Foreman server and proxy. When picking, I hit a conflict on 3.8 and noticed that on this branch, a simpler `package-install` is used for the same purpose.
N/A
> Replace server-pkg-install with pkg-install

- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/attributes.adoc
- guides/common/modules/con_upgrade-paths.adoc
- guides/common/modules/con_upgrading-smartproxies-separately-from-project.adoc
- guides/common/modules/snip_prerequisites-upgrading-project-server.adoc
Project	now supports Smart Proxies of verions N-1 and N-2. Added a	new attribute for N-2 Smart Proxy : {ProjectVersionPrevious-Previous}. Added information about N-2 Smart Proxy support for Upgrade guide modules.
> Include	information about N-2 Smart Proxy support

- guides/doc-Release_Notes/topics/foreman.adoc
Foreman 3.14 drops EL7 builds for the client repositories.
https://community.theforeman.org/t/drop-el7-packages-from-foreman-client-with-foreman-3-14/40505
I started in https://github.com/theforeman/foreman-documentation/pull/3596 but realized it was more complex. This limits to only adding the release note.
> Add release note for EL7 client repository removal

- guides/common/modules/proc_synchronizing-the-new-repositories.adoc
The EL version mentioned in the `Synchronizing the new repositories` chapter is 8, changing it to 9 for the newest release.
> Fix EL version for repositories

- guides/common/modules/proc_registering-hosts-by-using-the-bootstrap-script.adoc
- guides/common/modules/snip_deprecated-feature.adoc
Making the deprecation more visible and the first sentence less prescriptive in registration by using bootstrap.py
It's too encouraging
Bug [SAT-30255](https://issues.redhat.com/browse/SAT-30255) (public)
- I've introduced a snippet for feature deprecation so that we have a unified form for deprecations in docs.
> Redeprecate bootstrap registration more strongly

- guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc
Adding deprecation notice for KubeVirt compute resource
[SAT-29985](https://issues.redhat.com/browse/SAT-29985) (private)
Please cherry-pick my commits into: F3.14
> Deprecate KubeVirt compute resource

- guides/common/assembly_managing-errata.adoc
- guides/common/modules/proc_adding-errata-to-an-incremental-content-view.adoc
Adding procedure for applying errata to hosts 
running Red Hat Enterprise Linux 10.
In reference to https://issues.redhat.com/browse/SAT-28099
> Add procedure for RHEL 10

- guides/common/modules/proc_assigning-resource-quotas-to-a-user-group.adoc
- guides/common/modules/proc_assigning-resource-quotas-to-a-user.adoc
- guides/common/modules/proc_creating-a-resource-quota.adoc
- guides/common/modules/proc_deleting-a-resource-quota.adoc
- guides/common/modules/proc_editing-a-resource-quota.adoc
- guides/common/modules/proc_installing-the-resource-quota-plugin.adoc
* Add command to install Hammer CLI plugin for foreman_resource_quota
* Use Hammer CLI to assign resource quotes to users
* Use Hammer CLI to manage resource quotas
* Refs [PR 97 in foreman_resource_quota on GitHub](https://github.com/ATIX-AG/foreman_resource_quota/pull/97)
* Refs new Hammer CLI plugin https://github.com/ATIX-AG/hammer-cli-foreman-resource-quota/
no cherry-picks: only foreman_resource_quota is part of 3.13; the Hammer CLI plugin is not available in nightly.
> Limit host resources via Hammer CLI

- guides/common/modules/proc_registering-hosts-by-using-the-bootstrap-script.adoc
Adding limitations for registering hosts via SmartProxies by using the bootstrap script
Bootstrap script no longer works because of [Disabled Capsule port 8443](https://docs.redhat.com/en/documentation/red_hat_satellite/6.16/html/release_notes/deprecated-functionality#Jira-SAT-24522)
Bug [SAT-30255](https://issues.redhat.com/browse/SAT-30255)
> Add limitations to bootstrap registration

- guides/common/assembly_supported-usage-and-versions-of-project-components.adoc
- guides/common/modules/con_client-operating-systems.adoc
Remove unnecessary macros to simplify reading the source code of foreman-documentation.
As a response to https://github.com/theforeman/foreman-documentation/issues/2773, I looked at these files.
* Refs https://github.com/theforeman/foreman-documentation/issues/2773#issuecomment-2626640057
* GHA bot proofs that output does not change
> Remove unnecessary macros

- guides/common/modules/proc_invalidating-jwts-of-other-users.adoc
- guides/common/modules/proc_invalidating-your-own-jwts.adoc
Adding a newline between two sentences with xrefs
Our downstream build cannot handle two xrefs in one paragraph
> Add newline between two xrefs

- guides/common/modules/proc_adding-vmware-details-to-a-compute-profile.adoc
- guides/common/modules/proc_creating-a-vmware-user.adoc
Adding Virtual Trusted Platform Module compute-profile option and user permissions to VMware provisioning
Documents https://github.com/theforeman/foreman/pull/10324
[SAT-30464](https://issues.redhat.com/browse/SAT-30464) (public)
Please cherry-pick my commits into: probably none
> Add vTPM to VMware provisioning

- guides/common/modules/ref_general-settings-information.adoc
- Add HTTP(S) proxy username setting
- Add HTTP(S) proxy password setting
https://github.com/theforeman/foreman/pull/10432
> Add HTTP(S) proxy username and password Setting

- guides/common/modules/con_configuring-project-to-manage-the-lifecycle-of-a-host-registered-to-a-freeipa-realm.adoc
Making more precise the instructions on where to execute what command.
https://issues.redhat.com/browse/SAT-29941
> More precise steps on keytab move and ownership change for realm support

- guides/common/modules/proc_upgrading-smartproxy-server.adoc
Removing a no-longer-necessary step.
https://issues.redhat.com/browse/SAT-25812
> Remove unnecessary step (enabling custom repositories after upgrade)

- guides/common/modules/proc_creating-a-virt-who-configuration.adoc
Fixing an anchor ID that was missing hyphens
No issue. However, d/s doc will not build.
No style review or tech review required. I have tested this fix downstream.
> Fix anchor ID

- .github/workflows/deploy.yml
While 22.04 is not EOL yet, we can still jump to 24.04 already
> Update CI workflows to use Ubuntu 24.04

- .github/workflows/linkchecker.yml
- guides/Makefile
- guides/scripts/linkchecker-tryer
Add `--no-warnings` as otherwise `linkchecker-tryer` gets confused
> Run linkchecker on Ubuntu 24.04

- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
Updating references to Debian/Ubuntu so that they use an attribute.
Came up in https://github.com/theforeman/foreman-documentation/pull/3653
N/A
everywhere?
> Refer to Debian with an attribute

- guides/common/modules/con_guide-not-ready.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Configuring_User_Authentication/master.adoc
- guides/doc-Deploying_Hosts_AppCentric/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Configurations_Salt/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Managing_Organizations_and_Locations/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Project_API/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Provisioning_Installer/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Updating_Project/master.adoc
- guides/doc-Upgrading_Project_Disconnected/master.adoc
Turning the 'guide not ready yet' snippet into a proper module with its own heading.
This came up in https://github.com/theforeman/foreman-documentation/pull/3653. Adding the ribbon/banner causes build failures if there are headings missing in certain places. The 'guide not ready yet' snippet is one of them.
N/A
> Formally turn snippet into module

- guides/common/modules/con_guide-not-ready.adoc
- guides/doc-Administering_with_Ansible/master.adoc
- guides/doc-Configuring_Load_Balancer/master.adoc
- guides/doc-Configuring_User_Authentication/master.adoc
- guides/doc-Deploying_Hosts_AppCentric/master.adoc
- guides/doc-Deploying_Project_on_AWS/master.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
- guides/doc-Managing_Configurations_Salt/master.adoc
- guides/doc-Managing_Hosts/master.adoc
- guides/doc-Managing_Organizations_and_Locations/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- guides/doc-Project_API/master.adoc
- guides/doc-Provisioning_Hosts/master.adoc
- guides/doc-Tuning_Performance/master.adoc
- guides/doc-Updating_Project/master.adoc
- guides/doc-Upgrading_Project_Disconnected/master.adoc
Everything in https://github.com/theforeman/foreman-documentation/pull/3661 plus the same change for Administering with Ansible.
N/A
N/A
> Turn 'guide-not-ready' snippet into module (3.13 edition)

- guides/common/modules/proc_adding-a-remote-console-connection-for-a-host-on-proxmox.adoc
- guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
- guides/common/modules/proc_downloading-python-packages-to-a-host-from-a-python-repository.adoc
- guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
Fixing a wrong link.
https://issues.redhat.com/browse/SAT-30160
I would prefer to include the module in the provisioning guide directly but that would require changes in structure so as an alternative, I think this is good enough.
> Fix broken link in Using noVNC

- guides/common/modules/con_configuring-an-ldap-server-as-an-external-identity-provider-for-project.adoc
- guides/common/modules/con_configuring-kerberos-sso-for-active-directory-users-in-project.adoc
- guides/common/modules/con_configuring-kerberos-sso-with-freeipa-in-project.adoc
- guides/common/modules/proc_adding-a-remote-console-connection-for-a-host-on-proxmox.adoc
- guides/common/modules/proc_configuring-external-user-groups.adoc
- guides/common/modules/proc_configuring-host-based-access-control-for-freeipa-users-logging-in-to-project.adoc
- guides/common/modules/proc_creating-a-user.adoc
- guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
- guides/common/modules/proc_downloading-python-packages-to-a-host-from-a-python-repository.adoc
- guides/common/modules/proc_importing-the-katello-root-ca-certificate.adoc
- guides/common/modules/proc_logging-in-to-hammer-cli-with-freeipa-credentials.adoc
- guides/common/modules/proc_logging-in-to-the-projectwebui-with-freeipa-credentials-in-chrome.adoc
- guides/common/modules/proc_logging-in-to-the-projectwebui-with-freeipa-credentials-in-mozilla-firefox.adoc
- guides/common/modules/proc_logging-in-to-the-projectwebui.adoc
- guides/common/modules/proc_renaming-server.adoc
- guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
- guides/common/modules/ref_overview-of-authentication-methods-in-project.adoc
* Fix broken links
* Align anchors to file names
* Fix capitalization when changing the link
some links are broken in nightly docs
> Fix various broken links to/in Configuring User Authentication chapter

- guides/common/modules/proc_installing-the-resource-quota-plugin.adoc
Install the hammer cli package for the `foreman_resource_quota` via `foreman-installer` instead of `dnf`.
`foreman-installer` is the preferred installation method and becomes available with https://github.com/theforeman/foreman-installer/pull/1007
no cherry-picks: only foreman_resource_quota is part of 3.13; the Hammer CLI plugin is not available in nightly.
> Use foreman-installer for hammer resource quota

- guides/common/assembly_using-network-boot-to-provision-hosts.adoc
- guides/common/assembly_using-pxe-to-provision-hosts.adoc
- guides/common/modules/con_using-network-boot-to-provision-hosts.adoc
- guides/common/modules/con_using-pxe-to-provision-hosts.adoc
- guides/common/modules/proc_configuring-smart-proxy-to-provision-secure-boot-enabled-hosts.adoc
Improving texts around Secure Boot - text missing, a feature unsupported in Satellite, links missing...
Feedback from QE review in [SAT-23380](https://issues.redhat.com/browse/SAT-23380)
Please cherry-pick my commits into: Not sure
> Improve Secure Boot provisioning

- guides/common/modules/con_provisioning-methods-in-project.adoc
Adding a reference to Secure Boot to Planning.
https://issues.redhat.com/browse/SAT-30959
N/A
> Add Secure Boot to provisioning overview

- guides/common/modules/proc_adding-lifecycle-environments.adoc
- guides/common/modules/proc_importing-all-available-ansible-playbooks.adoc
- guides/common/modules/proc_importing-an-ansible-playbook-by-name.adoc
- guides/common/modules/proc_recovering-corrupted-content-on-a-smart-proxy.adoc
- guides/common/modules/proc_renaming-server.adoc
- guides/common/modules/proc_synchronizing-a-content-view-to-a-smart-proxy-server.adoc
* Add missing argument for Hammer CLI command
````
Could not synchronize capsule content:
Missing arguments for '--id'.
````
* tested on Foreman+Katello 3.11/4.13; should affect all versions
> Add ID arg to CV sync to Smart Proxy Servers

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- guides/common/attributes.adoc
- web/releases/3.14.adoc
- web/releases/3.14.json
> Update master for 3.14 branching

- guides/common/modules/con_managing-ssh-keys.adoc
Updating a link to an SSH key procedure in RHEL docs from RHEL 8 to RHEL 9. Also, the new link now points to the chapter rather than a low-level section (I expect chapter links to be more stable).
https://issues.redhat.com/browse/SAT-31199 reports this particular link.
There might be more links to update but because I don't have a good plan for how to address this across the whole repo, I'd like to update just this one to address the bug report.
> Update link from RHEL 8 to RHEL 9

- guides/common/modules/ref_general-settings-information.adoc
This reverts commit 9a795c2f4c7eaf02e8ae5784acb76b8ef9be7aca.
https://github.com/theforeman/foreman-documentation/pull/3635#issuecomment-2683234003
Changes in https://github.com/theforeman/foreman-documentation/pull/3635 will need a new PR if the corresponding code gets merged.
> Revert "Add HTTP(S) proxy username and password Setting"

- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
The self-upgrade command for Disconnected upgrade is missing the --maintenance-repo-label option.
JIRA link: https://issues.redhat.com/browse/SAT-31105
> Add missing option to self-upgrade command

- guides/doc-Release_Notes/topics/katello-contributors.adoc
- guides/doc-Release_Notes/topics/katello.adoc
Add Katello 4.16 release notes
Standard release procedure.
[see comment below]
> Add Katello 4.16 release notes

- guides/common/modules/proc_enabling-the-flatpak-remote.adoc
- guides/common/modules/proc_importing-and-exporting-content-to-project-server-for-flatpak.adoc
- guides/common/modules/proc_installing-flatpak-applications-on-project-hosts.adoc
- guides/common/modules/proc_setting-up-flatpak-remote-for-smartproxy.adoc
* split lines in code blocks
* align anchors to current conventions (they're not published anywhere yet)
Minor mostly cosmetic follow-up to https://github.com/theforeman/foreman-documentation/pull/3624
> Split arguments in code blocks into separate lines

- guides/common/assembly_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
- guides/doc-Administering_Project/master.adoc
Moving {parent-context} magic from master.adoc to a disaster recovery assembly.
The {parent-context} attribute is defined to enable reusing a procedure. However, I want to reuse the procedure in all upcoming DR scenarios so it can't stay in master.adoc; it needs to be set and unset for each of the DR assemblies.
This is a bit of a prerequisite for https://github.com/theforeman/foreman-documentation/pull/3679.
> Move parent-context from master.adoc to assembly

- guides/common/modules/proc_selecting-host-columns.adoc
Clarified that some data may be missing from the host table if no source provides it. Updated the documentation to reflect that Web UI collects data from multiple sources, which report different sets of facts.
Bug [SAT-23504](https://issues.redhat.com/browse/SAT-23504)
> Clarify that some data may be missing from the host table if not provided by any source

- guides/common/modules/proc_configuring-project-to-use-ldap.adoc
- guides/common/modules/proc_creating-an-api-only-user.adoc
- guides/common/modules/proc_exporting-templates.adoc
- guides/common/modules/proc_importing-templates.adoc
Adding labels to a few xref cross-links.
https://issues.redhat.com/browse/SAT-31298 reports a few xrefs that appear broken in Satellite builds. Satellite d/s docs tooling doesn't support multiple xrefs included on a single line, unless their labels are explicitly defined.
Another solution would be to include each xref on a separate line, for example as bullet point lists. But adding the label should work too (example: [9.4 Setting the global out-of-sync interval](https://docs.redhat.com/en/documentation/red_hat_satellite/6.16/html-single/managing_configurations_by_using_puppet_integration/index#setting-the-global-out-of-sync-interval_managing-configurations-puppet)).
> Update xrefs that are broken in satellite d/s builds

- guides/common/modules/con_upgrading-prerequisites.adoc
As  PostgreSQL 12 to PostgreSQL 13 upgrade is already performed in the previous upgrade, there is no need to repeat it in the prerequisites again. Removing this line.
JIRA: https://issues.redhat.com/browse/SAT-31306
> Remove Postgres space prerequisite

- guides/common/modules/ref_port-and-firewall-requirements.adoc
- guides/common/modules/snip_host-names-for-http-proxy.adoc
In order to use Insights with a proxy or firewall, users need to configure connections for both console.redhat.com and cert.console.redhat.com. Added these missing entries to the `Ports and Firewall requirements` and `Hostnames for HTTP proxy` tables.
JIRA: https://issues.redhat.com/browse/SAT-30953
> Add Insights settings for proxy/firewall

- guides/doc-Release_Notes/topics/foreman-3.14.0.adoc
Updating release notes for 3.14.0 rc2. Waiting on headlines, deprecations, and upgrade warnings
> update release notes 3.14.0 rc2

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
Adding a package clean-up command for EL 8+
The previous command only works until EL 7
Bug [SAT-24621](https://issues.redhat.com/browse/SAT-24621) (public)
- I haven't tested the new command but it's based on a RH knowledgebase solution
> Update package cleanup for EL 8+ cloud-init images

- guides/common/attributes-orcharhino.adoc
- guides/common/linkchecker.ini
- guides/common/modules/con_content-views-in-project.adoc
- guides/common/modules/proc_configuring-custom-alternate-content-sources.adoc
- guides/common/modules/proc_configuring-hosts-to-use-an-alternate-cname-for-content-management.adoc
- guides/common/modules/proc_configuring-rhui-alternate-content-sources.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-server.adoc
- guides/common/modules/snip_host-parameters-for-orcharhino-clients.adoc
Make links to `*.example.com` not clickable
* to improve SEO by removing broken links
> Hide clickable links to "*.example.com"

- guides/common/attributes-base.adoc
- guides/common/modules/proc_configuring-a-project-client-to-provide-hammer-cli-authentication-with-keycloak.adoc
Replacing two (now obsolete) replaceables for Keycloak realm with `{Project}_Realm`.
To be consistent with the other references to a Keycloak realm for Foreman, which already use `{Project}_Realm`: https://github.com/theforeman/foreman-documentation/blob/6239e9211bb1a59750d195247290dad8a0969e4e/guides/common/modules/proc_configuring-a-project-client-to-provide-hammer-cli-authentication-with-keycloak.adoc?plain=1#L17
I seem to have missed these in https://github.com/theforeman/foreman-documentation/commit/50b9023ea0779c82d9b399e428cc1fc1eb159559 where I originally updated the realm replaceable.
> Consolidate 'keycloak realm' replaceables

- guides/common/modules/proc_exporting-templates.adoc
- guides/common/modules/proc_importing-templates.adoc
Removing several custom xref labels.
I accidentally included them in https://github.com/theforeman/foreman-documentation/pull/3692.
> Remove custom xref labels

- guides/common/modules/proc_upgrading-the-external-database.adoc
Document to fix EVR permissions after PostgreSQL 13 upgrade
Otherwise DB restore using foreman-maintain will fail.
Inspired by #3167
> Document to fix EVR permissions after PostgreSQL 13 upgrade

- guides/common/modules/proc_configuring-project-to-use-ldap.adoc
- guides/common/modules/proc_creating-an-api-only-user.adoc
- guides/common/modules/proc_exporting-templates.adoc
- guides/common/modules/proc_importing-templates.adoc
This combines https://github.com/theforeman/foreman-documentation/pull/3692 (where there was a conflict on 3.11) and https://github.com/theforeman/foreman-documentation/pull/3706 (where I fixed a mistake I made in the first PR).
Satellite d/s toolchain doesn't support multiple xrefs on a single line.
N/A
> Fix broken xrefs in satellite d/s

- guides/common/assembly_importing-content.adoc
- guides/common/modules/proc_enabling-red-hat-repositories.adoc
- guides/common/modules/ref_required-red-hat-repositories.adoc
- guides/doc-Managing_Content/master.adoc
Splitting off required repos from _Enabling RH repos_ into a reference module
And adding RHEL 9 and 10 repos
Adding Kickstart repos needed for provisioning
- Splitting off because the list would become too long
- Adding RHEL 9 because it was missing, RHEL 10 will soon be available
Bug [SAT-31200](https://issues.redhat.com/browse/SAT-31200) (public)
> Restructure required RHEL repos + 9, 10 to Managing content

- guides/common/assembly_administering-hosts.adoc
- guides/common/assembly_configuring-and-setting-up-remote-jobs.adoc
- guides/common/assembly_registering-hosts.adoc
- guides/common/assembly_using-report-templates.adoc
- guides/common/modules/con_browsing-hosts-in-foreman-webui.adoc
- guides/common/modules/con_registering-hosts-and-setting-up-host-integration.adoc
- guides/common/modules/proc_executing-a-remote-job.adoc
- guides/common/modules/proc_installing-the-remote-execution-plugin.adoc
- guides/doc-Managing_Hosts/master.adoc
- web/releases/nightly.json
Show "Managing Hosts" for all flavours
Part of https://github.com/theforeman/foreman-documentation/issues/396
Needs tech ACK for:
* Is "tracer" a Katello-only feature? -> Yes :heavy_check_mark: 
* Does Leapp on EL hosts work without Katello? -> Yes, no change necessary.
* Is "Deploying a SSL certificate to hosts" Katello-only? -> in some use cases yes -> shown for all flavours :heavy_check_mark: 
no cherry-picks
> Show managing hosts for all flavours

- guides/common/assembly_managing-content-views.adoc
- guides/common/modules/con_rolling-content-views.adoc
- guides/common/modules/proc_creating-a-rolling-content-view.adoc
documentation for rolling content views:
new feature -> new docs
Refs PR 11240 in katello on GitHub
Refs 38048 in Redmine
no cherry-picks
> Add docs for rolling content views

- .github/workflows/preview.yml
If a PR doens't generate a diff (like this change) then the message shouldn't link to any diffs. By making this message explicit it makes reviewing a bit easier.
> Optimize the diff text when there's no change

- guides/common/assembly_common-deployment-scenarios.adoc
- guides/common/assembly_configuring-inter-server-synchronization.adoc
- guides/common/modules/con_synchronizing-content-between-servers.adoc
Moving ISS deployment scenarios from Managing Content to Planning.
I found these deployment scenarios for ISS when browsing Managing Content and thought they might be a better fit for Planning. We have a chapter dedicated to listing deployment scenarios in Planning.
This time, I even remembered to check the repo for all occurrences of the anchor I'm moving.
> Move ISS deployment scenarios to Planning

- guides/common/modules/con_hammer-cli-overview.adoc
> Use attribute in favor of downstream product name

- guides/common/modules/con_configuring-sso-and-2fa-with-keycloak-wildfly-in-project.adoc
- guides/common/modules/proc_registering-hosts-by-using-the-bootstrap-script.adoc
- guides/common/modules/snip_deprecated-feature.adoc
- guides/doc-Configuring_User_Authentication/master.adoc
* Deprecating procedures for the Wildfly distribution of Keycloak (all builds)
* Including procedures for the Quarkus distribution of Keycloak (Satellite only because they are already included in the other builds)
Keycloak based on Wildfly itself has been deprecated for a long time.
N/A
> Deprecate old keycloak and redirect all users to new keycloak

- guides/common/assembly_disaster-recovery-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/assembly_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
- guides/common/modules/con_disaster-recovery-for-active-and-passive-project-server-with-backup-and-restore.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/modules/proc_recovering-from-disaster-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/modules/ref_prerequisites-disaster-recovery-with-active-and-passive-project-server-and-backup-and-restore.adoc
Adding a new disaster recovery scenario: Active and passive server with backup and restore.
A follow-up to https://github.com/theforeman/foreman-documentation/pull/3558
With this scenario, it's becoming especially clear that it might be better to turn some of the procedure steps into separate modules (steps like cloning or taking backups). But for now, what matters is to get an agreement on the steps and record those. We can tweak the assembly structure later -- if there is time.
> Add DR for active-passive with backup&restore

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_viewing-the-project-ansible-modules.adoc
Replacing the `{ansible-namespace-example}` attribute with a (partially) hardcoded `{ansible-namespace}._module_name_` string.
The markup doesn't seem to get processed when enclosed in an attribute.
Personally, I'd also say that the same reasoning explained before in https://github.com/theforeman/foreman-documentation/pull/3709#issuecomment-2700417050 applies here too but that is not why I raised this PR.
Everywhere as long as there really is only one instance of the attribute on all branches.
> Fix broken rendering of ansible-namespace-example attr

- guides/common/modules/proc_updating-and-refreshing-red-hat-subscription-manifests.adoc
Adding a note to 2.5 Updating and refreshing 
Red Hat subscription manifests that tells the user
the web UI notifies them when their subscription
manifest expires.
Copy link
In reference to https://issues.redhat.com/browse/SAT-30326
> Add note about manifest expiry

- guides/doc-Release_Notes/topics/foreman-3.14.0.adoc
- guides/doc-Release_Notes/topics/foreman.adoc
Adding Headline Features for 3.14.0 Release notes
> Update notes for 3.14.0 GA

- guides/common/modules/proc_disabling-dns-dhcp-tftp-for-unmanaged-networks.adoc
Adding missing steps for disabling TFTP and DNS for unmanaged networks.
https://issues.redhat.com/browse/SAT-18574
> Add missing steps for disabling TFTP and DNS

- guides/common/modules/con_configuring-keycloak-quarkus-authentication-with-piv-cards-for-project.adoc
- guides/common/modules/con_configuring-keycloak-quarkus-authentication-with-totp-cards-for-project.adoc
- guides/common/modules/con_configuring-keycloak-wildfly-authentication-with-totp-cards-for-project.adoc
Removing a few intro modules on Keycloak.
Unused modules are a bad thing.
Thanks @apinnick for finding these.
> Remove a few unused Keycloak modules

- guides/common/modules/proc_creating-a-vmware-user.adoc
Add name of required permission to create VM snapshots on VMware.
required to use foreman_snapshot_management
> Add permission to take snapshots of VMs on VMware

- guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc
- guides/common/modules/con_postgresql-as-an-external-database-considerations.adoc
- guides/common/modules/proc_installing-postgresql.adoc
- guides/common/modules/proc_migrating-to-external-databases.adoc
Users must not manually create the "hstore" extension when preparing an external database host. If they do, the import of the pulpcore DB fails as follows:
````
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 6115; 0 0 COMMENT EXTENSION hstore 
pg_restore: error: could not execute query: ERROR:  must be owner of extension hstore
Command was: COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';
````
to fix the procedure :)
* Only tested on Foreman 3.12 on EL9 with an external DB host on EL9 running PostgreSQL 13.20
> Fix procedure to migrate to external database

- guides/common/modules/proc_loading-the-default-scap-contents.adoc
Adding a note to clarify the state of default SCAP contents on server.
https://issues.redhat.com/browse/SAT-30760 and https://issues.redhat.com/browse/SAT-19336
N/A
> Clarify that SCAP contents on server might not be up-to-date

- guides/common/modules/proc_registering-project-as-a-client-of-keycloak.adoc
Removing a step from the Keycloak setup.
Feedback from additional testing.
N/A
> Drop step to reset keycloak auth

- guides/doc-Release_Notes/topics/foreman.adoc
Add a release note about the parameter change, explaining that
`ansible_tower_fqdn` has been replaced and highlighting the default API path behavior.
See `Update Ansible Tower API URL for AAP 2.5+ compatibility` PR: https://github.com/theforeman/foreman/pull/10445
> Add upgrade warning for `ansible_tower_fqdn` removal

- guides/common/modules/proc_configuring-provisioning-callback-for-a-host.adoc
Update provisioning callback documentation to use `ansible_tower_api_url`,
ensuring the required API path is included. Clarify the correct path for older versions of AWX.
See `Update Ansible Tower API URL for AAP 2.5+ compatibility` PR: https://github.com/theforeman/foreman/pull/10445
> Replace `ansible_tower_fqdn` with `ansible_tower_api_url` in docs

- guides/common/assembly_monitoring-hosts-by-using-red-hat-insights.adoc
On orcharhino, the default is "false" but users can change it to "true".
show procedure about RH Insights also for orcharhino
To fix a broken link on https://docs.orcharhino.com/or/docs/sources/guides/red_hat_enterprise_linux/rhel_subscriptions.html in the second paragraph.
I take my live docs as tech review -> only style review required.
> Show insights procedure for orcharhino

- guides/common/modules/con_configuring-sso-and-2fa-with-keycloak-quarkus-in-project.adoc
- guides/common/modules/con_configuring-sso-and-2fa-with-keycloak-wildfly-in-project.adoc
- guides/common/modules/proc_configuring-a-project-client-to-provide-hammer-cli-authentication-with-keycloak.adoc
* Removing references to enabling both UI and CLI authentication for Keycloak users
* Clarifying that Project doesn't support both UI and CLI authentication for Keycloak users
https://issues.redhat.com/browse/SAT-31480
N/A
A separate PR will probably be needed for the earlier versions.
> Clarify that Keycloak doesn't work with both UI and CLI

- guides/doc-Administering_Project/master.adoc
Moving the chapter on disaster recovery closer to the beginning of the Admin guide.
As I noted in https://github.com/theforeman/foreman-documentation/pull/3614, I don't know how much point there is in worrying about the exact placement of the DR chapter in the (very large) guide. But still, a chapter on disaster recovery probably shouldn't follow _after_ a chapter on searching and bookmarking. So I decided to try to find a more prominent place after all.
N/A
> Move DR assembly to somewhere more prominent

- guides/common/assembly_disaster-recovery-with-two-active-project-servers.adoc
- guides/common/assembly_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
- guides/common/modules/con_disaster-recovery-with-two-active-project-servers.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-with-two-active-project-servers.adoc
- guides/common/modules/proc_recovering-from-disaster-with-two-active-project-servers.adoc
- guides/common/modules/ref_prerequisites-disaster-recovery-with-two-active-project-servers.adoc
Adding a new disaster recovery scenario: Two active servers.
A follow-up to https://github.com/theforeman/foreman-documentation/pull/3558
N/A
> Add DR scenario for multiple active server setup

- guides/scripts/find_unused_modules.py
Added a line to detect snippets included in modules.
Added a comment that script does not work on file includes that contain attributes. User will have to ignore those files in the output.
Snippets included in modules were reported as false positives.
I tested this with a fake snippet. It was detected.
No style review required.
> Updating find_unused_modules script

- guides/common/modules/proc_registering-project-as-a-client-of-keycloak.adoc
Dropping information on enabling both CLI and web UI authentication with Keycloak.
I missed this in https://github.com/theforeman/foreman-documentation/pull/3737. Project doesn't support both UI and CLI authentication for Keycloak users.
N/A
I'll raise a separate PR for 3.10 and below that combines this change and https://github.com/theforeman/foreman-documentation/pull/3737.
> Drop intro about enabling two keycloak auth methods

- guides/common/assembly_configuring-external-services.adoc
- guides/common/modules/con_converting-a-host-to-rhel.adoc
- guides/common/modules/con_how-puppet-integrates-with-project.adoc
- guides/common/modules/con_project-server-upgrade-considerations.adoc
- guides/common/modules/con_remote-execution-in-project.adoc
- guides/common/modules/proc_assigning-a-host-to-a-specific-location.adoc
- guides/common/modules/proc_assigning-a-host-to-a-specific-organization.adoc
- guides/common/modules/proc_configuring-kerberos-authentication-for-remote-execution.adoc
- guides/common/modules/proc_configuring-your-project-to-run-ansible-roles.adoc
- guides/common/modules/proc_creating-a-job-template.adoc
- guides/common/modules/proc_executing-a-restorecon-template-on-multiple-hosts.adoc
- guides/common/modules/proc_setting-up-job-templates.adoc
- guides/common/modules/ref_example-including-power-options-in-a-job-template.adoc
- guides/common/modules/ref_example-restorecon-template.adoc
- guides/common/modules/ref_glossary-of-terms-used-in-project.adoc
- guides/common/modules/ref_rendering-a-restorecon-template.adoc
* fix broken links
* avoid cross-guide linking, e.g. when "run REX jobs" is part of managing hosts and configuring hosts by using Ansible, when we should not link to the managing hosts guide by default.
improve UX :)
follow-up to https://github.com/theforeman/foreman-documentation/pull/3756
> Fix and simplify links part 5

- guides/common/modules/proc_configuring-project-settings-for-keycloak-authentication-using-the-cli.adoc
- guides/common/modules/proc_registering-project-as-a-keycloak-client.adoc
I reviewed the information we have on Keycloak on branch 3.10 and want to remove references to configuring both CLI and web UI login methods.
In https://github.com/theforeman/foreman-documentation/pull/3737 and https://github.com/theforeman/foreman-documentation/pull/3759, I removed this information from 3.11 and above. This is because as noted in https://github.com/theforeman/foreman-documentation/pull/3737, during testing it was uncovered that both login methods cannot be configured at the same time even when using multiple Keycloak clients.
N/A
> Remove references to both CLI and web UI login with Keycloak

- guides/common/assembly_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-with-active-and-passive-project-server-with-external-storage.adoc
Replacing references to cloning in the "DR with external storage" scenario with steps to back up and restore. Cloning is documented only for downstream Satellite and to be able to include the scenario upstream, backup and restore is an alternative.
https://github.com/theforeman/foreman-documentation/issues/3717
N/A
> Make DR with external storage work for upstream

- guides/common/modules/proc_installing-proxy-packages.adoc
Replacing step description that says "install server packages" with "install capsule packages".
It _is_ a procedure for installing a capsule. https://issues.redhat.com/browse/SAT-32158
Affects Satellite only.
> Fix wording for installing capsule packages

- guides/common/assembly_preparing-environment-for-capsule-installation.adoc
- guides/common/assembly_preparing-environment-for-installation.adoc
- guides/common/modules/con_upgrading-overview.adoc
- guides/common/modules/snip_red-hat-helper-apps.adoc
* Consolidating introductions in the installation and upgrade guides
* Moving the (satellite-only) paragraph about upgrade helper app to a snippet
* Extending the new snippet with a similar paragraph about installation helper app
* EDIT: Improving the existing wording in introductions and the app descriptions
The installation helper app is a new feature.
I'd like to find a solution that is consistent across all the installation (connected, disconnected, proxy) and upgrade (connected, disconnected) guides. This is so that users can expect to find a reference to the installation/upgrade apps at approximately the same place in all of the guides.
> Add reference to satellite installation helper

- guides/common/modules/proc_performing-post-upgrade-tasks.adoc
Adding a single step on deleting a directory with backup PostgreSQL data after upgrading.
Based on https://issues.redhat.com/browse/SAT-32182
Since this update seems to apply only to upgrading to Sat 6.16, I'm branching it out from the corresponding Foreman branch (3.12). 
> Add info on removing backup PostgreSQL data

- guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
Removing selected [v3_req] parameters from example openssl.cnf.
The current list includes parameters that are not strictly necessary. https://issues.redhat.com/browse/SAT-31112
N/A
> Only list required v3_req parameters in openssl.conf

- guides/common/assembly_foreman-deployment-planning.adoc
- guides/common/assembly_foreman-overview-and-concepts.adoc
- guides/doc-Planning_for_Project/master.adoc
Include "overview & concepts" and "deployment planning" as assemblies rather than AsciiDoc parts.
To clean up master.adoc a bit and also to resolve errors about too many level 0 headings.
I'm adding a new part/assembly to the Planning guide and this would help keep things a bit more tidy.
> Clean up master.adoc in Planning

- guides/common/assembly_api-cheat-sheet.adoc
- guides/common/modules/proc_applying-errata-to-a-host-collection.adoc
- guides/common/modules/proc_applying-errata-to-hosts.adoc
Removing procedures that reference `install_content`.
The `install_content` endpoint was removed. According to Satellite downstream release notes, this happened in 6.15: https://docs.redhat.com/en/documentation/red_hat_satellite/6.15/html-single/release_notes/index#removed-functionality
https://issues.redhat.com/browse/SAT-31867 requests replacing the old procedures with an example that uses `job_invocations` but looking at the API guide, I think the cheat sheet chapter already has enough examples on working with hosts so I think we're fine just dropping the obsolete ones.
> Drop procedures that use an obsolete API endpoint

- guides/common/modules/proc_configuring-satellite-for-outgoing-emails.adoc
* Updating the configuration example for using gmail.com as an SMTP server
* Changing the layout of the tables with example to better support adding the new information
Reported in https://issues.redhat.com/browse/SAT-32049
Per https://support.google.com/a/answer/176600?hl=en, using the app password is now the only supported way while before the standard Google password was also possible.
N/A
> Update SMTP configuration for Gmail

- guides/common/modules/proc_applying-errata-to-hosts.adoc
Removing procedures that reference install_content.
The install_content endpoint was removed. See https://github.com/theforeman/foreman-documentation/pull/3780 which removes the references for branches 3.13 and above.
N/A
No picks because the guide doesn't exist on 3.11 and lower.
> Remove references to 'install_content'

- guides/common/modules/proc_creating-hosts-on-proxmox.adoc
- guides/common/modules/proc_creating-hosts-on-vmware.adoc
- guides/common/modules/proc_creating-hosts-with-pxe-boot-provisioning.adoc
- guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
- guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
- guides/common/modules/proc_creating-hosts-with-unattended-provisioning.adoc
- guides/common/modules/proc_creating-image-based-hosts-on-amazon-ec2.adoc
- guides/common/modules/proc_creating-image-only-hosts.adoc
- guides/common/modules/proc_creating-network-or-image-based-hosts.adoc
- guides/common/modules/snip_step-parameter-ak.adoc
Introducing a snippet for a repeating instruction step that was too vague in most places of provisioning
Specific parameter is needed and docs failed to mention it.
https://issues.redhat.com/browse/SAT-32160
> Fix vague AK parameter instruction step

- guides/common/attributes-satellite.adoc
- guides/common/attributes-titles.adoc
Removing D/S RHEL conversion toolkit doc, which was last published for Sat 6.15.
> Removing obsolete RHEL conversion doc

- guides/common/modules/proc_creating-a-host-group.adoc
* Make example password italic
* Sort attributes in alphabetical order
* Use one option per line
currently, example values are not italic.
> Allow italic emphasis for host group CLI command

- .github/PULL_REQUEST_TEMPLATE.md
- guides/common/attributes-orcharhino.adoc
orcharhino 7.2 has been released: https://orcharhino.com/en/ressourcen/release-notes/orcharhino-7-2/ :tada:
> Bump orcharhino version to 7.2

- guides/common/modules/proc_performing-an-online-backup.adoc
Since online backups are supported for production, after snapshot backups were dropped [1], removing the now irrelevant line about online backups being unsupported. [1] https://issues.redhat.com/browse/SAT-25667
JIRA: https://issues.redhat.com/browse/SAT-29507
> Modify production environment backup recommendation

- web/releases/3.14.json
- web/releases/nightly.json
Drop unmaintained guide from navigation.
Refs da81664d2ee91df36a8ac83173a53f02662973f4 on "3.14" Refs b0dd9eb8a8f32c35230f2b970f8ff61a5e81d5b7 on "master"
Refs PR 3815 on GitHub
> Remove Foreman on AWS from navigation

- guides/common/modules/proc_configuring-remaining-smart-proxy-servers-with-custom-ssl-certificates.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-custom-ssl-certificates-for-load-balancing-without-puppet.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-custom-ssl-certificates-to-generate-and-sign-puppet-certificates.adoc
- guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-server.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
We've been pushing users away from katello-certs-check now that it's always called by foreman-installer and foreman-proxy-certs-generate. This simplifies operation by having fewer steps which also simplifies documentation.
It's a further follow up of https://github.com/theforeman/foreman-documentation/commit/7394c6a882228c2c9405721c687fc117cfb9984f and https://issues.redhat.com/browse/SAT-3878 was the trigger to look at this.
> Avoid running katello-certs-check in most cases

- guides/common/assembly_preparing-environment-for-installation-in-ipv6-network.adoc
- guides/common/modules/con_limitations-of-installation-in-an-ipv6-network.adoc
A note saying Satellite does not support 
configuring a proxy using a direct IPv6 address
and to use a FQDN.
DDF request in https://issues.redhat.com/browse/SAT-25719
> Add note about IPv6 and proxy failing

- web/releases/3.14.json
- web/releases/nightly.json
#3830 accidentally uses title case for a guide in the navigation. This update changes the name to sentence case in the master branch.
Consistency in the navigation
> Change guide name in navigation to lowercase

- guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc
- guides/common/modules/proc_configuring-the-freeipa-authentication-source-on-projectserver.adoc
Adding a step to configure SSSD to enable Kerberos authentication for IPA and AD users. To be able to fit the new step in neatly, I also tweaked the procedures a little.
https://issues.redhat.com/browse/SAT-32530 explains the problem and includes a description of the known issue.
This is caused by a bug on the SSSD side. The SSSD issue: https://github.com/SSSD/sssd/issues/3057. The bug has been fixed in SSSD but the updated version of SSSD is not yet available for Foreman.
> Add workaround for IPA and AD Kerberos auth

- guides/common/modules/snip_steps-needs-reboot.adoc
The step for rebooting for Satellite build, currently reads "If the previous command told you to reboot, then reboot the system". This does not make sense for Satellite as the command to determine whether a reboot is required is only rendered for non-Satellite builds.
JIRA: https://issues.redhat.com/browse/SAT-33361
> Reword the step to reboot

- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
- guides/common/modules/ref_port-and-firewall-requirements.adoc
- guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc
For remote execution pull-mode to work,	port 9090 should be accessible as well.
JIRA: https://issues.redhat.com/browse/SAT-32031
> Add port 9090 for MQTT

- guides/common/assembly_configuring-provisioning-resources.adoc
- guides/common/assembly_preparing-provisioning-content.adoc
- guides/common/modules/con_preparing-provisioning-content.adoc
- guides/common/modules/proc_preparing-a-synchronized-kickstart-repository.adoc
- guides/common/modules/ref_initialization-script-for-provisioning-examples.adoc
Previously this included notes that Katello provided a feature, but it's better to hide the text altogether on irrelevant builds. That is done around the include statement.
On Katello builds this hides a redundant note and on foreman-el builds it hides an irrelevant chapter that users must always skip.
> Properly use ifdef to hide Katello content

- guides/common/modules/con_registering-clients-to-the-load-balancer.adoc
Adds a note about how to consume container content to the registration part of the load balancing guide.
https://github.com/Katello/smart_proxy_container_gateway/pull/46 added container support for load balancers, so this adds a small note about how to consume the content.
The fact that you use the LB hostname should be obvious I'd think, but I'm adding this for completion.
> Add container content note to load balancing guide

- guides/common/assembly_disaster-recovery-by-virtualizing-your-projectserver.adoc
- guides/common/assembly_disaster-recovery-for-active-and-passive-project-server-with-external-storage.adoc
- guides/common/assembly_disaster-recovery-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/assembly_disaster-recovery-with-two-active-project-servers.adoc
- guides/common/assembly_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
- guides/common/modules/con_disaster-recovery-by-virtualizing-your-projectserver.adoc
- guides/common/modules/con_disaster-recovery-for-active-and-passive-project-server-with-backup-and-restore.adoc
- guides/common/modules/con_disaster-recovery-for-active-and-passive-project-server-with-external-storage.adoc
- guides/common/modules/con_disaster-recovery-with-two-active-project-servers.adoc
- guides/common/modules/con_overview-of-recommended-disaster-recovery-plans.adoc
- guides/common/modules/con_preparing-for-disaster-recovery-and-recovering-from-data-loss.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-by-virtualizing-your-projectserver.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-with-active-and-passive-project-server-with-external-storage.adoc
- guides/common/modules/proc_preparing-for-disaster-recovery-with-two-active-project-servers.adoc
- guides/common/modules/proc_recovering-from-disaster-by-restoring-a-vm-snapshot-of-projectserver.adoc
- guides/common/modules/proc_recovering-from-disaster-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/modules/proc_recovering-from-disaster-with-active-and-passive-project-server-with-external-storage.adoc
- guides/common/modules/proc_recovering-from-disaster-with-two-active-project-servers.adoc
- guides/common/modules/ref_prerequisites-disaster-recovery-by-virtualizing-your-projectserver.adoc
- guides/common/modules/ref_prerequisites-disaster-recovery-with-active-and-passive-project-server-and-backup-and-restore.adoc
- guides/common/modules/ref_prerequisites-disaster-recovery-with-active-and-passive-project-server-and-external-storage.adoc
- guides/common/modules/ref_prerequisites-disaster-recovery-with-two-active-project-servers.adoc
- guides/common/modules/snip_disaster-recovery-hostname-cannot-change.adoc
- guides/doc-Administering_Project/master.adoc
Adding documentation on disaster recovery to versions 3.13 and earlier.
Previously included only on 3.14 and later, this now adds the documentation to 3.13 and earlier because the content is valid for these versions too.
I didn't look for all the individual commits to cherry-pick them because, among other things, those commits also add a module to Planning where the structure is very different between 3.13 and 3.14. Instead, I copied whole files.
> Add disaster recovery guide to 3.13

- guides/doc-Integrating_Provisioning_Infrastructure_Services/docinfo.xml
Update the subtitle of "Integrating provisioning infrastructure services".
The subtitle of the "Integrating provisioning infrastructure services" guide was accidentally overridden in a [previous update](https://github.com/theforeman/foreman-documentation/commit/ebf8b4bfdecd904a6ab5758476119930c976e57a#diff-fabc485bc8b8a3568598891f295f4f292bef4ca18e8f1e6f5d8a987d37f56c4cR4). This PR restores the subtitle.
> Restore subtitle of "Integrating provisioning infrastructure services"

- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
Adding step 7 from Upgrading Guide in 6.15 
https://docs.redhat.com/en/documentation/red_hat_satellite/6.15/html-single/upgrading_connected_red_hat_satellite_to_6.15/index#upgrading_a_connected_satellite_server_upgrading-connected back to the latest version because it was affecting
upgrading to 6.17. 
https://issues.redhat.com/browse/SAT-33478 raised an urgent doc bug because it was causing
users to fail upgrading to 6.17.
> Add step to enable Satellite repositories

- guides/common/modules/con_host-collections-overview.adoc
- guides/common/modules/con_managing-activation-keys.adoc
- guides/common/modules/con_restricting-hosts-access-to-content.adoc
- guides/common/modules/proc_changing-the-repository-sets-status-for-a-host-in-project.adoc
- guides/common/modules/proc_creating-an-activation-key.adoc
- guides/common/modules/proc_installing-packages-on-a-host.adoc
- guides/common/modules/proc_using-activation-keys-for-host-registration.adoc
- guides/common/modules/proc_viewing-errata-by-applicable-and-installable.adoc
- guides/common/modules/ref_best-practices-for-content-views.adoc
- guides/common/modules/ref_best-practices-for-errata.adoc
- guides/common/modules/ref_best-practices-for-patching-content-hosts.adoc
Adding (s) to content view to say content view(s).
Link to doc bug Jira: https://issues.redhat.com/browse/SAT-33205
> Pluralize content view to view(s)

- guides/common/modules/proc_upgrading-smartproxy-server.adoc
Changing part of a step as requested in 
https://issues.redhat.com/browse/SAT-33478 to 
the same step in #3848 as requested in the
comments in Jira.
Comment in Jira suggested "In step 6, we can replace text "Ensure Capsule has access to satellite-maintenance-6.17-for-rhel-9-x86_64-rpms and execute:" with the command to enable the repository.
> Change part of step in procedure

- guides/common/modules/proc_installing-postgresql.adoc
Same change as https://github.com/theforeman/foreman-documentation/pull/3832.
The Installing PostgreSQL as an external database section does not have the command for RHEL9. Dropping the RHEL8 command for newer Project versions.
JIRA: https://issues.redhat.com/browse/SAT-33417
> Update postgresql command for RHEL9 for newer versions

- guides/scripts/find_unused_modules
Treating it as errors means CI will fail on it and make it clear there's something to act on.
In https://github.com/theforeman/foreman-documentation/pull/3790#discussion_r2046832997 I asked if it should be an error. Since then the warnings have been resolved and we can make it fatal.
> Treat unused modules as errors

- guides/common/modules/proc_adding-a-vmware-connection-to-server.adoc
This only works on libvirt, but is in the VMware connection instructions.
It was present all the way back in the initial version (156d071a3e61).
> Remove libvirt specific text from VMware procedure

- guides/common/modules/proc_creating-hosts-with-uefi-http-boot-provisioning.adoc
In fbc716deb22d3ae37db84aeb64b243661fb4a54b the section id was renamed from http-booting-requirements to http-booting.
> Correct http-booting anchor

- guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
- guides/common/assembly_installing-capsule-server.adoc
- guides/common/modules/con_configuring-project-to-manage-the-lifecycle-of-a-host-registered-to-a-freeipa-realm.adoc
- guides/common/modules/con_preparing-networking.adoc
- guides/common/modules/con_prerequisites-for-image-based-provisioning.adoc
- guides/common/modules/proc_creating-hosts-on-proxmox.adoc
- guides/common/modules/proc_creating-hosts-on-vmware.adoc
- guides/common/modules/proc_creating-network-or-image-based-hosts.adoc
- guides/common/modules/proc_installing-smart-proxy-server.adoc
- guides/common/modules/proc_registering-hosts-by-using-the-bootstrap-script.adoc
- guides/common/modules/proc_troubleshooting-dhcp-problems.adoc
- guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc
- guides/common/modules/ref_smart-proxy-server-scalability-considerations-when-managing-puppet-clients.adoc
Use proper attribute for Smart Proxies and Smart Proxy Servers.
fixes #2774
> Reword external Smart Proxies to Smart Proxy Servers

- guides/common/modules/proc_configuring-salt-on-project.adoc
Add docs for service file to fix file permissions for Salt.
due to a bug in Salt
> Add instructions to fix Publisher ACL for Salt

- guides/common/modules/proc_registering-capsule-to-satellite-server.adoc
Turning the step to register content proxy to Foreman from optional to mandatory.
In https://github.com/theforeman/foreman-documentation/pull/3855#pullrequestreview-2842525514, it was suggested that the proxy installation instructions and upgrade instructions for katello are inconsistent.
* Registering the proxy base system is a mandatory step in the upgrade process: https://github.com/theforeman/foreman-documentation/blob/028b74684e59bcb042835d20da4713e095cd67ed/guides/common/modules/proc_upgrading-smartproxy-server.adoc?plain=1#L20
* Syncing repositories is also mandatory in the upgrade process: https://github.com/theforeman/foreman-documentation/blob/028b74684e59bcb042835d20da4713e095cd67ed/guides/common/modules/proc_synchronizing-the-new-repositories.adoc?plain=1#L4 and …
> Make registering proxy mandatory for katello

- guides/common/modules/con_red-hat-offline-knowledge-portal.adoc
- guides/common/modules/snip_red-hat-offline-knowledge-portal.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Upgrading_Project_Disconnected/master.adoc
The Red Hat Offline Knowledge Portal (RHOKP) will be included with the Satellite subscription for 6.17. Created a snippet and added it to the disconnected install and disconnected upgrade guides.
JIRA:
https://issues.redhat.com/browse/SAT-31163
https://issues.redhat.com/browse/SAT-31164
* [] Foreman 3.13/Katello 4.15 (EL9 only)
> Add a note about RHOKP in the disconnected guides

- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
Removing a step in the upgrade procedure for upgrading the external database to PostgreSQL 13.
Upgrading to PostgreSQL 13 was already a mandatory step in the Foreman 3.12/Satellite 6.16 upgrade guides. This means that we can remove the step starting with Foreman 3.13.
https://issues.redhat.com/browse/SAT-34149
N/A
> Drop upgrade step to upgrade to PostgreSQL 13

- .github/PULL_REQUEST_TEMPLATE.md
> add Foreman 3.15/Katello 4.17 and mark 3.14 as the Sat 6.17 base

- guides/common/modules/con_supported-client-architectures-for-configuration-management.adoc
- guides/common/modules/con_supported-client-architectures-for-content-management.adoc
- guides/common/modules/con_supported-client-architectures-for-host-provisioning.adoc
Adding RHEL 10 and supported architectures to the Planning guide for Satellite
RHEL 10 is supported in Satellite 6.17+
- I've only copy-pasted architectures of RHEL 9. This has to be confirmed by SMEs.
> Add RHEL 10 to Planning guide

- guides/common/assembly_preparing-environment-for-capsule-installation.adoc
- guides/common/assembly_preparing-environment-for-installation.adoc
- guides/common/modules/con_preparing-for-project-upgrade.adoc
- guides/common/modules/con_red-hat-helper-app.adoc
- guides/doc-Installing_Proxy/master.adoc
- guides/doc-Installing_Server/master.adoc
- guides/doc-Installing_Server_Disconnected/master.adoc
- guides/doc-Upgrading_Project/master.adoc
- guides/doc-Upgrading_Project_Disconnected/master.adoc
Moving the current snippet about Satellite helper apps to a separate section.
We have feedback saying that customers are often not aware of the helper apps' existence. Giving the references to the apps their own section with a title could help with that.
https://issues.redhat.com/browse/SAT-34067
N/A
> Create a section for helper app references

- guides/common/modules/proc_enrolling-projectserver-in-freeipa-domain.adoc
This replaces literal `ipa-server.example.com` with the proper attribute.
Using the attribute ensures that the server name is displayed correctly in all flavors.
N/A
All applicable branches.
> Use attribute for FreeIPA server name

- guides/doc-Release_Notes/topics/foreman.adoc
oVirt integration is deprecated in 3.15 and removed in 3.16
Replaces #3724
https://community.theforeman.org/t/rfc-deprecation-and-removal-of-ovirt-compute-resource/42527
https://projects.theforeman.org/issues/38266
https://issues.redhat.com/browse/SAT-12005
Filing a new PR because the 3.15 release has been branched.
- Migration is covered in PR #3871
> Deprecate oVirt in 3.15

- guides/common/modules/proc_enabling-the-flatpak-remote.adoc
Changing the command
Otherwise things fail:
Error: No such sub-command 'repository'.
See: 'hammer flatpak-remote --help'.
Fixes: 2a0e9d2a746b6eaecfc48c7df8dc7bd782b68fae
> use `hammer flatpak-remote remote-repository list` to list contents

- guides/common/modules/proc_installing-the-project-ansible-modules.adoc
On orcharhino, there is a meta package that is always installed which requires the Foreman Ansible collection. On orcharhino Server:
`$ rpm -qa "ansible-collection-*"`
Refs PR 3844 on GitHub
Please cherry-pick as applicable.
> Do not require Ansible collection on orcharhino

- guides/common/modules/proc_downloading-the-binary-dvd-images.adoc
To download the binary DVD images, the user now has to perform an additional step to navigate to the RHEL downloads page.
JIRA:https://issues.redhat.com/browse/SAT-29878
> Fix the binary download procedure

- guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc
- guides/common/modules/proc_configuring-the-freeipa-authentication-source-on-projectserver.adoc
Specifying the RHEL versions that need a workaround for SSSD in IPA and AD setups to be applied.
The SSSD issue: https://github.com/SSSD/sssd/issues/3057
A downstream doc ticket on the Satellite side: https://issues.redhat.com/browse/SAT-32530
N/A
> Limit SSSD workaround to certain RHEL versions only

- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
Mentioning that the `dbus-tools` package has to be installed on EL 9 cloud-init images
[SAT-31366](https://issues.redhat.com/browse/SAT-31366) (public)
- Is this okay or should I repeat the install command for EL versions instead?
> Mention dbus-tools package required for EL 9 cloud-init images

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_integrating-project-and-awx.adoc
- guides/common/modules/proc_configuring-provisioning-callback-for-a-host.adoc
Fixing AWX as an equivalent of Ansible Automation Platform instead of Ansible Automation Controller for Satellite
[SAT-32610](https://issues.redhat.com/browse/SAT-32610) (public)
Only the following files use the `{awx}` attribute:
- guides/common/attributes-base.adoc
- guides/common/modules/proc_configuring-provisioning-callback-for-a-host.adoc
- guides/common/modules/con_integrating-project-and-awx.adoc - _updated_
- guides/common/modules/proc_adding-project-server-to-awx-as-a-dynamic-inventory-item.adoc
Only one of them seems to have required an additional change.
> Use AAP as the value of :awx: attribute for Satellite

- guides/doc-Release_Notes/topics/katello-4.17.0.adoc
Updating Katello 4.17.0.rc2 documentation to Foreman 3.15 branch
Working on Headline features for 4.17 documentation.
> Updating documentation for Katello 4.17.0.rc2

- guides/common/modules/proc_upgrading-a-connected-project-server.adoc
Changing the EL 9 repo in the step prior to the self-upgrade EL 8 maintenance repo.
JIRA: https://issues.redhat.com/browse/SAT-34218
- The step prior to the self-upgrade mentions the EL 9 maintenance repo.
- However, EL 8 to EL 9 upgrade can take place only after the Project server has been upgraded to 3.12.
> Fix maintenance	repo version

- guides/doc-Administering_Project/master.adoc
Satellite 6.17 does not provide the "rubygem-foreman_resource_quota" package.
Remove https://docs.redhat.com/en/documentation/red_hat_satellite/6.17/html/administering_red_hat_satellite/index
`ssh satellite dnf search rubygem-foreman_resource_quota` -> plugin is not packaged by RH.
Needs tech ACK.
> Hide foreman_resource_quota plugin for Satellite

- guides/common/modules/proc_configuring-installation.adoc
Since c140d0890eac01643fa945d987fa11559341ae31 the directory is `/media/rhel` and not `/media/rhel8`.
> Correct media umount path

- guides/common/modules/con_managing-ostree-content.adoc
- guides/common/modules/con_transport-modes-for-remote-execution.adoc
- guides/common/modules/proc_configuring-a-bmc-interface.adoc
- guides/common/modules/proc_configuring-host-based-access-control-for-freeipa-users-logging-in-to-project.adoc
- guides/common/modules/proc_configuring-pull-based-transport-for-remote-execution.adoc
- guides/common/modules/proc_configuring-puma-threads.adoc
- guides/common/modules/proc_configuring-puma-workers.adoc
- guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc
- guides/common/modules/proc_configuring-the-fallback-to-any-smartproxy-remote-execution-setting-in-project.adoc
- guides/common/modules/proc_configuring-the-freeipa-authentication-source-on-projectserver.adoc
- guides/common/modules/proc_configuring-the-global-smartproxy-remote-execution-setting-in-project.adoc
- guides/common/modules/proc_executing-a-remote-job.adoc
- guides/common/modules/proc_installing-smart-proxy-server.adoc
- guides/common/modules/proc_installing-the-discovery-service.adoc
- guides/common/modules/proc_manually-tuning-puma-workers-and-threads-count.adoc
- guides/common/modules/proc_restoring-manual-changes-overwritten-by-a-puppet-run.adoc
- guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
- guides/common/modules/proc_upgrading-your-project-server.adoc
- guides/common/modules/ref_port-and-firewall-requirements.adoc
- guides/common/modules/ref_smart-proxy-port-and-firewall-requirements.adoc
Use whitespace in favor of equal sign for `foreman-installer` and `hammer` commands for `true` and `false`.
fixes #2881
I do not have a regexp at hand right now to find _all_ instances, so I am limiting this PR to boolean options.
> Omit equal sign for bool options in foreman-installer/Hammer CLI

- guides/doc-Release_Notes/topics/katello.adoc
Adds a release warning for 4.16 as as response to https://community.theforeman.org/t/docker-image-repos-renamned-with-foreman-3-14-katello-4-16/43493
> Retroactively add 4.16 warning about container naming

- guides/common/modules/con_puma-workers-and-threads-recommendations.adoc
- guides/doc-Tuning_Performance/master.adoc
This reverts commit b3491afcd5fdc5ea1145e052d39c20f4272b9a9c and instead brings back the inclusion.
It was unintentionally removed in https://github.com/theforeman/foreman-documentation/pull/3534
Pointed out by @pablomh.
> Bring back the Puma workers and threads recommendations

- guides/common/modules/con_introduction-to-salt.adoc
- guides/common/modules/proc_enabling-salt-report-uploads.adoc
* specify supported Salt version
* fix command to manually upload reports
command is broken; command uses Python which depends on a Salt version
> Salt report upload

- guides/common/modules/proc_configuring-capsule-default-certificate.adoc
- guides/common/modules/proc_configuring-remaining-smart-proxy-servers-with-custom-ssl-certificates.adoc
- guides/common/modules/proc_configuring-remaining-smart-proxy-servers-with-default-ssl-certificates-for-load-balancing.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-custom-ssl-certificates-for-load-balancing-without-puppet.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-custom-ssl-certificates-to-generate-and-sign-puppet-certificates.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-default-ssl-certificates-for-load-balancing-without-puppet.adoc
- guides/common/modules/proc_configuring-smart-proxy-server-with-default-ssl-certificates-to-generate-and-sign-puppet-certificates.adoc
- guides/common/modules/proc_deploying-a-custom-ssl-certificate-to-smart-proxy-server.adoc
- guides/common/modules/proc_renewing-a-custom-ssl-certificate-on-smart-proxy.adoc
By removing mentions of this, it becomes an unsupported feature. This is good because various parts of the documentation assume it's turned on.  Users can easily get into unexpected errors way further down the line if they disable this feature.
Where there were explicit instructions to disable it, the text is changed into troubleshooting.
I'd appreciate some feedback on the phrasing of the changed lines.
> Drop mentions of --foreman-proxy-register-in-foreman

- guides/common/modules/con_content-view-environment-ordering-and-priority.adoc
Allow usage of asciidoc attributes in two specific code blocks.
Fixes https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#content-view-environment-ordering-and-priority
> Allow attributes in code blocks

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Adding 'review checklists' to the PR template.
Discussions over what conditions need to be met for a PR to be considered reviewed have been popping up recently. For example: Should we request a second opinion for PRs filed by engineers? How to introduce the requirement for QE/testing review when the concept of QE reviews is not native to upstream? What should be the scope of a review anyway?
Standardizing expectations could be beneficial for all sides: both writers and reviewers. These checklists could also eliminate the need to manually assign the `needs testing`/`testing done` labels (because they include testing as part of the regular tech review).
~~EDIT: This might actually eliminate the tech and style review labels too!~~
A previous suggestion by @ekohl was to use [Github's saved …
> Add review checklists to PR template

- guides/common/assembly_invalidating-registration-tokens.adoc
- guides/common/assembly_registering-hosts.adoc
drop an assembly that is only used once.
This simplifies consuming the content for ATIX in downstream.
I do not expect any change in the rendered docs.
> Do not use assembly within another assembly

- guides/common/modules/proc_migrating-project-or-smartproxy-using-backup-restore.adoc
After migrating from EL8 to EL9, the sync tasks fail with a network error. This is because DNS changes takes time.
Adding a note about this and also a step to shut down the old system and reassign the IP to the new EL9 system.
JIRA:
https://issues.redhat.com/browse/SAT-28024
> Add a note about IP addresses after migration

- guides/common/modules/con_upgrading-prerequisites.adoc
Since SHA1 is not supported, any certificates that use these need to be updated otherwise the upgrade fails.
JIRA: https://issues.redhat.com/browse/SAT-30262
> Add a prerequisite to update any SHA1 certificates

- guides/scripts/generate-hammer-reference.sh
Changing the interpreter for the generate-hammer-reference script to `bash`
It has to run in `bash`. `sh` doesn't recognize the `-e` argument of `echo` consistently
- It seems that the script is POSIX incompliant. Will this cause trouble for [Ansible automation](https://github.com/theforeman/foreman-documentation/tree/master/hammer_cli_reference)?
- Should we change the file extension as well?
> Run script in bash

- CONTRIBUTING.md
- guides/README.md
Adding guidelines for the mod docs content attribute.
This attribute is required for migrating d/s files to DITA.
> Add mod docs content attribute guidelines

- guides/common/modules/con_overview-of-usage-metrics-collection-in-project.adoc
- guides/common/modules/proc_disabling-the-collection-of-usage-metrics.adoc
- guides/common/modules/proc_reviewing-usage-metrics-collected-from-your-project.adoc
Adding information about a new timer that collects usage metrics from Satellite.
https://github.com/theforeman/foreman_maintain/pull/996
> Document new usage metrics timer

- guides/common/modules/ref_supported-virtualization-infrastructures.adoc
- guides/doc-Configuring_virt_who_VM_Subscriptions/master.adoc
orcharhino does not support compute resource KubeVirt.
Follow-up to #3995
Prerequisite to #4017
> Hide KubeVirt for orcharhino

- guides/common/modules/ref_generic-project-specific-macros.adoc
use attribute for Foreman Server URL instead of `HOST`.
> Use attribute in favor of HOST

- guides/common/modules/con_how-puppet-integrates-with-project.adoc
- guides/common/modules/proc_assigning-a-puppet-class-to-a-host-group.adoc
- guides/common/modules/proc_creating-a-custom-puppet-environment.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-provisioning.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
- guides/common/modules/proc_installing-and-configuring-puppet-agent-manually.adoc
- guides/common/modules/proc_overriding-a-smart-class-parameter-on-an-individual-host.adoc
- guides/common/modules/proc_overriding-out-of-sync-interval-for-a-host-group.adoc
- guides/common/modules/proc_overriding-out-of-sync-interval-for-an-individual-host.adoc
- guides/common/modules/proc_setting-the-global-out-of-sync-interval.adoc
- guides/common/modules/proc_setting-the-puppet-out-of-sync-interval.adoc
- guides/doc-Managing_Configurations_Puppet/master.adoc
Make "Configuring hosts by using Puppet" available for all builds
part of https://github.com/theforeman/foreman-documentation/issues/396
Tech ack needed for two assumptions:
* You can enable foreman_puppet on all builds equally
* You can disable foreman_puppet on all builds equally
> Make "Configuring hosts by using Puppet" available for all builds

- guides/common/modules/con_preparing-networking.adoc
- guides/common/modules/con_provisioning-virtual-machines-on-kvm.adoc
- guides/common/modules/proc_adding-openstack-connection.adoc
- guides/common/modules/proc_cloning-satellite-server.adoc
- guides/common/modules/proc_creating-image-only-hosts.adoc
- guides/common/modules/proc_installing-vmware-plugin.adoc
- guides/common/modules/proc_provisioning-ubuntu-autoinstall-through-smart-proxies.adoc
- guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
- guides/common/modules/ref_permissions-required-to-provision-hosts.adoc
- guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc
- guides/doc-Provisioning_Hosts/master.adoc
Make "Provisioning Hosts" fit for all build flavours
The guide was not officially ready yet for Foreman on Debian/Ubuntu and Foreman on EL.
> Make "Provisioning Hosts" fit for all build flavours

- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
Rebrand "Insights advisor in Satellite -> "Red Hat Lightspeed advisor in Satellite" (do not capitalize "advisor" for Satellite)
Has been rebranded together with Insights https://github.com/theforeman/foreman-documentation/pull/4031
Branding for Satellite confirmed per [comment](https://issues.redhat.com/browse/SAT-34946?focusedId=27676681&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27676681) (private)
- Putting the attributes one after another so that attribute can be reused and for better findability in source code
N/A
> Rebrand :advisorengine:

- guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
Rephrase "server" to "HTTP server" to help differentiate between Foreman Server, hosts (sometimes also called "servers" by users) and the required HTTP server.
To install "pulp-manifest" on EL9, you need to consume the same content that orcharhino Proxy Servers consume.
Alternative wording: "web server".
> Clarify required OS content of remote web servers

- guides/common/attributes-orcharhino.adoc
- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
Simplify maintenance of the procedure to install yggdrasil on hosts.
Context: In the future, I want to completely get rid of "client-content-*" attributes in upstream docs.
The attribute will be overwritten in downstream docs for orcharhino.
> Simplify installing yggdrasil on Client OS

- guides/common/header.adoc
- guides/doc-Configuring_virt_who_VM_Subscriptions/master.adoc
- guides/doc-Managing_Content/master.adoc
- guides/doc-Managing_Security_Compliance/master.adoc
- guides/doc-Planning_for_Project/master.adoc
- web/content/css/_ribbon.scss
- web/content/css/default.scss
Adding the banner for unsupported and pre-release versions to 3.13.
https://github.com/theforeman/foreman-documentation/pull/3653
> Add banner for unsupported and pre-release to 3.13

- guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc
Samba has removed command `net ads keytab add`  in version 4.21.1 and 
https://issues.redhat.com/browse/SAT-34783
I expect that most users will already have the more recent version in Samba, which is why I'm adding the information about the previous command only as a note.
> Update cmd to add krb principal with Samba

- guides/common/modules/proc_integrating-the-libvirt-api-to-manage-dhcp-leases.adoc
- guides/common/modules/proc_integrating-the-libvirt-api-to-manage-dns-records.adoc
correction to foreman-installer option example command replacing obsolete option
the foreman-installer option --foreman-proxy-libvirt-url no longers exists making the guide incorrect
> correct installer option to connect to libvirt for dns/dhcp

- guides/common/attributes-foreman-deb.adoc
- guides/common/modules/con_migrating-from-internal-databases-to-external-databases.adoc
- guides/common/modules/con_postgresql-as-an-external-database-considerations.adoc
- guides/common/modules/proc_installing-postgresql.adoc
- guides/common/modules/proc_migrating-to-external-databases.adoc
Explain that foreman-deb for Foreman on Debian 12 and Foreman on Ubuntu 22.04 relies on two different versions of PostgreSQL provided by the OS vendor.
* Debian 12 provides PostgreSQL 15
* Ubuntu 22.04 provides PostgreSQL 14
The examples use PostgreSQL 14, so on Debian 12, you have to adjust the paths in two procedures.
Fixes #3999
I am quite unsure about my change:
* Should we really write that Foreman supports different versions of PostgreSQL depending on the flavour?
> Clarify PostgreSQL versions on Debian/Ubuntu

- guides/common/modules/proc_configuring-repositories-el.adoc
- guides/common/modules/proc_configuring-repositories-foreman-el.adoc
This is always the same, so it doesn't have to be set as an attribute. If it were to change, the actual procedeure would need to use it too.
This was part of https://github.com/theforeman/foreman-documentation/pull/2936 but I'm splitting this off into its own change so it's easier to review.
> Remove distribution attribute when configuring repos

- guides/doc-Planning_for_Project/master.adoc
Adjusting leveloffset values in master.adoc for Planning.
Cherry-picking https://github.com/theforeman/foreman-documentation/pull/4098 to 3.14 broke the build because in order for a ribbon to be displayed, all content needs to have a heading of the appropriate level. On 3.14, there are currently multiple 0-level headings.
> Fix build errors in Planning

- guides/common/modules/proc_adding-a-google-gce-connection.adoc
Remove the instructions to place the key in `/etc/foreman`.
Hammer uploads the key to Foreman (just like in the UI procedure) and never read again. This means there's no point in storing the file in /etc/foreman with specific permissions.
It was introduced in 40b118063bf980dbd92469793abfc1229b691d99 (https://github.com/theforeman/foreman-documentation/pull/1949).
I changed the Hammer command to run as root for two reasons: the scp command also uses root and the installer sets up Hammer for root by default.  1137d3a971688a8bfef350962fdb1bc9afc17cae changed it to non-root and this goes against that.
An alternative is to change the instruction to a prerequisite to have Hammer set up and the key file present. Then you only need to list the Hammer command.
* …
> Remove instructions to place GCE key in /etc/foreman

- web/content/css/_ribbon.scss
Adding a missing style definition for ribbons.
In https://github.com/theforeman/foreman-documentation/pull/4147 and its equivalents on the lower branches, I forgot to add a few lines of the CSS definitions for the ribbons. This currently manifests on 3.13-3.9 guides as the "Unsupported version" ribbon being displayed not as a ribbon, but as a plain link at the bottom of each guide:
This PR should ensure that the style definitions are loaded correctly and the link is displayed as a ribbon again.
> Add missing CSS for ribbons

- guides/common/modules/con_configuring-project-to-manage-the-lifecycle-of-a-host-registered-to-a-freeipa-realm.adoc
- guides/common/modules/con_package-mode-and-image-mode-hosts.adoc
- guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
- guides/common/modules/ref_registration-methods.adoc
* Hide links to redhat.com for orcharhino builds
* Reword "AppStream" as required Yum repo on Clients because not all Clients are EL Clients
* Hide bootstrap.py for orcharhino
> Hide various lines for orcharhino builds

- guides/common/ribbons.adoc
Changing the link in the 'Report issue' ribbon from a link to open a blank issue to a link to open a pre-filled issue template.
To help ensure that when a user reports an issue when reading the documentation, they know what information the docs team needs.
N/A
> Update link in 'Report issue' ribbon

- guides/common/assembly_building-cloud-images.adoc
- guides/common/assembly_registering-hosts.adoc
- guides/common/assembly_synchronizing-template-repositories.adoc
- guides/common/attributes-base.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/proc_importing-templates-using-ansible.adoc
- guides/common/modules/proc_importing-templates.adoc
- guides/common/modules/proc_registering-a-host-using-ansible.adoc
- guides/common/modules/proc_registering-a-host.adoc
How to split off modules:
* Search for applicable modules: $ rg "^.Ansible procedure"
* Delete the block in the source modules
* Move content to separate procedure $ git diff > _original_module-using-X.adoc # with "X" as "ansible", "cli", or "api"
* Copy over missing header
* modular docs attribute
* anchor > add "using-X": Do not use attributes if at all possible
* title > add "using X"
* shortest introduction possible (TODO: discuss and reach consensus)
* If you deleted any anchors: search and replace them
* Add module below original procedure to any affected assembly with the same leveloffset (TODO: discuss and reach consensus)
* In your commit message, reference #4083
Part of #4083
**Needs appreciated**, specifically on the two items above.
* We do …
> Split off Ansible procedures into separate modules

- README.md
- guides/common/attributes.adoc
- guides/common/header.adoc
- guides/common/ribbons.adoc
Introducing the 'RC' document state, in addition to the existing 'nightly', 'supported', and 'unsupported' states.
The https://docs.theforeman.org/ website lists:
* "Supported releases"
* "Pre-release versions"
and it also mentions:
* "Unsupported releases", from which users are recommended to update to a supported release.
Based on this, we shouldn't label release candidate documentation as "unsupported" because the website lists it as "pre-release" and also, users can't update to a supported version from a release candidate.
https://github.com/theforeman/foreman-documentation/pull/4157 is there to make the change on 3.16, the current release candidate.
Tech review (performed by an Engineer who did not …
> Add 'RC' DocState

- guides/common/assembly_configuring-satellite-with-an-http-proxy.adoc
- guides/common/modules/proc_configuring-http-proxy-for-pxe-file-downloads-on-smart-proxies.adoc
While reviewing an unreleated PR, I found myself wondering "which proxy" the docs are talking about & I realized that the anchor, title, and file name do not match.
We must use the correct terminology "Smart Proxy" in favor of "proxy" which could leads users to think of  "HTTP proxy", "Smart Proxy", or even something completely unreleated.
The procedure is only used for non-Satellite builds.
> Use SmartProxy in favor of proxy

- guides/doc-Release_Notes/master.adoc
- guides/doc-Release_Notes/topics/katello-4.18.0.adoc
- guides/doc-Release_Notes/topics/katello-contributors.adoc
Add Katello 4.18 documentation to Foreman 3.16 branch
Working on Headline features for 4.18 documentation.
> Add Katello 4.18 documentation

- guides/common/modules/snip_generating-content.adoc
The documentation says 
"You cannot directly import Syncable Format exports". 
But the user has been able to use `hammer content-import` 
as a syncable-format export since 6.12. Changed the `snip_generating-content.adoc`
to reflect that change. 
https://issues.redhat.com/browse/SAT-27625
> Change instructions on importing syncable exports

- guides/common/attributes-base.adoc
- guides/common/attributes-katello.adoc
- guides/common/attributes-orcharhino.adoc
- guides/common/attributes-satellite.adoc
- guides/common/modules/con_supported-usage-of-project-components.adoc
- guides/common/modules/ref_supported-operating-systems.adoc
- guides/common/modules/ref_system-requirements.adoc
Streamlining the system requirements a bit, to phrase them as actionable steps and remove some duplicates I noticed.
The goal is to make the requirements easier to follow and to turn them from lengthy-ish descriptions into a sort of a quick "pre-flight" checklist.
This started with my noticing that we advise installing on a fresh system in 3 different places. What was supposed to be a very quick PR to consolidate that, turned into a slightly larger PR along the lines "while I'm here, why don't I try fixing up the whole section..."
> Review system requirements

- guides/common/assembly_managing-content-views.adoc
- guides/common/modules/con_rolling-content-views.adoc
- guides/common/modules/proc_assigning-a-rolling-content-view-to-lifecycle-environments.adoc
- guides/common/modules/proc_creating-a-rolling-content-view.adoc
- guides/common/modules/ref_best-practices-for-content-views.adoc
document assigning rolling content views to lifecycle environments.
this will simplify RCV usage because users no longer have to sync Library to Smart Proxy Servers. Instead, they can either create new or use existing LE that are on SmartProxyServers and sync RCV to those Smart Proxy Servers.
I was unsure if we need a new procedure, so I have added it to a second commit. We should either squash them or drop it.
> Assign rolling CV to LE (to omit synchronizing Library to Smart Proxy Servers to use RCV)

- guides/common/modules/proc_running-installer.adoc
- guides/doc-Quickstart/master.adoc
* Moving installer details from the Quickstart's abstract to the section on running the installer
* Adding a new abstract that explains the purpose of the guide
This came up during the review of https://github.com/theforeman/foreman-documentation/pull/4203
N/A
> Update Quickstart abstract

- guides/common/modules/con_backing-up-server-and-proxy.adoc
- guides/common/modules/snip_backup-usecase-note.adoc
Removing backup-usecase-note snippet
Snippet is very short and used in only one module.
Tech review and testing not required.
> Removing backup-note snippet

- guides/common/modules/proc_performing-a-full-backup.adoc
If you create a backup on Foreman+Katello Server or Smart Proxy Servers by using `foreman-maintain backup [online|offline]`, `foreman-maintain` creates a dump of the database.
Regardless of the method (online or offline), the backup contains a dump of the database.
Tested on Foreman 3.14/Katello 4.16: Create an online/offline backup on Foreman Server; migrate to external DB as documented; recreate an online/offline backup on Foreman Server:
````
$ du -ksh /my-backup*
4.0G /my-backup-offline
4.0G /my-backup-online
5.2G /my-backup-post-migration-offline
5.2G /my-backup-post-migration-online
$ find /my-backup* -name "*.dump"
/my-backup-offline/foreman-backup-2025-09-10-07-36-30/candlepin.dump
/my-backup-offline/foreman-backup-2025-09-10-07-36-30/foreman.dump …
```
> Fix result of remote DB backup

- guides/common/modules/proc_customizing-the-registration-templates.adoc
- guides/common/modules/snip_note-custom-templates-unsupported.adoc
Removing `guides/common/modules/snip_note-custom-templates-unsupported.adoc`
Snippet is very short and used only once.
No tech review or testing required.
> Remove custom templates snippet

- guides/common/modules/proc_configuring-tls-for-secure-ldap.adoc
* Highlighting an existing prerequisite as an actual prerequisite so it's harder to miss
* Adding a step to restart services
* EDIT: Updating cert location
https://issues.redhat.com/browse/SAT-32048
Somewhat related to https://github.com/theforeman/foreman-documentation/pull/3941 which also adds a step to restart services after updating certs.
> Update procedure for TLS for secure LDAP connection

- guides/common/modules/con_configuring-project-to-manage-the-lifecycle-of-a-host-registered-to-a-freeipa-realm.adoc
- guides/common/modules/proc_configuring-satellite-for-outgoing-emails.adoc
- guides/common/modules/proc_using-vmware-cloud-init-and-userdata-templates-for-provisioning.adoc
Always only run `update-ca-trust extract`.
The enable command was never valid. On EL 7 & 8 it was just ignored so effectively it ran twice. On EL 9 there is argument parsing and enable emits a deprecation warning to use extract. On EL 10 the enable command is no longer accepted and only extract is valid.
https://github.com/voxpupuli/puppet-trusted_ca/commit/b3416c58e6a0d72ef8c49725a6193c3217b001cc is where I originally wrote down my findings in the period that ca-certificates on EL9 didn't accept `enable` at all. It has since started to accept it again, with a deprecation warning.
> Remove update-ca-trust enable step

- guides/common/assembly_installing-and-configuring-insights-iop.adoc
- guides/common/modules/proc_configuring-podman-to-use-an-http-proxy.adoc
Adding procedure to configure Podman for HTTP proxy in connected IoP installation
When ProjectServer is behind an HTTP proxy, foreman-installer fails to enable IoP unless Podman is configured to connect through that proxy as well.
[SAT-38117](https://issues.redhat.com/browse/SAT-38117) (public)
> Add Configuring Podman for HTTP proxy

- guides/common/modules/ref_kernel-parameters-for-discovery-customization.adoc
Remove URL
Either the URL is broken on a regular basis or gnu just doesn't like the GHA checking the URL. Either way, I've had enough of it.
> Remove broken URL

- guides/doc-Hammer_Reference/README.md
- guides/scripts/generate-hammer-reference.sh
Updating the `generate-hammer-reference.sh` for the new Hammer reference
- Assembly moved to a new guide
- More granular modularization
- DITA compliance
- Decreased nesting
- The subcommands are now split into multiple `ref_` modules. The generation results in over **800 modules** in addition to the existing ones! Are we sure we want them inside `common/modules`?
- The generation workflow now requires manual steps to decrease nesting of a small number of subcommands.
- I've tested it downstream thoroughly.
> Rework Hammer reference generation

- guides/common/modules/con_provisioning-templates.adoc
Clarifiy which templates are supported etc. 
Customer feedback
> Clarify wording that unlocked templates are not supported

- CONTRIBUTING.md
* Review PR checklist in the contribution doc for simplicity and clarity
* Drop a few items from the PR checklist that are obsolete or duplicate other parts of the contribution doc
* Splitting the PR checklist into two smaller checklist to make it a bit less overwhelming
Follow-up on https://github.com/theforeman/foreman-documentation/pull/4281
N/A
> Review PR checklist in CONTRIBUTING.md

- guides/common/modules/ref_supported-virtualization-infrastructures.adoc
This patch adds links to the relevant chapters in the "Provisioning hosts" guide. It also sorts the list as they are included in "master.adoc".
Similar to "ref_supported-cloud-providers.adoc".
Fixes #4017
> Add links to provisioning hosts chapters

- guides/common/modules/proc_running-an-ansible-playbook.adoc
- guides/common/modules/ref_host-parameters-in-ansible-playbooks.adoc
- guides/doc-Managing_Configurations_Ansible/master.adoc
Add example on how to use global parameters in Ansible Playbooks.
* This is a workaround for this limitation: https://docs.theforeman.org/nightly/Managing_Configurations_Ansible/index-katello.html#running-an-ansible-playbook-from-foreman_ansible
* It's not documented anywhere yet how to access host parameters in Ansible.
Tested on Foreman/Katello 3.14/4.16:
> Add example to access global host parameters via Ansible

- guides/common/modules/proc_configuring-a-bmc-interface.adoc
- guides/common/modules/proc_enabling-power-management-on-hosts.adoc
Moving installer stuff about power management (BMC) from _Managing hosts_ to _Installing X_
To align the procedures with personas: admin vs. non-admin users
[SAT-30833](https://issues.redhat.com/browse/SAT-30833) (public)
- Adding usage of power operations as such is out of scope.
> Fix power management sections per persona

- CONTRIBUTING.md
* Editing the 'contribution guide' section of CONTRIBUTING.md for clarity
* Removing some duplicate or redundant items
Follow up on https://github.com/theforeman/foreman-documentation/pull/4281
N/A
> Review 'contribution guide' in CONTRIBUTING.md

- guides/common/assembly_managing-ostree-content.adoc
- guides/common/modules/con_managing-ostree-content.adoc
- guides/common/modules/proc_enabling-os-tree-content.adoc
* Drop unnecessary prerequisite about OS platform
* Drop note about Katello plugin for Hammer CLI which _should_ be installed on Foreman/Katello Server anyway
* Fix anchor
I stumbled over the wording as part of https://github.com/theforeman/foreman-documentation/issues/3672 & the limitation to EL8/9 caught my eye which must be bogus because Foreman+Katello nightly only runs on EL9.
Untested anything else than enabling the feature.
> Fix modules to enable OSTree content
